export interface Module {
  slug: string;
  title: string;
  icon: string;
  xp: number;
  readTime: number;
  desc: string;
  seoDesc: string;
  keywords: string;
  externalUrl?: string;
}

export interface Trail {
  id: string;
  name: string;
  color: string;
  icon: string;
  desc: string;
  unlockAfter?: string;
  modules: Module[];
}

export interface Hub {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  href: string;
  color: string;
  icon: string;
  tagline: string;
  desc: string;
  trailIds: string[];
}

export const CURRICULUM: Trail[] = [
  {
    id: 'trail1',
    name: 'Fundamentos da IA',
    color: '#58a6ff',
    icon: '🧠',
    desc: 'Do zero ao LLM — entenda como a IA realmente funciona',
    modules: [
      {
        slug: 'o-que-e-ia',
        title: 'O que é Inteligência Artificial?',
        icon: '🤖',
        xp: 30,
        readTime: 6,
        desc: 'Do conceito à realidade: o que é IA, o que não é, e por que você precisa entender isso agora.',
        seoDesc: 'Entenda o que é Inteligência Artificial de verdade, sem buzzwords. Definição clara, exemplos práticos e histórico.',
        keywords: 'o que é inteligencia artificial, IA para iniciantes, definição IA',
      },
      {
        slug: 'dados-o-combustivel',
        title: 'Dados: o Combustível da IA',
        icon: '⛽',
        xp: 30,
        readTime: 7,
        desc: 'Por que "dados são o novo petróleo" — e o que isso significa na prática para treinar um modelo.',
        seoDesc: 'Entenda por que dados são essenciais para a IA funcionar, como datasets são criados e o que é qualidade de dados.',
        keywords: 'dados inteligencia artificial, dataset machine learning, treinamento IA',
      },
      {
        slug: 'como-ia-aprende',
        title: 'Como a IA Aprende (Machine Learning)',
        icon: '📈',
        xp: 40,
        readTime: 8,
        desc: 'Gradiente descendente, loss function, backpropagation — explicados sem complicar.',
        seoDesc: 'Como machine learning funciona na prática: treinamento, gradiente descendente e otimização explicados de forma simples.',
        keywords: 'como machine learning funciona, gradiente descendente explicado, treinamento modelo IA',
      },
      {
        slug: 'redes-neurais',
        title: 'Redes Neurais: o Cérebro Artificial',
        icon: '🕸️',
        xp: 50,
        readTime: 10,
        desc: 'Neurônios, camadas, ativações — a arquitetura que imita (e supera) o cérebro em tarefas específicas.',
        seoDesc: 'O que são redes neurais artificiais, como funcionam neurônios artificiais, camadas e funções de ativação.',
        keywords: 'redes neurais artificiais, deep learning, como funciona rede neural',
      },
      {
        slug: 'o-que-e-llm',
        title: 'O que é um LLM?',
        icon: '💬',
        xp: 50,
        readTime: 9,
        desc: 'Large Language Models: o que os torna diferentes, como foram treinados e por que o ChatGPT foi um divisor de águas.',
        seoDesc: 'O que é um LLM (Large Language Model), como funciona o ChatGPT, Claude e Gemini. Explicação completa.',
        keywords: 'o que é LLM, large language model explicado, como funciona chatgpt',
      },
      {
        slug: 'tokens',
        title: 'Tokens e Tokenização',
        icon: '🔤',
        xp: 40,
        readTime: 7,
        desc: 'A IA não lê palavras — ela lê tokens. Entenda o que isso muda em custo, velocidade e limites de contexto.',
        seoDesc: 'O que são tokens em IA, como funciona tokenização BPE, por que contexto é medido em tokens e como isso afeta o custo.',
        keywords: 'tokens IA, tokenização LLM, contexto tokens, BPE tokenizacao',
      },
      {
        slug: 'transformers',
        title: 'Transformers e Mecanismo de Atenção',
        icon: '⚙️',
        xp: 60,
        readTime: 12,
        desc: 'A arquitetura que mudou tudo em 2017 — Attention Is All You Need e por que o transformer é onipresente.',
        seoDesc: 'Como funciona o Transformer e mecanismo de atenção. A arquitetura por trás de GPT, Claude e BERT explicada.',
        keywords: 'transformer arquitetura IA, mecanismo atencao IA, attention is all you need',
      },
    ],
  },
  {
    id: 'trail2',
    name: 'IA Além do LLM',
    color: '#d2a8ff',
    icon: '🏗️',
    desc: 'KV Cache, MoE, Tool Calling, avaliação — como modelos funcionam em produção',
    modules: [
      {
        slug: 'kv-cache',
        title: 'KV Cache: Memória Eficiente',
        icon: '⚡',
        xp: 60,
        readTime: 8,
        desc: 'Por que um modelo de 30GB pode precisar de 60GB de VRAM — e como o KV Cache resolve isso.',
        seoDesc: 'O que é KV Cache em transformers, como funciona Key-Value Cache, por que é essencial para inferência eficiente.',
        keywords: 'kv cache transformers, key value cache LLM, memoria eficiente IA',
      },
      {
        slug: 'mixture-of-experts',
        title: 'Mixture of Experts (MoE)',
        icon: '🧩',
        xp: 70,
        readTime: 10,
        desc: '200B parâmetros que não cabem na GPU — veja como o MoE ativa só o que é necessário.',
        seoDesc: 'O que é Mixture of Experts (MoE), como funciona o roteamento de experts, Mixtral e modelos MoE explicados.',
        keywords: 'mixture of experts MoE, mixtral arquitetura, sparse model IA',
      },
      {
        slug: 'tool-calling',
        title: 'Tool Calling e Agentes',
        icon: '🔧',
        xp: 70,
        readTime: 9,
        desc: 'Como a IA aprendeu a usar ferramentas externas — e por que isso transformou LLMs em agentes.',
        seoDesc: 'O que é tool calling em IA, como agentes usam ferramentas, function calling na API do Claude e OpenAI.',
        keywords: 'tool calling IA, function calling LLM, agentes IA ferramentas',
      },
      {
        slug: 'ia-alem-do-llm',
        title: 'Harness: a Infraestrutura do Agente',
        icon: '🏗️',
        xp: 80,
        readTime: 15,
        desc: 'Os 6 componentes que fazem um agente de IA funcionar de verdade.',
        seoDesc: 'O que é um coding harness para agentes de IA, os 6 componentes de um agente de programação, Claude Code vs Cursor.',
        keywords: 'harness agente IA, componentes agente programacao, claude code vs cursor',
      },
      {
        slug: 'como-avaliar-modelos',
        title: 'Como Avaliar Modelos de IA',
        icon: '📊',
        xp: 60,
        readTime: 8,
        desc: 'MMLU, HumanEval, benchmark contamination — como saber se um modelo é realmente melhor.',
        seoDesc: 'Como avaliar modelos de IA, o que são benchmarks MMLU HumanEval, como LM Eval Harness funciona.',
        keywords: 'avaliar modelos IA, benchmarks LLM, MMLU HumanEval, lm evaluation harness',
      },
    ],
  },
  {
    id: 'trail3',
    name: 'Ferramentas de IA para Código',
    color: '#ffa657',
    icon: '💻',
    desc: 'Claude Code, Codex, Cursor, Kiro — as diferenças reais entre os coding agents',
    modules: [
      {
        slug: 'coding-agents-panorama',
        title: 'O Panorama dos Coding Agents',
        icon: '🗺️',
        xp: 50,
        readTime: 8,
        desc: 'De Copilot ao Claude Code — como os assistentes de código evoluíram de autocomplete para agentes autônomos.',
        seoDesc: 'O que são coding agents, diferença entre autocomplete e agentes de IA para código, histórico e evolução.',
        keywords: 'coding agents IA, assistentes codigo IA, claude code vs copilot, ferramentas IA programacao',
      },
      {
        slug: 'claude-code-arquitetura',
        title: 'Claude Code: Filosofia e Arquitetura',
        icon: '🤖',
        xp: 70,
        readTime: 12,
        desc: 'Como o Claude Code funciona por dentro — o loop agêntico, as ferramentas, o modelo de confiança e por que é diferente dos IDEs.',
        seoDesc: 'Como Claude Code funciona internamente, loop agêntico, ferramentas bash/read/write, arquitetura do agente de terminal.',
        keywords: 'claude code como funciona, arquitetura claude code, loop agentico claude, CLI agente IA',
      },
      {
        slug: 'openai-codex-cloud',
        title: 'OpenAI Codex: o Agente na Nuvem',
        icon: '☁️',
        xp: 65,
        readTime: 10,
        desc: 'O novo Codex (2025) é completamente diferente do antigo — roda em sandbox na nuvem, é assíncrono e paralelo. Entenda o que isso muda.',
        seoDesc: 'Como funciona o OpenAI Codex 2025, sandbox cloud, execução assíncrona, diferença do Claude Code.',
        keywords: 'openai codex 2025, codex cloud sandbox, openai coding agent, codex vs claude code',
      },
      {
        slug: 'cursor-copilot-ides',
        title: 'Cursor, Copilot e os IDEs Aumentados',
        icon: '🖥️',
        xp: 60,
        readTime: 10,
        desc: 'A abordagem IDE-first — como Cursor e Copilot integram IA no editor e por que isso é uma filosofia diferente dos agentes de terminal.',
        seoDesc: 'Como Cursor e GitHub Copilot funcionam, diferenças entre IDEs com IA e agentes de terminal, comparação técnica.',
        keywords: 'cursor ide IA, github copilot arquitetura, cursor vs claude code, IDE aumentado IA',
      },
      {
        slug: 'amazon-q-kiro',
        title: 'Amazon Q e Kiro: a Aposta da AWS',
        icon: '☁️',
        xp: 60,
        readTime: 9,
        desc: 'O Amazon Q Developer e o novo Kiro têm filosofias distintas — um é extensão de IDE corporativo, o outro é spec-driven development.',
        seoDesc: 'O que é Amazon Q Developer, o que é Kiro AWS, spec-driven development, diferença entre Q e Kiro.',
        keywords: 'amazon q developer, kiro aws, spec driven development, amazon coding agent',
      },
      {
        slug: 'qual-coding-agent-usar',
        title: 'Qual Ferramenta Usar e Quando',
        icon: '⚖️',
        xp: 80,
        readTime: 12,
        desc: 'Matriz de decisão real: quando o Claude Code brilha, quando o Cursor vence, quando o Codex na nuvem faz sentido. Sem achismo.',
        seoDesc: 'Comparação técnica entre coding agents de IA: Claude Code vs Codex vs Cursor vs Copilot vs Kiro. Quando usar cada um.',
        keywords: 'comparar coding agents IA, claude code vs cursor vs copilot, qual IA usar para codigo, melhor ferramenta IA programacao',
      },
    ],
  },
  {
    id: 'trail4',
    name: 'AWS Cloud Practitioner',
    color: '#ff9900',
    icon: '☁️',
    desc: 'Fundamentos da AWS alinhados ao exame CLF-C02 — do zero ao certificado',
    modules: [
      {
        slug: 'o-que-e-cloud',
        title: 'O que é Cloud Computing?',
        icon: '☁️',
        xp: 30,
        readTime: 8,
        desc: 'IaaS, PaaS, SaaS, deployment models, economia de escala — o que a nuvem realmente muda e por que a AWS venceu.',
        seoDesc: 'O que é cloud computing, modelos IaaS PaaS SaaS, cloud pública privada híbrida, vantagens e desvantagens da nuvem.',
        keywords: 'o que é cloud computing, IaaS PaaS SaaS, cloud publica privada hibrida, aws cloud practitioner',
      },
      {
        slug: 'aws-global-infra',
        title: 'Infraestrutura Global: Regiões, AZs e Edge',
        icon: '🌍',
        xp: 40,
        readTime: 8,
        desc: 'Regions, Availability Zones, Edge Locations, Local Zones, Wavelength — como a AWS distribui capacidade no planeta.',
        seoDesc: 'AWS regions, availability zones explicadas, edge locations CloudFront, infraestrutura global AWS.',
        keywords: 'aws regions availability zones, AZ edge location, infraestrutura global aws, local zones wavelength',
      },
      {
        slug: 'modelo-responsabilidade-compartilhada',
        title: 'Modelo de Responsabilidade Compartilhada',
        icon: '🤝',
        xp: 35,
        readTime: 7,
        desc: 'O que é responsabilidade da AWS e o que é sua. A linha que cai em metade das questões de segurança do exame.',
        seoDesc: 'Modelo de responsabilidade compartilhada AWS, segurança da nuvem vs segurança na nuvem, shared responsibility model.',
        keywords: 'modelo responsabilidade compartilhada aws, shared responsibility model, seguranca aws cliente',
      },
      {
        slug: 'iam-fundamentos',
        title: 'IAM: Identidade, Grupos, Roles e Policies',
        icon: '🔐',
        xp: 60,
        readTime: 12,
        desc: 'Users, Groups, Roles, Policies, MFA, root account — os blocos fundamentais de segurança na AWS.',
        seoDesc: 'AWS IAM explicado: usuários, grupos, roles, policies JSON, MFA, diferença entre user e role, root account boas práticas.',
        keywords: 'aws iam fundamentos, iam user group role policy, mfa aws, root account aws',
      },
      {
        slug: 'compute-ec2-lambda',
        title: 'Compute: EC2, Lambda e Containers',
        icon: '🖥️',
        xp: 60,
        readTime: 12,
        desc: 'EC2 instance types, purchasing options, Lambda, Fargate, ECS e EKS — os serviços de compute que todo practitioner precisa dominar.',
        seoDesc: 'AWS compute services: EC2 instance types, on-demand reserved spot, Lambda serverless, Fargate ECS EKS containers.',
        keywords: 'aws ec2 lambda container, ec2 instance types, on demand reserved spot, fargate ecs eks',
      },
      {
        slug: 'storage-s3-ebs-efs',
        title: 'Storage: S3, EBS, EFS e Glacier',
        icon: '💾',
        xp: 55,
        readTime: 11,
        desc: 'Object, block, file storage — S3 storage classes, EBS volume types, EFS, Glacier, Storage Gateway. Como escolher.',
        seoDesc: 'AWS storage: S3 classes standard IA glacier, EBS SSD HDD, EFS file system, storage gateway, quando usar cada um.',
        keywords: 'aws s3 ebs efs glacier, s3 storage classes, ebs volume types, quando usar s3 ebs efs',
      },
      {
        slug: 'databases-aws-basico',
        title: 'Databases: RDS, Aurora, DynamoDB e Redshift',
        icon: '🗄️',
        xp: 60,
        readTime: 12,
        desc: 'Relacional vs NoSQL vs analítico. RDS, Aurora, DynamoDB, ElastiCache, Redshift — quando usar cada um no CLF-C02.',
        seoDesc: 'AWS databases: RDS Aurora DynamoDB ElastiCache Redshift, relacional vs NoSQL, quando usar cada banco AWS.',
        keywords: 'aws databases, rds aurora dynamodb, redshift elasticache, quando usar rds ou dynamodb',
      },
      {
        slug: 'networking-vpc-route53',
        title: 'Networking: VPC, Route 53 e CloudFront',
        icon: '🌐',
        xp: 55,
        readTime: 11,
        desc: 'VPC, subnets, Internet Gateway, NAT, Route 53 DNS, CloudFront CDN, Direct Connect, VPN — a rede da AWS demistificada.',
        seoDesc: 'AWS networking: VPC subnets IGW NAT, Route 53 DNS, CloudFront CDN, Direct Connect VPN site-to-site.',
        keywords: 'aws vpc networking, route 53 dns, cloudfront cdn, direct connect vpn aws',
      },
      {
        slug: 'seguranca-aws-servicos',
        title: 'Segurança AWS: KMS, GuardDuty, Shield e WAF',
        icon: '🛡️',
        xp: 60,
        readTime: 11,
        desc: 'KMS, Secrets Manager, GuardDuty, Shield, WAF, Inspector, Macie — o arsenal de segurança que cobre 30% do exame.',
        seoDesc: 'AWS security services: KMS encryption, Secrets Manager, GuardDuty threat detection, Shield DDoS, WAF, Inspector Macie.',
        keywords: 'aws kms guardduty shield waf, secrets manager, inspector macie, seguranca aws servicos',
      },
      {
        slug: 'monitoramento-cloudwatch',
        title: 'Monitoramento: CloudWatch, CloudTrail e Config',
        icon: '📊',
        xp: 45,
        readTime: 9,
        desc: 'CloudWatch (métricas e logs), CloudTrail (auditoria de API) e Config (compliance) — o tripé de observabilidade.',
        seoDesc: 'AWS monitoring: CloudWatch metrics logs, CloudTrail api audit, AWS Config compliance, diferença entre CloudWatch e CloudTrail.',
        keywords: 'aws cloudwatch cloudtrail config, cloudwatch vs cloudtrail, aws config compliance, monitoramento aws',
      },
      {
        slug: 'well-architected-framework',
        title: 'Well-Architected: os 6 Pilares',
        icon: '🏛️',
        xp: 50,
        readTime: 10,
        desc: 'Operational Excellence, Security, Reliability, Performance, Cost Optimization, Sustainability — o framework que guia toda decisão AWS.',
        seoDesc: 'AWS Well-Architected Framework explicado, 6 pilares operational security reliability performance cost sustainability.',
        keywords: 'well architected framework aws, 6 pilares aws, operational excellence security reliability',
      },
      {
        slug: 'cloud-adoption-framework',
        title: 'CAF e os 7 Rs da Migração',
        icon: '🚚',
        xp: 45,
        readTime: 9,
        desc: 'Cloud Adoption Framework (6 perspectivas) e as 7 estratégias de migração — Rehost, Replatform, Refactor, Relocate, Retire, Retain, Repurchase.',
        seoDesc: 'AWS Cloud Adoption Framework, 7 Rs migration strategies, rehost replatform refactor repurchase, CAF perspectives.',
        keywords: 'cloud adoption framework aws, 7 rs migracao, rehost replatform refactor, caf perspectives',
      },
      {
        slug: 'precificacao-suporte',
        title: 'Precificação, Free Tier e Planos de Suporte',
        icon: '💰',
        xp: 50,
        readTime: 10,
        desc: 'Pay-as-you-go, Free Tier, Pricing Calculator, Cost Explorer, Budgets, TCO Calculator e os 4 Support Plans — tudo sobre a fatura da AWS.',
        seoDesc: 'AWS pricing: free tier, pricing calculator, cost explorer, AWS Budgets, support plans basic developer business enterprise.',
        keywords: 'aws pricing free tier, pricing calculator cost explorer, aws budgets, support plans aws',
      },
      {
        slug: 'migracao-aws-servicos',
        title: 'Migração: Migration Hub, DMS, MGN e DataSync',
        icon: '🚚',
        xp: 45,
        readTime: 9,
        desc: 'Migration Hub, Application Migration Service (MGN), DMS, Application Discovery Service, DataSync e Mainframe Modernization — o arsenal de migração AWS.',
        seoDesc: 'AWS migration services: Migration Hub, AWS MGN Application Migration Service, DMS Database Migration, Application Discovery, DataSync.',
        keywords: 'aws migration hub, aws mgn application migration service, aws dms, application discovery service, aws datasync',
      },
      {
        slug: 'ai-ml-aws-servicos',
        title: 'IA e ML na AWS: Bedrock, SageMaker, Q e Amigos',
        icon: '🧠',
        xp: 50,
        readTime: 10,
        desc: 'SageMaker, Rekognition, Comprehend, Polly, Transcribe, Translate, Lex, Kendra, Bedrock e Amazon Q — o stack de IA da AWS para o CLF-C02.',
        seoDesc: 'AWS AI/ML services: SageMaker, Rekognition, Comprehend, Polly Transcribe Translate, Lex, Kendra, Bedrock, Amazon Q.',
        keywords: 'aws sagemaker, amazon bedrock, amazon q, aws rekognition comprehend, polly transcribe translate, amazon lex kendra',
      },
      {
        slug: 'developer-tools-aws',
        title: 'Developer Tools: CodePipeline, CDK, CloudFormation e SAM',
        icon: '🛠️',
        xp: 45,
        readTime: 9,
        desc: 'CodeCommit, CodeBuild, CodeDeploy, CodePipeline, CloudFormation, CDK, SAM, Amplify e X-Ray — os serviços de CI/CD e IaC da AWS.',
        seoDesc: 'AWS developer tools: CodeCommit CodeBuild CodeDeploy CodePipeline, CloudFormation CDK SAM, Amplify, X-Ray distributed tracing.',
        keywords: 'aws codepipeline cicd, aws cloudformation cdk, aws sam serverless, aws codebuild codedeploy, aws x-ray amplify',
      },
      {
        slug: 'simulado-practitioner',
        title: 'Simulado CLF-C02 Comentado',
        icon: '🎯',
        xp: 80,
        readTime: 20,
        desc: '20 questões no estilo oficial do exame, cada uma com explicação detalhada de por que a resposta certa é certa e as erradas são erradas.',
        seoDesc: 'Simulado AWS Cloud Practitioner CLF-C02 comentado, 20 questões com respostas explicadas, preparação para o exame.',
        keywords: 'simulado aws cloud practitioner, clf-c02 questoes comentadas, prova aws practitioner, preparacao exame aws',
      },
    ],
  },
  {
    id: 'trail5',
    name: 'AWS Solutions Architect Associate',
    color: '#146eb4',
    icon: '🏛️',
    desc: 'Arquitetura profissional de soluções AWS alinhada ao exame SAA-C03',
    modules: [
      {
        slug: 'saa-c03-intro',
        title: 'SAA-C03: Da Teoria à Arquitetura Real',
        icon: '🎓',
        xp: 40,
        readTime: 8,
        desc: 'O que muda do Practitioner para o SAA-C03, os 4 domínios do exame, pré-requisitos e a mentalidade do arquiteto AWS.',
        seoDesc: 'AWS SAA-C03 Solutions Architect Associate, domínios do exame, diferença Practitioner vs Associate, preparação SAA.',
        keywords: 'aws saa-c03, solutions architect associate, dominios exame saa, preparacao saa-c03',
      },
      {
        slug: 'iam-avancado-organizations',
        title: 'IAM Avançado: Policies JSON, STS e Organizations',
        icon: '🔑',
        xp: 75,
        readTime: 14,
        desc: 'Policy JSON em profundidade, STS AssumeRole, cross-account access, AWS Organizations, SCPs, Identity Center (SSO).',
        seoDesc: 'AWS IAM avançado: policy JSON elements, STS AssumeRole, cross-account access, Organizations SCPs, Identity Center SSO.',
        keywords: 'iam policy json aws, sts assume role, aws organizations scp, identity center sso, cross account access',
      },
      {
        slug: 'vpc-avancado',
        title: 'VPC em Profundidade: NAT, Peering e Transit Gateway',
        icon: '🕸️',
        xp: 85,
        readTime: 16,
        desc: 'VPC design real, subnets públicas/privadas, NAT Gateway vs NAT Instance, VPC Peering, Transit Gateway, PrivateLink, VPN vs Direct Connect.',
        seoDesc: 'AWS VPC avançado: NAT Gateway vs NAT Instance, VPC Peering Transit Gateway, PrivateLink, VPN Direct Connect, subnet design.',
        keywords: 'vpc avancado aws, transit gateway vpc peering, nat gateway nat instance, privatelink vpn direct connect',
      },
      {
        slug: 'dns-cdn-edge',
        title: 'Route 53, CloudFront e Global Accelerator',
        icon: '🌐',
        xp: 70,
        readTime: 13,
        desc: 'Route 53 routing policies (simple, weighted, latency, failover, geo, multi-value), CloudFront behaviors, Global Accelerator.',
        seoDesc: 'Route 53 routing policies simple weighted latency failover geolocation, CloudFront behaviors, AWS Global Accelerator.',
        keywords: 'route 53 routing policies, cloudfront behaviors, global accelerator aws, dns failover weighted',
      },
      {
        slug: 'ec2-autoscaling-elb',
        title: 'EC2 Profissional: Auto Scaling e Load Balancers',
        icon: '⚖️',
        xp: 80,
        readTime: 15,
        desc: 'Purchasing options profundos, Auto Scaling Groups, ALB vs NLB vs GWLB, target groups, placement groups, health checks.',
        seoDesc: 'EC2 Auto Scaling Groups, Application Load Balancer vs Network Load Balancer, target groups, placement groups, purchasing options.',
        keywords: 'ec2 auto scaling, alb nlb gwlb, target groups, placement groups aws, purchasing options ec2',
      },
      {
        slug: 'containers-ecs-eks',
        title: 'ECS vs EKS: Orquestração de Containers',
        icon: '📦',
        xp: 70,
        readTime: 13,
        desc: 'ECS (Fargate vs EC2 launch type), EKS (Kubernetes managed), service discovery, service mesh, quando escolher cada um.',
        seoDesc: 'AWS ECS vs EKS, Fargate vs EC2 launch type, Kubernetes managed, service discovery, container orchestration AWS.',
        keywords: 'ecs vs eks aws, fargate vs ec2, kubernetes aws, service discovery container aws',
      },
      {
        slug: 'serverless-lambda-avancado',
        title: 'Serverless Avançado: Lambda, API GW e Step Functions',
        icon: '⚡',
        xp: 80,
        readTime: 15,
        desc: 'Lambda deep dive (cold start, concurrency, layers, destinations), API Gateway (REST vs HTTP), Step Functions workflows.',
        seoDesc: 'AWS Lambda cold start concurrency layers, API Gateway REST vs HTTP, Step Functions workflows, serverless architecture.',
        keywords: 'lambda cold start concurrency, api gateway rest http, step functions workflow, serverless aws',
      },
      {
        slug: 's3-avancado',
        title: 'S3 Profundo: Classes, Lifecycle e Object Lock',
        icon: '🪣',
        xp: 80,
        readTime: 15,
        desc: 'Todas storage classes, lifecycle policies, versioning, replication (CRR/SRR), Object Lock, encryption (SSE-S3, SSE-KMS, SSE-C, CSE).',
        seoDesc: 'S3 storage classes detalhado, lifecycle policies, CRR SRR replication, Object Lock WORM, SSE-S3 SSE-KMS SSE-C encryption.',
        keywords: 's3 storage classes, s3 lifecycle policy, s3 replication crr srr, s3 object lock, s3 encryption sse',
      },
      {
        slug: 'block-file-storage',
        title: 'EBS, EFS e FSx: Quando Usar Cada Um',
        icon: '💽',
        xp: 60,
        readTime: 12,
        desc: 'EBS volume types (gp3, io2, st1, sc1), snapshots, EFS performance/throughput modes, FSx Windows/Lustre/NetApp, Storage Gateway.',
        seoDesc: 'EBS volume types gp3 io2 st1 sc1, EFS performance modes, FSx Windows Lustre NetApp, Storage Gateway.',
        keywords: 'ebs volume types gp3 io2, efs performance modes, fsx windows lustre, storage gateway aws',
      },
      {
        slug: 'rds-aurora-dynamodb',
        title: 'Bancos: Multi-AZ, Read Replicas e DynamoDB',
        icon: '🗃️',
        xp: 90,
        readTime: 17,
        desc: 'RDS Multi-AZ vs Read Replicas, Aurora (cluster + Serverless v2), DynamoDB (GSI/LSI, DAX, Streams, on-demand vs provisioned).',
        seoDesc: 'RDS Multi-AZ vs Read Replicas, Aurora cluster serverless, DynamoDB GSI LSI DAX streams, on-demand provisioned.',
        keywords: 'rds multi-az read replicas, aurora cluster serverless, dynamodb gsi lsi dax, dynamodb streams',
      },
      {
        slug: 'caching-performance',
        title: 'Caching: ElastiCache, DAX e CloudFront',
        icon: '🚀',
        xp: 60,
        readTime: 12,
        desc: 'ElastiCache Redis vs Memcached, DAX para DynamoDB, CloudFront cache behaviors, patterns (cache-aside, write-through).',
        seoDesc: 'ElastiCache Redis vs Memcached, DAX DynamoDB accelerator, CloudFront cache behaviors, cache patterns aside write-through.',
        keywords: 'elasticache redis memcached, dax dynamodb, cloudfront cache, cache patterns aws',
      },
      {
        slug: 'messaging-eventos',
        title: 'Messaging: SQS, SNS, EventBridge e Kinesis',
        icon: '📨',
        xp: 70,
        readTime: 13,
        desc: 'SQS (Standard vs FIFO, DLQ), SNS (topic fanout), EventBridge (event bus, rules, schedules), Kinesis (Streams vs Firehose vs Analytics).',
        seoDesc: 'AWS messaging services: SQS Standard FIFO DLQ, SNS topic fanout, EventBridge rules, Kinesis Streams Firehose.',
        keywords: 'sqs standard fifo dlq, sns fanout, eventbridge rules, kinesis streams firehose',
      },
      {
        slug: 'seguranca-avancada',
        title: 'Segurança Avançada: KMS, Secrets Manager e WAF',
        icon: '🔒',
        xp: 80,
        readTime: 15,
        desc: 'KMS envelope encryption, CMK vs AWS managed key, Secrets Manager vs Parameter Store, WAF rules, Shield Standard vs Advanced.',
        seoDesc: 'KMS envelope encryption, customer managed key CMK, Secrets Manager vs Parameter Store, AWS WAF rules, Shield Advanced.',
        keywords: 'kms envelope encryption, cmk customer managed key, secrets manager parameter store, waf rules shield advanced',
      },
      {
        slug: 'disaster-recovery',
        title: 'Disaster Recovery: RPO, RTO e 4 Estratégias',
        icon: '🆘',
        xp: 70,
        readTime: 13,
        desc: 'Backup & Restore, Pilot Light, Warm Standby, Multi-Site Active-Active — custo vs RTO/RPO, AWS Backup, cross-region DR.',
        seoDesc: 'AWS disaster recovery strategies: backup restore pilot light warm standby multi-site, RPO RTO, AWS Backup cross-region.',
        keywords: 'disaster recovery aws, backup restore pilot light warm standby, rpo rto, aws backup cross region',
      },
      {
        slug: 'cost-optimization-saa',
        title: 'Otimização de Custos: RI, Savings Plans e Spot',
        icon: '💵',
        xp: 60,
        readTime: 12,
        desc: 'Reserved Instances (standard/convertible), Savings Plans (compute/EC2), Spot Instances, Instance Scheduler, Trusted Advisor, Cost Allocation Tags.',
        seoDesc: 'AWS cost optimization: Reserved Instances, Savings Plans compute EC2, Spot Instances, Trusted Advisor, cost allocation tags.',
        keywords: 'reserved instances savings plans, spot instances aws, trusted advisor, cost allocation tags',
      },
      {
        slug: 'analytics-bigdata',
        title: 'Analytics: Athena, EMR, Kinesis e Glue',
        icon: '📈',
        xp: 60,
        readTime: 12,
        desc: 'Athena (serverless SQL on S3), EMR (Hadoop/Spark), Kinesis Data Streams vs Firehose, Glue ETL, Redshift Spectrum, QuickSight.',
        seoDesc: 'AWS analytics: Athena serverless SQL, EMR Spark Hadoop, Kinesis streams firehose, Glue ETL, Redshift Spectrum, QuickSight.',
        keywords: 'aws athena emr, kinesis streams firehose, aws glue etl, redshift spectrum quicksight',
      },
      {
        slug: 'migracao-transferencia-saa',
        title: 'Migração para o Arquiteto: DMS, SCT, MGN e DRS',
        icon: '🚚',
        xp: 65,
        readTime: 12,
        desc: 'DMS + SCT para migração de bancos heterogêneos, MGN para lift-and-shift, DRS para DR, DataSync, Transfer Family e Snow Family em cenários arquiteturais.',
        seoDesc: 'AWS SAA migration patterns: DMS Schema Conversion Tool, AWS MGN Application Migration, Elastic Disaster Recovery DRS, DataSync, Transfer Family, Snowball.',
        keywords: 'aws dms sct migration, aws mgn lift and shift, aws drs disaster recovery, datasync transfer family, snow family',
      },
      {
        slug: 'rede-hibrida-saa',
        title: 'Rede Híbrida: Direct Connect, VPN, PrivateLink e VPC Endpoints',
        icon: '🌉',
        xp: 70,
        readTime: 13,
        desc: 'Direct Connect + VIFs, Site-to-Site VPN, Client VPN, PrivateLink, Gateway vs Interface Endpoints, Route 53 Resolver híbrido e Transit Gateway inter-region.',
        seoDesc: 'AWS hybrid networking: Direct Connect DX, Site-to-Site VPN, Client VPN, PrivateLink, Gateway Interface Endpoints, Route 53 Resolver hybrid DNS.',
        keywords: 'aws direct connect dx, site to site vpn, client vpn aws, privatelink vpc endpoint, route 53 resolver hibrido',
      },
      {
        slug: 'ml-ia-arquiteto-saa',
        title: 'ML/IA para Arquiteto: SageMaker, Bedrock e Pipelines',
        icon: '🧬',
        xp: 60,
        readTime: 12,
        desc: 'Arquiteturas de inferência (real-time endpoint, serverless, async, batch), SageMaker + MLOps, integração com Bedrock e data lake alimentando pipelines de ML.',
        seoDesc: 'AWS SAA ML architecture: SageMaker real-time serverless async batch inference, Bedrock integration, MLOps pipelines, data lake feeds ML.',
        keywords: 'sagemaker endpoints arquitetura, bedrock integracao, mlops pipeline aws, data lake ml, inferencia real time serverless async',
      },
      {
        slug: 'simulado-saa-c03',
        title: 'Simulado SAA-C03 Comentado',
        icon: '🏆',
        xp: 100,
        readTime: 25,
        desc: '25 questões no estilo oficial SAA-C03 com explicações detalhadas. Arquitetura, decisões de design, trade-offs de custo e resiliência.',
        seoDesc: 'Simulado AWS SAA-C03 Solutions Architect Associate, 25 questões comentadas, preparação para o exame oficial AWS.',
        keywords: 'simulado saa-c03, solutions architect associate questoes, prova aws saa, preparacao exame saa',
      },
    ],
  },
  {
    id: 'trail6',
    name: 'Como Aprender',
    color: '#3fb950',
    icon: '🧠',
    desc: 'Psicologia do aprendizado: as técnicas com maior evidência científica para fixar conhecimento de verdade.',
    modules: [
      {
        slug: 'revisao-espacada',
        title: 'Revisão Espaçada: a técnica mais eficaz do mundo',
        icon: '🔁',
        xp: 50,
        readTime: 9,
        desc: 'Por que revisar 5 min hoje vale mais que estudar 2h amanhã — e como o algoritmo SM-2 do seu Hub aplica isso automaticamente.',
        seoDesc: 'Revisão espaçada SM-2 e FSRS: a técnica com maior evidência científica para retenção de longo prazo. Forgetting curve, Ebbinghaus, Anki.',
        keywords: 'revisao espacada, spaced repetition, sm-2, anki, curva do esquecimento, ebbinghaus, aprendizado cientifico',
      },
      {
        slug: 'recall-ativo',
        title: 'Recall Ativo: por que reler é quase inútil',
        icon: '🎯',
        xp: 45,
        readTime: 8,
        desc: 'A diferença entre reconhecer e lembrar. Por que o quiz é mais poderoso que o grifo, e como praticar recall ativo todos os dias.',
        seoDesc: 'Recall ativo vs reler: a ciência por trás dos quizzes e flashcards. Testing effect, Roediger & Karpicke, retrieval practice.',
        keywords: 'recall ativo, active recall, testing effect, flashcards, retrieval practice, como estudar melhor',
      },
      {
        slug: 'tecnica-feynman',
        title: 'Técnica Feynman: se não explica, não entendeu',
        icon: '🧑\u200d🏫',
        xp: 40,
        readTime: 7,
        desc: 'Como Richard Feynman aprendia qualquer coisa: ensinar para um iniciante imaginário expõe todas as lacunas.',
        seoDesc: 'Técnica Feynman: aprenda qualquer conceito ensinando em linguagem simples. Metacognição, protégé effect, gaps de conhecimento.',
        keywords: 'tecnica feynman, feynman technique, como aprender qualquer coisa, metacognicao, protege effect',
      },
      {
        slug: 'interleaving',
        title: 'Interleaving: por que misturar tópicos é melhor',
        icon: '🎲',
        xp: 45,
        readTime: 8,
        desc: 'Estudar A-A-A-B-B-B é intuitivo mas inferior a A-B-A-B-A-B. A ciência da variabilidade no aprendizado.',
        seoDesc: 'Interleaving: estudar tópicos intercalados supera blocos. Desirable difficulty, Rohrer, Bjork, prática variada e discriminativa.',
        keywords: 'interleaving, pratica intercalada, desirable difficulty, rohrer, bjork, como estudar multiplos topicos',
      },
      {
        slug: 'deep-work-pomodoro',
        title: 'Deep Work e Pomodoro: o combo da concentração',
        icon: '⏱️',
        xp: 40,
        readTime: 7,
        desc: 'Cal Newport + Cirillo: como criar blocos de foco profundo que realmente produzem conhecimento, sem queimar.',
        seoDesc: 'Deep work Cal Newport + Pomodoro Francesco Cirillo: técnicas de concentração profunda, bloqueio de distrações, foco intenso.',
        keywords: 'deep work cal newport, pomodoro francesco cirillo, como focar, bloco de estudo, foco profundo',
      },
      {
        slug: 'habito-estudo-diario',
        title: 'Hábito diário: como estudar sem depender de motivação',
        icon: '🪜',
        xp: 50,
        readTime: 9,
        desc: 'Atomic Habits aplicado ao aprendizado: sistema > motivação. Streak, fricção zero, identidade e o poder dos 5 minutos diários.',
        seoDesc: 'Como criar hábito diário de estudo: Atomic Habits James Clear aplicado ao aprendizado. Streak, identidade, fricção, regra dos 2 minutos.',
        keywords: 'habito estudo diario, atomic habits, james clear, streak estudos, identidade aprendizado, regra dois minutos',
      },
    ],
  },
  {
    id: 'trail7',
    name: 'DevOps & Containers',
    color: '#2496ed',
    icon: '📦',
    desc: 'Docker e Kubernetes do zero ao avançado — os dois pilares de toda infra moderna, explicados para durar.',
    modules: [
      {
        slug: 'docker-completo',
        title: 'Docker Completo: do zero ao production-ready',
        icon: '🐳',
        xp: 100,
        readTime: 22,
        desc: 'Imagens, containers, Dockerfile, Compose, volumes, redes, multi-stage builds, segurança e otimização — tudo que um dev precisa saber sobre Docker em um só lugar.',
        seoDesc: 'Docker tutorial completo em português: imagens, containers, Dockerfile, volumes, redes, Docker Compose, multi-stage, segurança e boas práticas.',
        keywords: 'docker tutorial completo, docker para iniciantes, dockerfile boas praticas, docker compose, multi-stage build, volumes docker, redes docker, containers vs vm',
      },
      {
        slug: 'kubernetes-completo',
        title: 'Kubernetes Completo: do Pod ao cluster de produção',
        icon: '☸️',
        xp: 120,
        readTime: 28,
        desc: 'Arquitetura do control plane, Pods, Deployments, Services, Ingress, ConfigMaps/Secrets, Storage, RBAC, autoscaling, Helm e troubleshooting — o guia definitivo do K8s.',
        seoDesc: 'Kubernetes tutorial completo em português: arquitetura, Pods, Deployments, Services, Ingress, ConfigMaps, Secrets, RBAC, HPA, Helm e kubectl essencial.',
        keywords: 'kubernetes tutorial completo, k8s para iniciantes, arquitetura kubernetes, pod deployment service, ingress kubernetes, rbac k8s, helm charts, hpa kubernetes, kubectl cheat sheet',
      },
      {
        slug: 'github-actions-cicd',
        title: 'GitHub Actions: CI/CD profissional do zero',
        icon: '🐙',
        xp: 90,
        readTime: 20,
        desc: 'Workflows, jobs, matrix, reusable workflows, secrets, OIDC para cloud, cache inteligente, release automatizado e deploy em Kubernetes — GH Actions como plataforma de CI/CD séria.',
        seoDesc: 'GitHub Actions tutorial completo PT-BR: workflows YAML, jobs, matrix, secrets, OIDC AWS/Azure, cache, reusable workflows, release e deploy em K8s.',
        keywords: 'github actions tutorial completo, ci cd github actions, workflow yaml, github actions oidc aws, reusable workflows, matrix build, deploy kubernetes github actions',
      },
      {
        slug: 'jenkins-pipelines',
        title: 'Jenkins Pipelines: o CI/CD da era enterprise',
        icon: '🏛️',
        xp: 85,
        readTime: 19,
        desc: 'Jenkinsfile declarativo, agents dinâmicos, shared libraries, Blue Ocean, credentials, integração com K8s e o porquê do Jenkins ainda ser o padrão em grandes empresas.',
        seoDesc: 'Jenkins tutorial completo PT-BR: pipeline declarativo, Jenkinsfile, agents Kubernetes, shared libraries, credentials, webhooks, Blue Ocean e migração de freestyle.',
        keywords: 'jenkins tutorial, jenkinsfile declarative pipeline, jenkins kubernetes agent, shared libraries jenkins, jenkins blue ocean, ci cd jenkins enterprise',
      },
      {
        slug: 'azure-devops-pipelines',
        title: 'Azure DevOps Pipelines: CI/CD na Microsoft Cloud',
        icon: '🔷',
        xp: 80,
        readTime: 18,
        desc: 'Azure Pipelines em YAML, stages, approvals, environments, service connections, templates, variable groups e deploy em AKS + App Service com gate de aprovação.',
        seoDesc: 'Azure DevOps Pipelines tutorial PT-BR: azure-pipelines.yml, stages, environments, approvals, service connections, templates, deploy em AKS.',
        keywords: 'azure devops pipelines, azure-pipelines yml, azure pipelines stages, service connection azure, variable groups, deploy aks azure devops',
      },
      {
        slug: 'rancher-multicluster',
        title: 'Rancher: gerenciando múltiplos clusters K8s sem sofrer',
        icon: '🐄',
        xp: 75,
        readTime: 16,
        desc: 'Rancher Manager, RKE2, importar clusters, Fleet para GitOps multi-cluster, RBAC unificado, projetos, monitoring e quando Rancher vale (ou não) a pena.',
        seoDesc: 'Rancher tutorial PT-BR: Rancher Manager, RKE2, multi-cluster, Fleet GitOps, RBAC, Projects, monitoring — como gerenciar dezenas de clusters Kubernetes.',
        keywords: 'rancher kubernetes, rancher manager, rke2, fleet gitops, multi cluster kubernetes, rancher vs argo cd, rancher rbac',
      },
    ],
  },
  {
    id: 'trail8',
    name: 'Engenharia de Software Moderna',
    color: '#e3b341',
    icon: '🏗️',
    desc: 'SDD, gerenciamento e criação de agents, testes profissionais, segurança real e arquitetura — deixar de ser coder e virar engenheiro de software de verdade.',
    modules: [
      {
        slug: 'engenheiro-vs-coder',
        title: 'Engenheiro vs Coder: o que mudou na era dos agents',
        icon: '🧭',
        xp: 60,
        readTime: 14,
        desc: 'Por que 80% do que você faz vai ser automatizado — e o que sobra como skill real: decompor problema, ler sistema, escrever spec, revisar PR de agent, tomar decisão de arquitetura.',
        seoDesc: 'Diferença entre coder e engenheiro de software em 2026: skills que importam, como parar de depender do prompt e virar profissional que entrega sistema de verdade.',
        keywords: 'engenheiro de software 2026, programador vs engenheiro, skills engenharia software ia, carreira developer ia, software engineer vs coder',
      },
      {
        slug: 'spec-driven-development',
        title: 'Spec-Driven Development (SDD): a nova espinha dorsal',
        icon: '📜',
        xp: 85,
        readTime: 18,
        desc: 'SDD não é documento morto: é spec executável que vira teste, código e PR. Anatomia de uma spec, workflow com agent, templates reais, controle de qualidade.',
        seoDesc: 'Spec-Driven Development em PT-BR: como escrever specs que agents transformam em código e testes, templates, workflow, boas práticas.',
        keywords: 'spec driven development, sdd, spec to code, specification agent coding, product requirements doc tech, prd para agent ia',
      },
      {
        slug: 'gerenciando-agents-ia',
        title: 'Gerenciando Agents: orquestração, contexto e custo',
        icon: '🎛️',
        xp: 80,
        readTime: 17,
        desc: 'Agent não é mágica — é processo com contexto, memória, ferramentas, orçamento e política. Como orquestrar múltiplos agents, controlar token, definir limites e auditar resultado.',
        seoDesc: 'Como gerenciar agents de IA em times profissionais: orquestração, contexto, custo, limites, políticas e auditoria. Guia real em PT-BR.',
        keywords: 'gerenciar agents ia, orquestracao agents, contexto agent ia, custo token llm, auditoria agent, multi agent workflow',
      },
      {
        slug: 'criando-agents-customizados',
        title: 'Criando Agents Customizados: do subagent ao MCP',
        icon: '🛠️',
        xp: 90,
        readTime: 19,
        desc: 'Como criar agents de verdade: subagents com system prompt curto, integração com tools via MCP (Model Context Protocol), sandbox, permissões, ciclos de vida.',
        seoDesc: 'Criando agents customizados com Claude Code e MCP: subagents, system prompt, tools, MCP server, sandbox, permissões — passo a passo em PT-BR.',
        keywords: 'criar agent customizado, mcp server tutorial, subagent claude, system prompt agent, agent coding protocol, claude agent sdk',
      },
      {
        slug: 'testes-profissionais',
        title: 'Testes Profissionais: pirâmide, propriedades, contrato e fuzz',
        icon: '🧪',
        xp: 85,
        readTime: 18,
        desc: 'Unit, integração, contrato, E2E, property-based, snapshot, mutation, fuzz, chaos. Qual usar, onde usar e por que cobertura sozinha mente.',
        seoDesc: 'Tipos de testes profissionais em 2026: pirâmide, contrato, property-based, fuzz, mutation, snapshot, E2E e cobertura inteligente. Guia em PT-BR.',
        keywords: 'tipos de testes software, piramide de testes, contract testing, property based testing, mutation testing, fuzz testing, cobertura de testes',
      },
      {
        slug: 'seguranca-software-real',
        title: 'Segurança de Software de Verdade: threat model ao SBOM',
        icon: '🛡️',
        xp: 90,
        readTime: 19,
        desc: 'Threat modeling (STRIDE), OWASP Top 10 de verdade, secrets, supply chain (SBOM, SLSA, SHA pinning), shift-left vs shift-right, DAST/SAST/IAST.',
        seoDesc: 'Segurança de software profissional em 2026: threat modeling STRIDE, OWASP Top 10, SBOM, SLSA, SAST/DAST, supply chain — guia real em PT-BR.',
        keywords: 'seguranca software, threat modeling stride, owasp top 10, sbom slsa, supply chain security, sast dast, shift left security',
      },
      {
        slug: 'arquitetura-software-moderna',
        title: 'Arquitetura Moderna: trade-offs, ADRs, C4 e evolução',
        icon: '🏛️',
        xp: 95,
        readTime: 20,
        desc: 'Monolito modular vs microserviços, DDD pragmático, ADRs (Architecture Decision Records), modelo C4, evolução sem big-rewrite, fitness functions.',
        seoDesc: 'Arquitetura de software moderna em 2026: monolito modular vs microserviços, DDD, ADR, modelo C4, fitness functions, evolução — tudo em PT-BR.',
        keywords: 'arquitetura software moderna, monolito modular, microservicos, ddd, adr architecture decision record, modelo c4, fitness functions',
      },
    ],
  },
];

export const LEVELS = [
  { level: 1, name: 'Curioso',         xpMin: 0,    xpMax: 100,  color: '#8b949e', icon: '🌱' },
  { level: 2, name: 'Aprendiz',        xpMin: 100,  xpMax: 250,  color: '#58a6ff', icon: '📚' },
  { level: 3, name: 'Praticante',      xpMin: 250,  xpMax: 500,  color: '#3fb950', icon: '⚡' },
  { level: 4, name: 'Desenvolvedor',   xpMin: 500,  xpMax: 800,  color: '#ffa657', icon: '🔧' },
  { level: 5, name: 'Especialista',    xpMin: 800,  xpMax: 1200, color: '#d2a8ff', icon: '🧠' },
  { level: 6, name: 'Arquiteto de IA', xpMin: 1200, xpMax: 1800, color: '#f78166', icon: '🏗️' },
  { level: 7, name: 'Mestre da IA',    xpMin: 1800, xpMax: 9999, color: '#ffa657', icon: '🚀' },
];

export interface BadgeDef {
  id: string;
  name: string;
  icon: string;
  desc: string;
  xpBonus: number;
}

export const BADGES_DEF: BadgeDef[] = [
  { id: 'first_step',     name: 'Primeiro Passo',      icon: '👣', desc: 'Completou seu primeiro módulo',         xpBonus: 10  },
  { id: 'quiz_perfect',   name: 'Gabarito',             icon: '🎯', desc: 'Acertou todas as questões de um quiz', xpBonus: 20  },
  { id: 'streak_3',       name: '3 Dias Seguidos',      icon: '🔥', desc: '3 dias de estudo consecutivos',        xpBonus: 30  },
  { id: 'streak_7',       name: 'Semana Perfeita',      icon: '💪', desc: '7 dias de estudo consecutivos',        xpBonus: 75  },
  { id: 'streak_30',      name: 'Mês Dedicado',         icon: '🏆', desc: '30 dias de estudo consecutivos',       xpBonus: 200 },
  { id: 'trail1_done',    name: 'Fundamentos Sólidos',  icon: '🏅', desc: 'Completou a Trilha 1 completa',        xpBonus: 100 },
  { id: 'trail2_done',    name: 'Arquitetura Profunda', icon: '🥇', desc: 'Completou a Trilha 2 completa',        xpBonus: 150 },
  { id: 'trail3_done',    name: 'Engenheiro de Agentes',icon: '💻', desc: 'Completou a Trilha 3 completa',        xpBonus: 175 },
  { id: 'trail4_done',    name: 'Cloud Practitioner',   icon: '☁️', desc: 'Completou a trilha AWS Cloud Practitioner (CLF-C02)', xpBonus: 200 },
  { id: 'trail5_done',    name: 'Solutions Architect',  icon: '🏛️', desc: 'Completou a trilha AWS Solutions Architect Associate (SAA-C03)', xpBonus: 300 },
  { id: 'trail6_done',    name: 'Meta-Aprendiz',        icon: '🧠', desc: 'Dominou as técnicas de psicologia do aprendizado', xpBonus: 150 },
  { id: 'trail7_done',    name: 'Container Engineer',   icon: '📦', desc: 'Dominou Docker e Kubernetes',          xpBonus: 250 },
  { id: 'trail8_done',    name: 'Engenheiro Sênior',     icon: '🏗️', desc: 'Completou a trilha de Engenharia de Software Moderna', xpBonus: 300 },
  { id: 'all_done',       name: 'Mestre Completo',      icon: '👑', desc: 'Completou TODAS as trilhas',           xpBonus: 500 },
  { id: 'speed_run',      name: 'Speed Run',            icon: '⚡', desc: 'Completou 3 módulos no mesmo dia',     xpBonus: 50  },
  { id: 'curious',        name: 'Muito Curioso',        icon: '🔍', desc: 'Revisitou um módulo já concluído',     xpBonus: 5   },
];

export function getLevelInfo(xp: number) {
  return LEVELS.find(l => xp >= l.xpMin && xp < l.xpMax) ?? LEVELS[LEVELS.length - 1];
}

export function getTrailProgress(trailModules: Module[], completedModules: string[]) {
  const done = trailModules.filter(m => completedModules.includes(m.slug)).length;
  return { done, total: trailModules.length, pct: Math.round((done / trailModules.length) * 100) };
}

/* ──────────────────────────────────────────────
   HUBS — temáticas editoriais que agrupam trilhas
──────────────────────────────────────────────── */

export const HUBS: Hub[] = [
  {
    id: 'hub-ia',
    slug: 'ia',
    name: 'Inteligência Artificial',
    shortName: 'IA',
    href: '/ia',
    color: '#58a6ff',
    icon: '🧠',
    tagline: 'Do conceito ao agent — sem hype, com profundidade.',
    desc: 'Três trilhas que cobrem a IA moderna por dentro: fundamentos matemáticos, arquiteturas além do LLM (KV cache, MoE, tool calling) e as ferramentas de código que reorganizaram o mercado dev.',
    trailIds: ['trail1', 'trail2', 'trail3'],
  },
  {
    id: 'hub-aws',
    slug: 'aws',
    name: 'AWS Cloud',
    shortName: 'AWS',
    href: '/aws',
    color: '#ff9900',
    icon: '☁️',
    tagline: 'Dois caminhos oficiais — CLF-C02 e SAA-C03 — com profundidade real.',
    desc: 'Certificação profissional da AWS: o Practitioner nivela os 4 domínios do CLF-C02, e o Solutions Architect Associate leva à arquitetura de verdade — resiliente, segura, performática e com custo otimizado.',
    trailIds: ['trail4', 'trail5'],
  },
  {
    id: 'hub-engenharia',
    slug: 'engenharia',
    name: 'Engenharia de Software',
    shortName: 'Engenharia',
    href: '/engenharia',
    color: '#e3b341',
    icon: '🏗️',
    tagline: 'DevOps + engenharia moderna — sair do coder, virar engenheiro.',
    desc: 'Duas trilhas para profissionalizar a stack: Docker + Kubernetes + CI/CD profissional, e engenharia de software na era dos agents — SDD, testes profissionais, segurança real e arquitetura.',
    trailIds: ['trail7', 'trail8'],
  },
  {
    id: 'hub-como-aprender',
    slug: 'como-aprender',
    name: 'Como Aprender',
    shortName: 'Como Aprender',
    href: '/como-aprender',
    color: '#3fb950',
    icon: '📚',
    tagline: 'Meta-aprendizado — as técnicas com maior evidência científica.',
    desc: 'Trilha transversal que ensina como o cérebro aprende: revisão espaçada, recall ativo, Feynman, interleaving, deep work e hábito diário. Complementa o mecanismo SRS do próprio Hub.',
    trailIds: ['trail6'],
  },
];

export function getHubBySlug(slug: string): Hub | undefined {
  return HUBS.find(h => h.slug === slug);
}

export function getHubForTrail(trailId: string): Hub | undefined {
  return HUBS.find(h => h.trailIds.includes(trailId));
}

export function getHubTrails(hub: Hub): Trail[] {
  return hub.trailIds
    .map(id => CURRICULUM.find(t => t.id === id))
    .filter((t): t is Trail => !!t);
}

export function getHubStats(hub: Hub, completedSlugs: string[] = []) {
  const trails = getHubTrails(hub);
  const modules = trails.flatMap(t => t.modules);
  const totalXp = modules.reduce((acc, m) => acc + m.xp, 0);
  const done = modules.filter(m => completedSlugs.includes(m.slug)).length;
  const minutes = modules.reduce((acc, m) => acc + m.readTime, 0);
  return {
    trailCount: trails.length,
    moduleCount: modules.length,
    totalXp,
    minutes,
    done,
    pct: modules.length === 0 ? 0 : Math.round((done / modules.length) * 100),
  };
}
