import * as path from 'path';
import { GeneratedFile, ScanResult } from '../core/types';
import { walk } from '../utils/fs';

const SOURCE_EXT = new Set(['.ts', '.tsx', '.js', '.jsx', '.py', '.go', '.java', '.rs']);

interface TreeNode {
  name: string;
  children: Map<string, TreeNode>;
  fileCount: number;
}

/**
 * Mermaid `graph TD` tree of the project's source layout — a static map
 * that gives any AI an immediate sense of structure.
 */
export async function generateArchitectureDiagram(
  scan: ScanResult,
  folder: string
): Promise<GeneratedFile> {
  const sourceRoot = path.join(scan.rootPath, scan.structure.sourceRoot);
  const files = await walk(sourceRoot, { maxDepth: 6 });
  const sources = files.filter((f) => SOURCE_EXT.has(path.extname(f)));

  const root: TreeNode = { name: scan.structure.sourceRoot, children: new Map(), fileCount: 0 };
  for (const f of sources) {
    const rel = path.relative(sourceRoot, f);
    const parts = rel.split(path.sep);
    insert(root, parts);
  }

  const lines: string[] = ['graph TD'];
  let counter = 0;
  const nextId = (): string => `n${counter++}`;

  function emit(node: TreeNode, parentId: string | null): void {
    const id = nextId();
    const label = node.fileCount > 0 ? `${node.name}<br/><i>${node.fileCount} files</i>` : node.name;
    lines.push(`    ${id}["${label}"]`);
    if (parentId) lines.push(`    ${parentId} --> ${id}`);
    for (const child of node.children.values()) emit(child, id);
  }

  emit(root, null);

  const today = new Date().toISOString().slice(0, 10);
  const content = `# Architecture — Source Tree

> Generated by AI Codebase Toolkit on ${today}. Run **AI Toolkit: Generate Architecture Diagram** to refresh.

## Module tree

\`\`\`mermaid
${lines.join('\n')}
\`\`\`

## Stats
- Source root: \`${scan.structure.sourceRoot}\`
- Total source files: ${sources.length}
- Frameworks: ${scan.stack.frameworks.join(', ') || 'none detected'}

## How to read
- Each node is a folder.
- Leaves with file counts are the actual modules.
- Use this as the high-level map; for deep inspection of a single module, use **Generate Module Flowchart**.
`;

  return { path: `${folder}/source-tree.md`, content };
}

function insert(root: TreeNode, parts: string[]): void {
  let node = root;
  for (let i = 0; i < parts.length; i++) {
    const part = parts[i];
    const isFile = i === parts.length - 1;
    if (isFile) {
      node.fileCount++;
      continue;
    }
    let next = node.children.get(part);
    if (!next) {
      next = { name: part, children: new Map(), fileCount: 0 };
      node.children.set(part, next);
    }
    node = next;
  }
}

