import { GeneratedFile, ScanResult } from '../core/types';

/**
 * Generates a complete VitePress documentation site, runnable locally with:
 *   npm install --prefix docs && npm run docs:dev
 *
 * Pages cover: overview, getting started, architecture, modules, API reference,
 * decisions (ADR index), specs (SDD index), contributing, glossary.
 *
 * The skeleton is filled with TODO(ai) markers so the user's AI can flesh out
 * each page from the actual codebase.
 */
export function generateDocsSite(scan: ScanResult): GeneratedFile[] {
  const projectName = inferProjectName(scan);
  const stackLine = `${scan.stack.language}${scan.stack.hasTypeScript ? ' (strict TS)' : ''}`;

  return [
    {
      path: 'docs/package.json',
      content: JSON.stringify(
        {
          name: `${projectName}-docs`,
          private: true,
          scripts: {
            'docs:dev': 'vitepress dev .',
            'docs:build': 'vitepress build .',
            'docs:preview': 'vitepress preview .',
          },
          devDependencies: { vitepress: '^1.2.0' },
        },
        null,
        2
      ) + '\n',
    },
    {
      path: 'docs/.vitepress/config.ts',
      content: `import { defineConfig } from 'vitepress';

export default defineConfig({
  title: '${projectName}',
  description: 'Project documentation generated by AI Codebase Toolkit.',
  lastUpdated: true,
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Architecture', link: '/architecture/overview' },
      { text: 'Reference', link: '/reference/api' },
      { text: 'Decisions', link: '/decisions/' },
      { text: 'Specs', link: '/specs/' },
    ],
    sidebar: {
      '/guide/': [
        { text: 'Getting started', link: '/guide/getting-started' },
        { text: 'Installation', link: '/guide/installation' },
        { text: 'Configuration', link: '/guide/configuration' },
        { text: 'Contributing', link: '/guide/contributing' },
      ],
      '/architecture/': [
        { text: 'Overview', link: '/architecture/overview' },
        { text: 'Source tree', link: '/architecture/source-tree' },
        { text: 'Modules', link: '/architecture/modules' },
        { text: 'Data model', link: '/architecture/data-model' },
        { text: 'Cross-cutting concerns', link: '/architecture/cross-cutting' },
      ],
      '/reference/': [
        { text: 'API', link: '/reference/api' },
        { text: 'CLI', link: '/reference/cli' },
        { text: 'Events', link: '/reference/events' },
        { text: 'Glossary', link: '/reference/glossary' },
      ],
    },
    search: { provider: 'local' },
    socialLinks: [],
  },
  markdown: {
    // Mermaid is supported via copy-paste of fenced blocks; for live rendering
    // add a Mermaid plugin of your choice.
  },
});
`,
    },
    {
      path: 'docs/index.md',
      content: `---
layout: home

hero:
  name: ${projectName}
  text: Project documentation
  tagline: ${stackLine} · ${scan.stack.frameworks.join(', ') || 'no major framework'}
  actions:
    - theme: brand
      text: Get started
      link: /guide/getting-started
    - theme: alt
      text: Architecture
      link: /architecture/overview

features:
  - title: Guide
    details: How to install, configure, and contribute.
  - title: Architecture
    details: System overview, modules, data model.
  - title: Reference
    details: API, CLI, events, glossary.
  - title: Decisions & Specs
    details: ADRs and SDD specs that drive the system.
---
`,
    },
    {
      path: 'docs/guide/getting-started.md',
      content: page(
        'Getting started',
        `## Prerequisites
- ${scan.stack.packageManager}
- ${stackLine} runtime

## Install
\`\`\`bash
${scan.stack.packageManager} install
\`\`\`

## Run
\`\`\`bash
${scan.stack.scripts.dev ? scan.stack.packageManager + ' run dev' : '<add a dev script>'}
\`\`\`

## Test
\`\`\`bash
${scan.stack.scripts.test ? scan.stack.packageManager + ' run test' : '<add a test script>'}
\`\`\`
`
      ),
    },
    { path: 'docs/guide/installation.md', content: page('Installation', '<!-- TODO(ai): expand installation steps for each supported environment. -->') },
    { path: 'docs/guide/configuration.md', content: page('Configuration', '<!-- TODO(ai): document env vars, config files, and feature flags. -->') },
    { path: 'docs/guide/contributing.md', content: page('Contributing', '<!-- TODO(ai): document branching model, commit style, review process. -->') },
    {
      path: 'docs/architecture/overview.md',
      content: page(
        'Architecture overview',
        `## High-level view

\`\`\`mermaid
graph LR
  Client --> API
  API --> Service
  Service --> Database[(Database)]
\`\`\`

<!-- TODO(ai): replace with the real high-level diagram of this system. -->

## Components
- _Component A_ — _responsibility_
- _Component B_ — _responsibility_

## Tech choices
- Stack: ${stackLine}
- Frameworks: ${scan.stack.frameworks.join(', ') || 'n/a'}
`
      ),
    },
    {
      path: 'docs/architecture/source-tree.md',
      content: page(
        'Source tree',
        '<!-- TODO(ai): paste the output of "AI Toolkit: Generate Architecture Diagram" here, or import it. -->'
      ),
    },
    { path: 'docs/architecture/modules.md', content: page('Modules', '<!-- TODO(ai): one section per top-level module with purpose, public API, and dependencies. -->') },
    { path: 'docs/architecture/data-model.md', content: page('Data model', '<!-- TODO(ai): ER diagram (Mermaid) and entity descriptions. -->') },
    { path: 'docs/architecture/cross-cutting.md', content: page('Cross-cutting concerns', '<!-- TODO(ai): logging, auth, error handling, observability, security. -->') },
    { path: 'docs/reference/api.md', content: page('API reference', '<!-- TODO(ai): endpoint-by-endpoint reference with request/response examples. -->') },
    { path: 'docs/reference/cli.md', content: page('CLI reference', '<!-- TODO(ai): one section per command with flags and examples. -->') },
    { path: 'docs/reference/events.md', content: page('Events', '<!-- TODO(ai): published/consumed events with payloads. -->') },
    { path: 'docs/reference/glossary.md', content: page('Glossary', '<!-- TODO(ai): domain terms and their definitions. -->') },
    { path: 'docs/decisions/index.md', content: page('Architecture decisions (ADRs)', '<!-- TODO(ai): list ADRs from docs/adr/ with one-line summaries. -->') },
    { path: 'docs/specs/index.md', content: page('Specifications (SDD)', '<!-- TODO(ai): list SDD specs from docs/specs/ with status and owner. -->') },
    {
      path: 'docs/README.md',
      content: `# Documentation site

This folder contains a [VitePress](https://vitepress.dev) site for the project's docs.

## Run locally
\`\`\`bash
cd docs
npm install
npm run docs:dev
\`\`\`

Then open the printed URL (default http://localhost:5173).

## Build static site
\`\`\`bash
npm run docs:build
\`\`\`

The static site is emitted to \`.vitepress/dist\`.

## Authoring
Pages are plain Markdown. Mermaid diagrams use fenced \\\`\\\`\\\`mermaid blocks.
The structure is generated by **AI Toolkit: Generate Documentation Site** —
re-run it to regenerate the skeleton when the project evolves significantly.
`,
    },
    {
      path: 'docs/.gitignore',
      content: 'node_modules/\n.vitepress/dist/\n.vitepress/cache/\n',
    },
  ];
}

function page(title: string, body: string): string {
  return `# ${title}\n\n${body}\n`;
}

function inferProjectName(scan: ScanResult): string {
  const last = scan.rootPath.split(/[\\/]/).filter(Boolean).pop() ?? 'project';
  return last;
}
