import { GeneratedFile, ScanResult } from '../core/types';
import { computeManifest, manifestComment } from '../drift/manifest';

/**
 * Generates ONBOARDING.md — a structured guide for new contributors based on
 * the scan result (language, scripts, conventions, git history, frameworks).
 */
export function generateOnboarding(scan: ScanResult): GeneratedFile {
  const hash = computeManifest(scan);
  const lang = scan.stack.language;
  const pm = scan.stack.packageManager;
  const scripts = scan.stack.scripts;
  const frameworks = scan.stack.frameworks.filter((f) => f !== 'unknown');
  const naming = scan.conventions.fileNaming;
  const src = scan.structure.sourceRoot;

  const content = `<!-- Generated by AI Codebase Toolkit. -->
${manifestComment(hash)}

# Onboarding Guide

Welcome to this **${lang}** project. This guide will help you get up and running quickly.

## Prerequisites

${prerequisitesList(lang, pm)}

## First-time setup

${setupSteps(lang, pm)}

## Running the project

${runningSteps(scripts)}

## Running tests

${testingSteps(scripts, lang)}

## Key files to read first

${keyFiles(scan)}

## Architecture overview

${architectureOverview(src, frameworks, scan)}

## Working agreements

${workingAgreements(naming, scan)}
`;

  return { path: 'ONBOARDING.md', content };
}

function prerequisitesList(lang: string, pm: string): string {
  const lines: string[] = [];

  switch (lang) {
    case 'typescript':
    case 'javascript':
      lines.push('- Node.js 18+');
      break;
    case 'python':
      lines.push('- Python 3.10+');
      break;
    case 'go':
      lines.push('- Go 1.20+');
      break;
    case 'java':
      lines.push('- JDK 17+');
      break;
    case 'rust':
      lines.push('- Rust (stable toolchain via rustup)');
      break;
    case 'csharp':
      lines.push('- .NET 8 SDK');
      break;
    default:
      lines.push(`- Runtime for ${lang}`);
  }

  if (pm && pm !== 'unknown' && pm !== 'go' && pm !== 'make' && pm !== 'cmake') {
    lines.push(`- ${pm}`);
  }

  lines.push('- Git');

  return lines.join('\n');
}

function setupSteps(lang: string, pm: string): string {
  const steps: string[] = ['1. Clone the repository and navigate into it.'];

  switch (pm) {
    case 'npm':
      steps.push('2. Install dependencies: `npm install`');
      break;
    case 'yarn':
      steps.push('2. Install dependencies: `yarn install`');
      break;
    case 'pnpm':
      steps.push('2. Install dependencies: `pnpm install`');
      break;
    case 'bun':
      steps.push('2. Install dependencies: `bun install`');
      break;
    case 'pip':
      steps.push('2. Create a virtual environment: `python -m venv .venv && source .venv/bin/activate`');
      steps.push('3. Install dependencies: `pip install -r requirements.txt`');
      break;
    case 'poetry':
      steps.push('2. Install dependencies: `poetry install`');
      steps.push('3. Activate the shell: `poetry shell`');
      break;
    case 'cargo':
      steps.push('2. Build the project: `cargo build`');
      break;
    case 'go':
      steps.push('2. Download modules: `go mod download`');
      break;
    default:
      if (lang === 'go') {
        steps.push('2. Download modules: `go mod download`');
      } else {
        steps.push('2. Install dependencies as described by the project package manager.');
      }
  }

  return steps.join('\n');
}

function runningSteps(scripts: ScanResult['stack']['scripts']): string {
  if (scripts.dev) {
    return `Run the development server:\n\n\`\`\`\n${scripts.dev}\n\`\`\``;
  }
  if (scripts.start) {
    return `Start the application:\n\n\`\`\`\n${scripts.start}\n\`\`\``;
  }
  return 'Refer to the project README or package configuration for the start command.';
}

function testingSteps(scripts: ScanResult['stack']['scripts'], lang: string): string {
  if (scripts.test) {
    return `Run the test suite:\n\n\`\`\`\n${scripts.test}\n\`\`\``;
  }
  if (lang === 'go') {
    return 'Run the test suite:\n\n```\ngo test ./...\n```';
  }
  if (lang === 'python') {
    return 'Run the test suite:\n\n```\npytest\n```';
  }
  return 'Run the test suite as described in the project documentation.';
}

function keyFiles(scan: ScanResult): string {
  const hotFiles = scan.gitHistory?.hotFiles ?? [];
  const items: string[] = [];

  if (hotFiles.length > 0) {
    // Use hot files (most frequently changed) as the key files to read
    for (const f of hotFiles.slice(0, 6)) {
      items.push(`- \`${f}\``);
    }
  } else {
    // Fall back to entry points in the source root
    const src = scan.structure.sourceRoot;
    const candidates = [
      `${src}/index.ts`,
      `${src}/main.ts`,
      `${src}/app.ts`,
      `${src}/index.js`,
      `${src}/main.js`,
    ];
    for (const c of candidates.slice(0, 4)) {
      items.push(`- \`${c}\``);
    }
  }

  return items.length > 0 ? items.join('\n') : '- Explore the source root to find key modules.';
}

function architectureOverview(
  src: string,
  frameworks: string[],
  scan: ScanResult
): string {
  const lines: string[] = [];

  lines.push(`**Source root:** \`${src}/\``);

  if (frameworks.length > 0) {
    lines.push(`**Frameworks:** ${frameworks.join(', ')}`);
  }

  const rootFolders = scan.structure.rootFolders.filter(
    (f) => !['node_modules', '.git', 'dist', 'build', 'out'].includes(f)
  );
  if (rootFolders.length > 0) {
    lines.push('**Top-level structure:**');
    for (const folder of rootFolders.slice(0, 8)) {
      lines.push(`- \`${folder}/\``);
    }
  }

  if (scan.stack.isMonorepo) {
    lines.push('');
    lines.push('This is a **monorepo**. Each package has its own configuration.');
  }

  return lines.join('\n');
}

function workingAgreements(naming: string, scan: ScanResult): string {
  const lines: string[] = [
    `- **File naming:** ${naming}`,
  ];

  if (scan.conventions.importStyle) {
    lines.push(`- **Import style:** ${scan.conventions.importStyle} imports`);
  }

  if (scan.conventions.formatter) {
    lines.push(`- **Formatter:** ${scan.conventions.formatter} (run before committing)`);
  }

  if (scan.conventions.indentStyle) {
    const size = scan.conventions.indentSize ? ` (${scan.conventions.indentSize})` : '';
    lines.push(`- **Indentation:** ${scan.conventions.indentStyle}${size}`);
  }

  if (scan.stack.scripts.lint) {
    lines.push(`- **Lint:** \`${scan.stack.scripts.lint}\` — fix all errors before submitting`);
  }

  if (scan.structure.hasTests) {
    lines.push('- **Tests:** all new code must include tests; keep the suite green');
  }

  if (scan.gitHistory?.conventionalCommits) {
    lines.push('- **Commits:** follow Conventional Commits format (e.g. `feat:`, `fix:`, `chore:`)');
  }

  return lines.join('\n');
}
