import { getModuleMetadata } from '@/lib/metadata';
import { ModuleLayout } from '@/components/ModuleLayout';
import type { QuizQuestion } from '@/components/ModuleLayout';
import {
  Section,
  Callout,
  ComparisonTable,
} from '@/components/article/primitives';

export const metadata = getModuleMetadata('ingles-1000-frases');

const ACCENT = '#22d3ee';

const quiz: QuizQuestion[] = [
  {
    question: 'Como dizer "Vai fundo!" ou "Manda ver!" para encorajar alguém em inglês?',
    options: [
      'Go well!',
      'Go for it! / Break a leg!',
      'Go to it!',
      'Go ahead!',
    ],
    correct: 1,
    explanation:
      '"Go for it!" é a expressão mais comum para encorajar alguém a tentar algo. "Break a leg!" é uma expressão idiomática usada para desejar boa sorte (especialmente antes de performances). "Good luck!" também funciona em qualquer contexto.',
  },
  {
    question: 'Qual é a frase correta para pedir a conta no restaurante?',
    options: [
      'Give me the check!',
      'Could I have the check, please? / Can I have the bill, please?',
      'I want the check.',
      'Bring the bill now.',
    ],
    correct: 1,
    explanation:
      '"Could I have the check/bill, please?" é a forma mais educada e comum. "Check" é mais usado nos EUA; "bill" é mais britânico. Ambas são amplamente entendidas. "Give me" e "I want" soam abrupto em contexto de restaurante.',
  },
  {
    question: 'Como responder quando alguém te agradece e você quer soar natural?',
    options: [
      'No problem! / Of course! / My pleasure! / Don\'t mention it!',
      'You are welcome. (única opção correta)',
      'Thanks.',
      'OK.',
    ],
    correct: 1,
    explanation:
      'Existem muitas formas de responder a um agradecimento em inglês: "You\'re welcome!", "No problem!", "Of course!", "My pleasure!", "Don\'t mention it!", "Not at all!", "Anytime!" — todas são naturais e corretas dependendo do contexto.',
  },
  {
    question: 'Qual expressão significa "O negócio é comigo" (eu pago)?',
    options: [
      "It's free.",
      "It's on me.",
      "I'll pay you back.",
      "Charge me.",
    ],
    correct: 1,
    explanation:
      '"It\'s on me" significa "estou pagando" ou "é por minha conta". Exemplo: "Don\'t worry about the coffee — it\'s on me." Outra expressão comum: "I\'ve got this" ou "Let me treat you."',
  },
];

export default function Page() {
  return (
    <ModuleLayout
      slug="ingles-1000-frases"
      title="As 1000 frases mais usadas do inglês"
      icon="💬"
      xp={80}
      readTime={35}
      trailName="Inglês Prático"
      trailColor={ACCENT}
      nextSlug="ingles-fase1-pronomes-to-be"
      nextTitle="Fase 1 — Pronomes pessoais e verbo To Be"
      relatedSlugs={['ingles-1000-palavras', 'ingles-fase7-verbos-modais', 'ingles-fase2-perguntas']}
      quiz={quiz}
    >
      <Content />
    </ModuleLayout>
  );
}

function Content() {
  return (
    <div className="flex flex-col gap-8 text-sm leading-7">
      <p className="text-base leading-8" style={{ color: 'var(--ffv-muted)' }}>
        Esta é uma página de <strong>referência completa</strong>. As 1000 frases mais usadas do inglês cotidiano,
        organizadas por situação. Não tente ler tudo de uma vez — use por categoria conforme a necessidade e revise
        regularmente. Com as primeiras 200 frases, você já consegue se virar em 80% das situações.
      </p>

      <Section title="Como usar esta página" accent={ACCENT}>
        <Callout tone="info">
          <strong>Prioridades:</strong> saudações e apresentações → trabalho → emergências → viagem → restaurante.
          Grave áudio de si mesmo dizendo as frases — ouvir sua própria voz treina a fluência. As frases de
          emergência são as mais importantes de decorar na ordem certa.
        </Callout>
      </Section>

      <Section title="Saudações e apresentações (100 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ['Hello!', 'Olá!'],
            ['Hi!', 'Oi!'],
            ['Hey!', 'Ei! / Oi!'],
            ['Good morning!', 'Bom dia!'],
            ['Good afternoon!', 'Boa tarde!'],
            ['Good evening!', 'Boa tarde / Boa noite! (ao chegar)'],
            ['Good night!', 'Boa noite! (ao se despedir)'],
            ['How are you?', 'Como você está?'],
            ["How's it going?", 'Como vai?'],
            ["How's everything?", 'Como está tudo?'],
            ["What's up?", 'O que há de novo? / Tudo bem?'],
            ["What's new?", 'O que há de novo?'],
            ['Fine, thank you!', 'Bem, obrigado(a)!'],
            ['Pretty good, thanks!', 'Muito bem, obrigado(a)!'],
            ['Not bad, thanks.', 'Não muito mal, obrigado(a).'],
            ['Could be better.', 'Poderia estar melhor.'],
            ['A bit tired, to be honest.', 'Um pouco cansado(a), para ser honesto(a).'],
            ['What is your name?', 'Qual é o seu nome?'],
            ['My name is...', 'Meu nome é...'],
            ['Nice to meet you!', 'Prazer em conhecê-lo(a)!'],
            ['The pleasure is mine.', 'O prazer é meu.'],
            ['Where are you from?', 'De onde você é?'],
            ["I'm from Brazil.", 'Sou do Brasil.'],
            ['How old are you?', 'Quantos anos você tem?'],
            ["I'm 25 years old.", 'Tenho 25 anos.'],
            ['What do you do for a living?', 'O que você faz da vida?'],
            ["I'm a developer.", 'Sou desenvolvedor(a).'],
            ["I'm a student.", 'Sou estudante.'],
            ["I'm a teacher.", 'Sou professor(a).'],
            ["I'm married.", 'Sou casado(a).'],
            ["I'm single.", 'Sou solteiro(a).'],
            ['Do you have children?', 'Você tem filhos?'],
            ["Yes, I have a son.", 'Sim, tenho um filho.'],
            ["Yes, I have a daughter.", 'Sim, tenho uma filha.'],
            ["No, I don't have children.", 'Não, não tenho filhos.'],
            ['See you later!', 'Até mais tarde!'],
            ['See you soon!', 'Até logo!'],
            ['See you tomorrow!', 'Até amanhã!'],
            ['Take care!', 'Cuide-se!'],
            ['Talk to you soon!', 'Falo com você em breve!'],
            ['Have a great day!', 'Tenha um ótimo dia!'],
            ['You too!', 'Você também!'],
            ['Same to you!', 'Igualmente!'],
            ['It was nice talking to you.', 'Foi um prazer conversar com você.'],
            ['Long time no see!', 'Há quanto tempo!'],
            ['How have you been?', 'Como você tem estado?'],
            ["I've been great!", 'Tenho estado ótimo(a)!'],
            ["It's been a while.", 'Já faz um tempo.'],
            ['I missed you!', 'Saudades de você!'],
            ['Welcome!', 'Bem-vindo(a)!'],
            ['Welcome back!', 'Bem-vindo(a) de volta!'],
            ['This is my friend...', 'Este/a é meu/minha amigo/a...'],
            ['Have you met...?', 'Você já conheceu...?'],
            ['We have already met.', 'Já nos conhecemos.'],
            ['Nice to see you again!', 'Prazer em vê-lo(a) novamente!'],
            ["How's your family?", 'Como está sua família?'],
            ["They're doing well, thanks.", 'Estão bem, obrigado(a).'],
            ['Are you new here?', 'Você é novo(a) aqui?'],
            ["Yes, I just started.", 'Sim, acabei de começar.'],
            ["What do you do in your free time?", 'O que você faz no seu tempo livre?'],
            ["I love reading / cooking / traveling.", 'Adoro ler / cozinhar / viajar.'],
            ['Do you like sports?', 'Você gosta de esportes?'],
            ['What kind of music do you like?', 'Que tipo de música você gosta?'],
            ['Where do you live?', 'Onde você mora?'],
            ["I live in São Paulo.", 'Moro em São Paulo.'],
            ['Do you speak any other languages?', 'Você fala outros idiomas?'],
            ["I'm learning English.", 'Estou aprendendo inglês.'],
            ["My English is not perfect.", 'Meu inglês não é perfeito.'],
            ["I'm sorry, I don't speak English well.", 'Desculpe, não falo inglês bem.'],
            ['Nice haircut!', 'Corte de cabelo bonito!'],
            ['You look great!', 'Você está ótimo(a)!'],
            ["That's a nice shirt.", 'Que camisa bonita.'],
            ['Happy birthday!', 'Feliz aniversário!'],
            ['Many happy returns!', 'Muitos anos de vida!'],
            ['Congratulations!', 'Parabéns!'],
            ['Happy New Year!', 'Feliz Ano Novo!'],
            ['Merry Christmas!', 'Feliz Natal!'],
            ['Happy holidays!', 'Boas festas!'],
            ['I have to go now.', 'Preciso ir agora.'],
            ['It was great seeing you.', 'Foi ótimo te ver.'],
            ['Let us keep in touch.', 'Vamos nos manter em contato.'],
            ['Add me on LinkedIn.', 'Me adicione no LinkedIn.'],
            ['What is your email?', 'Qual é o seu e-mail?'],
            ["Here's my card.", 'Aqui está meu cartão.'],
            ['Are you on social media?', 'Você está nas redes sociais?'],
            ['Follow me on Instagram.', 'Me siga no Instagram.'],
            ['Can we meet sometime?', 'Podemos nos encontrar algum dia?'],
            ["Let's grab a coffee sometime.", 'Vamos tomar um café algum dia.'],
            ['Thank you for your time.', 'Obrigado(a) pelo seu tempo.'],
            ['It was a pleasure.', 'Foi um prazer.'],
            ['I hope to see you again soon.', 'Espero te ver novamente em breve.'],
            ['Good luck!', 'Boa sorte!'],
            ['All the best!', 'Tudo de bom!'],
            ['Take it easy!', 'Se cuida! / Vai com calma!'],
            ['Safe travels!', 'Boa viagem!'],
            ['Have fun!', 'Divirta-se!'],
            ['Enjoy!', 'Aproveite!'],
            ['Stay safe!', 'Fique seguro(a)!'],
          ]}
        />
      </Section>

      <Section title="No trabalho e negócios (100 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ['Can we schedule a meeting?', 'Podemos agendar uma reunião?'],
            ["I'll send you the agenda.", 'Vou te enviar a pauta.'],
            ['Let me know if that works for you.', 'Me diga se isso serve para você.'],
            ['Are you available on Tuesday?', 'Você está disponível na terça?'],
            ['My schedule is full this week.', 'Minha agenda está cheia esta semana.'],
            ['Can we reschedule?', 'Podemos remarcar?'],
            ['I need to move our meeting.', 'Preciso remarcar nossa reunião.'],
            ["Sorry I'm late.", 'Desculpe o atraso.'],
            ["Let's get started.", 'Vamos começar.'],
            ['Shall we begin?', 'Podemos começar?'],
            ['The purpose of this meeting is...', 'O objetivo desta reunião é...'],
            ["Let's move to the next item.", 'Vamos para o próximo item.'],
            ['Does anyone have questions?', 'Alguém tem perguntas?'],
            ["I'd like to add something.", 'Gostaria de acrescentar algo.'],
            ['Can you clarify that?', 'Você pode esclarecer isso?'],
            ['Could you elaborate?', 'Você poderia elaborar?'],
            ["I didn't quite follow. Could you repeat?", 'Não entendi bem. Pode repetir?'],
            ['I see your point.', 'Entendo o que você quer dizer.'],
            ['I agree with that.', 'Concordo com isso.'],
            ['I disagree.', 'Discordo.'],
            ["I'm not sure about that.", 'Não tenho certeza sobre isso.'],
            ["That's a good point.", 'Boa observação.'],
            ["That's an interesting perspective.", 'É uma perspectiva interessante.'],
            ["Let me think about it.", 'Deixe-me pensar sobre isso.'],
            ["I'll get back to you on that.", 'Vou te dar um retorno sobre isso.'],
            ['What is the deadline?', 'Qual é o prazo?'],
            ["I'll have it ready by Friday.", 'Terei pronto até sexta.'],
            ["I'm working on it.", 'Estou trabalhando nisso.'],
            ["I'll send you an update.", 'Vou te enviar uma atualização.'],
            ['Can you send me the file?', 'Você pode me enviar o arquivo?'],
            ['Please CC me on that email.', 'Por favor, coloque-me em cópia nesse e-mail.'],
            ['I need your approval.', 'Preciso da sua aprovação.'],
            ["Let's loop in the manager.", 'Vamos incluir o gerente.'],
            ['Can you follow up on this?', 'Você pode dar seguimento a isso?'],
            ['This is urgent.', 'Isso é urgente.'],
            ['Can we prioritize this?', 'Podemos priorizar isso?'],
            ["That's out of scope.", 'Isso está fora do escopo.'],
            ["That's not in the budget.", 'Isso não está no orçamento.'],
            ['We need to reduce costs.', 'Precisamos reduzir custos.'],
            ["I'll need more resources.", 'Vou precisar de mais recursos.'],
            ["Let's take this offline.", 'Vamos resolver isso fora da reunião.'],
            ['Can you take the lead on this?', 'Você pode liderar isso?'],
            ["I'll delegate that to my team.", 'Vou delegar isso para minha equipe.'],
            ['Thank you for your feedback.', 'Obrigado(a) pelo seu feedback.'],
            ['The project is on track.', 'O projeto está no caminho certo.'],
            ["We're behind schedule.", 'Estamos atrasados em relação ao cronograma.'],
            ["We're ahead of schedule.", 'Estamos adiantados em relação ao cronograma.'],
            ["Let's wrap up.", 'Vamos concluir.'],
            ['Any final comments?', 'Algum comentário final?'],
            ['Thank you everyone.', 'Obrigado(a) a todos.'],
            ['Great job, team!', 'Ótimo trabalho, equipe!'],
            ['The results exceeded expectations.', 'Os resultados superaram as expectativas.'],
            ["I'll present the findings.", 'Apresentarei as conclusões.'],
            ['As you can see on the slide...', 'Como podem ver no slide...'],
            ['In conclusion...', 'Em conclusão...'],
            ['To summarize...', 'Para resumir...'],
            ['Our main takeaway is...', 'Nossa principal conclusão é...'],
            ["I'm open to questions.", 'Estou aberto(a) a perguntas.'],
            ["I'd appreciate your input.", 'Agradeceria sua contribuição.'],
            ["Let's set a follow-up meeting.", 'Vamos agendar uma reunião de acompanhamento.'],
            ['Who is responsible for this action item?', 'Quem é responsável por essa ação?'],
            ['Please update the task board.', 'Por favor, atualize o quadro de tarefas.'],
            ["I'll document this decision.", 'Vou documentar essa decisão.'],
            ['What are the next steps?', 'Quais são os próximos passos?'],
            ['Can we get alignment on this?', 'Podemos nos alinhar sobre isso?'],
            ["Let's revisit this next week.", 'Vamos revisitar isso semana que vem.'],
            ["I'm available for a quick call.", 'Estou disponível para uma chamada rápida.'],
            ['Please review and approve.', 'Por favor, revise e aprove.'],
            ['This needs more research.', 'Isso precisa de mais pesquisa.'],
            ["I'll escalate this if needed.", 'Vou escalar isso se necessário.'],
            ["That's a risk we need to address.", 'Esse é um risco que precisamos endereçar.'],
            ['The stakeholders are aligned.', 'As partes interessadas estão alinhadas.'],
            ['We delivered on time.', 'Entregamos no prazo.'],
            ['Great work on this project.', 'Ótimo trabalho neste projeto.'],
            ['Well done!', 'Muito bem!'],
            ['Keep up the good work.', 'Continue com o bom trabalho.'],
            ['I appreciate your effort.', 'Aprecio seu esforço.'],
            ["You've done a fantastic job.", 'Você fez um trabalho fantástico.'],
            ['Thank you for your hard work.', 'Obrigado(a) pelo seu trabalho árduo.'],
            ["I'm impressed.", 'Estou impressionado(a).'],
            ['You exceeded my expectations.', 'Você superou minhas expectativas.'],
            ['This is exactly what we needed.', 'Isso é exatamente o que precisávamos.'],
            ["Let's celebrate this win.", 'Vamos celebrar essa conquista.'],
            ['Congratulations on the promotion!', 'Parabéns pela promoção!'],
            ["I'd like to discuss my performance.", 'Gostaria de discutir meu desempenho.'],
            ['Can we set up a 1-on-1?', 'Podemos agendar um encontro individual?'],
            ["I'd like to grow in this area.", 'Gostaria de crescer nessa área.'],
            ["What are my development areas?", 'Quais são minhas áreas de desenvolvimento?'],
            ["I'm applying for this position.", 'Estou me candidatando para essa posição.'],
            ['Here is my resume.', 'Aqui está meu currículo.'],
            ['Thank you for the opportunity.', 'Obrigado(a) pela oportunidade.'],
            ['When can I expect a response?', 'Quando posso esperar uma resposta?'],
            ['I look forward to hearing from you.', 'Aguardo seu retorno.'],
            ['It was a pleasure meeting you.', 'Foi um prazer conhecê-lo(a).'],
            ['I am available to start immediately.', 'Estou disponível para começar imediatamente.'],
          ]}
        />
      </Section>

      <Section title="Viagem e turismo (100 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ['Where is the airport?', 'Onde fica o aeroporto?'],
            ['Can you call me a taxi?', 'Você pode me chamar um táxi?'],
            ['How much does it cost?', 'Quanto custa?'],
            ['Where can I buy a ticket?', 'Onde posso comprar uma passagem?'],
            ['One-way or round trip?', 'Só de ida ou ida e volta?'],
            ['One round trip to... please.', 'Uma passagem de ida e volta para..., por favor.'],
            ['Which platform/gate?', 'Qual plataforma/portão?'],
            ['Is this seat taken?', 'Este lugar está ocupado?'],
            ['Excuse me, how do I get to...?', 'Com licença, como chego a...?'],
            ['Turn left.', 'Vire à esquerda.'],
            ['Turn right.', 'Vire à direita.'],
            ["It's straight ahead.", 'É em frente.'],
            ['Take the subway to...', 'Pegue o metrô até...'],
            ['Take the bus number...', 'Pegue o ônibus número...'],
            ['How far is it?', 'Qual é a distância?'],
            ['How long does it take?', 'Quanto tempo leva?'],
            ['Is there a direct route?', 'Há uma rota direta?'],
            ['I need to check in.', 'Preciso fazer o check-in.'],
            ['What time is check-out?', 'A que horas é o check-out?'],
            ['Do you have a room available?', 'Você tem quarto disponível?'],
            ["I'd like a single room.", 'Gostaria de um quarto individual.'],
            ["I'd like a double room.", 'Gostaria de um quarto duplo.'],
            ['Is breakfast included?', 'O café da manhã está incluído?'],
            ['Can I have a wake-up call at 7am?', 'Pode me acordar às 7h?'],
            ['Where is the nearest ATM?', 'Onde fica o caixa eletrônico mais próximo?'],
            ['Where is the nearest pharmacy?', 'Onde fica a farmácia mais próxima?'],
            ['Can you recommend a restaurant?', 'Você pode recomendar um restaurante?'],
            ['What are the must-see sights?', 'Quais são os pontos turísticos imperdíveis?'],
            ["Is there a tourist map?", 'Tem um mapa turístico?'],
            ['Where is the tourist information center?', 'Onde fica o centro de informações turísticas?'],
            ["Can I exchange currency here?", 'Posso trocar dinheiro aqui?'],
            ['What is the exchange rate?', 'Qual é a taxa de câmbio?'],
            ['Do you accept US dollars?', 'Vocês aceitam dólares americanos?'],
            ['Do you accept credit cards?', 'Vocês aceitam cartão de crédito?'],
            ['Is Wi-Fi included?', 'O Wi-Fi está incluído?'],
            ['What is the Wi-Fi password?', 'Qual é a senha do Wi-Fi?'],
            ['Can I leave my luggage here?', 'Posso deixar minha bagagem aqui?'],
            ['My luggage is lost.', 'Minha bagagem foi extraviada.'],
            ['I need to file a complaint.', 'Preciso registrar uma reclamação.'],
            ['The room is not clean.', 'O quarto não está limpo.'],
            ['The air conditioning is not working.', 'O ar-condicionado não está funcionando.'],
            ['Can I have a different room?', 'Posso ter um quarto diferente?'],
            ['I have a reservation.', 'Tenho uma reserva.'],
            ['Under the name...', 'No nome de...'],
            ['Can I extend my stay?', 'Posso estender minha estadia?'],
            ["I'd like to check out tomorrow.", 'Gostaria de fazer check-out amanhã.'],
            ['Can I have a receipt?', 'Posso ter um recibo?'],
            ['Is there a bus to the city center?', 'Há um ônibus para o centro da cidade?'],
            ['How often do the buses run?', 'Com que frequência os ônibus passam?'],
            ['Where is the bus stop?', 'Onde fica a parada de ônibus?'],
            ['I missed my flight.', 'Perdi meu voo.'],
            ['I need to rebook my flight.', 'Preciso remarcar meu voo.'],
            ['When is the next flight to...?', 'Quando é o próximo voo para...?'],
            ['Is the flight on time?', 'O voo está no horário?'],
            ['The flight is delayed.', 'O voo está atrasado.'],
            ['Where is the customs?', 'Onde fica a alfândega?'],
            ['I have nothing to declare.', 'Não tenho nada a declarar.'],
            ['I have something to declare.', 'Tenho algo a declarar.'],
            ['This is a gift.', 'Isso é um presente.'],
            ['This is for personal use.', 'Isso é para uso pessoal.'],
            ['How long will you be staying?', 'Por quanto tempo vai ficar?'],
            ['I will be staying for one week.', 'Vou ficar por uma semana.'],
            ['What is the purpose of your visit?', 'Qual é o motivo da sua visita?'],
            ['Tourism / Business.', 'Turismo / Negócios.'],
            ['Where are you staying?', 'Onde você vai ficar?'],
            ["I'm staying at...hotel.", 'Vou ficar no hotel...'],
            ['Do you have travel insurance?', 'Você tem seguro viagem?'],
            ['My passport is lost.', 'Meu passaporte foi perdido.'],
            ['I need to contact my embassy.', 'Preciso entrar em contato com minha embaixada.'],
            ['Where is the Brazilian embassy?', 'Onde fica a embaixada brasileira?'],
            ['Can you take a photo of me?', 'Pode tirar uma foto minha?'],
            ['Can we take a selfie together?', 'Podemos tirar uma selfie juntos?'],
            ['This view is breathtaking!', 'Essa vista é de tirar o fôlego!'],
            ['This city is amazing.', 'Essa cidade é incrível.'],
            ["I'd love to come back someday.", 'Adoraria voltar algum dia.'],
            ['This is the best trip of my life.', 'Esta é a melhor viagem da minha vida.'],
            ["I'm jet-lagged.", 'Estou com jet lag.'],
            ["I'm homesick.", 'Estou com saudade de casa.'],
            ["I'd like a map of the city.", 'Gostaria de um mapa da cidade.'],
            ["Is there a guided tour?", 'Tem tour guiado?'],
            ['How much is the entrance fee?', 'Quanto é a taxa de entrada?'],
            ["Is it free to enter?", 'A entrada é gratuita?'],
            ["What time does it open/close?", 'A que horas abre/fecha?'],
            ['Is photography allowed?', 'Fotografia é permitida?'],
            ["I'd like a souvenir.", 'Gostaria de um souvenir.'],
            ["Where's the gift shop?", 'Onde fica a loja de presentes?'],
            ['Can you wrap it as a gift?', 'Pode embrulhar como presente?'],
            ['Do you have this in a smaller/bigger size?', 'Tem isso em tamanho menor/maior?'],
            ["This is too expensive.", 'Isso está muito caro.'],
            ["Can you give me a discount?", 'Pode me dar um desconto?'],
            ["I'll take it!", 'Vou levar!'],
            ["I'm just browsing, thanks.", 'Só estou olhando, obrigado(a).'],
            ['Do you ship internationally?', 'Vocês enviam internacionalmente?'],
            ["I'd like to return this.", 'Gostaria de devolver isso.'],
          ]}
        />
      </Section>

      <Section title="Compras e restaurante (100 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ['A table for two, please.', 'Uma mesa para dois, por favor.'],
            ['Do you have a reservation?', 'Vocês têm reserva?'],
            ["Yes, under the name...", 'Sim, no nome de...'],
            ["No, we don't have a reservation.", 'Não, não temos reserva.'],
            ['How long is the wait?', 'Quanto tempo é a espera?'],
            ["Could we sit by the window?", 'Poderíamos sentar perto da janela?'],
            ['Can I see the menu, please?', 'Posso ver o cardápio, por favor?'],
            ['What do you recommend?', 'O que você recomenda?'],
            ["What's the specialty of the house?", 'Qual é a especialidade da casa?'],
            ["I'd like the..., please.", 'Gostaria do/da..., por favor.'],
            ["I'll have the same.", 'Vou querer o mesmo.'],
            ['How would you like your steak?', 'Como você quer seu bife?'],
            ['Medium, please.', 'Ao ponto, por favor.'],
            ['Well done, please.', 'Bem passado, por favor.'],
            ['Rare, please.', 'Mal passado, por favor.'],
            ["I'm allergic to nuts.", 'Sou alérgico(a) a nozes.'],
            ["I'm allergic to gluten.", 'Sou alérgico(a) a glúten.'],
            ['No onions, please.', 'Sem cebola, por favor.'],
            ['Is this dish spicy?', 'Esse prato é apimentado?'],
            ['Could I have a glass of water?', 'Poderia me trazer um copo de água?'],
            ['Sparkling or still?', 'Com gás ou sem gás?'],
            ["Could we have some more bread?", 'Poderia nos trazer mais pão?'],
            ['Excuse me, my order is wrong.', 'Com licença, meu pedido está errado.'],
            ['I ordered the..., not the...', 'Pedi o/a..., não o/a...'],
            ['This is cold. Could you reheat it?', 'Isso está frio. Poderia esquentar?'],
            ['Could I have the check, please?', 'Poderia trazer a conta, por favor?'],
            ['Can we split the bill?', 'Podemos dividir a conta?'],
            ['Is service included?', 'O serviço está incluído?'],
            ['Keep the change.', 'Pode ficar com o troco.'],
            ['It was delicious!', 'Estava delicioso!'],
            ['My compliments to the chef.', 'Meus parabéns ao chef.'],
            ["I'll leave a review.", 'Vou deixar uma avaliação.'],
            ["Can I have a takeaway box?", 'Pode me dar uma caixa para viagem?'],
            ['For here or to go?', 'Para comer aqui ou para viagem?'],
            ["To go, please.", 'Para viagem, por favor.'],
            ['How much is this?', 'Quanto custa isso?'],
            ['Do you have this in blue/red?', 'Você tem isso em azul/vermelho?'],
            ['What size is this?', 'Qual é o tamanho disso?'],
            ['Can I try it on?', 'Posso experimentar?'],
            ['Where is the fitting room?', 'Onde fica o provador?'],
            ["It fits perfectly.", 'Ficou perfeitamente.'],
            ["It's a bit tight.", 'Está um pouco apertado.'],
            ["It's too big.", 'Está muito grande.'],
            ['Do you have a larger/smaller size?', 'Tem um tamanho maior/menor?'],
            ['Do you accept credit/debit cards?', 'Vocês aceitam cartão de crédito/débito?'],
            ['Can I pay by contactless?', 'Posso pagar por aproximação?'],
            ['Do you have any promotions?', 'Vocês têm alguma promoção?'],
            ['Is there a sale on?', 'Tem alguma liquidação?'],
            ["I'm just looking.", 'Só estou olhando.'],
            ['Can I have a bag?', 'Posso ter uma sacola?'],
            ['Can I have a receipt?', 'Posso ter um recibo?'],
            ['Can I return this?', 'Posso devolver isso?'],
            ['What is the return policy?', 'Qual é a política de devolução?'],
            ['I have a defective product.', 'Tenho um produto com defeito.'],
            ['Do you offer gift wrapping?', 'Vocês oferecem embrulho para presente?'],
            ['Is there a warranty?', 'Tem garantia?'],
            ["I'd like to exchange this.", 'Gostaria de trocar isso.'],
            ["Is this on sale?", 'Isso está na promoção?'],
            ["What's the original price?", 'Qual é o preço original?'],
            ["How much is the discount?", 'Qual é o desconto?'],
            ["That's a good deal!", 'É um bom negócio!'],
            ["I'll think about it.", 'Vou pensar.'],
            ['Can you hold this for me?', 'Pode guardar isso para mim?'],
            ["I'd like to place an order.", 'Gostaria de fazer um pedido.'],
            ['What is the delivery time?', 'Qual é o prazo de entrega?'],
            ['Do you deliver to Brazil?', 'Vocês entregam no Brasil?'],
            ['Can I track my order?', 'Posso rastrear meu pedido?'],
            ['I have a discount code.', 'Tenho um código de desconto.'],
            ['The item is out of stock.', 'O item está esgotado.'],
            ['When will it be back in stock?', 'Quando volta ao estoque?'],
            ["Can I preorder?", 'Posso fazer um pedido antecipado?'],
            ["I'd like to cancel my order.", 'Gostaria de cancelar meu pedido.'],
            ['Can I speak to the manager?', 'Posso falar com o gerente?'],
            ['I am not satisfied with the service.', 'Não estou satisfeito(a) com o serviço.'],
            ['This is not what I expected.', 'Isso não é o que eu esperava.'],
            ["I'd like a refund.", 'Gostaria de um reembolso.'],
            ['The total comes to...', 'O total é de...'],
            ["That's more than I expected.", 'Isso é mais do que eu esperava.'],
            ['Can you break a $100 bill?', 'Você pode trocar uma nota de 100?'],
            ["I don't have exact change.", 'Não tenho troco exato.'],
            ['Keep the change.', 'Pode ficar com o troco.'],
            ['Do you have a loyalty card?', 'Vocês têm cartão fidelidade?'],
            ["I'm a regular customer.", 'Sou cliente frequente.'],
            ['Can I use this coupon?', 'Posso usar este cupom?'],
            ['Do you price match?', 'Vocês fazem equiparação de preços?'],
            ["I saw it cheaper online.", 'Vi mais barato online.'],
            ["This is a birthday gift.", 'Isso é um presente de aniversário.'],
            ["Can you add a gift note?", 'Pode adicionar um cartão?'],
            ["I'd like gift wrapping.", 'Gostaria de embrulho para presente.'],
            ["What's your best seller?", 'Qual é o produto mais vendido?'],
            ["Do you have any new arrivals?", 'Tem novidades?'],
            ['Just browsing for now.', 'Só estou olhando por enquanto.'],
            ["I'll come back later.", 'Vou voltar mais tarde.'],
            ["You've been very helpful.", 'Você foi muito prestativo(a).'],
            ['Thank you for your help!', 'Obrigado(a) pela sua ajuda!'],
            ["I'll be a regular customer.", 'Serei cliente regular.'],
          ]}
        />
      </Section>

      <Section title="Emergências e saúde (100 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ['Help!', 'Socorro!'],
            ['Call the police!', 'Chame a polícia!'],
            ['Call an ambulance!', 'Chame uma ambulância!'],
            ['Call the fire department!', 'Chame os bombeiros!'],
            ['I need a doctor.', 'Preciso de um médico.'],
            ["I don't feel well.", 'Não estou me sentindo bem.'],
            ['I am in pain.', 'Estou com dor.'],
            ['I have a headache.', 'Estou com dor de cabeça.'],
            ['I have a stomachache.', 'Estou com dor de barriga.'],
            ['I have a fever.', 'Estou com febre.'],
            ['I have a sore throat.', 'Estou com dor de garganta.'],
            ['I have chest pain.', 'Estou com dor no peito.'],
            ['I feel dizzy.', 'Estou me sentindo tonto(a).'],
            ['I feel nauseous.', 'Estou com náusea.'],
            ['I have been vomiting.', 'Estive vomitando.'],
            ['I have a rash.', 'Estou com uma erupção cutânea.'],
            ['I have been bitten by something.', 'Fui picado(a) por algo.'],
            ["I'm having trouble breathing.", 'Estou com dificuldade para respirar.'],
            ['I think I broke my arm.', 'Acho que quebrei o braço.'],
            ['I twisted my ankle.', 'Torci o tornozelo.'],
            ['I cut myself.', 'Me cortei.'],
            ['I need stitches.', 'Preciso de pontos.'],
            ["I'm bleeding.", 'Estou sangrando.'],
            ["I'm allergic to penicillin.", 'Sou alérgico(a) a penicilina.'],
            ["I'm allergic to aspirin.", 'Sou alérgico(a) a aspirina.'],
            ['I take medication for...', 'Tomo medicamento para...'],
            ['I have diabetes.', 'Tenho diabetes.'],
            ['I have high blood pressure.', 'Tenho pressão alta.'],
            ['I have a heart condition.', 'Tenho problema cardíaco.'],
            ['I am pregnant.', 'Estou grávida.'],
            ['Where is the nearest hospital?', 'Onde fica o hospital mais próximo?'],
            ['Where is the nearest pharmacy?', 'Onde fica a farmácia mais próxima?'],
            ['Is there a doctor available?', 'Há um médico disponível?'],
            ['I need to see a specialist.', 'Preciso ver um especialista.'],
            ['Can I have a prescription?', 'Posso ter uma receita médica?'],
            ['Do you have this medication?', 'Você tem este medicamento?'],
            ['What is the dosage?', 'Qual é a dosagem?'],
            ['How many times a day?', 'Quantas vezes por dia?'],
            ['Should I take it with food?', 'Devo tomar com comida?'],
            ['What are the side effects?', 'Quais são os efeitos colaterais?'],
            ['I need pain relief.', 'Preciso de analgésico.'],
            ['Do you have bandages?', 'Você tem curativos?'],
            ['I need an ice pack.', 'Preciso de uma bolsa de gelo.'],
            ['Call emergency number 911 / 190.', 'Ligue para emergência 911 / 190.'],
            ["I've been robbed.", 'Fui roubado(a).'],
            ["I've been mugged.", 'Fui assaltado(a).'],
            ['My wallet was stolen.', 'Minha carteira foi roubada.'],
            ['My passport was stolen.', 'Meu passaporte foi roubado.'],
            ['My phone was stolen.', 'Meu celular foi roubado.'],
            ["I've lost my bag.", 'Perdi minha bolsa.'],
            ['I need to file a police report.', 'Preciso registrar um boletim de ocorrência.'],
            ['Where is the nearest police station?', 'Onde fica a delegacia mais próxima?'],
            ["I don't know who did it.", 'Não sei quem fez isso.'],
            ['I can describe the person.', 'Posso descrever a pessoa.'],
            ['The person was tall/short.', 'A pessoa era alta/baixa.'],
            ['I need to contact my embassy.', 'Preciso entrar em contato com minha embaixada.'],
            ['My documents are in order.', 'Meus documentos estão em ordem.'],
            ['Can you help me?', 'Você pode me ajudar?'],
            ['I am lost.', 'Estou perdido(a).'],
            ['I need directions.', 'Preciso de instruções para chegar.'],
            ['I am in danger.', 'Estou em perigo.'],
            ['This is an emergency.', 'Esta é uma emergência.'],
            ['Please hurry!', 'Por favor, se apresse!'],
            ["Don't move.", 'Não se mova.'],
            ['Stay calm.', 'Fique calmo(a).'],
            ['Everything will be okay.', 'Tudo vai ficar bem.'],
            ['Someone needs help.', 'Alguém precisa de ajuda.'],
            ['Is anyone hurt?', 'Alguém está ferido?'],
            ['There has been an accident.', 'Houve um acidente.'],
            ['There is a fire.', 'Há um incêndio.'],
            ['Please evacuate the building.', 'Por favor, evacue o prédio.'],
            ['Follow the emergency exit signs.', 'Siga as placas de saída de emergência.'],
            ["Don't use the elevator.", 'Não use o elevador.'],
            ["I can't find my child.", 'Não consigo encontrar meu filho.'],
            ["My child is missing.", 'Meu filho está desaparecido.'],
            ["I've had a car accident.", 'Tive um acidente de carro.'],
            ['No one is hurt.', 'Ninguém se machucou.'],
            ['I need a tow truck.', 'Preciso de um guincho.'],
            ["The car broke down.", 'O carro quebrou.'],
            ['I have a flat tire.', 'Tenho um pneu furado.'],
            ["I ran out of gas.", 'Fiquei sem gasolina.'],
            ['I am locked out of my car.', 'Fiquei preso fora do meu carro.'],
            ["I need a locksmith.", 'Preciso de um chaveiro.'],
            ['Is there a gas station nearby?', 'Há um posto de gasolina próximo?'],
            ['I need roadside assistance.', 'Preciso de assistência na estrada.'],
            ['My child swallowed something.', 'Minha criança engoliu algo.'],
            ['I think I was poisoned.', 'Acho que fui envenenado(a).'],
            ['I overdosed on medication.', 'Tomei medicamento em excesso.'],
            ["I'm having a panic attack.", 'Estou tendo um ataque de pânico.'],
            ["I'm having a severe allergic reaction.", 'Estou tendo uma reação alérgica grave.'],
            ['I need an EpiPen.', 'Preciso de um EpiPen.'],
            ['Is there an AED nearby?', 'Há um desfibrilador por perto?'],
            ['I know CPR.', 'Sei fazer RCP.'],
            ['The person is unconscious.', 'A pessoa está inconsciente.'],
            ['The person is not breathing.', 'A pessoa não está respirando.'],
            ["Don't leave me alone.", 'Não me deixe sozinho(a).'],
          ]}
        />
      </Section>

      <Section title="Frases para aprender inglês e pedir ajuda (50 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ["I don't understand.", 'Não entendo.'],
            ['Could you speak more slowly, please?', 'Poderia falar mais devagar, por favor?'],
            ['Could you repeat that, please?', 'Poderia repetir, por favor?'],
            ['How do you say... in English?', 'Como se diz... em inglês?'],
            ['What does ... mean?', 'O que significa ...?'],
            ['Can you write that down?', 'Você pode escrever isso?'],
            ["I'm learning English.", 'Estou aprendendo inglês.'],
            ["My English isn't perfect.", 'Meu inglês não é perfeito.'],
            ["I'm sorry for my English.", 'Me desculpe pelo meu inglês.'],
            ['Do you speak Portuguese?', 'Você fala português?'],
            ['Is there anyone who speaks Portuguese?', 'Tem alguém que fala português?'],
            ['Can you help me understand this?', 'Pode me ajudar a entender isso?'],
            ["I'm confused.", 'Estou confuso(a).'],
            ['Let me check my dictionary.', 'Deixe-me verificar no meu dicionário.'],
            ['I think I understand.', 'Acho que entendi.'],
            ['Am I pronouncing this correctly?', 'Estou pronunciando isso corretamente?'],
            ['Could you help me with this sentence?', 'Poderia me ajudar com esta frase?'],
            ["I need to practice my English.", 'Preciso praticar meu inglês.'],
            ['Can you correct me if I make a mistake?', 'Pode me corrigir se eu errar?'],
            ['What is the correct way to say this?', 'Qual é a forma correta de dizer isso?'],
            ['Is this grammatically correct?', 'Isso está gramaticalmente correto?'],
            ['How do you spell that?', 'Como se soletra isso?'],
            ["What's another way to say this?', 'Qual é outra forma de dizer isso?"],
            ["Is this formal or informal?", 'Isso é formal ou informal?'],
            ["What's the difference between A and B?", 'Qual é a diferença entre A e B?'],
            ["Can you give me an example?", 'Pode me dar um exemplo?'],
            ["I've never heard that expression before.", 'Nunca ouvi essa expressão antes.'],
            ['That is a new word for me.', 'Essa é uma palavra nova para mim.'],
            ["I'll look it up later.", 'Vou pesquisar depois.'],
            ['How do native speakers say this?', 'Como os nativos dizem isso?'],
            ["Is this an idiom?", 'Isso é uma expressão idiomática?'],
            ["What does this idiom mean?", 'O que significa essa expressão idiomática?'],
            ["Can you translate this for me?", 'Pode traduzir isso para mim?'],
            ["I understand the words but not the meaning.", 'Entendo as palavras mas não o significado.'],
            ["Could you say that in simpler words?", 'Poderia dizer isso com palavras mais simples?'],
            ["What level would you say my English is?", 'Em que nível você diria que está meu inglês?'],
            ["I want to improve my vocabulary.", 'Quero melhorar meu vocabulário.'],
            ["I want to improve my pronunciation.", 'Quero melhorar minha pronúncia.'],
            ["I watch movies in English to practice.", 'Assisto filmes em inglês para praticar.'],
            ["I listen to podcasts in English.", 'Ouço podcasts em inglês.'],
            ["I read books in English.", 'Leio livros em inglês.'],
            ["English is a fascinating language.", 'O inglês é uma língua fascinante.'],
            ["Languages are my passion.", 'Idiomas são minha paixão.'],
            ["I hope to be fluent one day.", 'Espero ser fluente um dia.'],
            ["Fluency takes time and practice.", 'Fluência leva tempo e prática.'],
            ["Don't be afraid to make mistakes.", 'Não tenha medo de cometer erros.'],
            ["Mistakes help you learn.", 'Erros ajudam a aprender.'],
            ["Practice makes perfect.", 'Praticar leva à perfeição.'],
            ["Every day is a chance to improve.", 'Todo dia é uma chance de melhorar.'],
            ["Thank you for your patience.", 'Obrigado(a) pela sua paciência.'],
          ]}
        />
      </Section>

      <Section title="Frases cotidianas e expressões idiomáticas (150 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português / Explicação']}
          rows={[
            ['Hold on.', 'Espera um momento.'],
            ['Just a moment, please.', 'Só um momento, por favor.'],
            ["I'll be right back.", 'Já volto.'],
            ['Sorry to bother you.', 'Desculpe incomodar.'],
            ['No worries!', 'Sem problemas!'],
            ["Don't worry about it.", 'Não se preocupe com isso.'],
            ["It's on me.", 'Essa é por minha conta. (eu pago)'],
            ['What a coincidence!', 'Que coincidência!'],
            ["I can't believe it!", 'Não acredito!'],
            ["That's amazing!", 'Isso é incrível!'],
            ["That's too bad.", 'Que pena.'],
            ["I'm sorry to hear that.", 'Sinto muito por isso.'],
            ['Congratulations!', 'Parabéns!'],
            ['Good luck!', 'Boa sorte!'],
            ['Break a leg!', 'Boa sorte! (expressão idiomática, especialmente para performances)'],
            ['Happy birthday!', 'Feliz aniversário!'],
            ['Happy New Year!', 'Feliz Ano Novo!'],
            ['Merry Christmas!', 'Feliz Natal!'],
            ['What a shame!', 'Que vergonha / Que pena!'],
            ['It could be worse.', 'Poderia ser pior.'],
            ['It happens.', 'Acontece.'],
            ["You're welcome.", 'De nada.'],
            ["Don't mention it.", 'Não precisa agradecer.'],
            ['My pleasure.', 'Com prazer.'],
            ['Of course!', 'Claro!'],
            ['Absolutely!', 'Com certeza!'],
            ['Definitely!', 'Definitivamente!'],
            ['Not at all!', 'De maneira nenhuma! / Claro que não!'],
            ['By the way...', 'A propósito...'],
            ['As I was saying...', 'Como eu estava dizendo...'],
            ['To be honest...', 'Para ser honesto(a)...'],
            ['In my opinion...', 'Na minha opinião...'],
            ['As far as I know...', 'Até onde eu sei...'],
            ["I'm not sure.", 'Não tenho certeza.'],
            ['I have no idea.', 'Não faço ideia.'],
            ['It depends.', 'Depende.'],
            ['Let me think...', 'Deixe-me pensar...'],
            ['Give me a second.', 'Me dá um segundo.'],
            ["I'm on my way.", 'Estou a caminho.'],
            ["I'll be there soon.", 'Estarei lá em breve.'],
            ["I'm running late.", 'Estou atrasado(a).'],
            ['Can we postpone?', 'Podemos adiar?'],
            ['That reminds me...', 'Isso me lembra...'],
            ['Speaking of which...', 'Por falar nisso...'],
            ['I almost forgot!', 'Quase esqueci!'],
            ['Better late than never.', 'Antes tarde do que nunca.'],
            ['Every cloud has a silver lining.', 'Todo mal tem um bem. / Não há mal que sempre dure.'],
            ["It's a piece of cake.", 'É moleza. / É mamão com açúcar.'],
            ['Time flies.', 'O tempo voa.'],
            ['The more the merrier.', 'Quanto mais, melhor.'],
            ['No pain, no gain.', 'Sem dor, sem resultado.'],
            ['Actions speak louder than words.', 'Ações falam mais alto que palavras.'],
            ['The ball is in your court.', 'A bola está no seu campo. (a decisão é sua)'],
            ["Hit the nail on the head.", 'Acertou em cheio.'],
            ["Beat around the bush.", 'Enrolar / Rodeios.'],
            ["Back to square one.", 'Voltou à estaca zero.'],
            ["Break the ice.", 'Quebrar o gelo.'],
            ["Cut corners.", 'Fazer corpo mole / fazer de qualquer jeito.'],
            ["Under the weather.", 'Sentindo-se mal / indisposto.'],
            ["Bite the bullet.", 'Engolir o sapo. / Aguentar firme.'],
            ['The tip of the iceberg.', 'A ponta do iceberg.'],
            ["It's raining cats and dogs.", 'Está chovendo muito.'],
            ['Once in a blue moon.', 'De vez em quando / raramente.'],
            ['Speak of the devil!', 'Falando no diabo!'],
            ["Costs an arm and a leg.", 'Custa os olhos da cara.'],
            ["Pull someone's leg.", 'Estar gozando / fazer gracinha.'],
            ["Let the cat out of the bag.", 'Contar o segredo / revelar algo.'],
            ['Kill two birds with one stone.', 'Matar dois coelhos com uma cajadada.'],
            ["Bite off more than you can chew.", 'Pegar mais do que pode aguentar.'],
            ["On the fence.", 'Em cima do muro. (indeciso)'],
            ["Let it go.", 'Deixa para lá.'],
            ["Move on.", 'Seguir em frente.'],
            ["Get over it.", 'Supere isso.'],
            ["I hear you.", 'Entendo você. / Estou ouvindo.'],
            ["That makes sense.", 'Faz sentido.'],
            ["Fair enough.", 'Justo. / Tudo bem.'],
            ['Fair point.', 'Boa observação.'],
            ['Good point.', 'Boa observação.'],
            ["I never thought about it that way.", 'Nunca pensei desta forma.'],
            ["That's interesting.", 'Que interessante.'],
            ['Tell me more.', 'Me conta mais.'],
            ['How did that go?', 'Como foi?'],
            ['It went well.', 'Foi bem.'],
            ['Not so well.', 'Não muito bem.'],
            ['What happened?', 'O que aconteceu?'],
            ['Long story.', 'É uma longa história.'],
            ["I'll explain later.", 'Vou explicar depois.'],
            ["It's complicated.", 'É complicado.'],
            ["You won't believe this.", 'Você não vai acreditar nisso.'],
            ['Guess what?', 'Adivinha?'],
            ['No way!', 'De jeito nenhum! / Não acredito!'],
            ['Are you serious?', 'Você está falando sério?'],
            ["That's crazy!", 'Isso é loucura!'],
            ['I know, right?', 'Eu sei, né?'],
            ['I told you so.', 'Eu disse!'],
            ["It's not a big deal.", 'Não é grande coisa.'],
            ['Take it easy.', 'Relaxa. / Vai com calma.'],
            ["Don't stress.", 'Não estressa.'],
            ['You can do it!', 'Você consegue!'],
            ['Keep it up!', 'Continue assim!'],
            ['Well done!', 'Muito bem!'],
            ["I'm proud of you.", 'Estou orgulhoso(a) de você.'],
            ['That must be hard.', 'Isso deve ser difícil.'],
            ['I feel the same way.', 'Sinto o mesmo.'],
            ['I understand how you feel.', 'Entendo como você se sente.'],
            ["That's life.", 'É a vida.'],
            ["What's done is done.", 'O que foi feito, foi feito.'],
            ["Let's change the subject.", 'Vamos mudar de assunto.'],
            ['Go for it!', 'Vai em frente! / Vai fundo!'],
            ['You got this!', 'Você consegue! / Manda ver!'],
            ["Don't give up!", 'Não desista!'],
            ['Stay positive.', 'Mantenha o pensamento positivo.'],
            ['Look on the bright side.', 'Veja o lado positivo.'],
            ['Everything happens for a reason.', 'Tudo acontece por uma razão.'],
            ['Live in the moment.', 'Viva o momento.'],
            ['Enjoy the journey.', 'Aproveite o percurso.'],
            ["Life is short.", 'A vida é curta.'],
            ['Make the most of it.', 'Aproveite ao máximo.'],
            ["It is what it is.", 'É o que é.'],
            ['Worse things have happened.', 'Já passei por coisa pior.'],
            ["I'm over it.", 'Já superei.'],
            ["Moving on.", 'Seguindo em frente.'],
            ['New chapter.', 'Novo capítulo.'],
            ["Let's do this!", 'Vamos nessa!'],
            ["Here we go!", 'Lá vamos nós!'],
            ['Ready or not!', 'Preparado ou não!'],
            ["I'm all in.", 'Estou totalmente comprometido(a).'],
            ['Count me in.', 'Pode me incluir.'],
            ['Count me out.', 'Pode me excluir.'],
            ["I'm in.", 'Estou dentro.'],
            ["I'm out.", 'Estou fora.'],
            ['Deal!', 'Combinado!'],
            ['No deal.', 'Sem acordo.'],
            ["It's a deal.", 'É um acordo.'],
            ["You have a deal.", 'Você tem um acordo.'],
            ['Sounds like a plan.', 'Parece um bom plano.'],
            ["Let's make it happen.", 'Vamos fazer acontecer.'],
          ]}
        />
      </Section>

      <Section title="Frases telefônicas e mensagens (100 frases)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ['Can I speak to...?', 'Posso falar com...?'],
            ['Who is calling, please?', 'Quem está ligando, por favor?'],
            ['This is... speaking.', 'Aqui é...'],
            ['Hold the line, please.', 'Não desligte, por favor.'],
            ["I'll put you through.", 'Vou te transferir.'],
            ["He/She is not available right now.", 'Ele/Ela não está disponível agora.'],
            ['Can I take a message?', 'Posso anotar um recado?'],
            ["I'll call you back.", 'Vou te ligar de volta.'],
            ['Can you call me back?', 'Você pode me ligar de volta?'],
            ['The line is busy.', 'A linha está ocupada.'],
            ['Sorry, bad connection.', 'Desculpe, conexão ruim.'],
            ["I can't hear you well.", 'Não estou ouvindo bem.'],
            ['Can you speak up?', 'Pode falar mais alto?'],
            ['You are breaking up.', 'Sua ligação está caindo.'],
            ["I'll text you.", 'Vou te mandar mensagem.'],
            ['Can you send me a text?', 'Pode me mandar um texto?'],
            ['Can you send me your number?', 'Pode me mandar seu número?'],
            ['I just wanted to check in.', 'Só queria saber como você está.'],
            ['Thank you for calling.', 'Obrigado(a) por ligar.'],
            ["Sorry I missed your call.", 'Desculpe por não ter atendido.'],
            ["I'll get back to you as soon as I can.", 'Vou te responder assim que puder.'],
            ['Please leave a voicemail.', 'Por favor, deixe um recado.'],
            ["I left a voicemail.", 'Deixei um recado.'],
            ['Can you call me at this number?', 'Pode me ligar neste número?'],
            ['Is this a good time to talk?', 'É um bom momento para falar?'],
            ["I'm in a meeting right now.", 'Estou em uma reunião agora.'],
            ['Can I call you back in 10 minutes?', 'Posso te ligar de volta em 10 minutos?'],
            ['What is your number?', 'Qual é o seu número?'],
            ['Are you on WhatsApp?', 'Você está no WhatsApp?'],
            ["Let me know when you arrive.", 'Me diga quando chegar.'],
            ['Send me your location.', 'Me manda sua localização.'],
            ['Can you share the address?', 'Pode compartilhar o endereço?'],
            ["I'll be there in 20 minutes.", 'Estarei aí em 20 minutos.'],
            ["I'm on my way.", 'Estou a caminho.'],
            ["I'm 5 minutes away.", 'Estou a 5 minutos.'],
            ["I'll be late.", 'Vou me atrasar.'],
            ["I'll be there on time.", 'Estarei lá no horário.'],
            ['The call dropped.', 'A ligação caiu.'],
            ["Can you call me again?", 'Você pode me ligar de novo?'],
            ['I will call you tonight.', 'Vou te ligar esta noite.'],
            ['Can we do a video call?', 'Podemos fazer uma videochamada?'],
            ["I'll send you the link.", 'Vou te mandar o link.'],
            ['Can you see my screen?', 'Você consegue ver minha tela?'],
            ["You're on mute.", 'Você está no mudo.'],
            ['Can you unmute yourself?', 'Pode tirar o mudo?'],
            ["I can't see your video.", 'Não consigo ver seu vídeo.'],
            ['Can you turn on your camera?', 'Pode ligar sua câmera?'],
            ["There's an echo.", 'Tem eco.'],
            ['The audio is poor.', 'O áudio está ruim.'],
            ['Can everyone hear me?', 'Todo mundo pode me ouvir?'],
            ["Let's reconnect.", 'Vamos nos reconectar.'],
            ['Please reconnect.', 'Por favor, reconecte.'],
            ["I'll share my screen.", 'Vou compartilhar minha tela.'],
            ["Can you see it now?", 'Consegue ver agora?'],
            ['Screen sharing is off.', 'O compartilhamento de tela está desligado.'],
            ["I'll stop sharing now.", 'Vou parar de compartilhar agora.'],
            ["Let's move to the chat.", 'Vamos para o chat.'],
            ["I'll put the link in the chat.", 'Vou colocar o link no chat.'],
            ['Can you type that in the chat?', 'Pode digitar isso no chat?'],
            ["I'll follow up by email.", 'Vou enviar um e-mail de acompanhamento.'],
            ['Let me give you my contact info.', 'Deixa eu te dar meu contato.'],
            ["Here's my email.", 'Aqui está meu e-mail.'],
            ['Add me on LinkedIn.', 'Me adicione no LinkedIn.'],
            ["I'll connect with you online.", 'Vou me conectar com você online.'],
            ['Follow me on...', 'Me siga em...'],
            ['Check out my website.', 'Confira meu site.'],
            ["I'll DM you.", 'Vou te mandar uma mensagem direta.'],
            ['Did you see my message?', 'Você viu minha mensagem?'],
            ['Check your email.', 'Verifique seu e-mail.'],
            ['Did you get my email?', 'Você recebeu meu e-mail?'],
            ["I'll resend it.", 'Vou reenviar.'],
            ['Please confirm receipt.', 'Por favor, confirme o recebimento.'],
            ['Reply when you can.', 'Responda quando puder.'],
            ['Urgent: please reply ASAP.', 'Urgente: por favor responda assim que possível.'],
            ["I'm copying the team.", 'Estou copiando a equipe.'],
            ['See the attached file.', 'Veja o arquivo em anexo.'],
            ["I've forwarded the email.", 'Encaminhei o e-mail.'],
            ['Please review and respond.', 'Por favor, revise e responda.'],
            ["Let's schedule a call.", 'Vamos agendar uma ligação.'],
            ['Are you free for a quick call?', 'Você está livre para uma ligação rápida?'],
            ['I need to discuss something with you.', 'Preciso discutir algo com você.'],
            ['Can we talk?', 'Podemos conversar?'],
            ["I'll explain on the call.", 'Vou explicar na ligação.'],
            ["Let's talk tomorrow.", 'Vamos conversar amanhã.'],
            ["I'll reach out soon.", 'Vou entrar em contato em breve.'],
            ["Looking forward to hearing from you.", 'Aguardo seu retorno.'],
            ['Best regards,', 'Atenciosamente,'],
            ['Kind regards,', 'Com os melhores cumprimentos,'],
            ['Yours sincerely,', 'Sinceramente,'],
            ['Warm regards,', 'Com carinho,'],
            ['Thanks in advance.', 'Obrigado(a) antecipadamente.'],
            ['Please find attached.', 'Segue em anexo.'],
            ['As per our conversation,', 'Conforme nossa conversa,'],
            ['I hope this email finds you well.', 'Espero que este e-mail te encontre bem.'],
            ['Please do not hesitate to contact me.', 'Não hesite em me contatar.'],
            ['I look forward to your reply.', 'Aguardo sua resposta.'],
          ]}
        />
      </Section>

      <Section title="200 frases de conversação casual (nível intermediário)" accent={ACCENT}>
        <ComparisonTable
          accent={ACCENT}
          headers={['Inglês', 'Português']}
          rows={[
            ["What are you up to?", 'O que você está fazendo? / O que está aprontando?'],
            ["I'm just hanging out.", 'Só estou relaxando.'],
            ['Want to grab a coffee?', 'Quer tomar um café?'],
            ['Are you free this weekend?', 'Você está livre esse fim de semana?'],
            ["I'm busy but I'll try.", 'Estou ocupado(a), mas vou tentar.'],
            ["It's up to you.", 'É com você. / Você decide.'],
            ["I'm down for that.", 'Estou dentro disso. / Topo.'],
            ['Sounds good!', 'Parece ótimo!'],
            ["Let's do it.", 'Vamos fazer isso.'],
            ["I'm not really into that.", 'Não é muito a minha praia.'],
            ['Maybe some other time.', 'Talvez em outra hora.'],
            ['I totally agree.', 'Concordo totalmente.'],
            ["I'm not so sure about that.", 'Não tenho tanta certeza sobre isso.'],
            ['That makes sense.', 'Faz sentido.'],
            ['Good point.', 'Boa observação.'],
            ["I never thought about it that way.", 'Nunca pensei desta forma.'],
            ["That's interesting.", 'Que interessante.'],
            ['Tell me more.', 'Me conta mais.'],
            ['How did that go?', 'Como foi?'],
            ['It went well.', 'Foi bem.'],
            ['Not so well, actually.', 'Não muito bem, na verdade.'],
            ['What happened?', 'O que aconteceu?'],
            ['Long story short...', 'Resumindo...'],
            ["I'll explain later.", 'Explico depois.'],
            ["It's complicated.", 'É complicado.'],
            ["You won't believe this.", 'Você não vai acreditar nisso.'],
            ['Guess what!', 'Adivinha!'],
            ['No way!', 'Não acredito!'],
            ['Are you serious?', 'Você está falando sério?'],
            ["That's crazy.", 'Isso é loucura.'],
            ['I know, right?', 'Eu sei, né?'],
            ['I told you so.', 'Eu te disse.'],
            ["It's not a big deal.", 'Não é grande coisa.'],
            ['Take it easy.', 'Relaxa.'],
            ["Don't stress.", 'Não estressa.'],
            ['You can do it!', 'Você consegue!'],
            ['Keep it up!', 'Continue assim!'],
            ['Well done!', 'Muito bem!'],
            ["I'm proud of you.", 'Estou orgulhoso(a) de você.'],
            ['That must be hard.', 'Isso deve ser difícil.'],
            ['I understand how you feel.', 'Entendo como você se sente.'],
            ["That's life.", 'É a vida.'],
            ['Move on.', 'Segue em frente.'],
            ["What's done is done.", 'O que foi feito, foi feito.'],
            ["Let's change the subject.", 'Vamos mudar de assunto.'],
            ['By the way, have you heard about...?', 'A propósito, você ouviu sobre...?'],
            ["I've been thinking about...", 'Tenho pensado sobre...'],
            ["What's your take on...?", 'O que você acha de...?'],
            ["I've been meaning to ask you...", 'Queria te perguntar...'],
            ["Can I ask you something personal?", 'Posso te fazer uma pergunta pessoal?'],
            ["Don't take this the wrong way, but...", 'Não leve isso para o lado errado, mas...'],
            ["I need to be honest with you.", 'Preciso ser honesto(a) com você.'],
            ["Can I give you some advice?", 'Posso te dar um conselho?'],
            ["What would you do in my position?", 'O que você faria no meu lugar?'],
            ["Have you ever been to...?", 'Você já foi a...?'],
            ["What's your favorite...?", 'Qual é o seu favorito...?'],
            ["I can't decide between A and B.", 'Não consigo decidir entre A e B.'],
            ["What do you recommend?", 'O que você recomenda?'],
            ["I've always wanted to try that.", 'Sempre quis tentar isso.'],
            ["I've heard great things about it.", 'Ouvi ótimas coisas sobre isso.'],
            ["Let me know what you think.", 'Me diz o que você acha.'],
            ["I'd love to hear your opinion.", 'Adoraria ouvir sua opinião.'],
            ["What did you think of...?", 'O que você achou de...?'],
            ["I thought it was amazing.", 'Achei incrível.'],
            ["It was okay.", 'Foi ok.'],
            ["It wasn't my cup of tea.", 'Não foi muito a minha praia.'],
            ["I was blown away.", 'Fiquei de queixo caído.'],
            ["I was disappointed.", 'Fiquei desapontado(a).'],
            ["It exceeded my expectations.", 'Superou minhas expectativas.'],
            ["It was not what I expected.", 'Não foi o que eu esperava.'],
            ["I would highly recommend it.", 'Recomendo muito.'],
            ["I wouldn't bother.", 'Não me daria ao trabalho.'],
            ["It's worth it.", 'Vale a pena.'],
            ["It's not worth it.", 'Não vale a pena.'],
            ["Think before you act.", 'Pense antes de agir.'],
            ["Look before you leap.", 'Olhe antes de saltar. (Pense antes de agir)'],
            ["Better safe than sorry.", 'Melhor prevenir do que remediar.'],
            ["Two heads are better than one.", 'Duas cabeças pensam melhor do que uma.'],
            ["Practice makes perfect.", 'A prática leva à perfeição.'],
            ["When in Rome, do as the Romans do.", 'Em Roma, faça como os romanos.'],
            ["Don't count your chickens before they hatch.", 'Não conte com o ovo antes de pôr.'],
            ["The early bird catches the worm.", 'Deus ajuda quem cedo madruga.'],
            ["Easier said than done.", 'É mais fácil falar do que fazer.'],
            ["You can lead a horse to water but you can't make it drink.", 'Você pode levar um cavalo à água, mas não pode forçá-lo a beber. (Não se pode forçar ninguém)'],
            ["Where there's a will there's a way.", 'Onde há vontade, há um jeito.'],
            ["All that glitters is not gold.", 'Nem tudo que reluz é ouro.'],
            ["Don't judge a book by its cover.", 'Não julgue um livro pela capa.'],
            ["Honesty is the best policy.", 'A honestidade é a melhor política.'],
            ["Laughter is the best medicine.", 'O riso é o melhor remédio.'],
            ["You live and learn.", 'Errando e aprendendo. (Vivendo e aprendendo)'],
            ["Nothing ventured, nothing gained.", 'Nada arrisca, nada ganha.'],
            ["Curiosity killed the cat.", 'A curiosidade matou o gato.'],
            ["The grass is always greener on the other side.", 'A grama do vizinho é sempre mais verde.'],
            ["There is no place like home.", 'Lar doce lar.'],
            ["Old habits die hard.", 'Velhos hábitos são difíceis de mudar.'],
            ["Rome wasn't built in a day.", 'Roma não foi construída em um dia.'],
            ["Every little helps.", 'Todo pouquinho ajuda.'],
            ["Good things come to those who wait.", 'Quem espera sempre alcança.'],
            ["First things first.", 'Primeiro as coisas mais importantes.'],
            ["One step at a time.", 'Um passo de cada vez.'],
            ["You reap what you sow.", 'Você colhe o que planta.'],
            ["History repeats itself.", 'A história se repete.'],
            ["Knowledge is power.", 'Conhecimento é poder.'],
            ["Time is money.", 'Tempo é dinheiro.'],
            ["Money can't buy happiness.", 'Dinheiro não compra felicidade.'],
            ["Actions speak louder than words.", 'Ações falam mais alto que palavras.'],
            ["A friend in need is a friend indeed.", 'Amigo é aquele que está presente nas dificuldades.'],
            ["Don't bite the hand that feeds you.", 'Não morda a mão que te alimenta.'],
            ["Keep your friends close and your enemies closer.", 'Mantenha os amigos perto e os inimigos ainda mais perto.'],
            ["The truth will set you free.", 'A verdade vos libertará.'],
            ["Always look on the bright side of life.", 'Sempre veja o lado positivo da vida.'],
            ["What goes around comes around.", 'O que vai, volta.'],
            ["It takes two to tango.", 'Para dançar o tango é preciso dois. (Ambos têm culpa)'],
            ["There's no such thing as a free lunch.", 'Não existe almoço grátis.'],
            ["If it ain't broke, don't fix it.", 'Se não está quebrado, não conserte.'],
            ["Think outside the box.", 'Pense fora da caixa.'],
            ["Get to the point.", 'Vá direto ao ponto.'],
            ["Cut to the chase.", 'Vá ao que interessa.'],
            ["See eye to eye.", 'Concordar. (Ver olho a olho)'],
            ["Hit the books.", 'Estudar muito.'],
            ["Hit the road.", 'Ir embora / Vamos nessa.'],
            ["Hang in there.", 'Aguenta firme. / Não desista.'],
            ["Hang on a second.", 'Espera um segundo.'],
            ["Keep in touch.", 'Mantenha contato.'],
            ["Touch base.", 'Entrar em contato / checar.'],
            ["On the same page.", 'Com o mesmo entendimento.'],
            ["Get on the same page.", 'Se alinhar.'],
            ["Pull someone's weight.", 'Cumprir sua parte.'],
            ["At the end of the day...", 'No fim do dia... / No final das contas...'],
            ["Take the bull by the horns.", 'Pegar o touro pelos chifres.'],
            ["Burn bridges.", 'Queimar pontes.'],
            ["A blessing in disguise.", 'Uma bênção disfarçada.'],
            ["Bite the dust.", 'Morder o pó. / Fracassar.'],
            ["Under the radar.", 'Discretamente / Passando despercebido.'],
            ["Ahead of the curve.", 'Na vanguarda. / À frente do tempo.'],
            ["Back to basics.", 'De volta ao básico.'],
            ["The sky is the limit.", 'O céu é o limite.'],
            ["Dream big.", 'Sonhe grande.'],
            ["Follow your heart.", 'Siga seu coração.'],
            ["Trust the process.", 'Confie no processo.'],
            ["Believe in yourself.", 'Acredite em si mesmo.'],
            ["Stay focused.", 'Mantenha o foco.'],
            ["Stay consistent.", 'Seja consistente.'],
            ["Small progress is still progress.", 'Progresso pequeno ainda é progresso.'],
            ["Celebrate every win.", 'Celebre cada conquista.'],
            ["Embrace the challenge.", 'Abrace o desafio.'],
            ["Step out of your comfort zone.", 'Saia da sua zona de conforto.'],
            ["Face your fears.", 'Enfrente seus medos.'],
            ["The best is yet to come.", 'O melhor ainda está por vir.'],
            ["It is a marathon not a sprint.", 'É uma maratona, não uma corrida de velocidade.'],
            ["Work smart not just hard.", 'Trabalhe de forma inteligente, não apenas arduamente.'],
            ["Make every second count.", 'Faça cada segundo valer.'],
            ["You only live once.", 'Você só vive uma vez.'],
            ["Life is a journey.", 'A vida é uma jornada.'],
            ["Enjoy the ride.", 'Aproveite o passeio.'],
            ["Every day is a new beginning.", 'Todo dia é um novo começo.'],
            ["The future is bright.", 'O futuro é brilhante.'],
            ["Never stop learning.", 'Nunca pare de aprender.'],
            ["Keep growing.", 'Continue crescendo.'],
            ["Be the change you wish to see.", 'Seja a mudança que você quer ver.'],
            ["You are enough.", 'Você é suficiente.'],
            ["You are stronger than you think.", 'Você é mais forte do que pensa.'],
            ["This too shall pass.", 'Isso também vai passar.'],
            ["Tomorrow is another day.", 'Amanhã é um novo dia.'],
          ]}
        />
      </Section>

      <Callout tone="success">
        <strong>Você chegou longe!</strong> Com essas frases + as 1000 palavras + as 7 fases de gramática, você tem
        toda a base para se comunicar em inglês no dia a dia. O próximo passo é prática: filmes sem legenda, músicas,
        podcasts, conversas com nativos ou outros aprendizes. O medo de errar é o maior obstáculo — na prática,
        nativos adoram quando alguém tenta. Cada erro é uma oportunidade de aprendizado. <strong>Keep going!</strong>{' '}
        (Continue!)
      </Callout>
    </div>
  );
}
