import type { Trail } from '../types';

/** AI Safety, Red Teaming & Alinhamento */
export const trilha_trail30: Trail = {
    id: 'trail30', name: 'AI Safety, Red Teaming & Alinhamento',
    color: '#ef4444', icon: '🔒',
    desc: 'Segurança de IA como disciplina: jailbreaks e prompt injection, data exfiltration via tools, constitutional AI (Anthropic), guardrails (NeMo, Llama Guard, Claude Guardrails), red team playbook, capstone red team de agent próprio.',
    level: 'advanced', href: '/ai-safety',
    prerequisites: ['llm-apis-producao'],
    modules: [
      { slug: 'ai-safety-introducao', title: 'AI Safety: por que importa pra engenheiro', icon: '🛡️', xp: 50, readTime: 12, desc: 'Taxonomy: misuse, misalignment, misgeneralization. EU AI Act 2025. Corporate risk (reputational, legal). Engenheiro precisa entender pra operar IA em prod responsavelmente.',
        objetivo: 'Você distingue mau uso, desalinhamento e má generalização — e sabe qual desses riscos o seu sistema em produção corre de verdade.', keywords: 'ai safety, eu ai act 2025, misuse misalignment, ai risk', nextSuggested: ['jailbreaks-prompt-injection'], level: 'advanced' },
      { slug: 'jailbreaks-prompt-injection', title: 'Jailbreaks e prompt injection: taxonomia e defesas', icon: '🔓', xp: 60, readTime: 14, desc: 'Direct (DAN, role play), indirect (via tool output, RAG-poisoning), adversarial suffix (GCG), persona-based. Defenses: input/output filtering, system prompt hardening, constitutional classifier.', keywords: 'jailbreak llm, prompt injection, dan prompt, gcg attack, constitutional classifier', prerequisites: ['ai-safety-introducao'], nextSuggested: ['data-exfiltration-tools'], level: 'advanced' },
      { slug: 'data-exfiltration-tools', title: 'Data exfiltration via tools: o vetor principal em agents', icon: '🕵️', xp: 55, readTime: 13, desc: 'Agent com tool access pode ser manipulado a vazar dados (prompt injection no conteúdo ingested). Defesa: tool scoping estrito, no-network sandboxing, PII scan em I/O, least privilege.', keywords: 'agent data exfiltration, tool injection, pii scan llm, least privilege agents', prerequisites: ['jailbreaks-prompt-injection'], nextSuggested: ['constitutional-ai-rlhf'], level: 'advanced' },
      { slug: 'constitutional-ai-rlhf', title: 'Constitutional AI: Anthropic approach', icon: '📜', xp: 55, readTime: 13, desc: 'Constitutional AI (Anthropic, 2022): AI self-critique baseado em princípios escritos. RLAIF (RL from AI feedback). Core pra Claude safety. Aplicação: construir próprio sistema de críticos.', keywords: 'constitutional ai, rlaif, anthropic ai safety, self critique llm', prerequisites: ['data-exfiltration-tools'], nextSuggested: ['guardrails-nemo-llamaguard'], level: 'advanced' },
      { slug: 'guardrails-nemo-llamaguard', title: 'Guardrails: NeMo, Llama Guard, Claude Guardrails', icon: '🚧', xp: 55, readTime: 13, desc: 'NVIDIA NeMo Guardrails (dialog flow + checks), Llama Guard (Meta classifier pra safety), Claude Built-in Guardrails. Implementation patterns em produção.', keywords: 'nemo guardrails nvidia, llama guard meta, claude guardrails, llm safety filters', prerequisites: ['constitutional-ai-rlhf'], nextSuggested: ['red-team-playbook'], level: 'advanced' },
      { slug: 'red-team-playbook', title: 'Red team playbook: como atacar seu próprio LLM', icon: '🎯', xp: 65, readTime: 15, desc: 'Systematic red teaming: harm categories (Anthropic, DeepMind taxonomies), attack methods, reporting format. Automated red team (PyRIT Microsoft). Quando hire external red team.', keywords: 'llm red team, pyrit microsoft, ai harm categories, adversarial testing llm', prerequisites: ['guardrails-nemo-llamaguard'], nextSuggested: ['capstone-red-team-agent'], level: 'advanced' },
      { slug: 'capstone-red-team-agent', title: 'Capstone: red team do agent próprio', icon: '🏁', xp: 95, readTime: 22, desc: 'Pegue agent produção ou capstone anterior. Attacks sistemáticos: jailbreak (10 métodos), injection direct+indirect, data exfil via tools, PII leak, prompt stealing. Report com CVSS-ish severity + remediation.', nextSuggested: ['bedrock-o-que-e-e-por-que'], keywords: 'capstone red team ai, llm adversarial, agent security test', prerequisites: ['red-team-playbook'], level: 'advanced' },
    ],
  };
