import type { Trail } from '../types';

/** MLOps — ML em produção */
export const trilha_trail51: Trail = {
    id: 'trail51', name: 'MLOps — ML em produção',
    color: '#2ea5b3', icon: '🔁',
    desc: 'MLOps real: training pipelines (Airflow/Kubeflow), feature stores (Feast), experiment tracking + model registry (MLflow), data versioning (DVC), serving (Triton/TorchServe/BentoML), monitoring drift, CI/CD para modelos. Infraestrutura sólida, não hype.',
    level: 'advanced', href: '/mlops',
    prerequisites: ['capstone-ml-pipeline-completo'],
    modules: [
      { slug: 'mlops-ciclo-completo', title: 'MLOps: ciclo de vida completo', icon: '🔁', xp: 45, readTime: 11, desc: 'ML flywheel: data → train → eval → deploy → monitor → retrain. Google MLOps maturity levels 0/1/2. Diferença de LLMOps. Ferramentas 2026.',
        objetivo: 'Você percorre o ciclo data → train → eval → deploy → monitor → retrain e localiza em que estágio de maturidade seu time está hoje.', keywords: 'mlops ciclo vida, mlops maturity, mlops vs llmops, ml flywheel', nextSuggested: ['feature-stores-feast'], level: 'advanced' },
      { slug: 'feature-stores-feast', title: 'Feature stores: Feast e alternativas', icon: '🗃️', xp: 55, readTime: 13, desc: 'Por que feature store: training/serving skew, reutilização, governança. Feast arquitetura (offline store + online store), Tecton, Hopsworks. Integração com data warehouse.', keywords: 'feature store, feast, tecton, training serving skew, feature governance', prerequisites: ['mlops-ciclo-completo'], nextSuggested: ['model-registry-mlflow'], level: 'advanced' },
      { slug: 'model-registry-mlflow', title: 'Experiment tracking + registry: MLflow', icon: '📋', xp: 55, readTime: 13, desc: 'MLflow tracking (experiments, runs, params, metrics, artifacts). MLflow registry (stages: dev/staging/prod). Weights & Biases, Neptune. Model cards.', keywords: 'mlflow tracking, model registry, weights biases, neptune, model cards', prerequisites: ['feature-stores-feast'], nextSuggested: ['training-pipelines-kubeflow'], level: 'advanced' },
      { slug: 'training-pipelines-kubeflow', title: 'Training pipelines: Airflow, Kubeflow, Prefect', icon: '⚙️', xp: 60, readTime: 14, desc: 'Airflow DAGs para ML, Kubeflow Pipelines (K8s-native), Prefect 2.0, Argo Workflows. Orquestração, retries, caching, artifact passing.', keywords: 'airflow ml, kubeflow pipelines, prefect, argo workflows', prerequisites: ['model-registry-mlflow'], nextSuggested: ['model-serving-triton'], level: 'advanced' },
      { slug: 'model-serving-triton', title: 'Model serving: Triton, TorchServe, BentoML', icon: '🚀', xp: 60, readTime: 14, desc: 'Triton Inference Server (NVIDIA), TorchServe, Seldon, BentoML, Ray Serve. Dynamic batching, ensemble, A/B. GPU vs CPU inference.', keywords: 'triton inference server, torchserve, bentoml, ray serve, model serving', prerequisites: ['training-pipelines-kubeflow'], nextSuggested: ['data-versioning-dvc'], level: 'advanced' },
      { slug: 'data-versioning-dvc', title: 'Data versioning: DVC, lakeFS', icon: '📦', xp: 50, readTime: 12, desc: 'DVC git-like para data/models, lakeFS branches em lake, Pachyderm. Reprodutibilidade de training. Cost of reproducibility.', keywords: 'dvc data versioning, lakefs, pachyderm, ml reproducibility', prerequisites: ['model-serving-triton'], nextSuggested: ['ci-cd-para-modelos'], level: 'advanced' },
      { slug: 'ci-cd-para-modelos', title: 'CI/CD para modelos + monitoring drift', icon: '🚦', xp: 55, readTime: 13, desc: 'GitHub Actions com DVC e MLflow. Shadow deploy, canary, progressive rollout. Evidently AI, WhyLabs para drift detection. Retraining automation.', keywords: 'ml ci cd, shadow deploy canary, drift detection, evidently whylabs, retraining', prerequisites: ['data-versioning-dvc'], nextSuggested: ['capstone-mlops-plataforma'], level: 'advanced' },
      { slug: 'capstone-mlops-plataforma', title: 'Capstone: plataforma MLOps ponta a ponta', icon: '🏁', xp: 90, readTime: 20, desc: 'Entregáveis: repo com training pipeline (Kubeflow/Airflow) + feature store (Feast) + registry (MLflow) + serving (Triton ou BentoML) + monitoring (Evidently) + CI/CD completo. IaC (Terraform).', nextSuggested: ['observability-pilares'], keywords: 'mlops capstone, plataforma ml producao, mlflow feast triton', prerequisites: ['ci-cd-para-modelos'], level: 'advanced' },
    ],
  };
