import type { Trail } from '../types';

/** AWS Developer Associate (DVA-C02) */
export const trilha_trail23: Trail = {
    id: 'trail23',
    name: 'AWS Developer Associate (DVA-C02)',
    color: '#ff9900',
    icon: '🏗️',
    desc: 'Trilha completa pra certificação AWS DVA-C02: Lambda profundo, API Gateway, DynamoDB pra dev, S3 features (presigned, multipart), Step Functions, EventBridge/SQS/SNS, Cognito, KMS, CI/CD AWS-nativo, X-Ray, Secrets/Parameter Store, ECS Fargate, CloudFormation/SAM/CDK. Capstone: simulado de 65 questões comentadas.',
    level: 'intermediate',
    href: '/aws-developer-associate',
    prerequisites: ['aws-global-infra', 'iam-fundamentos'],
    modules: [
      {
        slug: 'dva-c02-intro',
        title: 'DVA-C02: domínios, pesos e estratégia de estudo',
        icon: '🎯',
        xp: 40, readTime: 10,
        desc: '4 domínios: Development (32%), Security (26%), Deployment (24%), Troubleshooting (18%). 65 questões, 130 min, passing 720/1000. Services priority list baseada em análise de exam. Calendário de 4 semanas.',
        objetivo: 'Você conhece o peso de cada domínio da DVA-C02 e monta um plano de estudo de semanas, não de sorte.',
        keywords: 'aws dva c02, aws developer associate, certificacao aws dva, dva dominios, estudar dva',
        nextSuggested: ['lambda-profundo'],
        level: 'intermediate',
      },
      {
        slug: 'lambda-profundo',
        title: 'Lambda profundo: cold start, layers e provisioned concurrency',
        icon: '⚡',
        xp: 60, readTime: 14,
        desc: 'Execution model: init phase (cold) vs invoke phase (warm). Runtime lifecycle, Lambda Execution Environment reuse. Layers pra deps compartilhadas, SnapStart pra Java/Python, provisioned concurrency quando p99 importa. Limits: 15min timeout, 10GB memória, 250MB unzipped.',
        keywords: 'lambda cold start, lambda layers, lambda snapstart, provisioned concurrency, lambda timeout',
        prerequisites: ['dva-c02-intro'],
        nextSuggested: ['api-gateway-rest-http-ws'],
        level: 'intermediate',
      },
      {
        slug: 'api-gateway-rest-http-ws',
        title: 'API Gateway: REST vs HTTP vs WebSocket',
        icon: '🌐',
        xp: 55, readTime: 12,
        desc: 'HTTP API (nova, barata, simples) vs REST API (features completas, WAF, request validation) vs WebSocket (conexões persistentes). Usage plans, API keys, Lambda authorizer, Cognito integration, mapping templates (ainda importa no REST).',
        keywords: 'api gateway aws, http api rest api, websocket api, lambda authorizer, usage plans',
        prerequisites: ['lambda-profundo'],
        nextSuggested: ['dynamodb-para-dev'],
        level: 'intermediate',
      },
      {
        slug: 'dynamodb-para-dev',
        title: 'DynamoDB pra dev: partition key, GSI e Streams',
        icon: '🗃️',
        xp: 65, readTime: 15,
        desc: 'Partition key + sort key compondo primary key. Hot partition (por que escolha de PK importa). LSI vs GSI (GSI pode ter PK diferente). DynamoDB Streams (CDC nativo). TTL, transactions, conditional writes, optimistic locking. Capacity: on-demand vs provisioned + auto scaling.',
        keywords: 'dynamodb partition key, dynamodb gsi lsi, dynamodb streams, dynamodb ttl, dynamodb transactions',
        prerequisites: ['api-gateway-rest-http-ws'],
        nextSuggested: ['s3-dev-features'],
        level: 'intermediate',
      },
      {
        slug: 's3-dev-features',
        title: 'S3 features pra dev: presigned URLs, multipart e events',
        icon: '🪣',
        xp: 50, readTime: 11,
        desc: 'Presigned URLs (upload/download direto do client, nunca expor credentials). Multipart upload (> 100MB obrigatório, resume). S3 Event Notifications → Lambda/SQS/SNS. Cross-Region Replication, versioning, object lock pra compliance. Transfer Acceleration.',
        keywords: 's3 presigned url, s3 multipart upload, s3 event notification, s3 replication, s3 versioning',
        prerequisites: ['dynamodb-para-dev'],
        nextSuggested: ['step-functions-workflows'],
        level: 'intermediate',
      },
      {
        slug: 'step-functions-workflows',
        title: 'Step Functions: orquestração de workflows',
        icon: '🔀',
        xp: 55, readTime: 12,
        desc: 'Standard vs Express (1y vs 5min, $1.25 vs $1 /M exec). States: Task, Choice, Parallel, Map, Wait, Succeed, Fail. Retries, catch, timeouts. Callback pattern pra approval humano. Nested workflows. Observabilidade nativa com visual.',
        keywords: 'step functions aws, standard express workflow, state machine aws, map parallel, callback token',
        prerequisites: ['s3-dev-features'],
        nextSuggested: ['eventbridge-sqs-sns-para-dev'],
        level: 'intermediate',
      },
      {
        slug: 'eventbridge-sqs-sns-para-dev',
        title: 'EventBridge, SQS e SNS: qual, quando, como combinar',
        icon: '📮',
        xp: 55, readTime: 12,
        desc: 'SNS pub/sub (fan-out, até 12.5M subs). SQS fila (FIFO vs Standard, DLQ, visibility timeout, long polling). EventBridge (antiga CloudWatch Events) com schema registry e filtros avançados. Padrão fan-out: SNS → múltiplos SQS → Lambdas.',
        keywords: 'aws eventbridge, sqs fifo dlq, sns fanout, visibility timeout, long polling sqs',
        prerequisites: ['step-functions-workflows'],
        nextSuggested: ['cognito-fluxos'],
        level: 'intermediate',
      },
      {
        slug: 'cognito-fluxos',
        title: 'Cognito: user pools vs identity pools',
        icon: '👥',
        xp: 50, readTime: 11,
        desc: 'User Pools (authn — signup, signin, MFA, social IdP via SAML/OIDC). Identity Pools (federação pra credenciais AWS temporárias). Fluxos: SRP (padrão), USER_PASSWORD, custom auth (Lambda triggers). Integration com API Gateway authorizer.',
        keywords: 'aws cognito user pool, identity pool, cognito srp, lambda triggers cognito, api gateway authorizer',
        prerequisites: ['eventbridge-sqs-sns-para-dev'],
        nextSuggested: ['kms-encryption-dev'],
        level: 'intermediate',
      },
      {
        slug: 'kms-encryption-dev',
        title: 'KMS: envelope encryption e quando usar CMK',
        icon: '🔏',
        xp: 50, readTime: 11,
        desc: 'Envelope encryption: CMK criptografa DEK; DEK criptografa dados. Customer Managed Key (CMK) vs AWS Managed vs AWS Owned. Grants, aliases, rotation automática. KMS policies + IAM (a lógica de interseção). Quando usar CloudHSM em vez de KMS (FIPS 140-2 L3).',
        keywords: 'aws kms envelope encryption, cmk customer managed key, kms rotation, kms grant, cloudhsm',
        prerequisites: ['cognito-fluxos'],
        nextSuggested: ['cicd-aws-nativo'],
        level: 'intermediate',
      },
      {
        slug: 'cicd-aws-nativo',
        title: 'CI/CD AWS-nativo: CodeBuild, CodeDeploy e CodePipeline',
        icon: '🚀',
        xp: 55, readTime: 12,
        desc: 'CodeCommit (deprecated em favor de GitHub Actions), CodeBuild pra builds (buildspec.yml, cache S3), CodeDeploy com deployment strategies (in-place, blue/green, canary, linear). CodePipeline compondo stages. Integration com GitHub + CodeStar.',
        keywords: 'codebuild buildspec, codedeploy blue green canary, codepipeline stages, cicd aws nativo, codecommit',
        prerequisites: ['kms-encryption-dev'],
        nextSuggested: ['x-ray-observability'],
        level: 'intermediate',
      },
      {
        slug: 'x-ray-observability',
        title: 'X-Ray: tracing distribuído na AWS',
        icon: '🔭',
        xp: 45, readTime: 10,
        desc: 'Segments, subsegments, sampling rules. Integration com Lambda (auto), ECS, EC2. Service map. X-Ray SDK vs ADOT (AWS Distro for OpenTelemetry — mais moderno). Custo: cobra por trace armazenado. Retention 30 dias.',
        keywords: 'aws x-ray tracing, x-ray segments, adot opentelemetry aws, sampling rules, service map',
        prerequisites: ['cicd-aws-nativo'],
        nextSuggested: ['secrets-parameter-store'],
        level: 'intermediate',
      },
      {
        slug: 'secrets-parameter-store',
        title: 'Secrets Manager vs Parameter Store: escolha',
        icon: '🔐',
        xp: 45, readTime: 10,
        desc: 'Parameter Store (grátis até 10k std, $0.05/advanced) pra config + SecureString. Secrets Manager ($0.40/secret/mês) pra credenciais DB com rotation automática. Quando usar cada. Integration com Lambda via extension (cache local). Hierarchy: /env/service/key.',
        keywords: 'parameter store ssm, secrets manager aws, securestring, rotation automatica, lambda extension',
        prerequisites: ['x-ray-observability'],
        nextSuggested: ['ecs-fargate-para-dev'],
        level: 'intermediate',
      },
      {
        slug: 'ecs-fargate-para-dev',
        title: 'ECS Fargate pra dev: quando escolher vs Lambda',
        icon: '🐳',
        xp: 55, readTime: 12,
        desc: 'Fargate = container serverless (sem gerenciar EC2). Task definition, service, ALB integration. Fargate Spot pra batch. Quando escolher Fargate sobre Lambda (> 15min, gRPC server, app com estado local, custom runtime). ECR pra imagens + lifecycle policies.',
        keywords: 'ecs fargate, task definition, ecs service, fargate spot, ecr lifecycle, fargate vs lambda',
        prerequisites: ['secrets-parameter-store'],
        nextSuggested: ['cloudformation-sam-cdk'],
        level: 'intermediate',
      },
      {
        slug: 'cloudformation-sam-cdk',
        title: 'IaC: CloudFormation vs SAM vs CDK',
        icon: '📜',
        xp: 55, readTime: 12,
        desc: 'CloudFormation (YAML/JSON declarativo, foundation). SAM (transform pra serverless, encurta boilerplate). CDK (TS/Python imperativo, synth pra CloudFormation). Terraform como alternativa cross-cloud. Drift detection, change sets, StackSets multi-account.',
        keywords: 'cloudformation aws, aws sam, aws cdk typescript, terraform aws, drift detection, stacksets',
        prerequisites: ['ecs-fargate-para-dev'],
        nextSuggested: ['simulado-dva-c02'],
        level: 'intermediate',
      },
      {
        slug: 'simulado-dva-c02',
        title: 'Fechamento DVA-C02: estratégia de prova e checklist',
        icon: '🏁',
        xp: 80, readTime: 18,
        desc: 'Como administrar a prova, como eliminar distrator sem saber a resposta e checklist por domínio antes de agendar. Traz 3 questões de amostra do estilo real — o simulado completo de 65 questões fica em /simulados.',
        nextSuggested: ['sap-c03-intro'],
        keywords: 'simulado dva c02, aws developer associate simulado, dva questions, aws exam prep, dva preparacao',
        prerequisites: ['cloudformation-sam-cdk'],
        level: 'advanced',
      },
    ],
  };
