import type { Trail } from '../types';

/** System Design Interview Prep */
export const trilha_trail52: Trail = {
    id: 'trail52', name: 'System Design Interview Prep',
    color: '#ea580c', icon: '🧩',
    desc: 'System design como disciplina de interview e de carreira: framework estruturado, back-of-envelope, cases canônicos (URL shortener, Twitter feed, rate limiter, chat, search, notification, distributed cache) e templates de whiteboard. Nível sênior/staff.',
    level: 'advanced', href: '/system-design-interview',
    modules: [
      { slug: 'sd-framework-completo', title: 'Framework de system design interview', icon: '🗺️', xp: 50, readTime: 12, desc: 'FRAME: Functional requirements, Non-functional (scale, latency, consistency), API, Model (data), Estimate. 5 passos que estruturam qualquer interview.',
        objetivo: 'Você estrutura qualquer entrevista de system design nos 5 passos do FRAME, sem travar no requisito não funcional.', keywords: 'system design framework, sd interview estrutura, sd requirements scale', nextSuggested: ['sd-back-of-envelope'], level: 'advanced' },
      { slug: 'sd-back-of-envelope', title: 'Back-of-envelope: cálculos que convencem', icon: '🧮', xp: 45, readTime: 11, desc: 'Latência (L1 0.5ns, disk 10ms, cross-region 150ms). Throughput (QPS por tipo). Storage (MB/record). Cost napkin. Powers of 10 + memorizados.', keywords: 'back of envelope, sd calculos, latency numbers, qps estimate', prerequisites: ['sd-framework-completo'], nextSuggested: ['sd-url-shortener'], level: 'advanced' },
      { slug: 'sd-url-shortener', title: 'Case: URL shortener', icon: '🔗', xp: 55, readTime: 13, desc: 'Design de bit.ly: hash vs counter, base62, DB schema, cache layer, analytics. Trade-offs consistency, hot shortcuts.', keywords: 'url shortener design, bitly system design, base62, sd case', prerequisites: ['sd-back-of-envelope'], nextSuggested: ['sd-twitter-feed'], level: 'advanced' },
      { slug: 'sd-twitter-feed', title: 'Case: Twitter feed / timeline', icon: '🐦', xp: 60, readTime: 14, desc: 'Fan-out on write vs read vs hybrid. Celebrity problem. Pull model. Feed ranking. Timeline storage. Cache warming.', keywords: 'twitter feed design, timeline fanout, celebrity problem, feed ranking', prerequisites: ['sd-url-shortener'], nextSuggested: ['sd-rate-limiter'], level: 'advanced' },
      { slug: 'sd-rate-limiter', title: 'Case: distributed rate limiter', icon: '🚦', xp: 55, readTime: 13, desc: 'Token bucket, leaky bucket, sliding window (counter + log). Redis-based (lua script atomic). Consistent vs approximate. Cross-region.', keywords: 'rate limiter design, token bucket, leaky bucket, sliding window, redis lua', prerequisites: ['sd-twitter-feed'], nextSuggested: ['sd-chat-system'], level: 'advanced' },
      { slug: 'sd-chat-system', title: 'Case: chat / messaging (WhatsApp-like)', icon: '💬', xp: 60, readTime: 14, desc: 'WebSocket connections, long polling fallback. Delivery semantics (at-least-once + idempotency). Read receipts. Group chat fan-out. Encryption at-rest + E2E.', keywords: 'chat system design, websocket chat, delivery semantics, e2e encryption', prerequisites: ['sd-rate-limiter'], nextSuggested: ['sd-notification-system'], level: 'advanced' },
      { slug: 'sd-notification-system', title: 'Case: sistema de notificações em escala', icon: '🔔', xp: 55, readTime: 13, desc: 'Push (APNs/FCM), email (SES/Sendgrid), SMS. Templates, user preferences, quiet hours. Priority queues, rate limiting por user. Delivery tracking.', keywords: 'notification system, push notification design, delivery tracking', prerequisites: ['sd-chat-system'], nextSuggested: ['sd-distributed-cache'], level: 'advanced' },
      { slug: 'sd-distributed-cache', title: 'Case: distributed cache (Redis/Memcached)', icon: '⚡', xp: 55, readTime: 13, desc: 'Hash ring (consistent hashing), replication, failover. Cache patterns (aside, through, back). Eviction policies. Hot keys, thundering herd.', keywords: 'distributed cache design, consistent hashing, cache patterns, hot keys', prerequisites: ['sd-notification-system'], nextSuggested: ['sd-search-system'], level: 'advanced' },
      { slug: 'sd-search-system', title: 'Case: search system (Google-like)', icon: '🔍', xp: 60, readTime: 14, desc: 'Inverted index, tokenization, ranking (BM25 + learning-to-rank), query suggest, autocomplete. Elasticsearch arch. Vector search hybrid.', keywords: 'search system design, inverted index, elasticsearch arch, ranking', prerequisites: ['sd-distributed-cache'], nextSuggested: ['capstone-sd-mock-interview'], level: 'advanced' },
      { slug: 'capstone-sd-mock-interview', title: 'Capstone: mock interview completo', icon: '🏁', xp: 85, readTime: 20, desc: 'Simular interview 45min: dropbox-like OU booking-like OU youtube-like. Usar framework. Entregáveis: diagrama + back-of-envelope + trade-offs escritos.', nextSuggested: ['lab-app-web-ecs-fargate-rds'], keywords: 'system design mock, sd interview capstone, whiteboard interview', prerequisites: ['sd-search-system'], level: 'advanced' },
    ],
  };
