import type { Trail } from '../types';

/** Redes & Web */
export const trilha_trail16: Trail = {
    id: 'trail16',
    name: 'Redes & Web',
    color: '#1f6feb',
    icon: '🌐',
    desc: 'TCP/IP, HTTP/1-2-3, TLS, DNS, CORS — o que acontece entre o teclado e a resposta. A fundação que faz arquitetura de nuvem, APIs e observabilidade fazerem sentido.',
    level: 'intermediate',
    href: '/redes-web',
    prerequisites: [],
    modules: [
      {
        slug: 'modelo-osi-tcp-ip',
        title: 'OSI e TCP/IP: as camadas que explicam tudo',
        icon: '📚',
        xp: 60,
        readTime: 12,
        desc: 'Por que o modelo OSI de 7 camadas existe (e por que ninguém usa), como TCP/IP realmente funciona em 4 camadas, e o que cada camada encapsula.',
        objetivo: 'Você aponta o que cada camada de rede encapsula e por que a discussão real hoje é em 4 camadas, não em 7.',
        nextSuggested: ['tcp-handshake-congestao'],
        keywords: 'modelo osi, tcp ip, camadas de rede, protocolo rede, encapsulamento',
        level: 'beginner',
      },
      {
        slug: 'tcp-handshake-congestao',
        title: 'TCP de verdade: handshake, congestion control, retransmissão',
        icon: '🤝',
        xp: 85,
        readTime: 17,
        desc: 'O 3-way handshake passo a passo, como TCP garante entrega ordenada, sliding window, slow start e congestion avoidance — por que TCP fica lento em alta latência.',
        nextSuggested: ['udp-quic-http3'],
        keywords: 'tcp handshake, congestion control, sliding window, tcp slow start, retransmissão tcp',
        level: 'intermediate',
      },
      {
        slug: 'udp-quic-http3',
        title: 'UDP, QUIC e HTTP/3: por que Google jogou TCP fora',
        icon: '🚀',
        xp: 70,
        readTime: 14,
        desc: 'UDP não é TCP sem garantias — é um protocolo diferente. QUIC reimplementa confiabilidade em user-space sobre UDP, resolvendo head-of-line blocking do TCP.',
        nextSuggested: ['http-1-vs-2-vs-3'],
        keywords: 'udp protocolo, quic protocolo, http3, head of line blocking, tcp vs udp',
        level: 'intermediate',
      },
      {
        slug: 'http-1-vs-2-vs-3',
        title: 'HTTP/1.1, /2, /3: multiplexing, HPACK, server push',
        icon: '📡',
        xp: 75,
        readTime: 15,
        desc: 'Por que HTTP/1.1 força 6 conexões paralelas por domínio, como HTTP/2 resolve com multiplexing, e o que HTTP/3 muda no transporte.',
        nextSuggested: ['tls-handshake-detalhe'],
        keywords: 'http2 vs http3, multiplexing http, hpack compressão, http versões comparação',
        level: 'intermediate',
      },
      {
        slug: 'tls-handshake-detalhe',
        title: 'TLS 1.3: handshake, chaves, certificados, SNI, ALPN',
        icon: '🔐',
        xp: 90,
        readTime: 18,
        desc: 'O handshake TLS 1.3 em detalhe: ECDHE para troca de chaves, certificados X.509, SNI para virtual hosting, ALPN para negociar protocolo. Por que HTTPS é mais rápido hoje.',
        nextSuggested: ['dns-recursivo-autoritativo'],
        keywords: 'tls 1.3, handshake tls, certificados ssl, sni, alpn, https como funciona',
        level: 'advanced',
      },
      {
        slug: 'dns-recursivo-autoritativo',
        title: 'DNS: recursivo, autoritativo, registros, TTL, DNSSEC',
        icon: '📖',
        xp: 70,
        readTime: 14,
        desc: 'O que acontece quando você digita um URL: resolver recursivo, root servers, TLD, authoritative. Registros A, AAAA, CNAME, MX, TXT, CAA. Cache e TTL.',
        nextSuggested: ['proxies-load-balancers'],
        keywords: 'como funciona dns, resolver dns, registros dns, cname vs a, dnssec, ttl dns',
        level: 'intermediate',
      },
      {
        slug: 'proxies-load-balancers',
        title: 'Proxies, reverse proxies, load balancers L4 vs L7',
        icon: '⚖️',
        xp: 70,
        readTime: 14,
        desc: 'Forward vs reverse proxy, Nginx como reverse proxy, load balancer L4 (TCP) vs L7 (HTTP), algoritmos de balanceamento, health checks e sticky sessions.',
        nextSuggested: ['websocket-sse-streaming'],
        keywords: 'load balancer l4 l7, reverse proxy nginx, round robin, sticky sessions, balanceamento carga',
        level: 'intermediate',
      },
      {
        slug: 'websocket-sse-streaming',
        title: 'WebSocket, SSE, streaming: comunicação bidirecional',
        icon: '🔄',
        xp: 60,
        readTime: 12,
        desc: 'Long polling vs SSE vs WebSocket: quando cada protocolo se encaixa. O handshake de upgrade do WebSocket, back-pressure em streaming, e SSE para updates unidirecionais.',
        nextSuggested: ['cors-csrf-cookies-seguros'],
        keywords: 'websocket, server sent events, streaming http, long polling, tempo real web',
        level: 'intermediate',
      },
      {
        slug: 'cors-csrf-cookies-seguros',
        title: 'CORS, CSRF, cookies seguros: segurança web fundamental',
        icon: '🛡️',
        xp: 70,
        readTime: 14,
        desc: 'Same-origin policy e por que existe, preflight CORS, CSRF tokens vs SameSite cookies, HttpOnly/Secure/SameSite — o mínimo de segurança web que todo dev precisa.',
        nextSuggested: ['relacional-vs-nao-relacional'],
        keywords: 'cors, csrf, same origin policy, cookies httponly secure samesite, segurança web',
        level: 'intermediate',
      },
    ],
  };
