import type { Level, Trail } from '../types';

/** AI Engineering Avançado: RLHF & Agents em Produção */
export const trilha_trail_ai_rlhf_agents: Trail = {
    id: 'trail-ai-rlhf-agents',
    name: 'AI Engineering Avançado: RLHF & Agents em Produção',
    color: '#06b6d4',
    icon: '🧬',
    desc: 'A camada AI moderna além do prompt engineering: RLHF/RLAIF, DPO/IPO/KTO, GRPO (DeepSeek-R1), reasoning models, agent swarms (CrewAI, AutoGen, LangGraph), observabilidade e evaluation de agentes em produção',
    level: 'advanced' as Level,
    href: '/ai-rlhf-agents',
    modules: [
      { slug: 'rlhf-fundamentos-ppo', title: 'RLHF do zero: PPO, KL penalty, reward hacking', icon: '🎯', xp: 80, readTime: 16, desc: 'A pipeline RLHF do InstructGPT/ChatGPT explicada matematicamente. PPO (Proximal Policy Optimization), KL divergence penalty, reward model training, advantage estimation. Por que reward hacking é o pesadelo de quem treina.',
        objetivo: 'Você lê a matemática do PPO com penalidade KL e reconhece reward hacking antes que ele apareça no seu próprio pipeline de treino.', keywords: 'rlhf ppo kl divergence, reward model llm, instructgpt openai, reward hacking', level: 'advanced' as Level, nextSuggested: ['rlaif-anthropic-claude'] },
      { slug: 'rlaif-anthropic-claude', title: 'RLAIF / Constitutional AI: como Anthropic treina o Claude', icon: '🤖', xp: 75, readTime: 15, desc: 'Constitutional AI da Anthropic: substitui human feedback por AI feedback via princípios escritos. Como o Claude é treinado, harmlessness training, character training. Paper Constitutional AI 2022 + atualizações 2025/2026.', keywords: 'rlaif anthropic, constitutional ai claude, character training, harmlessness training', level: 'advanced' as Level, prerequisites: ['rlhf-fundamentos-ppo'], nextSuggested: ['dpo-vs-ipo-vs-kto'] },
      { slug: 'dpo-vs-ipo-vs-kto', title: 'DPO vs IPO vs KTO: alinhamento sem reward model', icon: '⚖️', xp: 75, readTime: 15, desc: 'A revolução pós-RLHF: Direct Preference Optimization (Rafailov, NeurIPS 2023), IPO (Identity Preference Optimization), KTO (Kahneman-Tversky Optimization). Quando cada um vence — implementação na TRL da HuggingFace.', keywords: 'dpo direct preference optimization, ipo llm, kto kahneman tversky, trl huggingface', level: 'advanced' as Level, prerequisites: ['rlaif-anthropic-claude'], nextSuggested: ['grpo-deepseek-r1'] },
      { slug: 'grpo-deepseek-r1', title: 'GRPO e DeepSeek-R1: o salto reasoning de 2025', icon: '🚀', xp: 80, readTime: 16, desc: 'Group Relative Policy Optimization (GRPO) — o algoritmo que destravou reasoning emergente em DeepSeek-R1. Por que dispensa reward model. Como reproduzir com Unsloth/Axolotl em 2026.', keywords: 'grpo deepseek r1, group relative policy, reasoning model train, unsloth axolotl', level: 'advanced' as Level, prerequisites: ['dpo-vs-ipo-vs-kto'], nextSuggested: ['reasoning-models-internals'] },
      { slug: 'reasoning-models-internals', title: 'Reasoning models por dentro: o1, o3, R1, Gemini Thinking', icon: '🧠', xp: 70, readTime: 14, desc: 'Test-time compute, chain-of-thought interno, hidden reasoning tokens, budget control. Como o1 da OpenAI funciona, Claude com extended thinking, Gemini Thinking, DeepSeek-R1 — comparativo arquitetural.', keywords: 'reasoning model o1, extended thinking claude, gemini thinking, test-time compute', level: 'advanced' as Level, prerequisites: ['grpo-deepseek-r1'], nextSuggested: ['agent-swarms-crewai-autogen'] },
      { slug: 'agent-swarms-crewai-autogen', title: 'Agent swarms: CrewAI, AutoGen, OpenAI Swarm', icon: '🐝', xp: 70, readTime: 14, desc: 'Os 3 frameworks dominantes de agent orchestration em 2026 — comparativo e quando usar cada. CrewAI hierarchical, AutoGen v0.4 conversational, OpenAI Swarm minimal. Patterns: supervisor, debate, voting, ReAct.', keywords: 'agent swarm crewai, autogen v0.4, openai swarm, multi-agent framework', level: 'advanced' as Level, prerequisites: ['reasoning-models-internals'], nextSuggested: ['langgraph-state-machines'] },
      { slug: 'langgraph-state-machines', title: 'LangGraph: agentes como state machines (com cycles)', icon: '🕸️', xp: 75, readTime: 15, desc: 'Agentes como grafos de estado com ciclos — diferente de DAG do Airflow. LangGraph patterns: human-in-loop, persistent state, time travel, subgraphs. Por que LangChain abandonou o LangChain Expression Language.', keywords: 'langgraph, agent state machine, human in loop ai, langchain langgraph', level: 'advanced' as Level, prerequisites: ['agent-swarms-crewai-autogen'], nextSuggested: ['multi-agent-orchestration'] },
      { slug: 'multi-agent-orchestration', title: 'Multi-agent orchestration patterns avançados', icon: '🎼', xp: 70, readTime: 14, desc: 'Patterns que funcionam em produção: hierarchical (manager/workers), debate (2 agents adversariais convergem), voting (N agents → consensus), router-based, planner-executor. Quando NÃO usar multi-agent (90% dos casos).', keywords: 'multi-agent patterns, hierarchical agent, debate agent, planner executor llm', level: 'advanced' as Level, prerequisites: ['langgraph-state-machines'], nextSuggested: ['agent-observability-langsmith'] },
      { slug: 'agent-observability-langsmith', title: 'Agent observability: LangSmith, Helicone, Phoenix Arize', icon: '🔭', xp: 65, readTime: 13, desc: 'Você não pode debugar o que não vê. Trace de agent runs (spans hierárquicos), prompt versioning, dataset capture, A/B testing de prompts em produção. LangSmith vs Helicone vs Phoenix vs Langfuse.', keywords: 'langsmith observability, helicone llm, phoenix arize, langfuse agent trace', level: 'advanced' as Level, prerequisites: ['multi-agent-orchestration'], nextSuggested: ['agent-evaluation-prod'] },
      { slug: 'agent-evaluation-prod', title: 'Agent evaluation em produção: golden sets vs LLM-as-judge', icon: '📏', xp: 70, readTime: 14, desc: 'Avaliar agente é mais difícil que avaliar LLM single-turn. Golden trajectories vs LLM-as-judge, eval em CI (regression de agente), agent-arena style benchmarks, custom rubrics. Por que human eval ainda é o ground truth.', keywords: 'agent evaluation, llm as judge, golden trajectory, regression agent ci', level: 'advanced' as Level, prerequisites: ['agent-observability-langsmith'], nextSuggested: ['agent-cost-optimization'] },
      { slug: 'agent-cost-optimization', title: 'Custo de agente: $/action, prompt cache, cascade routing', icon: '💸', xp: 60, readTime: 12, desc: 'Agente sai US$50/mês por usuário se não otimizar. Anthropic prompt caching (90% off), OpenAI cached input, cascade routing (Haiku → Sonnet → Opus por confiança), context compression. Modelo de custo por agent action.', keywords: 'agent cost optimization, anthropic prompt cache, cascade routing llm, agente custo', level: 'advanced' as Level, prerequisites: ['agent-evaluation-prod'], nextSuggested: ['agent-security-prompt-injection'] },
      { slug: 'agent-security-prompt-injection', title: 'Agent security: prompt injection, jailbreak, tool abuse', icon: '🛡️', xp: 70, readTime: 14, desc: 'Indirect prompt injection (dados envenenados), jailbreak resistance, tool abuse (agente faz ação destrutiva), Spotlight from Microsoft, sandboxing de tools, allowlist de domínios. OWASP LLM Top 10 atualizado 2026.', nextSuggested: ['bedrock-o-que-e-e-por-que'], keywords: 'prompt injection defense, agent jailbreak, tool abuse llm, owasp llm top 10', level: 'advanced' as Level, prerequisites: ['agent-cost-optimization'] },
    ],
  };
