import type { Trail } from '../types';

/** Engenharia AI-Native */
export const trilha_trail9: Trail = {
    id: 'trail9',
    name: 'Engenharia AI-Native',
    color: '#ff7eb6',
    icon: '🧬',
    desc: 'RAG real, agent patterns, MCP, LLMOps, evaluation — o que separa um protótipo de IA de um sistema AI-native em produção.',
    level: 'advanced',
    href: '/ai-native',
    prerequisites: ['trail1', 'trail2'],
    modules: [
      {
        slug: 'rag-fundamentos',
        title: 'RAG: por que "só jogar tudo no LLM" não funciona',
        icon: '🧩',
        xp: 80,
        readTime: 16,
        desc: 'Retrieval-Augmented Generation na prática: limite de contexto, alucinação, arquitetura em dois estágios (retrieve → generate), quando RAG vence fine-tuning.',
        objetivo: 'Você explica por que \'jogar tudo no LLM\' quebra em produção e desenha um RAG de dois estágios que resolve isso.',
        level: 'advanced',
        keywords: 'rag retrieval augmented generation, o que e rag, rag vs fine tuning, arquitetura rag producao, rag llm',
        prerequisites: ['transformers', 'tool-calling'],
        nextSuggested: ['chunking-embeddings'],
      },
      {
        slug: 'chunking-embeddings',
        title: 'Chunking e Embeddings: as decisões que fazem ou quebram seu RAG',
        icon: '🔪',
        xp: 85,
        readTime: 17,
        desc: 'Fixed vs semantic vs recursive chunking, overlap, contextual retrieval, escolha de embedding (OpenAI, Voyage, BGE), redução de dimensão, cosine vs dot product.',
        level: 'advanced',
        keywords: 'chunking rag, contextual retrieval anthropic, embeddings escolha, voyage openai bge, dimensao embedding, cosine similarity',
        prerequisites: ['rag-fundamentos'],
        nextSuggested: ['hybrid-search-reranking'],
      },
      {
        slug: 'hybrid-search-reranking',
        title: 'Hybrid Search + Reranking: do BM25 ao cross-encoder',
        icon: '🎯',
        xp: 90,
        readTime: 18,
        desc: 'BM25 + vector, reciprocal rank fusion, cross-encoder reranking (Cohere, Jina, Voyage), HyDE, query expansion — o pipeline de retrieval de produção.',
        level: 'advanced',
        keywords: 'hybrid search rag, bm25 vector, reciprocal rank fusion, cross encoder rerank, cohere rerank, hyde query expansion',
        prerequisites: ['chunking-embeddings'],
        nextSuggested: ['rag-evaluation'],
      },
      {
        slug: 'rag-evaluation',
        title: 'Avaliando RAG: recall@k, nDCG e LLM-as-judge',
        icon: '📊',
        xp: 80,
        readTime: 16,
        desc: 'Golden dataset, métricas de retrieval (recall@k, MRR, nDCG), métricas de generation (faithfulness, context relevance, answer relevance), RAGAS, LLM-as-judge sem vazamento.',
        level: 'advanced',
        keywords: 'avaliar rag, recall at k, ndcg, mrr, ragas, faithfulness, llm as judge, rag evaluation',
        prerequisites: ['hybrid-search-reranking'],
        nextSuggested: ['agentes-padroes', 'llmops-drift-canary'],
      },
      {
        slug: 'agentes-padroes',
        title: 'Agent Patterns: ReAct, Reflexion e Tree of Thoughts',
        icon: '🤖',
        xp: 90,
        readTime: 18,
        desc: 'ReAct (think-act-observe), Reflexion (self-critique), Tree of Thoughts, Plan-and-Execute, Router — padrões empíricos com quando cada um funciona e quando quebra.',
        level: 'advanced',
        keywords: 'agent patterns, react agent, reflexion, tree of thoughts, plan and execute, agent router, llm agent design',
        prerequisites: ['rag-fundamentos'],
        nextSuggested: ['multi-agent-systems'],
      },
      {
        slug: 'multi-agent-systems',
        title: 'Multi-Agent Systems: orchestrator-worker, swarms e handoffs',
        icon: '🕸️',
        xp: 85,
        readTime: 17,
        desc: 'Orchestrator-worker, swarm com handoffs (OpenAI Swarm), CrewAI, hierarquias, quando multi-agent vale (e quando só aumenta custo).',
        level: 'advanced',
        keywords: 'multi agent system, orchestrator worker, openai swarm, crewai, agent handoff, multi agent llm',
        prerequisites: ['agentes-padroes'],
        nextSuggested: ['context-engineering'],
      },
      {
        slug: 'context-engineering',
        title: 'Context Engineering: prompt caching, subagents e skills',
        icon: '🧠',
        xp: 80,
        readTime: 16,
        desc: 'Anthropic prompt caching, janela de contexto, compaction, subagent delegation, skills (Agent Skills), CLAUDE.md/AGENTS.md, context window budget.',
        level: 'advanced',
        keywords: 'context engineering, prompt caching anthropic, agent skills, subagent delegation, claude md, context window llm',
        prerequisites: ['multi-agent-systems'],
        nextSuggested: ['mcp-servers'],
      },
      {
        slug: 'mcp-servers',
        title: 'MCP Deep Dive: construindo um servidor profissional',
        icon: '🔌',
        xp: 90,
        readTime: 19,
        desc: 'Model Context Protocol em profundidade: stdio vs HTTP, tools/resources/prompts, autenticação, rate limit, logging, exemplo real em TypeScript e Python.',
        level: 'advanced',
        keywords: 'mcp server tutorial, model context protocol, mcp typescript, mcp python, mcp auth, mcp deploy, anthropic mcp',
        prerequisites: ['context-engineering'],
        nextSuggested: ['llm-apis-producao'],
      },
      {
        slug: 'llm-apis-producao',
        title: 'LLM APIs em Produção: streaming, structured output, batch e cache',
        icon: '🚀',
        xp: 80,
        readTime: 16,
        desc: 'Streaming SSE, tool use, structured output com JSON schema/Zod, batch API (50% desconto), prompt caching, retry com jitter, rate limit handling.',
        level: 'advanced',
        keywords: 'llm api producao, streaming sse llm, structured output json schema, batch api anthropic openai, prompt caching, retry jitter',
        prerequisites: ['mcp-servers'],
        nextSuggested: ['llmops-drift-canary'],
      },
      {
        slug: 'llmops-drift-canary',
        title: 'LLMOps: eval harness, drift detection e canary de prompts',
        icon: '📈',
        xp: 90,
        readTime: 18,
        desc: 'Eval harness (promptfoo, LangSmith, custom), regressão de prompt, canary/A-B de prompts, drift detection, cost attribution, SLO de qualidade.',
        level: 'advanced',
        nextSuggested: ['capstone-ai-native-rag-producao'],
        keywords: 'llmops, eval harness, promptfoo langsmith, drift detection llm, canary prompt, cost attribution llm, slo llm',
        prerequisites: ['llm-apis-producao', 'rag-evaluation'],
      },
      {
        slug: 'capstone-ai-native-rag-producao',
        title: 'Capstone: RAG production-grade — de ponta a ponta',
        icon: '🏁',
        xp: 150, readTime: 45,
        desc: 'Projeto: RAG completo — ingestão (chunking + embed), store (Postgres pgvector ou Pinecone), retrieval (hybrid BM25 + vector + reranker), eval harness (golden set + LLM judge), observability (Langfuse), cost attribution. Deploy com feature flag pra canary.',
        nextSuggested: ['evals-como-disciplina'],
        keywords: 'capstone rag producao, pgvector, hybrid search reranker, rag eval, langfuse, canary llm, ai native capstone',
        prerequisites: ['llmops-drift-canary'],
        level: 'advanced',
      },
    ],
  };
