import type { Trail } from '../types';

/** Ferramentas de IA para Código */
export const trilha_trail3: Trail = {
    id: 'trail3',
    name: 'Ferramentas de IA para Código',
    color: '#ffa657',
    icon: '💻',
    desc: 'Claude Code, Codex, Cursor, Kiro — as diferenças reais entre os coding agents',
    level: 'intermediate',
    href: '/ferramentas-ia-codigo',
    prerequisites: ['trail2'],
    modules: [
      {
        slug: 'coding-agents-panorama',
        title: 'O Panorama dos Coding Agents',
        icon: '🗺️',
        xp: 50,
        readTime: 8,
        desc: 'De Copilot ao Claude Code — como os assistentes de código evoluíram de autocomplete para agentes autônomos.',
        objetivo: 'Você situa onde um agente de código está no espectro entre autocomplete e autonomia, e o que isso muda no seu fluxo.',
        level: 'intermediate',
        keywords: 'coding agents IA, assistentes codigo IA, claude code vs copilot, ferramentas IA programacao',
        prerequisites: ['como-avaliar-modelos'],
        nextSuggested: ['claude-code-arquitetura', 'openai-codex-cloud', 'cursor-copilot-ides'],
      },
      {
        slug: 'claude-code-arquitetura',
        title: 'Claude Code: Filosofia e Arquitetura',
        icon: '🤖',
        xp: 70,
        readTime: 12,
        desc: 'Como o Claude Code funciona por dentro — o loop agêntico, as ferramentas, o modelo de confiança e por que é diferente dos IDEs.',
        level: 'intermediate',
        keywords: 'claude code como funciona, arquitetura claude code, loop agentico claude, CLI agente IA',
        prerequisites: ['coding-agents-panorama'],
        nextSuggested: ['openai-codex-cloud', 'qual-coding-agent-usar'],
      },
      {
        slug: 'openai-codex-cloud',
        title: 'OpenAI Codex: o Agente na Nuvem',
        icon: '☁️',
        xp: 65,
        readTime: 10,
        desc: 'O novo Codex (2025) é completamente diferente do antigo — roda em sandbox na nuvem, é assíncrono e paralelo. Entenda o que isso muda.',
        level: 'intermediate',
        keywords: 'openai codex 2025, codex cloud sandbox, openai coding agent, codex vs claude code',
        prerequisites: ['coding-agents-panorama'],
        nextSuggested: ['cursor-copilot-ides', 'qual-coding-agent-usar'],
      },
      {
        slug: 'cursor-copilot-ides',
        title: 'Cursor, Copilot e os IDEs Aumentados',
        icon: '🖥️',
        xp: 60,
        readTime: 10,
        desc: 'A abordagem IDE-first — como Cursor e Copilot integram IA no editor e por que isso é uma filosofia diferente dos agentes de terminal.',
        level: 'intermediate',
        keywords: 'cursor ide IA, github copilot arquitetura, cursor vs claude code, IDE aumentado IA',
        prerequisites: ['coding-agents-panorama'],
        nextSuggested: ['amazon-q-kiro', 'qual-coding-agent-usar'],
      },
      {
        slug: 'amazon-q-kiro',
        title: 'Amazon Q e Kiro: a Aposta da AWS',
        icon: '☁️',
        xp: 60,
        readTime: 9,
        desc: 'O Amazon Q Developer e o novo Kiro têm filosofias distintas — um é extensão de IDE corporativo, o outro é spec-driven development.',
        level: 'intermediate',
        keywords: 'amazon q developer, kiro aws, spec driven development, amazon coding agent',
        prerequisites: ['coding-agents-panorama'],
        nextSuggested: ['qual-coding-agent-usar'],
      },
      {
        slug: 'qual-coding-agent-usar',
        title: 'Qual Ferramenta Usar e Quando',
        icon: '⚖️',
        xp: 80,
        readTime: 12,
        desc: 'Matriz de decisão real: quando o Claude Code brilha, quando o Cursor vence, quando o Codex na nuvem faz sentido. Sem achismo.',
        level: 'intermediate',
        keywords: 'comparar coding agents IA, claude code vs cursor vs copilot, qual IA usar para codigo, melhor ferramenta IA programacao',
        prerequisites: ['claude-code-arquitetura', 'openai-codex-cloud', 'cursor-copilot-ides', 'amazon-q-kiro'],
        nextSuggested: ['agentes-padroes', 'bedrock-o-que-e-e-por-que'],
      },
    ],
  };
