import type { Trail } from '../types';

/** NoSQL + Vector Databases */
export const trilha_trail54: Trail = {
    id: 'trail54', name: 'NoSQL + Vector Databases',
    color: '#0ea5e9', icon: '🗄️',
    desc: 'Além do Postgres: MongoDB (documents), Redis avançado (structures + streams), DynamoDB (single-table design), ClickHouse (analytics OLAP), SQLite moderno (embedded 2026), Vector DBs (pgvector/Pinecone/Weaviate/Qdrant). Quando usar cada, anti-patterns, casos reais.',
    level: 'intermediate', href: '/nosql-vector-dbs',
    prerequisites: ['relacional-vs-nao-relacional'],
    modules: [
      { slug: 'nosql-mental-model', title: 'NoSQL: mental model 2026', icon: '🧩', xp: 45, readTime: 10, desc: 'Por que "NoSQL" é rótulo pobre: document (Mongo), KV (Redis/DynamoDB), wide-column (Cassandra), graph (Neo4j), time-series (InfluxDB), vector (Pinecone). Quando cada.',
        objetivo: 'Você escolhe entre documento, chave-valor, wide-column, grafo ou série temporal pelo ACESSO que seu dado vai sofrer, não pelo rótulo \'NoSQL\'.', keywords: 'nosql mental model, document store, key value, wide column, vector database', nextSuggested: ['mongodb-producao'], level: 'intermediate' },
      { slug: 'mongodb-producao', title: 'MongoDB em produção', icon: '🍃', xp: 55, readTime: 13, desc: 'Schema design (embed vs reference), indexes compostos/parciais, aggregation pipeline, change streams, transactions multi-doc, Atlas. Anti-patterns (massive arrays, unbounded).', keywords: 'mongodb producao, mongodb schema design, aggregation pipeline, change streams', prerequisites: ['nosql-mental-model'], nextSuggested: ['redis-avancado-serio'], level: 'intermediate' },
      { slug: 'redis-avancado-serio', title: 'Redis além de cache: streams, pub/sub, scripts', icon: '🔴', xp: 55, readTime: 13, desc: 'Data structures além STRING: SETs, SORTED SETs (leaderboard), HASHes, STREAMs (Kafka-lite), HyperLogLog. Lua scripts atomic. Cluster mode. Redis Stack (JSON, Search).', keywords: 'redis avancado, redis streams, redis sorted set, lua script atomic, redis stack', prerequisites: ['mongodb-producao'], nextSuggested: ['dynamodb-design-patterns'], level: 'intermediate' },
      { slug: 'dynamodb-design-patterns', title: 'DynamoDB: single-table design', icon: '⚡', xp: 60, readTime: 14, desc: 'PK/SK, GSI, sparse indexes. Single-table design (Alex DeBrie). Access patterns first. Streams, TTL, DAX. Custo por RCU/WCU, on-demand vs provisioned.', keywords: 'dynamodb single table design, alex debrie, gsi, pk sk dynamodb', prerequisites: ['redis-avancado-serio'], nextSuggested: ['clickhouse-analytics'], level: 'intermediate' },
      { slug: 'clickhouse-analytics', title: 'ClickHouse: OLAP analytics de alto throughput', icon: '📊', xp: 55, readTime: 13, desc: 'Columnar storage, MergeTree engine, materialized views, dedup, compression. Queries ad-hoc em bilhões de linhas. vs Snowflake/BigQuery/Druid.', keywords: 'clickhouse analytics, columnar storage, merge tree, olap vs oltp', prerequisites: ['dynamodb-design-patterns'], nextSuggested: ['sqlite-embedded-moderno'], level: 'intermediate' },
      { slug: 'sqlite-embedded-moderno', title: 'SQLite moderno: edge, mobile e backend 2026', icon: '🪨', xp: 50, readTime: 12, desc: 'SQLite em 2026: Turso (edge replication), Litestream (streaming backup), Cloudflare D1, libSQL. Por que SQLite bate Postgres em leituras locais. WAL mode.', keywords: 'sqlite moderno, turso libsql, litestream, cloudflare d1, edge sqlite', prerequisites: ['clickhouse-analytics'], nextSuggested: ['vector-dbs-pgvector-pinecone'], level: 'intermediate' },
      { slug: 'vector-dbs-pgvector-pinecone', title: 'Vector DBs: pgvector, Pinecone, Weaviate, Qdrant', icon: '🧬', xp: 60, readTime: 14, desc: 'HNSW, IVF, scalar quantization. pgvector (quando Postgres basta), Pinecone (managed), Weaviate (hybrid), Qdrant (rust-based), Milvus. Custo per M vetors.', keywords: 'vector database, pgvector, pinecone, weaviate, qdrant, hnsw ivf', prerequisites: ['sqlite-embedded-moderno'], nextSuggested: ['capstone-multi-db-arquitetura'], level: 'intermediate' },
      { slug: 'capstone-multi-db-arquitetura', title: 'Capstone: arquitetura multi-DB real', icon: '🏁', xp: 85, readTime: 20, desc: 'Projeto: app que usa Postgres (source of truth) + Redis (cache/sessions) + MongoDB (user-generated docs) + pgvector (semantic search). Sync estratégia. Trade-offs documentados.', nextSuggested: ['bm25-tfidf-fundamentos'], keywords: 'multi database architecture, polyglot persistence, postgres redis mongodb pgvector', prerequisites: ['vector-dbs-pgvector-pinecone'], level: 'intermediate' },
    ],
  };
