import type { Trail } from '../types';

/** Python para Engenheiros */
export const trilha_trail36: Trail = {
    id: 'trail36',
    name: 'Python para Engenheiros',
    color: '#3776ab',
    icon: '🐍',
    desc: 'Python pra devs TypeScript que querem atacar camadas de IA: diferenças mentais TS↔Python, ambiente moderno com uv, type hints rigorosos, Pydantic v2, asyncio sem dor, FastAPI, Jupyter pra engenharia, capstone de agent completo com Claude SDK Python.',
    level: 'intermediate',
    href: '/python-engenheiros',
    prerequisites: ['typescript-como-mental-model'],
    modules: [
      {
        slug: 'python-pra-dev-ts',
        title: 'Python pra dev TS: diferenças mentais críticas',
        icon: '🔄',
        xp: 40, readTime: 10,
        desc: 'Duck typing vs structural typing, GIL vs event loop, pacotes como pastas (não arquivos), escopo de variável (LEGB), truthiness mais agressivo, lista vs tuple vs set vs dict, comprehensions como ferramenta de pensamento. Os pontos que fazem TS dev travar.',
        objetivo: 'Você reconhece os pontos onde o modelo mental de TypeScript trava em Python — GIL, duck typing, escopo — antes de escrever o primeiro bug por causa deles.',
        keywords: 'python para dev typescript, gil python, duck typing, comprehensions, legb scoping',
        nextSuggested: ['uv-e-python-moderno'],
        level: 'intermediate',
      },
      {
        slug: 'uv-e-python-moderno',
        title: 'uv e Python moderno: chega de pip + venv manual',
        icon: '⚡',
        xp: 45, readTime: 11,
        desc: 'uv (escrito em Rust, 10-100x mais rápido que pip/poetry) é o futuro. pyproject.toml, uv.lock, scripts. Gerenciar múltiplas versões Python. Migrar de requirements.txt/poetry/pipenv. Quando ainda usar pip (scripts inline).',
        keywords: 'uv python, pyproject toml, python versions manager, rye hatch, python dependencies',
        prerequisites: ['python-pra-dev-ts'],
        nextSuggested: ['type-hints-rigorosos'],
        level: 'intermediate',
      },
      {
        slug: 'type-hints-rigorosos',
        title: 'Type hints rigorosos: PEP 695, Protocol, TypedDict',
        icon: '📝',
        xp: 55, readTime: 13,
        desc: 'Python 3.12+ com PEP 695 (syntax de generics mais limpa). TypedDict pra dicts tipados. Protocol pra structural typing (o TS inside). Literal, Annotated, NotRequired. mypy strict + ruff. Type hints são a ferramenta #1 pra escalar código Python.',
        keywords: 'python type hints, pep 695 generics, typeddict, protocol structural, mypy strict, ruff',
        prerequisites: ['uv-e-python-moderno'],
        nextSuggested: ['pydantic-v2-serio'],
        level: 'intermediate',
      },
      {
        slug: 'pydantic-v2-serio',
        title: 'Pydantic v2 sério: modelos, validação e settings',
        icon: '🛡️',
        xp: 60, readTime: 14,
        desc: 'Pydantic v2 (escrito em Rust, blazing) é o Zod do Python. BaseModel, field validators, model_validator. Serialization com model_dump. BaseSettings pra config com env vars. discriminator pra tagged unions. Dez vezes mais rápido que v1.',
        keywords: 'pydantic v2, pydantic basemodel, field validator, basesettings env, discriminator pydantic',
        prerequisites: ['type-hints-rigorosos'],
        nextSuggested: ['async-em-python'],
        level: 'intermediate',
      },
      {
        slug: 'async-em-python',
        title: 'Async em Python: asyncio, trio e trade-offs vs Node',
        icon: '⏳',
        xp: 55, readTime: 13,
        desc: 'asyncio: event loop, Task, gather, as_completed. Por que Python async é mais verboso que Node (cor/coloring problem). trio como alternativa estruturada. anyio pra code lib-agnóstico. Gotchas: sync no event loop trava tudo; usar asyncio.to_thread pra I/O legado.',
        keywords: 'python asyncio, trio structured concurrency, anyio, coloring problem, asyncio gather',
        prerequisites: ['pydantic-v2-serio'],
        nextSuggested: ['fastapi-na-pratica'],
        level: 'intermediate',
      },
      {
        slug: 'fastapi-na-pratica',
        title: 'FastAPI na prática: routers, DI e auth',
        icon: '🚀',
        xp: 60, readTime: 14,
        desc: 'FastAPI é o framework web de facto em Python moderno (async nativo, OpenAPI auto, Pydantic built-in). APIRouter, Depends (injeção de dependência elegante), middleware, background tasks. OAuth2 + JWT com Security. Testar com TestClient + pytest async.',
        keywords: 'fastapi, apirouter, depends fastapi, oauth2 jwt fastapi, testclient fastapi, pytest async',
        prerequisites: ['async-em-python'],
        nextSuggested: ['jupyter-pra-engenharia'],
        level: 'intermediate',
      },
      {
        slug: 'jupyter-pra-engenharia',
        title: 'Jupyter pra engenharia: notebook reprodutível',
        icon: '📓',
        xp: 45, readTime: 10,
        desc: 'Jupyter ≠ código bagunçado. nbdev pra testar/documentar em notebooks. papermill pra parametrizar e executar em batch. jupytext pra diff amigável em git. Marimo como alternativa sem state oculto. Quando notebook é a ferramenta certa (exploração, modelos, relatórios) e quando não.',
        keywords: 'jupyter notebook profissional, nbdev, papermill, jupytext git, marimo notebook',
        prerequisites: ['fastapi-na-pratica'],
        nextSuggested: ['capstone-agent-python-completo'],
        level: 'intermediate',
      },
      {
        slug: 'capstone-agent-python-completo',
        title: 'Capstone: agent Python completo com Claude SDK',
        icon: '🏁',
        xp: 80, readTime: 18,
        desc: 'Agente Python end-to-end: Pydantic pra schemas, FastAPI pra endpoint, Claude Agent SDK pra loop agentic, tool use, memory em Redis, logging estruturado, tests com pytest async. Deploy em Fly.io ou AWS Lambda com container.',
        nextSuggested: ['o-que-e-cloud'],
        keywords: 'capstone python agent, claude agent sdk python, pydantic fastapi agent, deploy python agent, ia python capstone',
        prerequisites: ['jupyter-pra-engenharia'],
        level: 'advanced',
      },
    ],
  };
