import type { Trail } from '../types';

/** TypeScript Profissional */
export const trilha_trail19: Trail = {
    id: 'trail19',
    name: 'TypeScript Profissional',
    color: '#3178c6',
    icon: '🔷',
    desc: 'TS como prova matemática: narrowing real, discriminated unions, generics com variance, validação runtime (Zod), async sem pegadinha, erros como valores, performance em Node, monorepos com pnpm/turbo. O TypeScript que times profissionais escrevem — não o que um tutorial de 5 min ensina.',
    level: 'intermediate',
    href: '/typescript-profissional',
    prerequisites: ['git-de-verdade', 'json-yaml-env'],
    modules: [
      {
        slug: 'typescript-como-mental-model',
        title: 'TypeScript como mental model: tipos são prova, não anotação',
        icon: '🧠',
        xp: 45,
        readTime: 11,
        desc: 'Por que TS não é "JS com comentários" e sim um sistema de tipos estrutural com inference poderosa. Tipos são asserções sobre o runtime; o compilador prova que o fluxo respeita essas asserções. O clique mental que muda tudo.',
        objetivo: 'Você lê um tipo TypeScript como uma prova sobre o runtime, não como comentário decorativo.',
        keywords: 'typescript mental model, tipos como prova, sistema tipos estrutural, inference typescript, typescript fundamentos',
        nextSuggested: ['narrowing-discriminated-unions'],
        level: 'intermediate',
      },
      {
        slug: 'narrowing-discriminated-unions',
        title: 'Narrowing e discriminated unions: o coração real do TypeScript',
        icon: '🎯',
        xp: 55,
        readTime: 13,
        desc: 'Narrowing via typeof, instanceof, `in`, truthiness, equality. Discriminated unions com tag field (`kind: "ok" | "err"`). Exhaustiveness check com `never`. Por que `as` quase sempre significa que você abandonou o sistema.',
        keywords: 'typescript narrowing, discriminated unions, tagged unions, exhaustiveness check, never typescript, type guards',
        prerequisites: ['typescript-como-mental-model'],
        nextSuggested: ['generics-de-verdade'],
        level: 'intermediate',
      },
      {
        slug: 'generics-de-verdade',
        title: 'Generics de verdade: variance, constraints e conditional types',
        icon: '⚙️',
        xp: 60,
        readTime: 14,
        desc: 'Generics além de `Array<T>`: constraints com `extends`, infer para extrair tipo de função/array, conditional types, variance (covariant, contravariant, invariant). Quando reescrever libs com generics robustos em vez de copiar-colar.',
        keywords: 'generics typescript, variance typescript, conditional types, infer typescript, generics constraints',
        prerequisites: ['narrowing-discriminated-unions'],
        nextSuggested: ['tipos-utilitarios-e-quando-nao-usar'],
        level: 'intermediate',
      },
      {
        slug: 'tipos-utilitarios-e-quando-nao-usar',
        title: 'Tipos utilitários (Partial, Pick, Omit...) e quando NÃO usar',
        icon: '🧰',
        xp: 45,
        readTime: 10,
        desc: 'Partial, Required, Readonly, Pick, Omit, Record, Exclude, Extract, NonNullable, ReturnType, Awaited. O que cada um faz, quando é gambiarra (ex: Partial<T> escondendo modelagem fraca) e como prefers tipos nomeados a combinações monstruosas.',
        keywords: 'utility types typescript, partial pick omit, record typescript, returnType awaited, tipos utilitarios',
        prerequisites: ['generics-de-verdade'],
        nextSuggested: ['type-safety-em-boundaries'],
        level: 'intermediate',
      },
      {
        slug: 'type-safety-em-boundaries',
        title: 'Type safety em boundaries: Zod, io-ts e validação runtime',
        icon: '🛡️',
        xp: 55,
        readTime: 12,
        desc: 'Tipo compilado não protege no runtime. Todo boundary (API, form, localStorage, query param) precisa parse com schema Zod/Valibot/io-ts. Padrão `safeParse` retornando Result. Como inferir tipo TS do schema com z.infer, fechando o loop.',
        keywords: 'zod typescript, runtime validation, io-ts valibot, parse api boundary, z.infer, tipos seguros runtime',
        prerequisites: ['tipos-utilitarios-e-quando-nao-usar'],
        nextSuggested: ['async-await-sem-pegadinha'],
        level: 'intermediate',
      },
      {
        slug: 'async-await-sem-pegadinha',
        title: 'Async/await sem pegadinha: promises, AbortController e cancelamento',
        icon: '⏳',
        xp: 50,
        readTime: 12,
        desc: 'Promise é um valor, não uma função. `async` wrappa função em Promise. `await` é a única forma sã de consumir. AbortController para cancelar fetch, setTimeout, streams. `Promise.all` vs `Promise.allSettled` vs `Promise.race`. Erros silenciosos em `.then` sem catch.',
        keywords: 'async await typescript, abortcontroller fetch, promise all allsettled, cancelamento promise, async sem pegadinha',
        prerequisites: ['type-safety-em-boundaries'],
        nextSuggested: ['erros-como-valores'],
        level: 'intermediate',
      },
      {
        slug: 'erros-como-valores',
        title: 'Erros como valores: Result, neverthrow e por que `throw` quebra',
        icon: '🚨',
        xp: 55,
        readTime: 13,
        desc: '`throw` é goto tipado fraco — quebra inference, não aparece na assinatura, impede exhaustiveness. Result<T, E> (estilo Rust) transforma erros em retorno explícito. Biblioteca neverthrow, padrões de railway-oriented programming, quando `throw` ainda faz sentido (unrecoverable).',
        keywords: 'result type typescript, neverthrow, railway oriented, erros como valores, throw typescript, tipos erros',
        prerequisites: ['async-await-sem-pegadinha'],
        nextSuggested: ['performance-em-node'],
        level: 'intermediate',
      },
      {
        slug: 'performance-em-node',
        title: 'Performance em Node: event loop, streams e backpressure',
        icon: '🚀',
        xp: 65,
        readTime: 15,
        desc: 'Event loop fases (timers, poll, check, close), libuv thread pool, sync vs async FS, Readable/Writable/Transform streams, backpressure via `pipeline()`, worker_threads quando CPU-bound. Como achar o gargalo com clinic.js, --prof e heap snapshot.',
        keywords: 'node event loop, streams node, backpressure pipeline, worker threads, performance nodejs, libuv',
        prerequisites: ['erros-como-valores'],
        nextSuggested: ['monorepo-pnpm-turbo'],
        level: 'advanced',
      },
      {
        slug: 'monorepo-pnpm-turbo',
        title: 'Monorepo profissional: pnpm workspaces + Turbo + shared configs',
        icon: '📦',
        xp: 55,
        readTime: 13,
        desc: 'Por que times sérios usam monorepo: shared packages, atomic commits cruzando apps, CI unificada. pnpm workspaces (packages/*), Turbo pipeline.json com cache, shared tsconfig base, shared ESLint/Prettier. Anti-padrões (circular deps, shared mutáveis).',
        keywords: 'monorepo typescript, pnpm workspaces, turbo repo, tsconfig shared, monorepo profissional, turborepo pipeline',
        prerequisites: ['performance-em-node'],
        nextSuggested: ['capstone-cli-tool-ts'],
        level: 'advanced',
      },
      {
        slug: 'capstone-cli-tool-ts',
        title: 'Capstone: construir um CLI tool TypeScript end-to-end',
        icon: '🏁',
        xp: 80,
        readTime: 18,
        desc: 'Projeto consolidando a trilha: CLI com commander/citty, flags tipadas com Zod, async com AbortController, erros via Result, publicação em npm com bin/, tests com vitest, release automático com changesets. Saída: binário usável de verdade.',
        nextSuggested: ['o-que-e-cloud'],
        keywords: 'cli tool typescript, capstone ts, commander citty, publicar npm cli, changesets release, cli vitest',
        prerequisites: ['monorepo-pnpm-turbo'],
        level: 'advanced',
      },
    ],
  };
