import type { Trail } from '../types';

/** Data Engineering Moderna */
export const trilha_trail24: Trail = {
    id: 'trail24',
    name: 'Data Engineering Moderna',
    color: '#10b981',
    icon: '🏭',
    desc: 'Data engineering profissional: batch vs stream mental model, dbt como transformação declarativa, orchestração (Airflow vs Dagster vs Prefect), revolução in-process (DuckDB/Polars), data lake/lakehouse/warehouse, CDC com Debezium, Kafka fundamentos, table formats abertos (Iceberg/Delta), qualidade de dados, capstone de pipeline end-to-end.',
    level: 'advanced',
    href: '/data-engineering',
    prerequisites: ['mvcc-e-isolation-levels-de-verdade', 'python-pra-dev-ts'],
    modules: [
      {
        slug: 'batch-vs-stream-mental-model',
        title: 'Batch vs stream: mental model e trade-offs reais',
        icon: '⏱️',
        xp: 50, readTime: 12,
        desc: 'Batch: rodadas periódicas, throughput alto, latency em minutos/horas (ETL noturno). Stream: eventos contínuos, latency ms-segundos (Kafka + Flink). Lambda e Kappa architectures. Quando batch é bom suficiente (a maioria dos casos), quando stream é mandatório (real-time fraud, personalization).',
        objetivo: 'Você decide entre batch e streaming pela latência que o negócio de fato precisa, não pela ferramenta mais nova.',
        keywords: 'batch vs stream, lambda architecture, kappa architecture, kafka flink, etl vs streaming',
        nextSuggested: ['dbt-transformacao-como-codigo'],
        level: 'intermediate',
      },
      {
        slug: 'dbt-transformacao-como-codigo',
        title: 'dbt: transformação como código, testável',
        icon: '🔧',
        xp: 60, readTime: 14,
        desc: 'dbt (data build tool) é SQL + Git + tests. Models (SELECT que vira table/view), sources (raw), seeds (static data), tests (not_null, unique, relationships, custom), macros (DRY SQL), docs auto-geradas, lineage graph. Core (CLI open) vs Cloud (manager pago).',
        keywords: 'dbt data build tool, dbt models sources, dbt tests lineage, analytics engineering, dbt core cloud',
        prerequisites: ['batch-vs-stream-mental-model'],
        nextSuggested: ['airflow-vs-dagster-vs-prefect'],
        level: 'intermediate',
      },
      {
        slug: 'airflow-vs-dagster-vs-prefect',
        title: 'Airflow vs Dagster vs Prefect: qual orquestrador',
        icon: '🎼',
        xp: 55, readTime: 13,
        desc: 'Airflow: dominante, maduro, verbose (DAGs em Python, ops pesada). Dagster: software-defined assets, DX moderna, melhor pra analytics engineering. Prefect: simples, dynamic flows, ótimo pra Python-first. Como escolher baseado em legacy + time size.',
        keywords: 'airflow dag, dagster assets, prefect flows, orquestrador pipeline, data orchestration',
        prerequisites: ['dbt-transformacao-como-codigo'],
        nextSuggested: ['duckdb-e-polars'],
        level: 'advanced',
      },
      {
        slug: 'duckdb-e-polars',
        title: 'DuckDB e Polars: a revolução in-process',
        icon: '🦆',
        xp: 55, readTime: 12,
        desc: 'DuckDB: SQLite pra analytics — embedded, colunar, 0-copy integra Pandas/Parquet. Polars: DataFrame em Rust 10-100x mais rápido que pandas. Matam cluster Spark pra dataset < 1TB. "Big data is dead" (Jordan Tigani, 2023) — maioria dos times não precisa cluster.',
        keywords: 'duckdb sqlite analytics, polars rust dataframe, pandas alternative, big data is dead, analytics in-process',
        prerequisites: ['airflow-vs-dagster-vs-prefect'],
        nextSuggested: ['data-lake-lakehouse-warehouse'],
        level: 'advanced',
      },
      {
        slug: 'data-lake-lakehouse-warehouse',
        title: 'Data lake vs lakehouse vs warehouse',
        icon: '🏛️',
        xp: 55, readTime: 13,
        desc: 'Warehouse (Snowflake/BigQuery/Redshift): estruturado, performance, caro. Lake (S3 + Parquet): flexível, barato, compute separado, menos performático sem optimization. Lakehouse (Databricks, Iceberg+spark): converge com ACID. Qual escolher por escala + pricing model.',
        keywords: 'data lake, lakehouse, data warehouse snowflake bigquery, databricks, iceberg spark',
        prerequisites: ['duckdb-e-polars'],
        nextSuggested: ['cdc-com-debezium'],
        level: 'advanced',
      },
      {
        slug: 'cdc-com-debezium',
        title: 'CDC com Debezium: change data capture sério',
        icon: '🔄',
        xp: 55, readTime: 13,
        desc: 'Change Data Capture: capturar INSERT/UPDATE/DELETE do DB e publicar como event stream. Debezium usa logical replication (Postgres) ou binlog (MySQL). Kafka Connect integra. Uso: replicar OLTP → OLAP sem batch ETL, outbox pattern, invalidação de cache.',
        keywords: 'debezium cdc, change data capture, logical replication postgres, kafka connect, outbox pattern',
        prerequisites: ['data-lake-lakehouse-warehouse'],
        nextSuggested: ['kafka-fundamentos'],
        level: 'advanced',
      },
      {
        slug: 'kafka-fundamentos',
        title: 'Kafka fundamentos: partições, consumer groups, exactly-once',
        icon: '📨',
        xp: 65, readTime: 15,
        desc: 'Kafka como commit log distribuído. Topic dividido em partitions (ordem garantida dentro de partition, não entre). Consumer groups dividem carga. Exactly-once via idempotent producer + transactional writes. Retention configurável (pode ser infinito). Event sourcing natural.',
        keywords: 'kafka fundamentos, kafka partitions, consumer groups, exactly once kafka, event sourcing',
        prerequisites: ['cdc-com-debezium'],
        nextSuggested: ['iceberg-delta-hudi'],
        level: 'advanced',
      },
      {
        slug: 'iceberg-delta-hudi',
        title: 'Iceberg, Delta e Hudi: table formats abertos',
        icon: '🧊',
        xp: 60, readTime: 14,
        desc: 'Parquet é formato de arquivo; table formats adicionam ACID + time-travel + schema evolution em cima. Iceberg (Apple/Netflix, open): leader em 2026. Delta (Databricks): maduro, proprietário-ish. Hudi (Uber): focado em upserts. Open Table Format é o futuro — fim do vendor lock-in.',
        keywords: 'apache iceberg, delta lake, apache hudi, table format, data lake acid, schema evolution',
        prerequisites: ['kafka-fundamentos'],
        nextSuggested: ['qualidade-de-dados'],
        level: 'advanced',
      },
      {
        slug: 'qualidade-de-dados',
        title: 'Qualidade de dados: Great Expectations, dbt tests, Soda',
        icon: '✅',
        xp: 50, readTime: 12,
        desc: 'Data quality não é opcional. Testes em pipeline: volume (count esperado), shape (schema), distribution (stats), freshness (SLA), referential (FK-like em lake). Great Expectations, Soda Core, dbt tests nativos. Alerting, circuit breaker (bloqueia pipeline downstream se upstream falha).',
        keywords: 'data quality, great expectations, soda core, dbt tests, data observability, data freshness sla',
        prerequisites: ['iceberg-delta-hudi'],
        nextSuggested: ['capstone-pipeline-analytics-completo'],
        level: 'advanced',
      },
      {
        slug: 'capstone-pipeline-analytics-completo',
        title: 'Capstone: pipeline analytics end-to-end',
        icon: '🏁',
        xp: 90, readTime: 20,
        desc: 'Projeto: ingestão (Kafka → S3/Iceberg), transformação (dbt + DuckDB), orchestration (Dagster), CDC de Postgres OLTP, data quality (GE tests), dashboard (Metabase/Superset). Mostra cada camada funcionando juntas; mede SLA de freshness.',
        nextSuggested: ['lab-projeto-final-plataforma-dotnet-aws-ia'],
        keywords: 'capstone data pipeline, kafka iceberg dbt, dagster orchestration, great expectations, metabase superset',
        prerequisites: ['qualidade-de-dados'],
        level: 'advanced',
      },
    ],
  };
