import type { Trail } from '../types';

/** Fundamentos Técnicos */
export const trilha_trail12: Trail = {
    id: 'trail12',
    name: 'Fundamentos Técnicos',
    color: '#8b949e',
    icon: '🧱',
    desc: 'CLI, Git, HTTP, SSH, JSON/YAML — a base inegociável que todo dev precisa antes de qualquer outra coisa.',
    level: 'foundational',
    href: '/fundamentos-tecnicos',
    modules: [
      {
        slug: 'como-computador-roda-codigo',
        title: 'Como o computador roda seu código (do teclado ao pixel)',
        icon: '💻',
        xp: 50,
        readTime: 10,
        desc: 'Do clique de tecla ao pixel na tela: CPU, memória, sistema operacional, processo, e por que tudo isso importa para quem programa.',
        objetivo: 'Você segue o caminho de uma tecla até o pixel na tela e nomeia cada camada que participa.',
        keywords: 'como computador funciona, cpu memoria, sistema operacional processo, como codigo executa, fundamentos computacao',
        nextSuggested: ['linux-terminal-basico'],
        level: 'foundational',
      },
      {
        slug: 'linux-terminal-basico',
        title: 'Linux no terminal: os 30 comandos que valem por 300',
        icon: '🐧',
        xp: 60,
        readTime: 12,
        desc: 'ls, cd, grep, find, pipe, redireção, man — os comandos que você vai usar todo dia com fluência real, não decoreba.',
        keywords: 'comandos linux terminal, bash basico, grep find pipe, linux iniciantes, terminal linux',
        prerequisites: ['como-computador-roda-codigo'],
        nextSuggested: ['filesystem-permissions'],
        level: 'foundational',
      },
      {
        slug: 'filesystem-permissions',
        title: 'Filesystem e permissões: rwx, chown, symlink, hardlink',
        icon: '📁',
        xp: 45,
        readTime: 9,
        desc: 'Como o Linux organiza arquivos, o que significa rwxr-xr-x, chown, chmod, ln -s vs ln — e por que isso quebra deploys.',
        keywords: 'permissoes linux, chmod chown, rwx linux, symlink hardlink, filesystem linux',
        prerequisites: ['linux-terminal-basico'],
        nextSuggested: ['processos-jobs-sinais'],
        level: 'foundational',
      },
      {
        slug: 'processos-jobs-sinais',
        title: 'Processos, jobs, sinais: como o SO organiza execução',
        icon: '⚙️',
        xp: 55,
        readTime: 11,
        desc: 'PID, fork, exec, foreground/background, kill, SIGTERM vs SIGKILL, ps, top, htop — entenda o que roda no seu sistema.',
        keywords: 'processos linux, pid fork exec, kill sigterm sigkill, jobs background, ps top htop linux',
        prerequisites: ['filesystem-permissions'],
        nextSuggested: ['ssh-chaves-acesso-remoto'],
        level: 'foundational',
      },
      {
        slug: 'ssh-chaves-acesso-remoto',
        title: 'SSH e chaves: como acessar máquinas remotas com segurança',
        icon: '🔑',
        xp: 50,
        readTime: 10,
        desc: 'Par de chaves RSA/Ed25519, ssh-keygen, authorized_keys, ssh-agent, config file, tunelamento — tudo que você precisa para nunca mais digitar senha.',
        keywords: 'ssh tutorial, chaves ssh, ssh-keygen, authorized keys, ssh config, acesso remoto seguro',
        prerequisites: ['processos-jobs-sinais'],
        nextSuggested: ['git-de-verdade'],
        level: 'foundational',
      },
      {
        slug: 'git-de-verdade',
        title: 'Git de verdade: commit, branch, merge, rebase, reflog',
        icon: '🌿',
        xp: 80,
        readTime: 16,
        desc: 'Não só os comandos — o modelo mental de commits como snapshots, DAG de objetos, staging area, rebase vs merge, reflog como rede de segurança.',
        keywords: 'git tutorial, git rebase merge, git branch, git reflog, git modelo mental, git profissional',
        prerequisites: ['ssh-chaves-acesso-remoto'],
        nextSuggested: ['github-fluxo-profissional'],
        level: 'foundational',
      },
      {
        slug: 'github-fluxo-profissional',
        title: 'GitHub profissional: PR, review, issues, Actions básico',
        icon: '🐙',
        xp: 60,
        readTime: 12,
        desc: 'Fork vs clone, Pull Request, code review, issues, labels, milestones, GitHub Actions para CI/CD básico — o fluxo que empresas usam.',
        keywords: 'github tutorial, pull request, code review, github actions, fluxo profissional github',
        prerequisites: ['git-de-verdade'],
        nextSuggested: ['http-do-zero'],
        level: 'foundational',
      },
      {
        slug: 'http-do-zero',
        title: 'HTTP do zero: request, response, status, headers, cookies',
        icon: '🌐',
        xp: 70,
        readTime: 14,
        desc: 'GET, POST, PUT, DELETE, status codes, headers, cookies, CORS, REST vs GraphQL básico — o protocolo que move a web inteira.',
        keywords: 'http tutorial, status codes http, headers http, cookies, cors, rest api, protocolo http',
        prerequisites: ['github-fluxo-profissional'],
        nextSuggested: ['dns-tls-certificados'],
        level: 'foundational',
      },
      {
        slug: 'dns-tls-certificados',
        title: 'DNS, TLS e certificados: o que acontece antes do seu request',
        icon: '🔒',
        xp: 60,
        readTime: 12,
        desc: 'Resolução DNS (recursivo, autoritativo, TTL), handshake TLS 1.3, certificados X.509, CA, HTTPS — tudo antes do seu código rodar.',
        keywords: 'dns tutorial, tls certificados, https como funciona, resolucao dns, handshake tls, certificado ssl',
        prerequisites: ['http-do-zero'],
        nextSuggested: ['json-yaml-env'],
        level: 'foundational',
      },
      {
        slug: 'json-yaml-env',
        title: 'JSON, YAML e variáveis de ambiente: config moderna',
        icon: '📄',
        xp: 40,
        readTime: 8,
        desc: 'JSON e YAML como formatos universais de config, variáveis de ambiente e .env, 12-factor app — como configurar sistemas sem hardcode.',
        keywords: 'json yaml tutorial, variaveis de ambiente, arquivo env, 12 factor app, configuracao aplicacao',
        prerequisites: ['dns-tls-certificados'],
        nextSuggested: ['editores-produtividade'],
        level: 'foundational',
      },
      {
        slug: 'editores-produtividade',
        title: 'VSCode/Vim produtivos: atalhos, plugins, multi-cursor',
        icon: '✏️',
        xp: 35,
        readTime: 7,
        desc: 'Os atalhos de teclado que mudam tudo, plugins essenciais, multi-cursor, terminal integrado, Vim básico para quando não tem outra opção.',
        keywords: 'vscode atalhos, vim basico, produtividade editor, plugins vscode, multi cursor, terminal integrado vscode',
        prerequisites: ['json-yaml-env'],
        nextSuggested: ['o-que-e-ia', 'python-pra-dev-ts', 'modelo-osi-tcp-ip'],
        level: 'foundational',
      },
    ],
  };
