import type { Trail } from '../types';

/** Observabilidade & SRE */
export const trilha_trail11: Trail = {
    id: 'trail11',
    name: 'Observabilidade & SRE',
    color: '#79c0ff',
    icon: '🔭',
    desc: 'Métricas RED/USE, OpenTelemetry, SLOs, error budgets, incident response — o que separa "fazer deploy" de operar sistema em produção.',
    level: 'advanced',
    href: '/observabilidade-sre',
    modules: [
      {
        slug: 'observability-pilares',
        title: 'Observability: os 3 pilares (logs, métricas, traces) e por que não basta',
        icon: '🔍',
        xp: 75,
        readTime: 15,
        desc: 'Os 3 pilares clássicos, por que "observability" > monitoring, cardinalidade, events como 4º pilar, profiles (pprof, Pyroscope) como 5º, o que realmente medir.',
        objetivo: 'Você sabe qual dos três pilares — log, métrica ou trace — responde a pergunta que você tem, antes de abrir o dashboard errado.',
        level: 'advanced',
        keywords: 'observability 3 pilares, logs metricas traces, cardinalidade metricas, continuous profiling pprof, monitoring vs observability',
        nextSuggested: ['metricas-red-use'],
      },
      {
        slug: 'metricas-red-use',
        title: 'Métricas RED e USE: os frameworks que cobrem 90% dos casos',
        icon: '📉',
        xp: 70,
        readTime: 14,
        desc: 'RED (Rate, Errors, Duration) para serviços, USE (Utilization, Saturation, Errors) para recursos, Golden Signals do Google SRE, quando aplicar cada um.',
        level: 'advanced',
        keywords: 'metricas red use, red method, use method, golden signals sre, metricas servico, metricas recurso',
        prerequisites: ['observability-pilares'],
        nextSuggested: ['opentelemetry-stack'],
      },
      {
        slug: 'opentelemetry-stack',
        title: 'OpenTelemetry end-to-end: instrumentação app → backend',
        icon: '🛰️',
        xp: 90,
        readTime: 18,
        desc: 'OpenTelemetry SDK (auto vs manual), Collector (receivers, processors, exporters), context propagation, resource detection, pipelines reais em Node, Python e Go.',
        level: 'advanced',
        keywords: 'opentelemetry tutorial, otel collector, otel sdk, context propagation, instrumentacao auto manual, opentelemetry producao',
        prerequisites: ['metricas-red-use'],
        nextSuggested: ['logs-estruturados', 'distributed-tracing'],
      },
      {
        slug: 'logs-estruturados',
        title: 'Logs Estruturados: JSON, correlation IDs e levels com propósito',
        icon: '📝',
        xp: 70,
        readTime: 14,
        desc: 'JSON logs, trace_id/span_id correlation, log levels (o que DEBUG, INFO, WARN, ERROR realmente significam), structured logging libs, formatter cost.',
        level: 'advanced',
        nextSuggested: ['distributed-tracing'],
        keywords: 'logs estruturados, structured logging json, correlation id, trace id logs, log levels semantica, structured logging producao',
        prerequisites: ['opentelemetry-stack'],
      },
      {
        slug: 'distributed-tracing',
        title: 'Distributed Tracing: spans, baggage e sampling strategies',
        icon: '🧵',
        xp: 80,
        readTime: 16,
        desc: 'Spans, parent-child, context propagation (W3C Trace Context), baggage, head vs tail sampling, probabilistic vs rule-based, Jaeger e Tempo comparados.',
        level: 'advanced',
        keywords: 'distributed tracing, span parent child, w3c trace context, baggage, head tail sampling, jaeger tempo',
        prerequisites: ['opentelemetry-stack'],
        nextSuggested: ['slos-error-budgets'],
      },
      {
        slug: 'slos-error-budgets',
        title: 'SLOs e Error Budgets: a contabilidade da confiabilidade',
        icon: '🎯',
        xp: 80,
        readTime: 16,
        desc: 'SLI → SLO → SLA, error budget, burn rate alerts multi-window/multi-burn, toil budget, política de freeze quando orçamento estoura.',
        level: 'advanced',
        keywords: 'slo error budget, sli slo sla, burn rate alert, multi window multi burn, toil budget, sre confiabilidade',
        prerequisites: ['metricas-red-use'],
        nextSuggested: ['incident-response-postmortem'],
      },
      {
        slug: 'incident-response-postmortem',
        title: 'Incident Response: comando, comunicação e postmortem blameless',
        icon: '🚑',
        xp: 80,
        readTime: 16,
        desc: 'Incident Commander, Comms Lead, Ops Lead, timeline, postmortem blameless, 5 whys, action items com SLA, learning review mensal.',
        level: 'advanced',
        nextSuggested: ['capstone-sre-slo-runbook'],
        keywords: 'incident response, incident commander, postmortem blameless, 5 whys, comms lead ops lead, learning review',
        prerequisites: ['slos-error-budgets'],
      },
      {
        slug: 'capstone-sre-slo-runbook',
        title: 'Capstone: SLO + error budget + runbook reais',
        icon: '🏁',
        xp: 90, readTime: 20,
        desc: 'Projeto: definir SLIs (latency, availability) pra serviço real, calcular SLO (99.9%?), error budget mensal, alertas multi-burn-rate (fast/slow), runbook com ações por alerta, gameday simulado pra validar.',
        nextSuggested: ['cap-pacelc'],
        keywords: 'capstone sre, slo error budget, multi burn rate alerts, runbook producao, gameday chaos',
        prerequisites: ['incident-response-postmortem'],
        level: 'advanced',
      },
    ],
  };
