import type { Trail } from '../types';

/** Sistemas Distribuídos */
export const trilha_trail10: Trail = {
    id: 'trail10',
    name: 'Sistemas Distribuídos',
    color: '#f78166',
    icon: '🧭',
    desc: 'CAP, consensus, idempotência, sagas, event sourcing — a base técnica que separa "funciona no localhost" de "funciona com 3 nós e 1000 req/s".',
    level: 'advanced',
    href: '/sistemas-distribuidos',
    modules: [
      {
        slug: 'cap-pacelc',
        title: 'CAP e PACELC: o teorema que define toda arquitetura distribuída',
        icon: '⚖️',
        xp: 80,
        readTime: 16,
        desc: 'Partition tolerance, availability, consistency — e por que você sempre escolhe entre 2. PACELC estende para latência. Decisões reais: Dynamo vs Spanner, Cassandra vs HBase.',
        objetivo: 'Você escolhe entre consistência e disponibilidade sabendo qual das duas está sendo sacrificada, e por quê.',
        level: 'advanced',
        keywords: 'teorema cap, pacelc, sistemas distribuidos, consistencia disponibilidade, dynamo spanner, cassandra hbase',
        nextSuggested: ['consistency-models'],
      },
      {
        slug: 'consistency-models',
        title: 'Modelos de Consistência: strong, eventual, causal, read-your-writes',
        icon: '🔄',
        xp: 85,
        readTime: 17,
        desc: 'Linearizability, sequential consistency, causal, eventual. Session guarantees (read-your-writes, monotonic reads, bounded staleness). Qual usar em cada cenário.',
        level: 'advanced',
        keywords: 'modelos consistencia, linearizability, eventual consistency, causal consistency, read your writes, session guarantees',
        prerequisites: ['cap-pacelc'],
        nextSuggested: ['consensus-raft'],
      },
      {
        slug: 'consensus-raft',
        title: 'Consensus e Raft: como nós discordam e chegam a acordo',
        icon: '🗳️',
        xp: 90,
        readTime: 18,
        desc: 'FLP impossibility, intuição do Paxos, Raft explicado (leader election, log replication, safety). Por que etcd, Consul, K8s, CockroachDB usam Raft.',
        level: 'advanced',
        keywords: 'consensus distribuido, raft algoritmo, paxos, flp impossibility, etcd raft, kubernetes consensus',
        prerequisites: ['consistency-models'],
        nextSuggested: ['idempotencia-retries'],
      },
      {
        slug: 'idempotencia-retries',
        title: 'Idempotência e Retries: o antídoto pra rede que quebra',
        icon: '🔁',
        xp: 75,
        readTime: 15,
        desc: 'Idempotency keys, exponential backoff com jitter, circuit breaker, deadline propagation, dedup via Redis/Postgres, at-least-once vs exactly-once.',
        level: 'advanced',
        keywords: 'idempotencia api, idempotency key, retry backoff jitter, circuit breaker, exactly once, at least once, deduplicacao',
        prerequisites: ['consensus-raft'],
        nextSuggested: ['sagas-2pc'],
      },
      {
        slug: 'sagas-2pc',
        title: 'Sagas vs 2PC: transações distribuídas sem perder o sono',
        icon: '🪢',
        xp: 85,
        readTime: 17,
        desc: 'Por que 2PC trava tudo, saga orchestration vs choreography, compensating actions, outbox pattern, idempotência nas compensações.',
        level: 'advanced',
        keywords: 'saga pattern, two phase commit 2pc, orchestration choreography, outbox pattern, compensating action, transacao distribuida',
        prerequisites: ['idempotencia-retries'],
        nextSuggested: ['event-sourcing-cqrs'],
      },
      {
        slug: 'event-sourcing-cqrs',
        title: 'Event Sourcing e CQRS: quando eventos são a fonte da verdade',
        icon: '📜',
        xp: 85,
        readTime: 17,
        desc: 'Event log como source of truth, projections, CQRS (command vs query), event store (Kafka, EventStoreDB), vantagens, armadilhas, quando evitar.',
        level: 'advanced',
        keywords: 'event sourcing, cqrs, event log, projection, kafka event store, eventstoredb, command query separation',
        prerequisites: ['sagas-2pc'],
        nextSuggested: ['postgres-mvcc-isolation'],
      },
      {
        slug: 'postgres-mvcc-isolation',
        title: 'Postgres Profundo: MVCC, Isolation Levels e Locks',
        icon: '🐘',
        xp: 85,
        readTime: 17,
        desc: 'Como MVCC funciona por dentro, read committed vs repeatable read vs serializable, SELECT FOR UPDATE, advisory locks, VACUUM e bloat.',
        level: 'advanced',
        keywords: 'postgres mvcc, isolation levels postgres, select for update, advisory lock postgres, vacuum bloat, repeatable read serializable',
        prerequisites: ['consistency-models'],
        nextSuggested: ['rate-limiting-distribuido'],
      },
      {
        slug: 'rate-limiting-distribuido',
        title: 'Rate Limiting Distribuído: token bucket, sliding window, Redis',
        icon: '🚦',
        xp: 75,
        readTime: 15,
        desc: 'Token bucket, leaky bucket, sliding window log, sliding window counter, implementação com Redis + Lua script atômico, distributed rate limit em produção.',
        level: 'advanced',
        nextSuggested: ['capstone-sistemas-distribuidos-saga'],
        keywords: 'rate limiting distribuido, token bucket, sliding window, redis lua rate limit, leaky bucket, api rate limit',
        prerequisites: ['idempotencia-retries'],
      },
      {
        slug: 'capstone-sistemas-distribuidos-saga',
        title: 'Capstone: saga distribuída ponta a ponta',
        icon: '🏁',
        xp: 95, readTime: 20,
        desc: 'Projeto: e-commerce com 3 serviços (orders, payments, inventory). Saga orchestrator em Step Functions/Temporal. Compensations em cada fail. Outbox pattern pra eventos. Idempotency em retry. Tracing distribuído.',
        nextSuggested: ['unit-economics-em-software'],
        keywords: 'capstone saga distribuida, outbox pattern, compensations, temporal saga, step functions saga',
        prerequisites: ['rate-limiting-distribuido'],
        level: 'advanced',
      },
    ],
  };
