import type { Trail } from '../types';

/** Security Engineering */
export const trilha_trail22: Trail = {
    id: 'trail22',
    name: 'Security Engineering',
    color: '#ef4444',
    icon: '🛡️',
    desc: 'Segurança como disciplina própria: threat modeling STRIDE, authn vs authz, OAuth2/OIDC do zero, JWT/Paseto/sessions, password hashing moderno (argon2), OWASP Top 10 com código, secrets management (Vault/SOPS), supply chain (SBOM, sigstore), Zero Trust + mTLS, capstone pentest em app próprio.',
    level: 'advanced',
    href: '/security-engineering',
    prerequisites: ['type-safety-em-boundaries', 'iam-fundamentos'],
    modules: [
      {
        slug: 'threat-modeling-stride',
        title: 'Threat modeling com STRIDE: de onde vêm os ataques',
        icon: '🎯',
        xp: 55, readTime: 13,
        desc: 'STRIDE (Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege) como checklist pragmático; DFD (data flow diagram) pra visualizar surface; priorizar por DREAD ou Risk Matrix; integrar no design review.',
        objetivo: 'Você aplica STRIDE para nomear de onde vem cada ameaça antes de escrever a primeira linha de código de um sistema novo.',
        keywords: 'threat modeling stride, dfd security, dread risk, design review seguranca, modelagem ameaca',
        nextSuggested: ['authn-vs-authz'],
        level: 'advanced',
      },
      {
        slug: 'authn-vs-authz',
        title: 'Authn vs Authz: a diferença e as armadilhas',
        icon: '🔑',
        xp: 50, readTime: 11,
        desc: 'Autenticação (quem é você) vs Autorização (o que pode fazer). Por que misturar no mesmo middleware é bug comum. RBAC vs ABAC vs ReBAC (Zanzibar/SpiceDB). Session vs stateless (JWT). Como TIPAR o Request<User> no TS pra nunca acessar endpoint sem authn.',
        keywords: 'autenticacao autorizacao diferenca, rbac abac, zanzibar spicedb, session vs jwt, authn authz',
        prerequisites: ['threat-modeling-stride'],
        nextSuggested: ['oauth2-oidc-do-zero'],
        level: 'advanced',
      },
      {
        slug: 'oauth2-oidc-do-zero',
        title: 'OAuth2 e OIDC do zero: fluxos e PKCE',
        icon: '🔐',
        xp: 65, readTime: 15,
        desc: 'Authorization Code + PKCE (único fluxo aceitável em 2026), Client Credentials (machine-to-machine), Device Code (CLI/TV). OIDC sobre OAuth2: id_token, scopes, claims. Erros fatais: implicit flow, ROPC. Como debugar token inválido sem expor secret.',
        keywords: 'oauth2 pkce, oidc openid connect, authorization code flow, device code flow, id token claims',
        prerequisites: ['authn-vs-authz'],
        nextSuggested: ['jwt-paseto-sessions'],
        level: 'advanced',
      },
      {
        slug: 'jwt-paseto-sessions',
        title: 'JWT, Paseto ou sessions: quando cada um',
        icon: '🎫',
        xp: 55, readTime: 12,
        desc: 'JWT: quando é bom (stateless, edge), quando é péssimo (logout, revoke, claim bloat). Paseto v4 como alternativa moderna (sem algorithm confusion). Sessions com Redis pra apps clássicos. Refresh token rotation, sliding expiration, revocation lists.',
        keywords: 'jwt vs session, paseto v4, refresh token rotation, revoke jwt, algorithm confusion',
        prerequisites: ['oauth2-oidc-do-zero'],
        nextSuggested: ['password-hashing-moderno'],
        level: 'advanced',
      },
      {
        slug: 'password-hashing-moderno',
        title: 'Password hashing moderno: argon2, bcrypt, peppers',
        icon: '🧂',
        xp: 45, readTime: 10,
        desc: 'Por que SHA-256 puro é crime em 2026. Argon2id (OWASP #1), bcrypt (aceitável), scrypt. Salt sempre, pepper opcional (server-side secret extra). Timing-safe compare. Migrar hash antigo sem quebrar login (re-hash no login).',
        keywords: 'argon2id hash senha, bcrypt owasp, pepper senha, timing safe compare, hash password moderno',
        prerequisites: ['jwt-paseto-sessions'],
        nextSuggested: ['owasp-top-10-com-exemplo-em-codigo'],
        level: 'advanced',
      },
      {
        slug: 'owasp-top-10-com-exemplo-em-codigo',
        title: 'OWASP Top 10 (2024) com exemplo em código',
        icon: '📋',
        xp: 70, readTime: 16,
        desc: 'A01 Broken Access Control, A02 Cryptographic Failures, A03 Injection, A04 Insecure Design, A05 Security Misconfig, A06 Vulnerable Components, A07 Identification & Authn Failures, A08 Software & Data Integrity Failures, A09 Logging Failures, A10 SSRF. Cada um com código ruim → código seguro em TS.',
        keywords: 'owasp top 10 2024, injection typescript, ssrf, broken access control, security misconfig',
        prerequisites: ['password-hashing-moderno'],
        nextSuggested: ['secrets-management'],
        level: 'advanced',
      },
      {
        slug: 'secrets-management',
        title: 'Secrets management: Vault, SOPS e AWS Secrets Manager',
        icon: '🗝️',
        xp: 55, readTime: 12,
        desc: 'Secret em env var é pior que sem segredo. HashiCorp Vault (dynamic secrets, leases), SOPS (git-friendly com KMS/age), AWS Secrets Manager (rotation automática), Doppler pra times pequenos. Padrão: secret never leaves vault; aplicação pede short-lived.',
        keywords: 'hashicorp vault, sops age kms, aws secrets manager, dynamic secrets, doppler secrets',
        prerequisites: ['owasp-top-10-com-exemplo-em-codigo'],
        nextSuggested: ['supply-chain-security'],
        level: 'advanced',
      },
      {
        slug: 'supply-chain-security',
        title: 'Supply chain: SBOM, sigstore e dependency confusion',
        icon: '📦',
        xp: 60, readTime: 13,
        desc: 'SolarWinds, XZ backdoor: atacante entra via deps. SBOM (CycloneDX, SPDX) pra inventário. Sigstore (cosign, rekor) pra assinatura verificável. Scanning com Trivy, Snyk, Dependabot, Socket.dev. Dependency confusion: como namespace privado vaza pra npm público.',
        keywords: 'sbom cyclonedx spdx, sigstore cosign rekor, dependency confusion, trivy snyk, xz backdoor',
        prerequisites: ['secrets-management'],
        nextSuggested: ['zero-trust-e-mtls'],
        level: 'advanced',
      },
      {
        slug: 'zero-trust-e-mtls',
        title: 'Zero Trust e mTLS: verificar sempre, nunca confiar na rede',
        icon: '🚪',
        xp: 55, readTime: 12,
        desc: 'Princípios Zero Trust (verify explicitly, least privilege, assume breach). mTLS pra autenticação mútua entre serviços. SPIFFE/SPIRE pra identidade de workload. Service mesh (Istio, Linkerd) como camada. Alternativa simples: Tailscale/Cloudflare Zero Trust em dev.',
        keywords: 'zero trust, mtls mutual tls, spiffe spire, service mesh istio, tailscale zero trust',
        prerequisites: ['supply-chain-security'],
        nextSuggested: ['capstone-pentest-em-app-proprio'],
        level: 'advanced',
      },
      {
        slug: 'capstone-pentest-em-app-proprio',
        title: 'Capstone: pentest em app próprio (ético)',
        icon: '🏁',
        xp: 85, readTime: 18,
        desc: 'Pegar app que você construiu (ex: Trail 21 capstone) e atacar: Burp Suite pra MITM, ffuf pra fuzzing, nuclei pra scan automatizado, sqlmap pra testar injection. Documentar cada vuln encontrada, severity (CVSS), fix aplicado, regression test. Entregável: relatório de pentest + PRs corrigindo.',
        nextSuggested: ['mvcc-e-isolation-levels-de-verdade'],
        keywords: 'pentest etico, burp suite, ffuf fuzzing, nuclei scan, sqlmap, cvss severity, capstone security',
        prerequisites: ['zero-trust-e-mtls'],
        level: 'advanced',
      },
    ],
  };
