import type { Trail } from '../types';

/** AWS Solutions Architect Professional (SAP-C03) */
export const trilha_trail27: Trail = {
    id: 'trail27', name: 'AWS Solutions Architect Professional (SAP-C03)',
    color: '#ff9900', icon: '🏛️',
    desc: 'Certificação expert da AWS: multi-account (Organizations, Control Tower, Landing Zone), networking avançado (RAM, Cloud WAN, Transit Gateway), migração complexa (7 Rs, DMS, SMS), cost allocation em escala, well-architected framework aplicado, edge, híbrido e disaster recovery. Capstone: simulado SAP-C03 comentado.',
    level: 'advanced', href: '/aws-sap-c03',
    prerequisites: ['simulado-saa-c03'],
    modules: [
      { slug: 'sap-c03-intro', title: 'SAP-C03 intro: domínios, pesos e estratégia', icon: '🎯', xp: 40, readTime: 10, desc: '4 domínios: Design Solutions (26%), New Solutions (29%), Migration Planning (20%), Continuous Improvement (25%). 75 questões, 180min, passing 750. Estudo 3-6 meses pós-SAA.',
        objetivo: 'Você conhece os quatro domínios da SAP-C03 e o que muda de fato em relação à SAA-C03.', keywords: 'aws sap c03, solutions architect professional, aws certification', nextSuggested: ['organizations-control-tower'], level: 'advanced' },
      { slug: 'organizations-control-tower', title: 'Organizations, Control Tower e Landing Zone', icon: '🏗️', xp: 60, readTime: 14, desc: 'Multi-account estratégia: OUs, SCPs, Control Tower guardrails, AFT (Account Factory for Terraform), IAM Identity Center (antes SSO). Padrão em enterprise AWS.', keywords: 'aws organizations, control tower, landing zone, scp service control policy, iam identity center', prerequisites: ['sap-c03-intro'], nextSuggested: ['advanced-networking-sap'], level: 'advanced' },
      { slug: 'advanced-networking-sap', title: 'Advanced networking: RAM, Cloud WAN, Transit Gateway', icon: '🌐', xp: 65, readTime: 15, desc: 'Transit Gateway pra hub-and-spoke, RAM (Resource Access Manager) compartilhando subnets, Cloud WAN (global WAN managed), VPC Lattice. Designs multi-region/multi-account complex.', keywords: 'aws transit gateway, aws ram, cloud wan, vpc lattice, multi-region networking', prerequisites: ['organizations-control-tower'], nextSuggested: ['migracao-7rs-sap'], level: 'advanced' },
      { slug: 'migracao-7rs-sap', title: 'Migration strategy: os 7 Rs + DMS + SMS', icon: '📦', xp: 55, readTime: 13, desc: '7 Rs: Retire, Retain, Rehost, Relocate, Replatform, Refactor, Repurchase. Database Migration Service + Schema Conversion Tool. Application Migration Service. AWS Migration Hub.', keywords: 'aws migration 7rs, dms database migration, aws application migration service, migration hub', prerequisites: ['advanced-networking-sap'], nextSuggested: ['cost-allocation-em-escala'], level: 'advanced' },
      { slug: 'cost-allocation-em-escala', title: 'Cost allocation tags em escala + Cost Categories', icon: '💰', xp: 50, readTime: 12, desc: 'Tagging strategy, Cost Categories (agrupar por project/team/env), Cost Anomaly Detection, AWS Budgets action-enabled, reserved capacity portfolio multi-account.', keywords: 'aws cost allocation tags, cost categories, cost anomaly detection, reserved instances portfolio', prerequisites: ['migracao-7rs-sap'], nextSuggested: ['well-architected-aplicado'], level: 'advanced' },
      { slug: 'well-architected-aplicado', title: 'Well-Architected Framework aplicado em review', icon: '🏛️', xp: 55, readTime: 13, desc: 'Os 6 pilares (Operational Excellence, Security, Reliability, Performance, Cost, Sustainability). WA Tool pra auto-review. Padrões comuns de antipattern e remediation.', keywords: 'well architected framework, wa tool, operational excellence, sustainability pilar', prerequisites: ['cost-allocation-em-escala'], nextSuggested: ['disaster-recovery-estrategias'], level: 'advanced' },
      { slug: 'disaster-recovery-estrategias', title: 'Disaster Recovery: 4 estratégias (backup a multi-site)', icon: '🚨', xp: 55, readTime: 13, desc: 'Backup/restore (RTO/RPO horas), Pilot Light (mins), Warm Standby (min), Multi-Site Active/Active (zero). Route 53 failover, RDS read replicas cross-region, S3 CRR, AWS Elastic Disaster Recovery.', keywords: 'aws disaster recovery, rto rpo, pilot light, warm standby, multi site, drs elastic', prerequisites: ['well-architected-aplicado'], nextSuggested: ['edge-hibrido-sap'], level: 'advanced' },
      { slug: 'edge-hibrido-sap', title: 'Edge e híbrido: Outposts, Wavelength, Local Zones', icon: '📡', xp: 55, readTime: 13, desc: 'Outposts (AWS on-prem rack), Wavelength (edge 5G telcos), Local Zones (urban low-latency), Snow Family (offline transfer). Quando cada um cabe.', keywords: 'aws outposts, wavelength 5g, local zones, snow family, edge hibrido', prerequisites: ['disaster-recovery-estrategias'], nextSuggested: ['analytics-bigdata-sap'], level: 'advanced' },
      { slug: 'analytics-bigdata-sap', title: 'Analytics em escala: Redshift, EMR, Athena, Lake Formation', icon: '📊', xp: 60, readTime: 14, desc: 'Data warehouse (Redshift), big data (EMR Spark/Hadoop), serverless SQL (Athena), lake governance (Lake Formation), pipelines (Glue, Step Functions), real-time (Kinesis).', keywords: 'aws redshift, emr spark, athena, lake formation, kinesis analytics', prerequisites: ['edge-hibrido-sap'], nextSuggested: ['seguranca-sap-avancada'], level: 'advanced' },
      { slug: 'seguranca-sap-avancada', title: 'Segurança enterprise: GuardDuty, Detective, Security Hub', icon: '🛡️', xp: 60, readTime: 14, desc: 'GuardDuty (threat detection ML), Detective (investigation), Security Hub (unified view), Macie (PII descoberta), Network Firewall, WAF avançado, Inspector continuous.', keywords: 'aws guardduty, detective, security hub, macie, network firewall, waf inspector', prerequisites: ['analytics-bigdata-sap'], nextSuggested: ['ml-ia-arquiteto-sap'], level: 'advanced' },
      { slug: 'ml-ia-arquiteto-sap', title: 'ML/IA sob ótica de arquiteto: Bedrock, SageMaker, Comprehend', icon: '🤖', xp: 55, readTime: 13, desc: 'Bedrock (foundation models managed), SageMaker (MLOps completo), Comprehend (NLP), Textract (OCR), Rekognition (vision). Quando managed vs self-host.', keywords: 'aws bedrock, sagemaker mlops, comprehend nlp, textract, rekognition', prerequisites: ['seguranca-sap-avancada'], nextSuggested: ['containers-serverless-sap'], level: 'advanced' },
      { slug: 'containers-serverless-sap', title: 'Containers e serverless em arquitetura enterprise', icon: '📦', xp: 55, readTime: 13, desc: 'ECS vs EKS vs App Runner, Fargate, Lambda com container image, App Mesh (service mesh), Cloud Map (service discovery), quando escolher cada.', keywords: 'aws ecs eks, fargate, app runner, app mesh service discovery, serverless containers', prerequisites: ['ml-ia-arquiteto-sap'], nextSuggested: ['hibrido-direct-connect'], level: 'advanced' },
      { slug: 'hibrido-direct-connect', title: 'Híbrido: Direct Connect, Site-to-Site VPN, Storage Gateway', icon: '🔗', xp: 55, readTime: 13, desc: 'DX (dedicated link on-prem ↔ AWS), VPN gateway, Storage Gateway (File/Volume/Tape), DataSync. Patterns híbridos reais + encryption in-transit.', keywords: 'aws direct connect, site to site vpn, storage gateway, datasync, hibrido on-prem', prerequisites: ['containers-serverless-sap'], nextSuggested: ['cicd-enterprise-sap'], level: 'advanced' },
      { slug: 'cicd-enterprise-sap', title: 'CI/CD enterprise multi-account com CDK Pipelines', icon: '🚀', xp: 60, readTime: 14, desc: 'CDK Pipelines pra deploy cross-account, CodePipeline com manual approval gates, artifact signing, rollback strategies, blue/green em escala.', keywords: 'cdk pipelines multi account, codepipeline enterprise, manual approval, blue green cicd', prerequisites: ['hibrido-direct-connect'], nextSuggested: ['governance-compliance-sap'], level: 'advanced' },
      { slug: 'governance-compliance-sap', title: 'Governance e compliance: Config, Audit Manager, Artifact', icon: '📋', xp: 50, readTime: 12, desc: 'AWS Config (config compliance), Audit Manager (frameworks PCI/HIPAA/SOC2), Artifact (compliance reports baixar), License Manager, Service Catalog.', keywords: 'aws config, audit manager, aws artifact, license manager, service catalog', prerequisites: ['cicd-enterprise-sap'], nextSuggested: ['observability-enterprise'], level: 'advanced' },
      { slug: 'observability-enterprise', title: 'Observability enterprise: CloudWatch, X-Ray, OpenSearch', icon: '🔭', xp: 55, readTime: 13, desc: 'CloudWatch Logs Insights, Metrics, Alarms, Dashboards, Application Insights, Container Insights. X-Ray service map. OpenSearch pra logs pesquisáveis em escala.', keywords: 'cloudwatch insights, x-ray service map, opensearch logs, container insights', prerequisites: ['governance-compliance-sap'], nextSuggested: ['cost-optimization-sap'], level: 'advanced' },
      { slug: 'cost-optimization-sap', title: 'Cost optimization avançado: rightsizing, purchasing, monitoring', icon: '💸', xp: 55, readTime: 13, desc: 'Compute Optimizer, Trusted Advisor, Savings Plans (Compute vs EC2 vs SageMaker), Reserved Instances portfolio, Spot Fleet, S3 Intelligent-Tiering, resource cleanup automation.', keywords: 'aws compute optimizer, savings plans, reserved instances, spot fleet, intelligent tiering', prerequisites: ['observability-enterprise'], nextSuggested: ['simulado-sap-c03'], level: 'advanced' },
      { slug: 'simulado-sap-c03', title: 'Capstone: simulado SAP-C03 comentado', icon: '🏁', xp: 95, readTime: 22, desc: 'Simulado estilo SAP-C03 com 10+ questões comentadas cobrindo todos os domínios. Estratégia de time management, elimination pattern, leitura de questões longas (250+ palavras).', nextSuggested: ['o-que-e-ia'], keywords: 'simulado aws sap c03, solutions architect professional exam, aws certification prep', prerequisites: ['cost-optimization-sap'], level: 'advanced' },
    ],
  };
