import type { Trail } from '../types';

/** AWS Cloud Practitioner */
export const trilha_trail4: Trail = {
    id: 'trail4',
    name: 'AWS Cloud Practitioner',
    color: '#ff9900',
    icon: '☁️',
    desc: 'Fundamentos da AWS alinhados ao exame CLF-C02 — do zero ao certificado',
    level: 'beginner',
    href: '/aws-cloud-practitioner',
    modules: [
      {
        slug: 'o-que-e-cloud',
        title: 'O que é Cloud Computing?',
        icon: '☁️',
        xp: 30,
        readTime: 8,
        desc: 'IaaS, PaaS, SaaS, deployment models, economia de escala — o que a nuvem realmente muda e por que a AWS venceu.',
        objetivo: 'Você diferencia IaaS, PaaS e SaaS e explica por que a AWS venceu, não só que ela venceu.',
        level: 'beginner',
        keywords: 'o que é cloud computing, IaaS PaaS SaaS, cloud publica privada hibrida, aws cloud practitioner',
        nextSuggested: ['aws-global-infra'],
      },
      {
        slug: 'aws-global-infra',
        title: 'Infraestrutura Global: Regiões, AZs e Edge',
        icon: '🌍',
        xp: 40,
        readTime: 8,
        desc: 'Regions, Availability Zones, Edge Locations, Local Zones, Wavelength — como a AWS distribui capacidade no planeta.',
        level: 'beginner',
        keywords: 'aws regions availability zones, AZ edge location, infraestrutura global aws, local zones wavelength',
        prerequisites: ['o-que-e-cloud'],
        nextSuggested: ['modelo-responsabilidade-compartilhada'],
      },
      {
        slug: 'modelo-responsabilidade-compartilhada',
        title: 'Modelo de Responsabilidade Compartilhada',
        icon: '🤝',
        xp: 35,
        readTime: 7,
        desc: 'O que é responsabilidade da AWS e o que é sua. A linha que cai em metade das questões de segurança do exame.',
        level: 'beginner',
        keywords: 'modelo responsabilidade compartilhada aws, shared responsibility model, seguranca aws cliente',
        prerequisites: ['aws-global-infra'],
        nextSuggested: ['iam-fundamentos'],
      },
      {
        slug: 'iam-fundamentos',
        title: 'IAM: Identidade, Grupos, Roles e Policies',
        icon: '🔐',
        xp: 60,
        readTime: 12,
        desc: 'Users, Groups, Roles, Policies, MFA, root account — os blocos fundamentais de segurança na AWS.',
        level: 'beginner',
        keywords: 'aws iam fundamentos, iam user group role policy, mfa aws, root account aws',
        prerequisites: ['modelo-responsabilidade-compartilhada'],
        nextSuggested: ['compute-ec2-lambda'],
      },
      {
        slug: 'compute-ec2-lambda',
        title: 'Compute: EC2, Lambda e Containers',
        icon: '🖥️',
        xp: 60,
        readTime: 12,
        desc: 'EC2 instance types, purchasing options, Lambda, Fargate, ECS e EKS — os serviços de compute que todo practitioner precisa dominar.',
        level: 'beginner',
        keywords: 'aws ec2 lambda container, ec2 instance types, on demand reserved spot, fargate ecs eks',
        prerequisites: ['iam-fundamentos'],
        nextSuggested: ['storage-s3-ebs-efs'],
      },
      {
        slug: 'storage-s3-ebs-efs',
        title: 'Storage: S3, EBS, EFS e Glacier',
        icon: '💾',
        xp: 55,
        readTime: 11,
        desc: 'Object, block, file storage — S3 storage classes, EBS volume types, EFS, Glacier, Storage Gateway. Como escolher.',
        level: 'beginner',
        keywords: 'aws s3 ebs efs glacier, s3 storage classes, ebs volume types, quando usar s3 ebs efs',
        prerequisites: ['compute-ec2-lambda'],
        nextSuggested: ['databases-aws-basico'],
      },
      {
        slug: 'databases-aws-basico',
        title: 'Databases: RDS, Aurora, DynamoDB e Redshift',
        icon: '🗄️',
        xp: 60,
        readTime: 12,
        desc: 'Relacional vs NoSQL vs analítico. RDS, Aurora, DynamoDB, ElastiCache, Redshift — quando usar cada um no CLF-C02.',
        level: 'beginner',
        keywords: 'aws databases, rds aurora dynamodb, redshift elasticache, quando usar rds ou dynamodb',
        prerequisites: ['storage-s3-ebs-efs'],
        nextSuggested: ['networking-vpc-route53'],
      },
      {
        slug: 'networking-vpc-route53',
        title: 'Networking: VPC, Route 53 e CloudFront',
        icon: '🌐',
        xp: 55,
        readTime: 11,
        desc: 'VPC, subnets, Internet Gateway, NAT, Route 53 DNS, CloudFront CDN, Direct Connect, VPN — a rede da AWS demistificada.',
        level: 'beginner',
        keywords: 'aws vpc networking, route 53 dns, cloudfront cdn, direct connect vpn aws',
        prerequisites: ['databases-aws-basico'],
        nextSuggested: ['seguranca-aws-servicos'],
      },
      {
        slug: 'seguranca-aws-servicos',
        title: 'Segurança AWS: KMS, GuardDuty, Shield e WAF',
        icon: '🛡️',
        xp: 60,
        readTime: 11,
        desc: 'KMS, Secrets Manager, GuardDuty, Shield, WAF, Inspector, Macie — o arsenal de segurança que cobre 30% do exame.',
        level: 'beginner',
        keywords: 'aws kms guardduty shield waf, secrets manager, inspector macie, seguranca aws servicos',
        prerequisites: ['iam-fundamentos'],
        nextSuggested: ['monitoramento-cloudwatch'],
      },
      {
        slug: 'monitoramento-cloudwatch',
        title: 'Monitoramento: CloudWatch, CloudTrail e Config',
        icon: '📊',
        xp: 45,
        readTime: 9,
        desc: 'CloudWatch (métricas e logs), CloudTrail (auditoria de API) e Config (compliance) — o tripé de observabilidade.',
        level: 'beginner',
        keywords: 'aws cloudwatch cloudtrail config, cloudwatch vs cloudtrail, aws config compliance, monitoramento aws',
        prerequisites: ['seguranca-aws-servicos'],
        nextSuggested: ['well-architected-framework'],
      },
      {
        slug: 'well-architected-framework',
        title: 'Well-Architected: os 6 Pilares',
        icon: '🏛️',
        xp: 50,
        readTime: 10,
        desc: 'Operational Excellence, Security, Reliability, Performance, Cost Optimization, Sustainability — o framework que guia toda decisão AWS.',
        level: 'beginner',
        keywords: 'well architected framework aws, 6 pilares aws, operational excellence security reliability',
        prerequisites: ['monitoramento-cloudwatch'],
        nextSuggested: ['cloud-adoption-framework'],
      },
      {
        slug: 'cloud-adoption-framework',
        title: 'CAF e os 7 Rs da Migração',
        icon: '🚚',
        xp: 45,
        readTime: 9,
        desc: 'Cloud Adoption Framework (6 perspectivas) e as 7 estratégias de migração — Rehost, Replatform, Refactor, Relocate, Retire, Retain, Repurchase.',
        level: 'beginner',
        keywords: 'cloud adoption framework aws, 7 rs migracao, rehost replatform refactor, caf perspectives',
        prerequisites: ['well-architected-framework'],
        nextSuggested: ['precificacao-suporte'],
      },
      {
        slug: 'precificacao-suporte',
        title: 'Precificação, Free Tier e Planos de Suporte',
        icon: '💰',
        xp: 50,
        readTime: 10,
        desc: 'Pay-as-you-go, Free Tier, Pricing Calculator, Cost Explorer, Budgets, TCO Calculator e os 4 Support Plans — tudo sobre a fatura da AWS.',
        level: 'beginner',
        keywords: 'aws pricing free tier, pricing calculator cost explorer, aws budgets, support plans aws',
        prerequisites: ['cloud-adoption-framework'],
        nextSuggested: ['migracao-aws-servicos'],
      },
      {
        slug: 'migracao-aws-servicos',
        title: 'Migração: Migration Hub, DMS, MGN e DataSync',
        icon: '🚚',
        xp: 45,
        readTime: 9,
        desc: 'Migration Hub, Application Migration Service (MGN), DMS, Application Discovery Service, DataSync e Mainframe Modernization — o arsenal de migração AWS.',
        level: 'beginner',
        keywords: 'aws migration hub, aws mgn application migration service, aws dms, application discovery service, aws datasync',
        prerequisites: ['precificacao-suporte'],
        nextSuggested: ['ai-ml-aws-servicos'],
      },
      {
        slug: 'ai-ml-aws-servicos',
        title: 'IA e ML na AWS: Bedrock, SageMaker, Q e Amigos',
        icon: '🧠',
        xp: 50,
        readTime: 10,
        desc: 'SageMaker, Rekognition, Comprehend, Polly, Transcribe, Translate, Lex, Kendra, Bedrock e Amazon Q — o stack de IA da AWS para o CLF-C02.',
        level: 'beginner',
        keywords: 'aws sagemaker, amazon bedrock, amazon q, aws rekognition comprehend, polly transcribe translate, amazon lex kendra',
        prerequisites: ['migracao-aws-servicos'],
        nextSuggested: ['developer-tools-aws'],
      },
      {
        slug: 'developer-tools-aws',
        title: 'Developer Tools: CodePipeline, CDK, CloudFormation e SAM',
        icon: '🛠️',
        xp: 45,
        readTime: 9,
        desc: 'CodeCommit, CodeBuild, CodeDeploy, CodePipeline, CloudFormation, CDK, SAM, Amplify e X-Ray — os serviços de CI/CD e IaC da AWS.',
        level: 'beginner',
        keywords: 'aws codepipeline cicd, aws cloudformation cdk, aws sam serverless, aws codebuild codedeploy, aws x-ray amplify',
        prerequisites: ['ai-ml-aws-servicos'],
        nextSuggested: ['simulado-practitioner'],
      },
      {
        slug: 'simulado-practitioner',
        title: 'Simulado CLF-C02 Comentado',
        icon: '🎯',
        xp: 80,
        readTime: 20,
        desc: '20 questões no estilo oficial do exame, cada uma com explicação detalhada de por que a resposta certa é certa e as erradas são erradas.',
        level: 'beginner',
        keywords: 'simulado aws cloud practitioner, clf-c02 questoes comentadas, prova aws practitioner, preparacao exame aws',
        prerequisites: ['developer-tools-aws'],
        nextSuggested: ['saa-c03-intro', 'lab-app-web-ecs-fargate-rds'],
      },
    ],
  };
