import type { Level, Trail } from '../types';

/** Search & Information Retrieval Profundo */
export const trilha_trail_search_ir_deep: Trail = {
    id: 'trail-search-ir-deep',
    name: 'Search & Information Retrieval Profundo',
    color: '#0ea5e9',
    icon: '🔎',
    desc: 'Busca como engenharia: BM25/TF-IDF, Elasticsearch internals, OpenSearch/Meilisearch/Typesense comparados, hybrid search, reranking BGE/Cohere, vector DBs e métricas de avaliação',
    level: 'advanced' as Level,
    href: '/search-ir-deep',
    modules: [
      { slug: 'bm25-tfidf-fundamentos', title: 'BM25 e TF-IDF: a math da busca clássica', icon: '📐', xp: 65, readTime: 13, desc: 'TF-IDF (1972), BM25 (Robertson, 1994) — a fundação que ainda manda em 2026. Term frequency saturation, IDF smoothing, parâmetros k1 e b do BM25. Por que BGE-M3 ainda combina com BM25 (hybrid).',
        objetivo: 'Você entende por que BM25 ainda vence em produção e quando combiná-lo com busca vetorial em vez de escolher só um dos dois.', keywords: 'bm25 tf-idf, robertson 1994, hybrid search bm25, term frequency saturation', level: 'advanced' as Level, nextSuggested: ['elasticsearch-internals'] },
      { slug: 'elasticsearch-internals', title: 'Elasticsearch internals: Lucene, segments, shards, refresh', icon: '🔬', xp: 75, readTime: 15, desc: 'Apache Lucene como motor (inverted index, segments, posting lists), refresh interval, translog, shard allocation, replicas, near-real-time search. ELK vs OpenSearch fork (Elastic license drama 2021).', keywords: 'elasticsearch lucene, segments lucene, opensearch fork, refresh interval', level: 'advanced' as Level, prerequisites: ['bm25-tfidf-fundamentos'], nextSuggested: ['opensearch-meilisearch-typesense'] },
      { slug: 'opensearch-meilisearch-typesense', title: 'OpenSearch vs Meilisearch vs Typesense: qual escolher', icon: '⚖️', xp: 65, readTime: 13, desc: 'OpenSearch (AWS, fork ES), Meilisearch (Rust, French startup, typo-tolerance), Typesense (faceted, fast). Comparativo: setup, latência, vector support, multi-tenant. Quando vale ES vs alternativa enxuta.', keywords: 'opensearch vs meilisearch typesense, search engine 2026, elasticsearch alternative', level: 'intermediate' as Level, prerequisites: ['elasticsearch-internals'], nextSuggested: ['hybrid-search-rerank'] },
      { slug: 'hybrid-search-rerank', title: 'Hybrid search + reranking: BM25 + dense + cross-encoder', icon: '🎯', xp: 75, readTime: 15, desc: 'Estado da arte 2026: combinar BM25 (lexical) + dense vector (semantic) com Reciprocal Rank Fusion (RRF), depois rerank com cross-encoder (BGE-reranker, Cohere Rerank). Pipeline 3-stage que vence single-method.', keywords: 'hybrid search, reciprocal rank fusion, bge reranker, cohere rerank, cross encoder', level: 'advanced' as Level, prerequisites: ['opensearch-meilisearch-typesense'], nextSuggested: ['embeddings-busca-bge'] },
      { slug: 'embeddings-busca-bge', title: 'Embeddings de busca: BGE-M3, e5, Voyage, Cohere v3', icon: '🧬', xp: 70, readTime: 14, desc: 'Modelos de embedding em 2026: BGE-M3 (BAAI, multilingual + multi-granularity), e5 (Microsoft), Voyage AI, Cohere embed v3, OpenAI text-embedding-3. Dimensões (768 → 1024 → 1536), MRL (Matryoshka Representation Learning).', keywords: 'bge-m3 embeddings, e5 microsoft, voyage ai, cohere embed v3, mrl matryoshka', level: 'advanced' as Level, prerequisites: ['hybrid-search-rerank'], nextSuggested: ['semantic-search-prod'] },
      { slug: 'semantic-search-prod', title: 'Semantic search em produção: indexing, sharding, freshness', icon: '🚢', xp: 70, readTime: 14, desc: 'Operacional de semantic search em escala: indexing pipelines (Airflow, Prefect), shard strategy, hot/cold tier, freshness lag, blue-green reindex, snapshot & restore. Custo de embedding em massa (1B docs).', keywords: 'semantic search production, indexing pipeline embedding, blue-green reindex', level: 'advanced' as Level, prerequisites: ['embeddings-busca-bge'], nextSuggested: ['vector-dbs-comparados'] },
      { slug: 'vector-dbs-comparados', title: 'Vector DBs em 2026: Qdrant, Weaviate, Pinecone, pgvector', icon: '🗄️', xp: 65, readTime: 13, desc: 'Qdrant (Rust, self-host friendly), Weaviate (modular), Pinecone (serverless, agora c/ namespaces), pgvector (Postgres extension, hybrid simples), LanceDB (embedded). HNSW vs IVF vs DiskANN. Quando cada um vence.', keywords: 'vector db 2026, qdrant weaviate pinecone, pgvector hnsw, lancedb embedded', level: 'advanced' as Level, prerequisites: ['semantic-search-prod'], nextSuggested: ['search-eval-mrr-ndcg'] },
      { slug: 'search-eval-mrr-ndcg', title: 'Avaliação de busca: MRR, NDCG, P@K, golden datasets', icon: '📊', xp: 65, readTime: 13, desc: 'Sem métrica, você vai no feeling. MRR (Mean Reciprocal Rank), NDCG@10 (Normalized Discounted Cumulative Gain), Precision@K, Recall@K. Como construir golden dataset (clickstream + manual annotation), A/B testing de ranking.', nextSuggested: ['batch-vs-stream-mental-model'], keywords: 'mrr ndcg precision recall, search evaluation, golden dataset search, ab test ranking', level: 'advanced' as Level, prerequisites: ['vector-dbs-comparados'] },
    ],
  };
