import type { Level, Trail } from '../types';

/** Diffusion Models & Geração Multimodal */
export const trilha_trail_diffusion_multimodal: Trail = {
    id: 'trail-diffusion-multimodal',
    name: 'Diffusion Models & Geração Multimodal',
    color: '#ec4899',
    icon: '🎨',
    desc: 'Stable Diffusion 3.5, Flux e Sora-like models por dentro: score matching, U-Net + VAE, ControlNet, LoRA de imagem, ComfyUI engineering, video generation, APIs de geração',
    level: 'advanced' as Level,
    href: '/diffusion-multimodal',
    modules: [
      { slug: 'diffusion-score-matching-math', title: 'Diffusion math: score matching e SDE/ODE', icon: '🧮', xp: 80, readTime: 16, desc: 'A matemática real: forward diffusion (gaussian noise progressivo), reverse process (denoising), score function ∇log p(x), SDE (Score-based Generative Modeling, Song & Ermon 2020) vs DDPM (Ho 2020) vs DDIM. Sem hand-waving.',
        objetivo: 'Você lê a matemática por trás de um diffusion model — forward, reverse e score function — sem recorrer a analogia solta.', keywords: 'diffusion model math, score matching, ddpm ddim, sde generative model', level: 'advanced' as Level, nextSuggested: ['vae-unet-internals'] },
      { slug: 'vae-unet-internals', title: 'VAE + U-Net: a arquitetura por trás do Stable Diffusion', icon: '🏗️', xp: 70, readTime: 14, desc: 'Variational Autoencoder (VAE) para latent space compression, U-Net com cross-attention para denoising condicional, text encoder (CLIP/T5). Latent Diffusion (Rombach 2022). Por que SD opera em latent space e não em pixels.', keywords: 'vae u-net stable diffusion, latent diffusion rombach, cross attention clip', level: 'advanced' as Level, prerequisites: ['diffusion-score-matching-math'], nextSuggested: ['stable-diffusion-3-flux'] },
      { slug: 'stable-diffusion-3-flux', title: 'Stable Diffusion 3.5 e Flux: MMDiT e DiT por dentro', icon: '⚡', xp: 75, readTime: 15, desc: 'A geração 2024-2026: SD3.5 com MMDiT (Multimodal Diffusion Transformer, Esser et al), Flux.1 da Black Forest Labs (RM Esser saiu da Stability), DiT architecture (Peebles & Xie 2023). Por que substitui U-Net.', keywords: 'stable diffusion 3.5, flux black forest labs, mmdit dit, peebles xie transformer', level: 'advanced' as Level, prerequisites: ['vae-unet-internals'], nextSuggested: ['controlnet-condicionamento'] },
      { slug: 'controlnet-condicionamento', title: 'ControlNet: condicionamento espacial preciso', icon: '🎛️', xp: 70, readTime: 14, desc: 'ControlNet (Zhang & Agrawala 2023, ICCV best paper): condicionamento por canny edge, depth map, pose, scribble. Como funciona internamente (zero-conv, weight copy), múltiplos ControlNets, IP-Adapter para style transfer.', keywords: 'controlnet, zero-conv, ip-adapter, canny depth pose conditioning', level: 'advanced' as Level, prerequisites: ['stable-diffusion-3-flux'], nextSuggested: ['lora-imagem-treino'] },
      { slug: 'lora-imagem-treino', title: 'LoRA de imagem: treinar style/character em 30 min', icon: '🎓', xp: 75, readTime: 15, desc: 'Low-Rank Adaptation aplicada a diffusion models. Kohya_ss, OneTrainer, ai-toolkit (Ostris). Datasets de 10-30 imagens, captioning automático, training loss curves, overfitting visual. SDXL vs Flux LoRA — por que Flux é mais difícil.', keywords: 'lora imagem treino, kohya ss, ai-toolkit ostris, flux lora training', level: 'advanced' as Level, prerequisites: ['controlnet-condicionamento'], nextSuggested: ['comfyui-engineering'] },
      { slug: 'comfyui-engineering', title: 'ComfyUI engineering: workflow como código', icon: '🔧', xp: 65, readTime: 13, desc: 'ComfyUI virou padrão profissional em 2024-26. Workflow JSON como artefato versionável, custom nodes em Python, ComfyUI API server, ComfyUI Deploy patterns. Por que substituiu A1111 em prod.', keywords: 'comfyui workflow, comfyui custom nodes, comfyui deploy, a1111 vs comfyui', level: 'intermediate' as Level, prerequisites: ['lora-imagem-treino'], nextSuggested: ['video-generation-sora'] },
      { slug: 'video-generation-sora', title: 'Video generation: Sora, Runway Gen-4, Kling, Veo', icon: '🎬', xp: 70, readTime: 14, desc: 'Estado da arte 2026: OpenAI Sora, Runway Gen-4, Kling 2.0, Google Veo 3. DiT estendido para temporal (3D attention), VAE temporal compression, image-to-video vs text-to-video. Limites práticos (8s, custo, controle).', keywords: 'sora video generation, runway gen-4, kling 2.0, google veo 3', level: 'advanced' as Level, prerequisites: ['comfyui-engineering'], nextSuggested: ['api-replicate-fal'] },
      { slug: 'api-replicate-fal', title: 'APIs de geração: Replicate, fal.ai, RunPod, Modal', icon: '🌐', xp: 55, readTime: 11, desc: 'Quando rodar em GPU própria vs usar API. Replicate (cold-start ok, marketplace), fal.ai (low-latency, websockets), RunPod (serverless GPU), Modal (Python-native). Modelos de pricing comparados, falbacks, rate limits.', keywords: 'replicate api, fal.ai, runpod serverless gpu, modal python ai', level: 'intermediate' as Level, prerequisites: ['video-generation-sora'], nextSuggested: ['eval-fid-clip'] },
      { slug: 'eval-fid-clip', title: 'Avaliação: FID, CLIP score, DPG-Bench, human eval', icon: '📊', xp: 60, readTime: 12, desc: 'Como medir "boa imagem". FID (Frechet Inception Distance), CLIP score (alinhamento texto-imagem), DPG-Bench (compositional), human pref via Elo (Imagen Arena). Por que human eval ainda manda em 2026.', keywords: 'fid score, clip score, dpg-bench, imagen arena human eval', level: 'advanced' as Level, prerequisites: ['api-replicate-fal'], nextSuggested: ['modelos-3d-mesh'] },
      { slug: 'modelos-3d-mesh', title: 'Geração 3D: TripoSR, Stable Fast 3D, mesh do prompt', icon: '🗿', xp: 65, readTime: 13, desc: 'Geração 3D madureceu 2024-26: TripoSR (single image → mesh em 0.5s), Stable Fast 3D, Hunyuan3D, Trellis. Pipeline: image-to-3D vs text-to-3D, mesh quality, retopology automática. Casos: AR/VR, jogos indie.', nextSuggested: ['bedrock-o-que-e-e-por-que'], keywords: 'triposr, stable fast 3d, hunyuan3d, trellis 3d generation', level: 'advanced' as Level, prerequisites: ['eval-fid-clip'] },
    ],
  };
