import type { Trail } from '../types';

/** AWS Solutions Architect Associate */
export const trilha_trail5: Trail = {
    id: 'trail5',
    name: 'AWS Solutions Architect Associate',
    color: '#146eb4',
    icon: '🏛️',
    // `desc` é o parágrafo de abertura da página da trilha, então descreve a
    // trilha em vez de rotulá-la. Tinha 66 caracteres e era a segunda mais curta.
    desc: 'Arquitetura de soluções na AWS alinhada ao SAA-C03: VPC de verdade, escolha entre EC2, containers e serverless, armazenamento por padrão de acesso, banco por carga, alta disponibilidade em várias zonas, recuperação de desastre com RPO e RTO declarados, e otimização de custo. Cada decisão com o trade-off à vista, não a resposta decorada.',
    level: 'advanced',
    href: '/aws-saa-c03',
    prerequisites: ['trail4'],
    modules: [
      {
        slug: 'saa-c03-intro',
        title: 'SAA-C03: Da Teoria à Arquitetura Real',
        icon: '🎓',
        xp: 40,
        readTime: 8,
        desc: 'O que muda do Practitioner para o SAA-C03, os 4 domínios do exame, pré-requisitos e a mentalidade do arquiteto AWS.',
        objetivo: 'Você sabe o que muda do Cloud Practitioner para o SAA-C03 e entra na trilha com a mentalidade certa, não só o vocabulário.',
        level: 'advanced',
        keywords: 'aws saa-c03, solutions architect associate, dominios exame saa, preparacao saa-c03',
        prerequisites: ['simulado-practitioner'],
        nextSuggested: ['iam-avancado-organizations', 'vpc-avancado'],
      },
      {
        slug: 'iam-avancado-organizations',
        title: 'IAM Avançado: Policies JSON, STS e Organizations',
        icon: '🔑',
        xp: 75,
        readTime: 14,
        desc: 'Policy JSON em profundidade, STS AssumeRole, cross-account access, AWS Organizations, SCPs, Identity Center (SSO).',
        level: 'advanced',
        nextSuggested: ['vpc-avancado'],
        keywords: 'iam policy json aws, sts assume role, aws organizations scp, identity center sso, cross account access',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 'vpc-avancado',
        title: 'VPC em Profundidade: NAT, Peering e Transit Gateway',
        icon: '🕸️',
        xp: 85,
        readTime: 16,
        desc: 'VPC design real, subnets públicas/privadas, NAT Gateway vs NAT Instance, VPC Peering, Transit Gateway, PrivateLink, VPN vs Direct Connect.',
        level: 'advanced',
        nextSuggested: ['dns-cdn-edge'],
        keywords: 'vpc avancado aws, transit gateway vpc peering, nat gateway nat instance, privatelink vpn direct connect',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 'dns-cdn-edge',
        title: 'Route 53, CloudFront e Global Accelerator',
        icon: '🌐',
        xp: 70,
        readTime: 13,
        desc: 'Route 53 routing policies (simple, weighted, latency, failover, geo, multi-value), CloudFront behaviors, Global Accelerator.',
        level: 'advanced',
        nextSuggested: ['ec2-autoscaling-elb'],
        keywords: 'route 53 routing policies, cloudfront behaviors, global accelerator aws, dns failover weighted',
        prerequisites: ['vpc-avancado'],
      },
      {
        slug: 'ec2-autoscaling-elb',
        title: 'EC2 Profissional: Auto Scaling e Load Balancers',
        icon: '⚖️',
        xp: 80,
        readTime: 15,
        desc: 'Purchasing options profundos, Auto Scaling Groups, ALB vs NLB vs GWLB, target groups, placement groups, health checks.',
        level: 'advanced',
        nextSuggested: ['containers-ecs-eks'],
        keywords: 'ec2 auto scaling, alb nlb gwlb, target groups, placement groups aws, purchasing options ec2',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 'containers-ecs-eks',
        title: 'ECS vs EKS: Orquestração de Containers',
        icon: '📦',
        xp: 70,
        readTime: 13,
        desc: 'ECS (Fargate vs EC2 launch type), EKS (Kubernetes managed), service discovery, service mesh, quando escolher cada um.',
        level: 'advanced',
        nextSuggested: ['serverless-lambda-avancado'],
        keywords: 'ecs vs eks aws, fargate vs ec2, kubernetes aws, service discovery container aws',
        prerequisites: ['ec2-autoscaling-elb'],
      },
      {
        slug: 'serverless-lambda-avancado',
        title: 'Serverless Avançado: Lambda, API GW e Step Functions',
        icon: '⚡',
        xp: 80,
        readTime: 15,
        desc: 'Lambda deep dive (cold start, concurrency, layers, destinations), API Gateway (REST vs HTTP), Step Functions workflows.',
        level: 'advanced',
        nextSuggested: ['s3-avancado'],
        keywords: 'lambda cold start concurrency, api gateway rest http, step functions workflow, serverless aws',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 's3-avancado',
        title: 'S3 Profundo: Classes, Lifecycle e Object Lock',
        icon: '🪣',
        xp: 80,
        readTime: 15,
        desc: 'Todas storage classes, lifecycle policies, versioning, replication (CRR/SRR), Object Lock, encryption (SSE-S3, SSE-KMS, SSE-C, CSE).',
        level: 'advanced',
        nextSuggested: ['block-file-storage'],
        keywords: 's3 storage classes, s3 lifecycle policy, s3 replication crr srr, s3 object lock, s3 encryption sse',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 'block-file-storage',
        title: 'EBS, EFS e FSx: Quando Usar Cada Um',
        icon: '💽',
        xp: 60,
        readTime: 12,
        desc: 'EBS volume types (gp3, io2, st1, sc1), snapshots, EFS performance/throughput modes, FSx Windows/Lustre/NetApp, Storage Gateway.',
        level: 'advanced',
        nextSuggested: ['rds-aurora-dynamodb'],
        keywords: 'ebs volume types gp3 io2, efs performance modes, fsx windows lustre, storage gateway aws',
        prerequisites: ['s3-avancado'],
      },
      {
        slug: 'rds-aurora-dynamodb',
        title: 'Bancos: Multi-AZ, Read Replicas e DynamoDB',
        icon: '🗃️',
        xp: 90,
        readTime: 17,
        desc: 'RDS Multi-AZ vs Read Replicas, Aurora (cluster + Serverless v2), DynamoDB (GSI/LSI, DAX, Streams, on-demand vs provisioned).',
        level: 'advanced',
        nextSuggested: ['caching-performance'],
        keywords: 'rds multi-az read replicas, aurora cluster serverless, dynamodb gsi lsi dax, dynamodb streams',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 'caching-performance',
        title: 'Caching: ElastiCache, DAX e CloudFront',
        icon: '🚀',
        xp: 60,
        readTime: 12,
        desc: 'ElastiCache Redis vs Memcached, DAX para DynamoDB, CloudFront cache behaviors, patterns (cache-aside, write-through).',
        level: 'advanced',
        nextSuggested: ['messaging-eventos'],
        keywords: 'elasticache redis memcached, dax dynamodb, cloudfront cache, cache patterns aws',
        prerequisites: ['rds-aurora-dynamodb'],
      },
      {
        slug: 'messaging-eventos',
        title: 'Messaging: SQS, SNS, EventBridge e Kinesis',
        icon: '📨',
        xp: 70,
        readTime: 13,
        desc: 'SQS (Standard vs FIFO, DLQ), SNS (topic fanout), EventBridge (event bus, rules, schedules), Kinesis (Streams vs Firehose vs Analytics).',
        level: 'advanced',
        nextSuggested: ['seguranca-avancada'],
        keywords: 'sqs standard fifo dlq, sns fanout, eventbridge rules, kinesis streams firehose',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 'seguranca-avancada',
        title: 'Segurança Avançada: KMS, Secrets Manager e WAF',
        icon: '🔒',
        xp: 80,
        readTime: 15,
        desc: 'KMS envelope encryption, CMK vs AWS managed key, Secrets Manager vs Parameter Store, WAF rules, Shield Standard vs Advanced.',
        level: 'advanced',
        nextSuggested: ['disaster-recovery'],
        keywords: 'kms envelope encryption, cmk customer managed key, secrets manager parameter store, waf rules shield advanced',
        prerequisites: ['iam-avancado-organizations'],
      },
      {
        slug: 'disaster-recovery',
        title: 'Disaster Recovery: RPO, RTO e 4 Estratégias',
        icon: '🆘',
        xp: 70,
        readTime: 13,
        desc: 'Backup & Restore, Pilot Light, Warm Standby, Multi-Site Active-Active — custo vs RTO/RPO, AWS Backup, cross-region DR.',
        level: 'advanced',
        nextSuggested: ['cost-optimization-saa'],
        keywords: 'disaster recovery aws, backup restore pilot light warm standby, rpo rto, aws backup cross region',
        prerequisites: ['s3-avancado', 'rds-aurora-dynamodb'],
      },
      {
        slug: 'cost-optimization-saa',
        title: 'Otimização de Custos: RI, Savings Plans e Spot',
        icon: '💵',
        xp: 60,
        readTime: 12,
        desc: 'Reserved Instances (standard/convertible), Savings Plans (compute/EC2), Spot Instances, Instance Scheduler, Trusted Advisor, Cost Allocation Tags.',
        level: 'advanced',
        nextSuggested: ['analytics-bigdata'],
        keywords: 'reserved instances savings plans, spot instances aws, trusted advisor, cost allocation tags',
        prerequisites: ['ec2-autoscaling-elb'],
      },
      {
        slug: 'analytics-bigdata',
        title: 'Analytics: Athena, EMR, Kinesis e Glue',
        icon: '📈',
        xp: 60,
        readTime: 12,
        desc: 'Athena (serverless SQL on S3), EMR (Hadoop/Spark), Kinesis Data Streams vs Firehose, Glue ETL, Redshift Spectrum, QuickSight.',
        level: 'advanced',
        nextSuggested: ['migracao-transferencia-saa'],
        keywords: 'aws athena emr, kinesis streams firehose, aws glue etl, redshift spectrum quicksight',
        prerequisites: ['s3-avancado'],
      },
      {
        slug: 'migracao-transferencia-saa',
        title: 'Migração para o Arquiteto: DMS, SCT, MGN e DRS',
        icon: '🚚',
        xp: 65,
        readTime: 12,
        desc: 'DMS + SCT para migração de bancos heterogêneos, MGN para lift-and-shift, DRS para DR, DataSync, Transfer Family e Snow Family em cenários arquiteturais.',
        level: 'advanced',
        nextSuggested: ['rede-hibrida-saa'],
        keywords: 'aws dms sct migration, aws mgn lift and shift, aws drs disaster recovery, datasync transfer family, snow family',
        prerequisites: ['rds-aurora-dynamodb'],
      },
      {
        slug: 'rede-hibrida-saa',
        title: 'Rede Híbrida: Direct Connect, VPN, PrivateLink e VPC Endpoints',
        icon: '🌉',
        xp: 70,
        readTime: 13,
        desc: 'Direct Connect + VIFs, Site-to-Site VPN, Client VPN, PrivateLink, Gateway vs Interface Endpoints, Route 53 Resolver híbrido e Transit Gateway inter-region.',
        level: 'advanced',
        nextSuggested: ['ml-ia-arquiteto-saa'],
        keywords: 'aws direct connect dx, site to site vpn, client vpn aws, privatelink vpc endpoint, route 53 resolver hibrido',
        prerequisites: ['vpc-avancado'],
      },
      {
        slug: 'ml-ia-arquiteto-saa',
        title: 'ML/IA para Arquiteto: SageMaker, Bedrock e Pipelines',
        icon: '🧬',
        xp: 60,
        readTime: 12,
        desc: 'Arquiteturas de inferência (real-time endpoint, serverless, async, batch), SageMaker + MLOps, integração com Bedrock e data lake alimentando pipelines de ML.',
        level: 'advanced',
        nextSuggested: ['simulado-saa-c03'],
        keywords: 'sagemaker endpoints arquitetura, bedrock integracao, mlops pipeline aws, data lake ml, inferencia real time serverless async',
        prerequisites: ['saa-c03-intro'],
      },
      {
        slug: 'simulado-saa-c03',
        title: 'Simulado SAA-C03 Comentado',
        icon: '🏆',
        xp: 100,
        readTime: 25,
        desc: '25 questões no estilo oficial SAA-C03 com explicações detalhadas. Arquitetura, decisões de design, trade-offs de custo e resiliência.',
        level: 'advanced',
        nextSuggested: ['dva-c02-intro'],
        keywords: 'simulado saa-c03, solutions architect associate questoes, prova aws saa, preparacao exame saa',
        prerequisites: ['seguranca-avancada', 'disaster-recovery', 'cost-optimization-saa'],
      },
    ],
  };
