import type { Level, Trail } from '../types';

/** Local LLMs & Edge AI */
export const trilha_trail_local_llms_edge: Trail = {
    id: 'trail-local-llms-edge',
    name: 'Local LLMs & Edge AI',
    color: '#14b8a6',
    icon: '💻',
    desc: 'LLMs rodando localmente em 2026: quantização (GGUF/AWQ/GPTQ), llama.cpp, ollama, vLLM, MLX (Apple Silicon), speculative decoding, on-device inference, RAG privado',
    level: 'advanced' as Level,
    href: '/local-llms-edge',
    modules: [
      { slug: 'quantizacao-gguf-awq-gptq', title: 'Quantização: GGUF, AWQ, GPTQ, INT8/INT4 explicados', icon: '📐', xp: 70, readTime: 14, desc: 'Como rodar Llama 70B num MacBook. GGUF (llama.cpp), AWQ (Activation-aware Weight Quantization, MIT 2023), GPTQ (Frantar et al), bitsandbytes NF4. Trade-offs perplexity vs VRAM, K-quants, importance matrix.',
        objetivo: 'Você escolhe entre GGUF, AWQ e GPTQ pelo trade-off real de perplexidade contra VRAM, não pelo nome mais familiar.', keywords: 'quantização llm, gguf llama.cpp, awq gptq, int4 quantization', level: 'advanced' as Level, nextSuggested: ['llama-cpp-internals'] },
      { slug: 'llama-cpp-internals', title: 'llama.cpp internals: ggml, KV cache, FlashAttention', icon: '⚙️', xp: 75, readTime: 15, desc: 'O motor C++ que destravou local LLM. ggml tensor library, KV cache management, FlashAttention-2 implementation, batch decoding, prompt processing vs generation. Como contribuir para o repo (Georgi Gerganov).', keywords: 'llama.cpp internals, ggml georgi gerganov, kv cache, flashattention', level: 'advanced' as Level, prerequisites: ['quantizacao-gguf-awq-gptq'], nextSuggested: ['ollama-production-deploy'] },
      { slug: 'ollama-production-deploy', title: 'Ollama em produção: model management, Docker, monitoring', icon: '🚢', xp: 60, readTime: 12, desc: 'Ollama como sucessor de llama.cpp para devs. Model registry, Modelfile (Dockerfile-like), Ollama API REST, multi-model loading, structured output (JSON mode), function calling. Deploy Docker + GPU passthrough.', keywords: 'ollama production, modelfile, ollama api, ollama docker gpu', level: 'intermediate' as Level, prerequisites: ['llama-cpp-internals'], nextSuggested: ['vllm-paged-attention'] },
      { slug: 'vllm-paged-attention', title: 'vLLM e PagedAttention: serving high-throughput', icon: '🚄', xp: 75, readTime: 15, desc: 'PagedAttention (Kwon et al, SOSP 2023): KV cache como virtual memory paginada. vLLM continuous batching, OpenAI-compatible API, tensor parallelism, prefix caching. Throughput 10-24x sobre HuggingFace.', keywords: 'vllm pagedattention, kv cache paging, continuous batching, vllm tensor parallel', level: 'advanced' as Level, prerequisites: ['ollama-production-deploy'], nextSuggested: ['speculative-decoding'] },
      { slug: 'speculative-decoding', title: 'Speculative decoding: 2-3x speedup grátis', icon: '🎯', xp: 70, readTime: 14, desc: 'Speculative decoding (Leviathan et al, ICML 2023): draft model rápido propõe N tokens, target model verifica em paralelo. EAGLE-2, Medusa, lookahead decoding. Como ativar em vLLM, llama.cpp, MLX.', keywords: 'speculative decoding, eagle-2, medusa decoding, lookahead vllm', level: 'advanced' as Level, prerequisites: ['vllm-paged-attention'], nextSuggested: ['mlx-apple-silicon'] },
      { slug: 'mlx-apple-silicon', title: 'MLX: rodar LLM nativo em M3/M4 Apple Silicon', icon: '🍎', xp: 65, readTime: 13, desc: 'MLX da Apple ML Research (2023): array framework lazy, unified memory, treina e infere em Mac. mlx-lm para LLMs, mlx-vlm para VLMs, fine-tune LoRA local. M3 Ultra 192GB roda Llama 3.3 70B. Comparação com llama.cpp Metal backend.', keywords: 'mlx apple silicon, mlx-lm, m3 ultra llama, lora local apple', level: 'advanced' as Level, prerequisites: ['speculative-decoding'], nextSuggested: ['on-device-inference-mobile'] },
      { slug: 'on-device-inference-mobile', title: 'On-device inference mobile: ExecuTorch, MediaPipe, Core ML', icon: '📱', xp: 65, readTime: 13, desc: 'LLMs rodando no celular em 2026. Apple Foundation Models (iOS 26+), Google AI Edge / MediaPipe LLM, ExecuTorch (PyTorch mobile), Phi-3 / Gemma 2B / Qwen 2.5 3B no device. Trade-offs battery vs quality.', keywords: 'on-device llm mobile, executorch, mediapipe llm, apple foundation models', level: 'advanced' as Level, prerequisites: ['mlx-apple-silicon'], nextSuggested: ['rag-local-private'] },
      { slug: 'rag-local-private', title: 'RAG 100% local e privado: LanceDB, Ollama, Qdrant local', icon: '🔒', xp: 70, readTime: 14, desc: 'RAG sem mandar nada pro cloud. Pipeline: docling para parsing, embeddings local (BGE-M3 com sentence-transformers), LanceDB ou Qdrant em Docker, Ollama para gen. Hybrid search local. Privacidade real para dados sensíveis.', keywords: 'rag local, lancedb, qdrant docker, bge-m3 local, rag privado', level: 'advanced' as Level, prerequisites: ['on-device-inference-mobile'], nextSuggested: ['eval-offline-local'] },
      { slug: 'eval-offline-local', title: 'Avaliação offline: lm-eval-harness, deepeval local', icon: '🧪', xp: 60, readTime: 12, desc: 'EleutherAI lm-evaluation-harness, deepeval, promptfoo. Benchmarks: MMLU, GSM8K, HumanEval, IFEval, GPQA. Como rodar suite completa em uma noite no seu modelo quantizado, comparar antes/depois de fine-tune.', keywords: 'lm-eval-harness, deepeval, mmlu local, promptfoo eval', level: 'advanced' as Level, prerequisites: ['rag-local-private'], nextSuggested: ['hardware-llm-comparativo'] },
      { slug: 'hardware-llm-comparativo', title: 'Hardware LLM 2026: Mac M3 Ultra vs RTX 5090 vs DGX', icon: '🔌', xp: 55, readTime: 11, desc: 'Comparativo de custo/throughput em maio/2026: Mac M3 Ultra 192GB (~US$7k), RTX 5090 32GB (~US$2k + PC), Mac Studio 4xM3 Ultra cluster, NVIDIA DGX Spark, AMD Ryzen AI Max+ 128GB. Tokens/sec por modelo, R$/1M tokens.', nextSuggested: ['bedrock-o-que-e-e-por-que'], keywords: 'hardware llm 2026, mac m3 ultra, rtx 5090 llm, dgx spark, ryzen ai max', level: 'intermediate' as Level, prerequisites: ['eval-offline-local'] },
    ],
  };
