import type { Trail } from '../types';

/** AWS Bedrock — GenAI em Produção */
export const trilha_trail_bedrock: Trail = {
    id: 'trail-bedrock',
    name: 'AWS Bedrock — GenAI em Produção',
    color: '#ff9900',
    icon: '🪨',
    desc: 'A trilha completa de engenharia de soluções de IA sobre a AWS: do primeiro hello world na Converse API até o ecossistema inteiro de serviços que orbitam o Bedrock, RAG de produção, tool use profissional, padrões agênticos, evals, o playbook de 14 alavancas de redução de custo, a arquitetura de referência corporativa e cases reais por setor. 36 módulos, do conceito ao sistema em produção. Atualizado para meados de 2026.',
    level: 'intermediate',
    href: '/aws-bedrock',
    modules: [
      {
        slug: 'bedrock-o-que-e-e-por-que',
        title: 'O que é o Amazon Bedrock (e por que ele existe)',
        icon: '🪨',
        xp: 35,
        readTime: 9,
        desc: 'A porta única e serverless para foundation models de vários provedores. O problema que resolve, o que é (e o que não é), o Model Deployment Account que isola seus dados, e por que virou o padrão de inferência gerenciada na AWS.',
        objetivo: 'Você explica o que o Bedrock resolve e o que ele não é, sem confundir com a API direta da Anthropic.',
        keywords: 'o que é amazon bedrock, aws bedrock para iniciantes, foundation models aws, bedrock serverless genai',
        nextSuggested: ['bedrock-vs-api-direta-quando-usar'],
        level: 'beginner',
      },
      {
        slug: 'bedrock-vs-api-direta-quando-usar',
        title: 'Bedrock vs API direta: quando usar cada um',
        icon: '⚖️',
        xp: 45,
        readTime: 11,
        desc: 'Por que escolher Bedrock e não a API direta da Anthropic/OpenAI? IAM, VPC/PrivateLink, dados que não treinam o modelo, multi-vendor com uma API, billing unificado — versus a defasagem de features. E o meio-termo: Claude Platform on AWS.',
        keywords: 'bedrock vs api direta, bedrock vs anthropic api, por que usar bedrock, claude platform on aws, governança iam bedrock',
        prerequisites: ['bedrock-o-que-e-e-por-que'],
        nextSuggested: ['bedrock-primeira-chamada-converse'],
        level: 'beginner',
      },
      {
        slug: 'bedrock-primeira-chamada-converse',
        title: 'Sua primeira chamada: a Converse API na prática',
        icon: '👋',
        xp: 50,
        readTime: 12,
        desc: 'Do zero à primeira resposta: Converse API vs InvokeModel, hello world em boto3 (Python) e AWS SDK (TS), campos modelId/messages/system/inferenceConfig, a IAM policy mínima, model access e inference profiles. Streaming com ConverseStream.',
        keywords: 'converse api bedrock, bedrock boto3 exemplo, invokemodel bedrock, bedrock aws sdk javascript, iam bedrock invokemodel',
        prerequisites: ['bedrock-vs-api-direta-quando-usar'],
        nextSuggested: ['bedrock-modalidades-texto-imagem-doc-video'],
        level: 'beginner',
      },
      {
        slug: 'bedrock-modalidades-texto-imagem-doc-video',
        title: 'Além do texto: imagem, documento, vídeo e áudio',
        icon: '🖼️',
        xp: 55,
        readTime: 13,
        desc: 'Bedrock não é só texto. Como enviar imagem (vision), PDF/DOCX (document blocks), vídeo e áudio pela Converse API — com limites reais (tamanho, quantidade), envio por bytes vs S3, reasoning/thinking e o gotcha de prompt injection no nome do documento.',
        keywords: 'bedrock multimodal, bedrock enviar imagem pdf, converse api document block, bedrock vision video, bedrock reasoning content',
        prerequisites: ['bedrock-primeira-chamada-converse'],
        nextSuggested: ['bedrock-catalogo-modelos-qual-escolher'],
        level: 'intermediate',
      },
      {
        slug: 'bedrock-catalogo-modelos-qual-escolher',
        title: 'O catálogo de modelos: qual escolher para cada caso',
        icon: '🗂️',
        xp: 55,
        readTime: 13,
        desc: 'O zoológico de modelos de 2026: Claude, Amazon Nova, Llama, Mistral, Cohere, DeepSeek e os open-weights. Qual família serve para cada cenário (chat, agentic, barato-em-escala, vision, código), embeddings e geração de imagem, e como trocar de modelo sem reescrever.',
        keywords: 'modelos amazon bedrock, qual modelo bedrock escolher, amazon nova vs claude, bedrock embeddings imagem, catálogo modelos bedrock 2026',
        prerequisites: ['bedrock-primeira-chamada-converse'],
        nextSuggested: ['bedrock-tool-use-function-calling'],
        level: 'intermediate',
      },
      {
        slug: 'bedrock-prompt-engineering',
        title: 'Engenharia de prompt no Bedrock: o que muda entre Nova, Claude e Llama',
        icon: '✍️',
        xp: 55,
        readTime: 11,
        desc: 'Escrever prompt quando o modelo é variável de configuração: o que a Converse padroniza, as quatro alavancas que migram entre famílias, as convenções de Nova, Claude, Llama e Mistral, e por que prompt caching dita a ORDEM das partes do prompt.',
        level: 'intermediate',
        keywords: 'engenharia de prompt bedrock, prompt engineering aws, prompt caching bedrock, cachepoint converse, nova claude llama prompt, additionalmodelrequestfields',
        prerequisites: ['bedrock-catalogo-modelos-qual-escolher'],
        nextSuggested: ['bedrock-reasoning-converse'],
      },
      {
        slug: 'bedrock-reasoning-converse',
        title: 'Reasoning na Converse: quando pensar mais vale o token',
        icon: '🤔',
        xp: 60,
        readTime: 8,
        desc: 'O modo de raciocínio como troca mensurável entre custo, latência e acerto: como ligar por additionalModelRequestFields, por que o orçamento sai do maxTokens, as seis tarefas em que paga e as em que é desperdício, e o roteador que evita pagar pelo caso fácil.',
        level: 'intermediate',
        keywords: 'reasoning bedrock, extended thinking converse, reasoning_config budget_tokens, raciocinio modelo bedrock, quando usar reasoning, custo reasoning aws',
        prerequisites: ['bedrock-prompt-engineering'],
        nextSuggested: ['bedrock-tool-use-function-calling'],
      },
      {
        slug: 'bedrock-tool-use-function-calling',
        title: 'Tool use: dando ferramentas ao modelo (function calling)',
        icon: '🔧',
        xp: 60,
        readTime: 14,
        desc: 'Como o modelo chama suas funções: toolConfig com JSON Schema, o ciclo toolUse → você executa → toolResult, tool_choice (auto/any/tool), structured outputs, e os três modos (client-side, server-side, Anthropic tool use). O tijolo que vira agent.',
        keywords: 'tool use bedrock, function calling bedrock, converse toolconfig, bedrock tooluse toolresult, structured output bedrock',
        prerequisites: ['bedrock-primeira-chamada-converse'],
        nextSuggested: ['bedrock-knowledge-bases-rag'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-knowledge-bases-rag',
        title: 'Knowledge Bases: RAG gerenciado de ponta a ponta',
        icon: '📚',
        xp: 65,
        readTime: 15,
        desc: 'RAG sem operar pipeline: conectores (S3, SharePoint, Confluence, web), estratégias de chunking (fixed, hierarchical, semantic), vector stores (OpenSearch, Aurora pgvector, S3 Vectors), Retrieve e RetrieveAndGenerate com citações, reranking e GraphRAG. E o custo escondido do vector store.',
        keywords: 'bedrock knowledge bases, rag gerenciado aws, bedrock retrieveandgenerate, vector store bedrock, graphrag neptune bedrock',
        prerequisites: ['bedrock-modalidades-texto-imagem-doc-video'],
        nextSuggested: ['bedrock-agents-agentcore'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-agents-agentcore',
        title: 'Agents e AgentCore: agents de IA em produção',
        icon: '🤖',
        xp: 70,
        readTime: 16,
        desc: 'A virada de 2026: Bedrock Agents virou Classic (maintenance mode) e o caminho novo é o AgentCore — Runtime, Gateway, Memory, Identity, Observability, Code Interpreter e Browser. Como rodar Strands, LangGraph ou CrewAI serverless, com MCP e A2A.',
        keywords: 'amazon bedrock agentcore, bedrock agents classic maintenance, strands agents, langgraph agentcore, agents ia produção aws',
        prerequisites: ['bedrock-tool-use-function-calling', 'bedrock-knowledge-bases-rag'],
        nextSuggested: ['bedrock-guardrails-seguranca-ia'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-mcp-fundamentos',
        title: 'MCP: o protocolo que o AgentCore Gateway fala',
        icon: '🔌',
        xp: 65,
        readTime: 8,
        desc: 'Model Context Protocol do ponto de vista de quem constrói na AWS: por que M × N vira M + N, a diferença entre tool, resource e prompt (e por que ela governa a segurança), os dois transportes, e onde o AgentCore Gateway entra.',
        level: 'intermediate',
        keywords: 'mcp aws, model context protocol, agentcore gateway mcp, servidor mcp bedrock, tool resource prompt mcp, streamable http stdio',
        prerequisites: ['bedrock-agents-agentcore'],
        nextSuggested: ['bedrock-agentcore-gateway-producao'],
      },
      {
        slug: 'bedrock-agentcore-gateway-producao',
        title: 'AgentCore Gateway em produção: identidade, rastro, escala e custo',
        icon: '🛡️',
        xp: 75,
        readTime: 9,
        desc: 'O Gateway como ponto de controle da arquitetura agêntica: as duas identidades que não podem ser a mesma, os cinco sinais que respondem "por que ele fez isso?", o gargalo que não é o modelo, e por que revisão humana domina a conta.',
        keywords: 'agentcore gateway producao, seguranca agente ia aws, identidade agente usuario, observabilidade agente bedrock, cota bedrock escala, custo agente aws',
        prerequisites: ['bedrock-mcp-fundamentos'],
        nextSuggested: ['bedrock-guardrails-seguranca-ia'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-guardrails-seguranca-ia',
        title: 'Guardrails: segurança e responsible AI',
        icon: '🛡️',
        xp: 55,
        readTime: 13,
        desc: 'A camada de segurança independente do modelo: content filters, denied topics, redação de PII, contextual grounding (anti-alucinação probabilístico) e automated reasoning checks (verificação formal). A ApplyGuardrail API que protege até modelos fora do Bedrock.',
        keywords: 'bedrock guardrails, guardrails pii bedrock, contextual grounding anti alucinação, automated reasoning checks, applyguardrail api',
        prerequisites: ['bedrock-primeira-chamada-converse'],
        nextSuggested: ['bedrock-flows-prompt-management-routing'],
        level: 'intermediate',
      },
      {
        slug: 'bedrock-flows-prompt-management-routing',
        title: 'Flows, Prompt Management e Intelligent Routing',
        icon: '🔀',
        xp: 55,
        readTime: 13,
        desc: 'Orquestração e governança de prompts: Bedrock Flows (workflow visual de GenAI), Prompt Management (versionar prompts como artefatos) e Intelligent Prompt Routing (mandar o fácil pro modelo barato). Quando usar Flows vs Agents vs Step Functions.',
        keywords: 'bedrock flows, prompt management bedrock, intelligent prompt routing, flows vs step functions, orquestração genai aws',
        prerequisites: ['bedrock-tool-use-function-calling'],
        nextSuggested: ['bedrock-data-automation-e-customizacao'],
        level: 'intermediate',
      },
      {
        slug: 'bedrock-data-automation-e-customizacao',
        title: 'Data Automation e customização de modelos',
        icon: '🏭',
        xp: 60,
        readTime: 14,
        desc: 'Extrair dados de documentos, imagens, vídeo e áudio com Bedrock Data Automation (IDP moderno). E quando o modelo pronto não basta: fine-tuning, Model Distillation (aluno 75% mais barato), Custom Model Import (traga seus pesos), Marketplace e avaliação.',
        keywords: 'bedrock data automation, idp aws bedrock, model distillation bedrock, custom model import, fine-tuning bedrock',
        prerequisites: ['bedrock-catalogo-modelos-qual-escolher'],
        nextSuggested: ['bedrock-precos-e-cobranca'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-precos-e-cobranca',
        title: 'Preços e cobrança: como o Bedrock cobra de você',
        icon: '💰',
        xp: 50,
        readTime: 12,
        desc: 'O modelo de cobrança sem enrolação: on-demand por token (input vs output), Batch (-50%), Provisioned Throughput (model units) e cross-region. Tabela de preços dos principais modelos em 2026 e prompt caching — a alavanca #1 que corta ~90% do custo de contexto repetido.',
        keywords: 'preço amazon bedrock, bedrock pricing 2026, bedrock caro ou barato, prompt caching bedrock, provisioned throughput bedrock',
        prerequisites: ['bedrock-o-que-e-e-por-que'],
        nextSuggested: ['bedrock-finops-roi-controle-de-custo'],
        level: 'intermediate',
      },
      {
        slug: 'bedrock-finops-roi-controle-de-custo',
        title: 'FinOps e ROI: controlar custo e provar retorno',
        icon: '📊',
        xp: 60,
        readTime: 14,
        desc: 'Como medir custo por request (fórmula), atribuir custo por app com application inference profiles + tags, monitorar com Cost Explorer/CloudWatch/Budgets, e comparar Bedrock vs API vs self-hosted. Os 8 erros que explodem a conta — começando pelo OpenSearch idle de US$350/mês.',
        keywords: 'bedrock finops, custo bedrock por request, application inference profile custo, roi bedrock, opensearch serverless custo escondido',
        prerequisites: ['bedrock-precos-e-cobranca'],
        nextSuggested: ['bedrock-arquiteturas-e-cases-reais'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-arquiteturas-e-cases-reais',
        title: 'Arquiteturas de referência e cases reais',
        icon: '🏗️',
        xp: 70,
        readTime: 16,
        desc: 'Fechando a trilha: os 5 padrões de integração (RAG serverless, IDP event-driven, agent com tools, batch com Step Functions, streaming pro frontend) e os serviços AWS que orbitam o Bedrock. Cases reais — DoorDash, Pfizer, iFood, C6 Bank, Mercado Livre, BDM/LOUIS — e os anti-padrões que derrubam projetos.',
        keywords: 'arquitetura bedrock serverless, cases amazon bedrock, bedrock rag lambda opensearch, bedrock cases brasil, padrões integração bedrock',
        prerequisites: ['bedrock-knowledge-bases-rag', 'bedrock-agents-agentcore', 'bedrock-finops-roi-controle-de-custo'],
        nextSuggested: ['bedrock-arquitetura-referencia-ia-corporativa'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-arquitetura-referencia-ia-corporativa',
        title: 'A arquitetura de referência de IA corporativa sobre Bedrock',
        icon: '🏛️',
        xp: 80,
        readTime: 20,
        desc: 'O blueprint de 7 camadas que uma empresa monta em volta do Bedrock: canais, AI gateway (quotas + chargeback + allowlist de modelos), orquestração, inferência, conhecimento, confiança e operação. Com política de modelos, código do gateway e o plano de implantação em 3 ondas.',
        keywords: 'arquitetura de ia corporativa aws, ai gateway bedrock, plataforma interna de ia, política de modelos bedrock, chargeback bedrock squad',
        prerequisites: ['bedrock-arquiteturas-e-cases-reais'],
        nextSuggested: ['bedrock-claude-na-aws-ecossistema'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-claude-na-aws-ecossistema',
        title: 'Claude na AWS: os quatro caminhos e onde cada um encaixa',
        icon: '⊕',
        xp: 65,
        readTime: 15,
        desc: 'Claude não é só um modelId no Bedrock. Os quatro caminhos — Converse API, cliente Mantle (Messages API nativa), Claude Platform on AWS e Claude Code/Agent SDK apontando pro Bedrock — o que cada um habilita, o que o Bedrock NÃO tem, e como escolher sem se arrepender.',
        keywords: 'claude na aws, anthropic claude bedrock model id, claude platform on aws, claude code bedrock empresa, mantle messages api bedrock',
        prerequisites: ['bedrock-arquitetura-referencia-ia-corporativa'],
        nextSuggested: ['bedrock-servicos-ia-especializada'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-servicos-ia-especializada',
        title: 'Serviços que somam ao Bedrock I: IA especializada e ML clássico',
        icon: '🎯',
        xp: 80,
        readTime: 20,
        desc: 'A família que faz uma coisa só, muito bem e muito barato: Textract, Comprehend, Transcribe, Polly, Translate, Rekognition, Personalize, Fraud Detector e Amazon Q — mais as peças do SageMaker que todo projeto de Bedrock deveria usar sem treinar nada. Metade do que se manda ao LLM é resolvido melhor aqui.',
        keywords: 'textract comprehend transcribe bedrock, quando não usar llm, ia especializada aws, sagemaker ground truth golden set, augmented ai revisão humana',
        prerequisites: ['bedrock-claude-na-aws-ecossistema'],
        nextSuggested: ['bedrock-servicos-seguranca-conformidade'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-servicos-seguranca-conformidade',
        title: 'Serviços que somam ao Bedrock II: segurança, identidade e conformidade',
        icon: '🛡️',
        xp: 80,
        readTime: 21,
        desc: 'A camada que não aparece no diagrama e decide se o projeto é aprovado: IAM com negação condicional, Identity Center, Cognito, KMS, Secrets Manager, Parameter Store, PrivateLink, WAF, Shield, Macie, GuardDuty, Config, Organizations, Control Tower, Audit Manager e Security Hub.',
        keywords: 'segurança bedrock iam kms privatelink, macie antes de indexar rag, waf endpoint ia custo, organizations scp modelo homologado, conformidade ia aws',
        prerequisites: ['bedrock-servicos-ia-especializada'],
        nextSuggested: ['bedrock-servicos-observabilidade-finops'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-servicos-observabilidade-finops',
        title: 'Serviços que somam ao Bedrock III: observabilidade, FinOps e entrega',
        icon: '📈',
        xp: 80,
        readTime: 21,
        desc: 'O que você mede e como isso sobe: CloudWatch, Logs Insights, Synthetics, X-Ray, OpenTelemetry, AgentCore Observability, CloudTrail e model invocation logging, Cost Explorer, Budgets, Cost Anomaly Detection, CUR, Compute Optimizer, IaC, CodePipeline e ECR. Os três registros que a auditoria pede.',
        keywords: 'observabilidade llm aws, model invocation logging bedrock, x-ray rastreamento ia, cost anomaly detection ia, budgets bedrock, custo por resultado de negócio',
        prerequisites: ['bedrock-servicos-seguranca-conformidade'],
        nextSuggested: ['bedrock-servicos-canais-borda'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-servicos-canais-borda',
        title: 'Serviços que somam ao Bedrock IV: canais e borda',
        icon: '🔌',
        xp: 80,
        readTime: 20,
        desc: 'Onde o humano encosta e por onde o pedido entra: Amazon Connect, Lex, Chime SDK, SES, End User Messaging, Amplify, as três variantes do API Gateway, AppSync, Function URL com streaming, ALB, CloudFront e Route 53. O timeout de borda e o orçamento de latência em voz.',
        keywords: 'api gateway websocket streaming llm, amazon connect lex bedrock, timeout borda resposta llm, appsync subscription ia, function url response streaming',
        prerequisites: ['bedrock-servicos-observabilidade-finops'],
        nextSuggested: ['bedrock-servicos-compute-orquestracao'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-servicos-compute-orquestracao',
        title: 'Serviços que somam ao Bedrock V: compute, orquestração e estado',
        icon: '⚙️',
        xp: 80,
        readTime: 22,
        desc: 'Onde o código roda e quem coordena os passos: Lambda, ECS/Fargate, EKS, EC2, Batch, AgentCore Runtime, Step Functions nos dois modos, EventBridge com Pipes e Scheduler, SQS, SNS — e onde mora o estado (DynamoDB, ElastiCache, Aurora, AgentCore Memory). O teto de 15 minutos e a entrega ao-menos-uma-vez.',
        keywords: 'lambda teto 15 minutos agent, step functions bedrock pipeline, eventbridge sqs idempotência ia, dynamodb estado conversa ttl, agentcore runtime sessão longa',
        prerequisites: ['bedrock-servicos-canais-borda'],
        nextSuggested: ['bedrock-servicos-dados-retrieval'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-servicos-dados-retrieval',
        title: 'Serviços que somam ao Bedrock VI: dados, retrieval e conhecimento',
        icon: '🗄️',
        xp: 80,
        readTime: 20,
        desc: 'A camada que alimenta o modelo: S3 e suas classes, S3 Vectors, OpenSearch Serverless, Aurora pgvector, Neptune Analytics, Kendra, Athena, Glue, Redshift, Lake Formation, DataZone e Kinesis. Os vector stores comparados pelo critério que decide de verdade — quanto custam parados.',
        keywords: 'vector store aws comparação custo, opensearch serverless s3 vectors pgvector, kendra retriever bedrock, athena agregação rag, lake formation permissão rag',
        prerequisites: ['bedrock-servicos-compute-orquestracao'],
        nextSuggested: ['bedrock-rag-producao-padroes'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-rag-producao-padroes',
        title: 'RAG de produção: os padrões que separam demo de sistema',
        icon: '🔎',
        xp: 80,
        readTime: 20,
        desc: 'O que ninguém conta no tutorial de RAG: por que busca puramente vetorial falha, chunking com trade-off real, busca híbrida, contextual retrieval, query rewriting, reranking, filtro de metadados e GraphRAG. Com as métricas de retrieval (recall@k, MRR, nDCG) e o custo de cada peça.',
        keywords: 'rag produção bedrock, busca híbrida bm25 vetorial, contextual retrieval anthropic, reranking rag, recall@k mrr ndcg, chunking hierárquico semântico',
        prerequisites: ['bedrock-servicos-dados-retrieval'],
        nextSuggested: ['bedrock-tool-use-producao'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-tool-use-producao',
        title: 'Tool use profissional: desenhar o contrato entre modelo e sistema',
        icon: '🛠️',
        xp: 75,
        readTime: 18,
        desc: 'Tool use além do hello world: granularidade e descrição como gatilho, schema estrito, chamadas paralelas, erros que ensinam o modelo, idempotência, gate de aprovação humana, injeção de prompt via tool result, MCP e tool search — e por que o conjunto de tools é a sua âncora de cache.',
        keywords: 'tool use profissional bedrock, design de ferramentas llm, prompt injection tool result, idempotência agent, mcp agentcore gateway, tool search defer loading',
        prerequisites: ['bedrock-rag-producao-padroes'],
        nextSuggested: ['bedrock-padroes-agenticos'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-padroes-agenticos',
        title: 'Padrões agênticos e context engineering',
        icon: '♟️',
        xp: 80,
        readTime: 19,
        desc: 'A taxonomia profissional: workflow vs agent, prompt chaining, roteamento, paralelização, orquestrador-trabalhadores e avaliador-otimizador. Quando NÃO construir um agent, como o contexto degrada ao longo do laço, e o custo relativo de cada padrão para a mesma tarefa.',
        keywords: 'padrões agênticos, workflow vs agent, orchestrator workers, evaluator optimizer, context engineering, compaction context editing, quando não usar agent',
        prerequisites: ['bedrock-tool-use-producao'],
        nextSuggested: ['bedrock-evals-qualidade-producao'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-evals-qualidade-producao',
        title: 'Evals: como saber se está bom (e como trocar de modelo sem medo)',
        icon: '🧪',
        xp: 75,
        readTime: 18,
        desc: 'A capacidade que destrava todas as outras: golden set, rubrica, LLM-as-judge com seus vieses, métricas de retrieval separadas das de geração, gate de regressão no CI e canário de modelo. Sem eval você não consegue descer de tier — e é aí que mora a maior economia.',
        keywords: 'llm evals produção, llm as judge viés, golden set eval, regressão prompt ci, canário de modelo, faithfulness groundedness',
        prerequisites: ['bedrock-padroes-agenticos'],
        nextSuggested: ['bedrock-playbook-reducao-custo'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-playbook-reducao-custo',
        title: 'Playbook de redução de custo: 14 alavancas em ordem de aplicação',
        icon: '✂️',
        xp: 85,
        readTime: 21,
        desc: 'O manual operacional de FinOps de IA: 14 alavancas com economia típica, esforço, risco e a ordem certa de aplicar. Cache, cascata de modelos, disciplina de saída, batch, cache semântico, distillation, right-sizing de RAG e a alavanca mais barata de todas — não usar LLM. Com fórmulas e código.',
        keywords: 'reduzir custo bedrock, cascata de modelos llm, cache semântico llm, distillation economia, otimizar tokens llm, finops ia playbook',
        prerequisites: ['bedrock-evals-qualidade-producao'],
        nextSuggested: ['bedrock-catalogo-cases-setor'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-catalogo-cases-setor',
        title: 'Catálogo de cases por setor: quem faz o quê, com qual padrão',
        icon: '🗺️',
        xp: 70,
        readTime: 17,
        desc: 'O mapa completo: cases públicos organizados por setor (banco, seguro, varejo, saúde, logística, mídia, indústria) cruzados com o padrão arquitetural que cada um usa. Os três casos de uso que sempre aparecem em cada setor, e como ler número de case sem se enganar.',
        keywords: 'cases amazon bedrock por setor, ia em bancos brasil, ia varejo ecommerce case, ia saúde farma case, casos de uso ia por indústria',
        prerequisites: ['bedrock-playbook-reducao-custo'],
        nextSuggested: ['bedrock-case-atendimento-inteligente'],
        level: 'intermediate',
      },
      {
        slug: 'bedrock-case-atendimento-inteligente',
        title: 'Case visual: atendimento inteligente ponta a ponta',
        icon: '🎧',
        xp: 70,
        readTime: 16,
        desc: 'O arquétipo front-office desenhado camada a camada: RAG sobre a base de conhecimento, human-in-the-loop no atendente, deflexão medida de verdade. Baseline, arquitetura, as 3 decisões que definiram o projeto, o que deu errado e o checklist para replicar.',
        keywords: 'case bedrock atendimento, chatbot rag contact center aws, deflexão atendimento ia, human in the loop atendimento bedrock, amazon connect claude',
        prerequisites: ['bedrock-catalogo-cases-setor'],
        nextSuggested: ['bedrock-case-documentos-setor-regulado'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-case-documentos-setor-regulado',
        title: 'Case visual: documentos em setor regulado (IDP)',
        icon: '📄',
        xp: 70,
        readTime: 16,
        desc: 'O arquétipo back-office: extrair dado estruturado de documento em banco, seguradora e farma — onde o erro custa caro e a auditoria pergunta. Pipeline event-driven, confidence routing, trilha de evidência, e a matemática do custo por documento.',
        keywords: 'idp bedrock setor regulado, extração documentos ia banco, bedrock data automation case, confidence routing idp, custo por documento ia',
        prerequisites: ['bedrock-case-atendimento-inteligente'],
        nextSuggested: ['bedrock-case-copiloto-interno-engenharia'],
        level: 'advanced',
      },
      {
        slug: 'bedrock-case-copiloto-interno-engenharia',
        title: 'Case visual: copiloto interno e agents de engenharia',
        icon: '🧭',
        xp: 70,
        readTime: 16,
        desc: 'O arquétipo que mais gera ROI e menos aparece em slide: IA voltada para dentro. Copiloto de conhecimento corporativo, agents que tocam sistemas legados e produtividade de engenharia — com o modelo de adoção, a métrica que não mente e o custo por funcionário ativo.',
        keywords: 'copiloto interno empresa bedrock, agents engenharia aws, produtividade dev ia corporativa, adoção ia interna, roi copiloto interno',
        prerequisites: ['bedrock-case-documentos-setor-regulado'],
        nextSuggested: ['aws-ia-100-solucoes'],
        level: 'advanced',
      },
      {
        slug: 'aws-ia-100-solucoes',
        title: '100 soluções de IA na AWS: problema, arquitetura e a decisão que ensina',
        icon: '🗂️',
        xp: 90,
        readTime: 24,
        desc: 'Cem problemas reais resolvidos com IA na AWS, organizados em dez famílias e cinco arquétipos de arquitetura. Cada linha traz o problema, a topologia de serviços, a decisão transferível e a ORIGEM da informação: 21 casos públicos com fonte, 32 arquiteturas de referência da AWS e 47 padrões compostos.',
        keywords: 'solucoes ia aws, casos de uso bedrock, arquitetura ia aws exemplos, cases bedrock producao, padroes arquitetura ia generativa aws, catalogo solucoes ia',
        prerequisites: ['bedrock-case-copiloto-interno-engenharia'],
        // O catálogo é o índice; a trilha `trail-arq-ia-aws` desenha as cem.
        nextSuggested: ['arq-ia-aws-atendimento'],
        level: 'advanced',
      },
    ],
  };
