import type { Trail } from '../types';

/** IA Além do LLM */
export const trilha_trail2: Trail = {
    id: 'trail2',
    name: 'IA Além do LLM',
    color: '#d2a8ff',
    icon: '🏗️',
    desc: 'KV Cache, MoE, Tool Calling, avaliação — como modelos funcionam em produção',
    level: 'intermediate',
    href: '/ia-alem-do-llm',
    prerequisites: ['trail1'],
    modules: [
      {
        slug: 'kv-cache',
        title: 'KV Cache: Memória Eficiente',
        icon: '⚡',
        xp: 60,
        readTime: 8,
        desc: 'Por que um modelo de 30GB pode precisar de 60GB de VRAM — e como o KV Cache resolve isso.',
        objetivo: 'Você calcula por que um modelo de 30GB pode exigir 60GB de VRAM e o que o KV cache muda nessa conta.',
        level: 'intermediate',
        keywords: 'kv cache transformers, key value cache LLM, memoria eficiente IA',
        prerequisites: ['transformers'],
        nextSuggested: ['mixture-of-experts'],
      },
      {
        slug: 'mixture-of-experts',
        title: 'Mixture of Experts (MoE)',
        icon: '🧩',
        xp: 70,
        readTime: 10,
        desc: '200B parâmetros que não cabem na GPU — veja como o MoE ativa só o que é necessário.',
        level: 'intermediate',
        keywords: 'mixture of experts MoE, mixtral arquitetura, sparse model IA',
        prerequisites: ['kv-cache'],
        nextSuggested: ['tool-calling'],
      },
      {
        slug: 'tool-calling',
        title: 'Tool Calling e Agentes',
        icon: '🔧',
        xp: 70,
        readTime: 9,
        desc: 'Como a IA aprendeu a usar ferramentas externas — e por que isso transformou LLMs em agentes.',
        level: 'intermediate',
        keywords: 'tool calling IA, function calling LLM, agentes IA ferramentas',
        prerequisites: ['mixture-of-experts'],
        nextSuggested: ['ia-alem-do-llm', 'rag-fundamentos'],
      },
      {
        slug: 'ia-alem-do-llm',
        title: 'Harness: a Infraestrutura do Agente',
        icon: '🏗️',
        xp: 80,
        readTime: 15,
        desc: 'Os 6 componentes que fazem um agente de IA funcionar de verdade.',
        level: 'intermediate',
        keywords: 'harness agente IA, componentes agente programacao, claude code vs cursor',
        prerequisites: ['tool-calling'],
        nextSuggested: ['como-avaliar-modelos', 'coding-agents-panorama'],
      },
      {
        slug: 'como-avaliar-modelos',
        title: 'Como Avaliar Modelos de IA',
        icon: '📊',
        xp: 60,
        readTime: 8,
        desc: 'MMLU, HumanEval, benchmark contamination — como saber se um modelo é realmente melhor.',
        level: 'intermediate',
        keywords: 'avaliar modelos IA, benchmarks LLM, MMLU HumanEval, lm evaluation harness',
        prerequisites: ['ia-alem-do-llm'],
        nextSuggested: ['coding-agents-panorama', 'rag-fundamentos'],
      },
    ],
  };
