import type { Trail } from '../types';

/**
 * 100 Laboratórios de Arquitetura AWS — do básico à solução com IA.
 *
 * O plano dos 100 vive em `docs/aws/CATALOGO_100_LABS_ARQUITETURA_AWS.md`, com
 * numeração `L01`–`L100`, dependência entre laboratórios e entregável de cada um.
 * O padrão de autoria está em `.claude/skills/lab-arquitetura-aws.md`.
 *
 * **Por que esta trilha não nasce com 100 módulos declarados.** Slug declarado sem
 * seed é 404 anunciado no sitemap, e `check-curriculum-seed-drift.mjs --strict`
 * reprova por isso. A trilha cresce um módulo por vez, e a tabela "Estado de
 * execução" do catálogo é o que separa o planejado do construído.
 *
 * **Não confundir com `trail-arq-ia-aws`.** Aquela trilha desenha 100 arquiteturas
 * de IA (`S01`–`S100`), uma por solução, e seus seeds são GERADOS. Esta constrói
 * laboratórios reproduzíveis, IA entra só na banda 9, e cada módulo é escrito.
 */
export const trilha_trail_labs_aws: Trail = {
  id: 'trail-labs-aws',
  name: '100 Laboratórios de Arquitetura AWS',
  color: '#fb923c',
  icon: '🧪',
  desc: 'Cem laboratórios reproduzíveis que constroem competência de arquitetura na AWS na ordem em que ela se usa: começa numa aplicação .NET 8 de três camadas que sobe de verdade — ECS Fargate, RDS em sub-rede privada, front na borda, tudo em Terraform — e avança por serverless, sistemas distribuídos, segurança, operação e dados até arquitetura de solução com IA. Cada laboratório tem entregável verificável, três arquiteturas (mínima, produção e evolução) e uma seção de limpeza, porque laboratório de arquitetura deixa recurso cobrando depois que a aula termina.',
  level: 'beginner',
  href: '/exemplos-arquitetura-aws',
  modules: [
    // A ordem aqui É a progressão da série: L02 descasca a rede da aplicação que
    // o L01 subiu, e o número vive no título, nunca no slug — renumerar a série
    // não pode quebrar URL.

    {
      slug: 'lab-app-web-ecs-fargate-rds',
      title: 'Lab 01 — App .NET 8 no ECS Fargate com RDS e CloudFront',
      icon: '🚀',
      xp: 130,
      readTime: 38,
      desc: 'A primeira aplicação completa: três camadas em duas AZs, banco que a internet não alcança, segredo rotacionado pelo RDS e deploy por digest — com o Terraform e o C# inteiros.',
        objetivo: 'Você sobe, em Terraform, uma aplicação de três camadas com banco isolado e segredo rotacionado — e sabe explicar cada decisão.',
      nextSuggested: ['lab-rede-vpc-subrede-privada-nat'],
      keywords: 'ecs fargate rds terraform exemplo, arquitetura aws tres camadas, dotnet 8 ecs fargate, alb ecs sub-rede privada, vpc endpoint ecr sem nat gateway',
      level: 'beginner',
    },
    {
      slug: 'lab-rede-vpc-subrede-privada-nat',
      title: 'Lab 02 — A rede por baixo: por que o banco não tem rota para a internet',
      icon: '🕸️',
      xp: 120,
      readTime: 32,
      desc: 'A sub-rede é privada por causa da tabela de rotas, não de uma flag. Duas camadas de sub-rede em duas AZs, NAT Gateway do lado certo, plano de endereçamento escrito — e a prova, por medição, de que o banco deixou de ter endereço alcançável.',
      nextSuggested: ['lab-deploy-ecr-rolling-update-drenagem'],
      keywords: 'subrede publica vs privada aws, nat gateway vs internet gateway, tabela de rotas vpc terraform, banco de dados sem ip publico, plano de enderecamento cidr vpc',
      level: 'beginner',
    },
    {
      slug: 'lab-deploy-ecr-rolling-update-drenagem',
      title: 'Lab 03 — Da imagem ao deploy sem indisponibilidade: ECR, rolling update e drenagem',
      icon: '🔁',
      xp: 125,
      readTime: 35,
      desc: 'O 5xx do deploy não vem da versão nova: vem de três relógios que não se conhecem. Tag imutável por SHA, excedente que permite as duas versões conviverem, prazo de drenagem derivado do p99 — e a prova de que a desregistragem acontece antes do SIGTERM, observada nos estados da task.',
      nextSuggested: ['lab-segredo-secrets-manager-rotacao'],
      keywords: 'ecs rolling update sem downtime, deregistration delay target group, ecs sigterm stoptimeout fargate, ecr tag imutavel rollback, health check readiness liveness ecs',
      level: 'beginner',
    },
    {
      slug: 'lab-segredo-secrets-manager-rotacao',
      title: 'Lab 04 — Segredo fora do código, com rotação que não derruba a aplicação',
      icon: '🔐',
      xp: 125,
      readTime: 36,
      desc: 'Segredo não é parâmetro sensível: é parâmetro com relógio. O ECS resolve o valor uma única vez, no arranque da task — então ligar rotação sem ensinar a aplicação a reler troca um vazamento por uma indisponibilidade agendada, que chega horas depois numa conexão nova.',
      nextSuggested: ['lab-dominio-tls-cloudfront-estatico'],
      keywords: 'secrets manager rotacao ecs fargate, segredo vs parameter store, envelope encryption kms decrypt, senha do banco no repositorio, reler credencial rotacionada sem reiniciar',
      level: 'beginner',
    },
    {
      slug: 'lab-dominio-tls-cloudfront-estatico',
      title: 'Lab 05 — Domínio, TLS e o estático na borda',
      icon: '🌐',
      xp: 125,
      readTime: 38,
      desc: 'A borda não é um interruptor: o domínio e o certificado decidem se ela responde, e a chave de cache mais o Cache-Control da origem decidem se ela economiza. Sem os dois lados, o CloudFront é só um salto de rede a mais.',
      nextSuggested: ['lab-escala-automatica-ecs-metrica'],
      keywords: 'cloudfront certificado us-east-1 acm, comportamento de cache por caminho, api e estatico no mesmo dominio, route 53 alias apice do dominio, cache control origem vs ttl minimo',
      level: 'beginner',
    },
    {
      slug: 'lab-escala-automatica-ecs-metrica',
      title: 'Lab 06 — Escalar quando chega gente de verdade',
      icon: '📈',
      xp: 135,
      readTime: 38,
      desc: 'A política não reage ao pico: reage ao retrato do pico, revelado tarde. A decisão nunca é qual número subir — é qual métrica observar, e quanto valem os quatro atrasos entre a chegada da carga e a chegada da capacidade.',
      nextSuggested: ['lab-banco-replica-multiaz-pool'],
      keywords: 'ecs service auto scaling target tracking, albrequestcountpertarget vs cpu, step scaling quando usar, escala programada pico de campanha, max capacity limite de conexoes do banco',
      level: 'intermediate',
    },
    {
      slug: 'lab-banco-replica-multiaz-pool',
      title: 'Lab 07 — O banco sob carga: réplica, Multi-AZ e o pool',
      icon: '🗄️',
      xp: 135,
      readTime: 38,
      desc: 'Multi-AZ compra disponibilidade e a réplica compra leitura — e a latência que você está medindo não é vendida por nenhuma das duas, porque sai de uma consulta sem índice e de uma conta de conexão que é tasks × pool, não pool.',
      nextSuggested: ['lab-observabilidade-trace-correlacao'],
      keywords: 'multi-az nao escala leitura, replica de leitura atraso replicacao, npgsql pool max_connections fargate, explain analyze indice composto rds, failover ensaiado rds tempo medido',
      level: 'intermediate',
    },
    {
      slug: 'lab-observabilidade-trace-correlacao',
      title: 'Lab 08 — Enxergar o que quebrou',
      icon: '🔍',
      xp: 135,
      readTime: 37,
      desc: 'Log não é texto para humano ler: é dado para máquina consultar, e o que transforma um no outro é um identificador que atravessa todas as camadas — e ele já existe antes do seu código, porque o balanceador o injeta.',
      nextSuggested: ['lab-custo-tags-orcamento-rateio'],
      keywords: 'x-amzn-trace-id correlacao alb, log estruturado dotnet 8 escopo, x-ray amostragem producao, embedded metric format vs metrica customizada, trace distribuido opentelemetry ecs',
      level: 'intermediate',
    },
    {
      slug: 'lab-custo-tags-orcamento-rateio',
      title: 'Lab 09 — A conta no fim do mês desta arquitetura',
      icon: '💰',
      xp: 130,
      readTime: 37,
      desc: 'Você não explica uma fatura, você a instrumenta antes de ela crescer — e são dois relógios de retroatividade: a ativação da tag retroage por meses, a presença da tag no recurso não retroage por nenhum mecanismo.',
      nextSuggested: ['lab-restauracao-ensaiada-rto-rpo'],
      keywords: 'tag de alocacao de custo retroativa, cost explorer vs relatorio detalhado cur, aws budgets alerta por previsao, custo oculto nat gateway por gb, rateio por ambiente e centro de custo',
      level: 'intermediate',
    },
    {
      slug: 'lab-restauracao-ensaiada-rto-rpo',
      title: 'Lab 10 — Voltar de um desastre, com ensaio',
      icon: '⏮️',
      xp: 135,
      readTime: 38,
      desc: 'RTO e RPO não são metas que se declaram numa reunião: são números que só existem depois do ensaio. E as duas maiores parcelas do RTO não estão na AWS — estão em detectar e em repontar a aplicação para o endpoint novo que a restauração cria.',
      nextSuggested: ['lab-api-gateway-cota-versao-ou-alb'],
      keywords: 'rds point in time recovery rpo real, restauracao cria instancia nova endpoint, snapshot automatico vs manual retencao, aws backup cofre com trava, rto medido detectar repontar validar',
      level: 'intermediate',
    },
    {
      slug: 'lab-api-gateway-cota-versao-ou-alb',
      title: 'Lab 11 — API Gateway na frente, ou ALB direto?',
      icon: '🚪',
      xp: 130,
      readTime: 36,
      desc: 'O API Gateway não substitui o ALB — administra um contrato que o ALB não sabe que existe. Sem terceiro para administrar, ele é só um salto de rede a mais e uma fatura por requisição. Prova por aritmética: cota em memória de cada task vira média entre réplicas.',
      nextSuggested: ['lab-autenticacao-cognito-sessao-sem-estado'],
      keywords: 'api gateway vs alb quando usar, http api sem chave de api, plano de uso quota vs throttle, vpc link network load balancer, cota por cliente em memoria falha',
      level: 'intermediate',
    },
    {
      slug: 'lab-autenticacao-cognito-sessao-sem-estado',
      title: 'Lab 12 — Autenticação e sessão que não guardam o que não devem',
      icon: '🔑',
      xp: 130,
      readTime: 35,
      desc: 'Sessão em memória não é defeito de escala: é um estado do cliente guardado no servidor errado. O token devolve esse estado sem consultar o Cognito a cada requisição — e o preço do ganho é que revogar deixa de ser imediato.',
      nextSuggested: ['lab-cache-redis-invalidacao-p95'],
      keywords: 'cognito jwt validacao local dotnet, token de identidade vs acesso vs atualizacao, jwks kid cache chave publica, pool de usuario vs pool de identidades, sessao sem estado ecs fargate',
      level: 'intermediate',
    },
    {
      slug: 'lab-cache-redis-invalidacao-p95',
      title: 'Lab 13 — Cache que salva o banco, e a invalidação que quebra tudo',
      icon: '⚡',
      xp: 130,
      readTime: 36,
      desc: 'Cache não é cópia mais rápida do banco: é uma segunda fonte de verdade que você aceitou manter. A pergunta não é o que cachear — é quanto tempo você tolera estar errado, e toda regra de invalidação responde a ela.',
      nextSuggested: ['lab-escolher-banco-pela-carga'],
      keywords: 'elasticache redis cache aside padrao, debandada de cache thundering herd, ttl com jitter trava reconstrucao, invalidacao vs expiracao corrida, latencia p95 antes depois cache',
      level: 'intermediate',
    },
    {
      slug: 'lab-escolher-banco-pela-carga',
      title: 'Lab 14 — Escolher o banco pela carga, no mesmo caso de uso',
      icon: '⚖️',
      xp: 135,
      readTime: 38,
      desc: 'Não se escolhe banco por tipo de dado — escolhe-se pelo padrão de acesso. A mesma feature implementada em RDS, Aurora e DynamoDB, medida sob carga, prova por que DynamoDB é previsível quando o acesso é conhecido e perde feio quando a pergunta é nova.',
      nextSuggested: ['lab-aurora-serverless-v2-endpoint-failover'],
      keywords: 'rds vs aurora vs dynamodb quando usar, padrao de acesso decide o banco, dynamodb scan vs query modelagem, endpoint de vpc gateway vs interface, consistencia forte vs eventual dynamodb',
      level: 'intermediate',
    },
    {
      slug: 'lab-aurora-serverless-v2-endpoint-failover',
      title: 'Lab 15 — Aurora de verdade: endpoint, Serverless v2 e failover',
      icon: '🌊',
      xp: 135,
      readTime: 37,
      desc: 'A pergunta não é quando o Aurora pode escalar sem travar sua transação — no Serverless v2 ele sempre pode. A pergunta é o que decide o piso e o teto de ACU, e a resposta é carga medida, não medo de bloqueio que pertence à v1.',
      nextSuggested: ['lab-dynamodb-modelagem-tabela-unica'],
      keywords: 'aurora serverless v2 acu minimo maximo, aurora vs rds arquitetura de armazenamento, endpoint writer vs reader aurora, failover aurora tempo medido, aurora scaling point v1 vs v2',
      level: 'advanced',
    },
    {
      slug: 'lab-dynamodb-modelagem-tabela-unica',
      title: 'Lab 16 — DynamoDB para quem vem do SQL',
      icon: '🗂️',
      xp: 135,
      readTime: 36,
      desc: 'A chave primária do DynamoDB não descreve a entidade: é a resposta compilada à pergunta que a tabela existe para responder. Modelar entidade primeiro e consulta depois transforma toda pergunta nova em Scan — a conta real está no módulo.',
      nextSuggested: ['lab-upload-direto-s3-url-assinada'],
      keywords: 'dynamodb single table design modelagem, chave composta overloading padrao de acesso, gsi indice secundario global quando usar, scan vs query custo rcu, dynamodb vindo do sql erro comum',
      level: 'advanced',
    },
    {
      slug: 'lab-upload-direto-s3-url-assinada',
      title: 'Lab 17 — Upload sem passar pela aplicação',
      icon: '📤',
      xp: 130,
      readTime: 37,
      desc: 'Assinar não é transportar: a URL assinada tira a aplicação do caminho do byte sem tirá-la da decisão. O preço é que o limite de tamanho deixa de ser código e vira condição de assinatura — e PUT simples não tem essa condição nenhuma.',
      nextSuggested: ['lab-migration-expand-contract-sem-janela'],
      keywords: 's3 presigned url limite de tamanho, post policy content-length-range, upload multipart parte incompleta cobrando, cors bucket upload direto navegador, validacao assincrona depois do upload',
      level: 'intermediate',
    },
    {
      slug: 'lab-migration-expand-contract-sem-janela',
      title: 'Lab 18 — Migrar schema em produção sem parar',
      icon: '🧬',
      xp: 140,
      readTime: 39,
      desc: 'A migration não precisa de janela: o acoplamento entre schema e código precisa. O defeito quase nunca é a duração do DDL — é a fila de bloqueio, onde uma transação aberta segurando um lock fraco faz todo leitor novo esperar atrás do ALTER.',
      nextSuggested: ['lab-busca-catalogo-opensearch-vs-like'],
      keywords: 'expand contract migration sem downtime, postgresql alter table lock level, create index concurrently ef core, fila de bloqueio pg_locks, compatibilidade para frente schema',
      level: 'advanced',
    },
    {
      slug: 'lab-busca-catalogo-opensearch-vs-like',
      title: 'Lab 19 — Busca no catálogo: LIKE até onde?',
      icon: '🔎',
      xp: 130,
      readTime: 36,
      desc: 'LIKE com curinga à esquerda não usa índice — vira varredura completa, e o PostgreSQL já tem índice invertido de verdade antes de OpenSearch se justificar. A mesma busca nos dois, com o limite de cada um medido.',
      nextSuggested: ['lab-spa-na-borda-ou-ssr-no-conteiner'],
      keywords: 'like curinga esquerda sem indice postgresql, tsvector gin busca textual postgres, opensearch fuzziness tolerancia digitacao, bm25 relevancia explicada, cdc sincronizacao indice atraso',
      level: 'intermediate',
    },
    {
      slug: 'lab-spa-na-borda-ou-ssr-no-conteiner',
      title: 'Lab 20 — SPA na borda ou SSR no contêiner',
      icon: '🖥️',
      xp: 135,
      readTime: 37,
      desc: 'A escolha não é de framework: é de onde o HTML é montado, e isso decide o que a borda cacheia, o TTFB e quanto computação você paga por visita. Achado na documentação: TTL mínimo acima de zero faz o CloudFront ignorar Cache-Control: no-store da origem.',
      nextSuggested: ['lab-lambda-dotnet8-cold-start'],
      keywords: 'spa vs ssr seo ttfb, cloudfront ttl minimo ignora no-store, cache key cookie fragmentando cache, html pre-renderizado no build, custo estatico vs conteiner por visita',
      level: 'intermediate',
    },
    {
      slug: 'lab-lambda-dotnet8-cold-start',
      title: 'Lab 21 — Primeira Lambda .NET 8, e o cold start',
      icon: '❄️',
      xp: 125,
      readTime: 35,
      desc: 'Fargate cobra por existir; Lambda cobra por rodar — e o cold start é o preço que ela paga, a cada ambiente novo, pelo mesmo boot que o Fargate faz uma vez e nunca mais cobra. Job de baixa frequência sofre MAIS cold start, não menos.',
      nextSuggested: ['lab-fila-sqs-dlq-idempotencia'],
      keywords: 'lambda dotnet8 cold start medido, native aot vs runtime gerenciado lambda, memoria proporcional a vcpu lambda, provisioned concurrency quando vale, job periodico fargate vs lambda custo',
      level: 'intermediate',
    },
    {
      slug: 'lab-fila-sqs-dlq-idempotencia',
      title: 'Lab 22 — Fila que absorve pico, com DLQ e idempotência',
      icon: '📬',
      xp: 135,
      readTime: 37,
      desc: 'SQS entrega ao menos uma vez — a duplicata não é bug, é o contrato. O que decide se ela vira cobrança duplicada é a escrita condicional do consumidor, não nenhum parâmetro da fila. DLQ, ReportBatchItemFailures e reprocessamento provado.',
      nextSuggested: ['lab-fanout-sns-sqs-multiplos-consumidores'],
      keywords: 'sqs at least once idempotencia consumidor, visibility timeout dlq maxreceivecount, lambda reportbatchitemfailures sqs, fila absorve pico sincrono derrubando, dynamodb condition attribute not exists',
      level: 'intermediate',
    },
    {
      slug: 'lab-fanout-sns-sqs-multiplos-consumidores',
      title: 'Lab 23 — Fanout: um evento, vários interessados',
      icon: '📡',
      xp: 130,
      readTime: 35,
      desc: 'O terceiro consumidor não deveria pedir linha nova no produtor — a lista de quem recebe nunca devia morar no código dele. SNS move essa lista para as assinaturas, e "publish com sucesso" mede aceitação, não entrega ao assinante.',
      nextSuggested: ['lab-eventbridge-espinha-dorsal'],
      keywords: 'sns sqs fanout publish subscribe, terceiro consumidor sem tocar produtor, dlq de assinatura vs dlq da fila, message filtering sns assinatura, publish sucesso nao e entrega',
      level: 'intermediate',
    },
    {
      slug: 'lab-eventbridge-espinha-dorsal',
      title: 'Lab 24 — EventBridge como espinha dorsal',
      icon: '🕸️',
      xp: 140,
      readTime: 38,
      desc: 'A teia não nasce de faltar fila — nasce de cada consumidor decidir sozinho a quem perguntar. EventBridge move essa decisão para uma regra nomeada, e o contrato de evento versionado impede a pergunta de quebrar quando o produtor muda um campo.',
      nextSuggested: ['lab-step-functions-orquestracao-ou-codigo'],
      keywords: 'eventbridge vs sns quando usar, schema registry evento versionado, event pattern matching roteamento, eventbridge replay arquivo de evento, integracao ponto a ponto teia antipadrao',
      level: 'advanced',
    },
    {
      slug: 'lab-step-functions-orquestracao-ou-codigo',
      title: 'Lab 25 — Orquestrar com Step Functions, ou no código?',
      icon: '🧩',
      xp: 140,
      readTime: 38,
      desc: 'O try/catch de 400 linhas não é feio por estilo: é ilegível porque em que passo estou e quantas vezes já tentei moram no mesmo texto. Step Functions separa a máquina de estados, visível, do código de cada passo, pequeno e testável isolado.',
      nextSuggested: ['lab-api-serverless-onde-nao-serve'],
      keywords: 'step functions vs codigo orquestracao, asl retry catch declarativo, standard vs express step functions, maquina de estados testavel, falha injetada orquestracao',
      level: 'advanced',
    },
    {
      slug: 'lab-api-serverless-onde-nao-serve',
      title: 'Lab 26 — API 100% serverless, e onde ela não serve',
      icon: '🧮',
      xp: 135,
      readTime: 37,
      desc: 'ECS cobra pela hora que a task existe; API Gateway + Lambda + DynamoDB cobram pela invocação que atendem. O ponto em que uma curva cruza a outra é aritmética sobre volume, não opinião sobre arquitetura.',
      nextSuggested: ['lab-eventbridge-scheduler-sem-ec2-cron'],
      keywords: 'serverless vs fargate custo comparado, api gateway lambda dynamodb custo, cold start em cadeia serverless, quando serverless nao serve, fargate ocioso homologacao',
      level: 'intermediate',
    },
    {
      slug: 'lab-eventbridge-scheduler-sem-ec2-cron',
      title: 'Lab 27 — Agendamento sem a EC2 do cron',
      icon: '⏰',
      xp: 125,
      readTime: 35,
      desc: 'O defeito da EC2 do cron não é o desperdício: é o silêncio. Quando o job não roda, o único sintoma é o efeito ausente. EventBridge Scheduler transforma ausência de execução em falha observável, com DLQ e alarme por agendamento.',
      nextSuggested: ['lab-pipeline-s3-evento-processamento'],
      keywords: 'eventbridge scheduler vs cron ec2, timezone agendamento horario de verao, flexible time window distribuir carga, retry policy dlq por agendamento, migrar cron para gerenciado',
      level: 'beginner',
    },
    {
      slug: 'lab-pipeline-s3-evento-processamento',
      title: 'Lab 28 — Processar o arquivo que acabou de chegar',
      icon: '📥',
      xp: 130,
      readTime: 36,
      desc: 'O atraso não é preguiça de quem deveria rodar o script — é ausência de gatilho. Notificação direta do bucket trava a evolução como o fanout travava o produtor: só cabe um destino. EventBridge resolve com trilha de estado por arquivo.',
      nextSuggested: ['lab-streaming-mudanca-dynamodb-streams'],
      keywords: 's3 evento eventbridge lambda pipeline, notificacao direta bucket limite, trilha de estado arquivo processado, arquivo malformado rejeitado motivo, upload dispara processamento automatico',
      level: 'intermediate',
    },
    {
      slug: 'lab-streaming-mudanca-dynamodb-streams',
      title: 'Lab 29 — Streaming de mudança do banco',
      icon: '🌊',
      xp: 135,
      readTime: 37,
      desc: 'Um job de polling não só atrasa — ele perde transições intermediárias entre execuções. DynamoDB Streams troca a pergunta por aviso, mas a ordem que garante é por chave de partição, não global, e a retenção é de 24 horas.',
      nextSuggested: ['lab-limites-serverless-medidos'],
      keywords: 'dynamodb streams vs polling, ordem preservada chave particao nao global, new and old images change data capture, retencao 24h stream perde evento, aurora cdc dms binlog',
      level: 'advanced',
    },
    {
      slug: 'lab-limites-serverless-medidos',
      title: 'Lab 30 — Os limites do serverless, medidos',
      icon: '📏',
      xp: 135,
      readTime: 37,
      desc: 'O job de 20 minutos não esbarra em um limite do Lambda — esbarra em cinco ao mesmo tempo, e a gambiarra que resolve o timeout piora os outros quatro. Step Functions orquestrando uma task Fargate resolve os cinco de uma vez.',
      nextSuggested: ['lab-extrair-servico-fronteira-transacao'],
      keywords: 'lambda timeout 15 minutos limite, quando voltar para fargate, step functions standard runtask sync, limites lambda tmp payload concorrencia, auto invocacao lambda antipadrao',
      level: 'advanced',
    },
    {
      slug: 'lab-extrair-servico-fronteira-transacao',
      title: 'Lab 31 — Quebrar o monolito pelo corte certo',
      icon: '🔪',
      xp: 140,
      readTime: 38,
      desc: 'Um serviço só está pronto para ser extraído quando termina a própria transação sem depender de outro serviço no mesmo commit. A maioria dos cortes ruins nasce de dividir por camada técnica em vez de por essa fronteira.',
      nextSuggested: ['lab-sincrono-ou-assincrono-entre-servicos'],
      keywords: 'extrair microsservico fronteira transacao, monolito distribuido antipadrao, transactional outbox dual write, database per service quando extrair, corte por capacidade de negocio',
      level: 'advanced',
    },
    {
      slug: 'lab-sincrono-ou-assincrono-entre-servicos',
      title: 'Lab 32 — Síncrono ou assíncrono entre serviços',
      icon: '🔗',
      xp: 140,
      readTime: 37,
      desc: 'Numa cadeia síncrona, a disponibilidade é o produto das disponibilidades, não a média — quatro serviços a 99,9% cada dão 99,6%, quase quatro vezes mais indisponibilidade. O serviço saudável no meio relata a falha alheia como se fosse sua.',
      nextSuggested: ['lab-descoberta-servico-connect-lattice'],
      keywords: 'disponibilidade composta cadeia sincrona, timeout decrescente chamada encadeada, quando assincrono vale a pena, acoplamento temporal microsservicos, sqs eventbridge desacoplar chamada',
      level: 'advanced',
    },
    {
      slug: 'lab-descoberta-servico-connect-lattice',
      title: 'Lab 33 — Descoberta e malha: Service Connect, VPC Lattice ou nada',
      icon: '🧭',
      xp: 140,
      readTime: 38,
      desc: 'IP de task muda a cada implantação — gravá-lo fixo é um bug adiado. Service Connect, Cloud Map isolado e VPC Lattice respondem perguntas diferentes, não são três níveis da mesma escala, e isolamento de rede não é identidade de quem chama.',
      nextSuggested: ['lab-eks-quando-ecs-nao-basta'],
      keywords: 'ecs service connect vs cloud map, vpc lattice multi conta quando usar, ip de task efemero variavel ambiente, tls automatico entre servicos ecs, descoberta de servico por nome dns',
      level: 'advanced',
    },
    {
      slug: 'lab-eks-quando-ecs-nao-basta',
      title: 'Lab 34 — EKS quando ECS não basta: o que muda de verdade',
      icon: '☸️',
      xp: 145,
      readTime: 39,
      desc: '"Vamos de Kubernetes" sem critério é quase sempre currículo, não requisito. EKS não troca de motor — acrescenta um segundo plano de operação sobre o mesmo Fargate que o ECS já usa, e esse plano só se paga com um requisito real.',
      nextSuggested: ['lab-saga-transacao-distribuida-compensacao'],
      keywords: 'eks vs ecs quando escolher, custo operacional control plane eks, irsa permissao pod vs execution role, helm chart operator requisito real, kubernetes na aws sem hype',
      level: 'advanced',
    },
    {
      slug: 'lab-saga-transacao-distribuida-compensacao',
      title: 'Lab 35 — Saga: transação distribuída sem 2PC',
      icon: '🔄',
      xp: 150,
      readTime: 40,
      desc: 'Quando cada serviço tem seu próprio banco, não existe mais transação ACID cruzando os dois. A saga resolve com transações locais e compensação explícita — código que desfaz o efeito, não rollback mágico, e a compensação também pode falhar.',
      nextSuggested: ['lab-retry-backoff-jitter-circuit-breaker-polly'],
      keywords: 'saga orquestrada vs coreografada, compensacao transacao distribuida, step functions saga pedido pago sem estoque, 2pc por que evitar sistemas distribuidos, falha injetada compensacao',
      level: 'advanced',
    },
    {
      slug: 'lab-retry-backoff-jitter-circuit-breaker-polly',
      title: 'Lab 36 — Retry, backoff, jitter e circuit breaker no .NET',
      icon: '🔁',
      xp: 140,
      readTime: 38,
      desc: 'Retry sem espera crescente faz um serviço já sobrecarregado receber mais carga exatamente quando tenta se recuperar. Jitter quebra a sincronização que o backoff exponencial sozinho não quebra — retry storm reproduzido antes e depois.',
      nextSuggested: ['lab-consistencia-eventual-ponto-de-vista-usuario'],
      keywords: 'polly retry exponential backoff jitter, circuit breaker tres estados dotnet, retry storm apagao cascata, decorrelated jitter formula aws, retry em operacao nao idempotente perigo',
      level: 'advanced',
    },
    {
      slug: 'lab-consistencia-eventual-ponto-de-vista-usuario',
      title: 'Lab 37 — Consistência eventual do ponto de vista do usuário',
      icon: '⏳',
      xp: 140,
      readTime: 38,
      desc: 'O usuário que acabou de salvar e não vê a própria mudança não pensa "consistência eventual" — pensa que o sistema tem bug. Leitura-própria-escrita resolve o sintoma para o autor, enquanto todo outro usuário segue eventualmente consistente, de propósito.',
      nextSuggested: ['lab-multi-tenant-linha-schema-conta'],
      keywords: 'consistencia eventual ux usuario, read your writes leitura propria escrita, marcador escrita recente dynamodb ttl, cache invalidado assincrono atraso, dois relogios fila e stream',
      level: 'advanced',
    },
    {
      slug: 'lab-multi-tenant-linha-schema-conta',
      title: 'Lab 38 — Multi-tenant: linha, schema ou conta',
      icon: '🏢',
      xp: 150,
      readTime: 40,
      desc: 'Isolamento de tenant não é feature da aplicação — é decisão de onde mora a fronteira. Um WHERE esquecido no modelo por linha vaza tudo; RLS com FORCE torna isso impossível no motor do banco. Os três modelos implementados, com teste de vazamento executável.',
      nextSuggested: ['lab-blue-green-canario-codedeploy-ecs'],
      keywords: 'multi tenant isolamento linha schema conta, row level security postgresql force, vazamento de dado entre tenants teste, saas tenant isolation aws whitepaper, dynamodb leading keys isolamento',
      level: 'advanced',
    },
    {
      slug: 'lab-blue-green-canario-codedeploy-ecs',
      title: 'Lab 39 — Blue/green e canário no ECS',
      icon: '🔵',
      xp: 145,
      readTime: 39,
      desc: 'O rollback do blue/green não é publicar a versão antiga de novo — é apontar um listener para uma frota que nunca parou de existir. Só o canário resolve deploy ruim aparecendo com 100% do tráfego dentro, porque blue/green direto ainda expõe todo mundo de uma vez.',
      nextSuggested: ['lab-teste-de-carga-gargalo-real'],
      keywords: 'codedeploy blue green canario ecs, rollback automatico alarme cloudwatch, listener de teste antes do trafego real, disjuntor implantacao vs alarme codedeploy, hook appspec validacao concorrencia',
      level: 'advanced',
    },
    {
      slug: 'lab-teste-de-carga-gargalo-real',
      title: 'Lab 40 — Teste de carga e o gargalo real',
      icon: '📊',
      xp: 140,
      readTime: 38,
      desc: 'O gargalo real não se acha perguntando quantos usuários — acha-se subindo a carga em degraus até sobrar uma camada só saturada, e ela quase nunca é a que a intuição aponta primeiro. O sucesso do autoscaling é o que aperta o banco.',
      nextSuggested: ['lab-iam-policy-menor-privilegio-auditoria'],
      keywords: 'teste de carga degraus gargalo real, autoscaling aperta pool de conexao banco, rds proxy maxconnectionspercent, curva de carga ate a quebra, metrica que revela camada saturada',
      level: 'advanced',
    },
    {
      slug: 'lab-iam-policy-menor-privilegio-auditoria',
      title: 'Lab 41 — Da policy `*` à policy que passa auditoria',
      icon: '🛡️',
      xp: 140,
      readTime: 39,
      desc: 'AdministratorAccess "para não travar" é medo disfarçado de pragmatismo. IAM Access Analyzer deriva a policy do uso REAL registrado no CloudTrail — mas derivada de evidência e correta não são sinônimos: o caminho raro vira AccessDenied na pior hora.',
      nextSuggested: ['lab-identidade-workload-task-role-irsa'],
      keywords: 'iam access analyzer gerar policy cloudtrail, menor privilegio derivado do uso real, permission boundary teto independente, acesso externo nao intencional access analyzer, administrator access risco real',
      level: 'advanced',
    },
    {
      slug: 'lab-identidade-workload-task-role-irsa',
      title: 'Lab 42 — Identidade de workload: task role, execution role, IRSA',
      icon: '🪪',
      xp: 140,
      readTime: 37,
      desc: 'A chave estática é perigosa não só por poder vazar — é perigosa porque a cadeia de credenciais do SDK a testa ANTES da task role, então uma role bem configurada fica muda, sem erro nenhum, atrás de uma variável que ninguém removeu.',
      nextSuggested: ['lab-multi-conta-organizations-scp-control-tower'],
      keywords: 'ecs task role vs execution role, irsa iam roles service account eks, credencial temporaria vs chave estatica, sts assumerolewithwebidentity, cadeia de credenciais sdk aws ordem',
      level: 'advanced',
    },
    {
      slug: 'lab-multi-conta-organizations-scp-control-tower',
      title: 'Lab 43 — Multi-conta: OU, SCP e Control Tower',
      icon: '🏛️',
      xp: 150,
      readTime: 40,
      desc: 'SCP nunca concede nada — só recorta o teto do que a policy IAM já concedeu. É por isso que a fronteira de conta é mais forte que qualquer policy: um wildcard pensado para dev pode casar com prod por prefixo, e só a conta torna isso impossível.',
      nextSuggested: ['lab-endpoint-vpc-privatelink-sem-nat'],
      keywords: 'scp vs iam policy diferenca, organizations ou service control policy, control tower landing zone, fronteira de conta mais forte que policy, dev e producao mesma conta risco',
      level: 'advanced',
    },
    {
      slug: 'lab-endpoint-vpc-privatelink-sem-nat',
      title: 'Lab 44 — Rede privada de verdade: o NAT que você não precisa',
      icon: '🔒',
      xp: 135,
      readTime: 37,
      desc: 'Tráfego para o S3 sai da VPC, atravessa a internet e volta, pago por GB no NAT. Endpoint Gateway para S3/DynamoDB é gratuito; endpoint Interface via PrivateLink resolve o resto sem o tráfego sair da rede da AWS — e ainda sai mais barato que o NAT.',
      nextSuggested: ['lab-rede-hibrida-vpn-direct-connect-transit-gateway'],
      keywords: 'vpc endpoint gateway vs interface custo, privatelink sem sair da internet, nat gateway substituir por endpoint, economia medida remover nat, dns privado endpoint interface',
      level: 'advanced',
    },
    {
      slug: 'lab-rede-hibrida-vpn-direct-connect-transit-gateway',
      title: 'Lab 45 — Rede híbrida: VPN, Direct Connect e Transit Gateway',
      icon: '🌉',
      xp: 150,
      readTime: 40,
      desc: 'Redundância de rede híbrida não é ter dois túneis — é ter dois caminhos físicos independentes. VPN já entrega dois túneis IPsec de série, e nenhum sobrevive à queda do único roteador on-premises que os origina.',
      nextSuggested: ['lab-kms-envelope-cmk-rotacao'],
      keywords: 'site to site vpn vs direct connect, transit gateway hub multiplas vpcs, bgp redundancia caminho fisico, direct connect primario vpn contingencia, conectividade hibrida datacenter vpc',
      level: 'advanced',
    },
    {
      slug: 'lab-kms-envelope-cmk-rotacao',
      title: 'Lab 46 — Criptografia: KMS, envelope, CMK e rotação',
      icon: '🔏',
      xp: 145,
      readTime: 39,
      desc: 'O byte nunca é cifrado pela CMK — é cifrado por uma chave de dados efêmera, e a CMK só cifra essa chave. Trocar para CMK própria não muda como o byte é cifrado, muda quem controla a política que decide quem pode pedir a operação.',
      nextSuggested: ['lab-waf-shield-bloqueio-na-borda'],
      keywords: 'kms envelope encryption chave de dados, cmk vs chave gerenciada aws, rotacao automatica kms 365 dias, kms via service policy de chave, cloudtrail uso por arn de chave',
      level: 'advanced',
    },
    {
      slug: 'lab-waf-shield-bloqueio-na-borda',
      title: 'Lab 47 — WAF e Shield: barrar antes de custar computação',
      icon: '🚧',
      xp: 140,
      readTime: 38,
      desc: 'O custo de um bot não nasce da resposta que ele recebe — nasce do fato de que, para dizer "não", a task já rodou. Bloquear na borda impede que ela chegue a rodar. Ataque simulado bloqueado no WAF, com custo evitado medido.',
      nextSuggested: ['lab-deteccao-guardduty-security-hub-config'],
      keywords: 'aws waf regra gerenciada rate based, shield standard vs advanced, bloquear bot antes do compute, webacl cloudfront us-east-1, custo evitado bloqueio na borda',
      level: 'advanced',
    },
    {
      slug: 'lab-deteccao-guardduty-security-hub-config',
      title: 'Lab 48 — Detecção: GuardDuty, Security Hub, Config',
      icon: '🚨',
      xp: 145,
      readTime: 39,
      desc: 'O achado de segurança não morre por falta de detecção — GuardDuty e Config já detectam sozinhos. Ele morre porque nenhum dos dois tem prazo no vocabulário. É o EventBridge, não o console, que transforma achado em ticket com SLA.',
      nextSuggested: ['lab-dado-pessoal-minimizar-mascarar-macie'],
      keywords: 'guardduty security hub config diferenca, asff formato de achado agregado, eventbridge sla por severidade achado, config regra de conformidade continua, achado de seguranca vira ticket',
      level: 'advanced',
    },
    {
      slug: 'lab-dado-pessoal-minimizar-mascarar-macie',
      title: 'Lab 49 — Dado pessoal: minimizar, mascarar, não logar',
      icon: '🕵️',
      xp: 140,
      readTime: 38,
      desc: 'O CPF no log não vaza pelo banco — vaza porque o log É um banco de dados de CPF que ninguém tratou como banco de dados: mesmo dado, controle de acesso mais largo, retenção decidida por outra pessoa. Varredura sem achado, log sem dado pessoal.',
      nextSuggested: ['lab-resposta-incidente-blast-radius'],
      keywords: 'macie varre s3 nao cloudwatch logs, minimizar antes de mascarar dado pessoal, cpf em log retencao 90 dias, allowlist de campos vs blocklist, dado pessoal exposto controle de acesso',
      level: 'advanced',
    },
    {
      slug: 'lab-resposta-incidente-blast-radius',
      title: 'Lab 50 — Resposta a incidente e blast radius',
      icon: '🧯',
      xp: 155,
      readTime: 41,
      desc: 'Desativar a credencial vazada não mata a sessão temporária que ela já emitiu. CloudTrail via Athena diz se essa segunda contenção é necessária, e é o mesmo dado que mede o raio de alcance — contenção cronometrada sobre trilha real, não suposição.',
      nextSuggested: ['lab-opentelemetry-tres-pilares-dotnet'],
      keywords: 'blast radius credencial vazada cloudtrail, athena consulta trilha de eventos, revogar sessao sts token issue time, contencao antes de investigacao completa, fronteira de conta limita alcance',
      level: 'advanced',
    },
    {
      slug: 'lab-opentelemetry-tres-pilares-dotnet',
      title: 'Lab 51 — Os três pilares no .NET com OpenTelemetry',
      icon: '🎛️',
      xp: 145,
      readTime: 39,
      desc: 'Log, métrica e trace deixam de exigir disciplina para se correlacionar quando nascem da mesma biblioteca sob o mesmo Resource. Trocar de backend de observação vira reconfigurar o coletor, nunca reinstrumentar a aplicação.',
      nextSuggested: ['lab-slo-error-budget-alarme-acionavel'],
      keywords: 'opentelemetry dotnet tres pilares, adot collector sidecar ecs, instrumentacao automatica vs manual span, otlp exportar x-ray cloudwatch, correlacao trace id unico modelo de dados',
      level: 'advanced',
    },
    {
      slug: 'lab-slo-error-budget-alarme-acionavel',
      title: 'Lab 52 — SLO, error budget e alarme que acorda alguém',
      icon: '📟',
      xp: 145,
      readTime: 39,
      desc: '40 alarmes de causa técnica são excesso sem priorização, não falta de monitoramento. Burn rate com duas janelas separa pico transiente de consumo sustentado antes de acionar o plantão — 3 SLOs com orçamento de erro, não alarme por sensação.',
      nextSuggested: ['lab-dashboard-pergunta-operacional'],
      keywords: 'slo error budget burn rate, alarme de sintoma vs alarme de causa, composite alarm duas janelas, incident manager escalonamento automatico, fadiga de alarme priorizacao',
      level: 'advanced',
    },
    {
      slug: 'lab-dashboard-pergunta-operacional',
      title: 'Lab 53 — Dashboard que responde pergunta de operação',
      icon: '📺',
      xp: 135,
      readTime: 37,
      desc: 'Um painel fica verde quando a porta de entrada responde e fica cego quando o negócio parou. 30 gráficos técnicos existem porque a métrica estava disponível — não porque alguém decidiu qual pergunta o painel precisa responder às 3h.',
      nextSuggested: ['lab-pipeline-cicd-oidc-sem-chave'],
      keywords: 'dashboard operacional pergunta nomeada, cloudwatch logs insights consulta, metrica de negocio via emf, painel organizado por pergunta nao servico, sistema disponivel mas negocio parado',
      level: 'intermediate',
    },
    {
      slug: 'lab-pipeline-cicd-oidc-sem-chave',
      title: 'Lab 54 — Pipeline: CodePipeline ou GitHub Actions com OIDC',
      icon: '🔗',
      xp: 145,
      readTime: 38,
      desc: 'A credencial de deploy deixa de ser algo que existe ENTRE deploys — passa a ser emitida, usada e descartada DENTRO de cada execução. Quem pode publicar é decidido pelo sub/aud da trust policy, não por quem guarda uma chave.',
      nextSuggested: ['lab-terraform-modulo-estado-remoto-drift'],
      keywords: 'github actions oidc aws sem chave, trust policy sub aud restricao, codepipeline codebuild ecr deploy, credencial federada sts curta duracao, pipeline sem segredo armazenado',
      level: 'advanced',
    },
    {
      slug: 'lab-terraform-modulo-estado-remoto-drift',
      title: 'Lab 55 — Terraform em módulo, com estado remoto e drift',
      icon: '🧱',
      xp: 140,
      readTime: 38,
      desc: 'Estado remoto elimina a corrida entre dois apply simultâneos — drift não. Drift só aparece quando alguém pergunta pela API real via terraform plan, e essa pergunta precisa rodar sozinha, agendada, ou ninguém a faz.',
      nextSuggested: ['lab-ambiente-por-conta-sem-copiar-colar'],
      keywords: 'terraform estado remoto s3 dynamodb lock, drift deteccao ci terraform plan, modulo reutilizavel variavel, terraform tfstate no laptop risco, plan agendado detailed-exitcode',
      level: 'advanced',
    },
    {
      slug: 'lab-ambiente-por-conta-sem-copiar-colar',
      title: 'Lab 56 — Um ambiente por conta, sem copiar e colar',
      icon: '📋',
      xp: 145,
      readTime: 39,
      desc: 'Dev e prod não divergem porque alguém errou uma variável — divergem porque existem duas cópias do código Terraform, cada uma editada em separado. A cura não é disciplina, é tornar a cópia estruturalmente impossível.',
      nextSuggested: ['lab-chaos-derrubar-az-fis'],
      keywords: 'ambiente por conta terraform modulo unico, promocao de artefato mesma tag, workspace vs diretorio por ambiente, drift estrutural entre dev e prod, organizations ou por ambiente',
      level: 'advanced',
    },
    {
      slug: 'lab-chaos-derrubar-az-fis',
      title: 'Lab 57 — Chaos: derrubar uma AZ de propósito',
      icon: '💥',
      xp: 150,
      readTime: 40,
      desc: 'Alta disponibilidade no desenho é uma afirmação não testada até alguém derrubar a zona de verdade. O cenário pronto do FIS não testa Fargate — testar exige compor a ação certa, com hipótese escrita e SLO como critério de sucesso.',
      nextSuggested: ['lab-dr-multiregiao-quatro-estrategias'],
      keywords: 'aws fault injection service chaos engineering, hipotese testavel antes do experimento, stop condition alarme aborta, derrubar az fargate ecs, blast radius do experimento',
      level: 'advanced',
    },
    {
      slug: 'lab-dr-multiregiao-quatro-estrategias',
      title: 'Lab 58 — DR multi-região: as quatro estratégias',
      icon: '🌍',
      xp: 155,
      readTime: 41,
      desc: 'O RTO de um plano de DR não vem da estratégia escolhida no papel — vem de quanto da segunda região já estava de pé antes do desastre. É isso, não o nome, que separa backup/restore, pilot light, warm standby e multi-site ativo-ativo.',
      nextSuggested: ['lab-finops-rightsizing-antes-compromisso'],
      keywords: 'dr multiregiao quatro estrategias aws, pilot light vs warm standby, aurora global database rpo, route 53 failover health check, rto rpo medido nao estimado',
      level: 'advanced',
    },
    {
      slug: 'lab-finops-rightsizing-antes-compromisso',
      title: 'Lab 59 — FinOps: medir antes de comprar compromisso',
      icon: '💵',
      xp: 140,
      readTime: 38,
      desc: 'Savings Plans comprado sobre o tamanho atual é desconto sobre desperdício assinado por até três anos. Compute Optimizer primeiro, compromisso depois — e Spot só para carga tolerante a interrupção, nunca a API síncrona.',
      nextSuggested: ['lab-well-architected-review-seis-pilares'],
      keywords: 'compute optimizer antes de savings plans, rightsizing antes de compromisso, spot vs savings plans vs reserved, savings plans nao pode alterar termos, finops reducao sem degradar slo',
      level: 'advanced',
    },
    {
      slug: 'lab-well-architected-review-seis-pilares',
      title: 'Lab 60 — Well-Architected review da sua própria arquitetura',
      icon: '🏆',
      xp: 150,
      readTime: 40,
      desc: 'A revisão não descobre risco novo — troca decisões dispersas em 59 laboratórios por um risco alto ou médio por pergunta. O risco mais alto de verdade é o pilar que nenhum dos 59 tratou ainda, não o que teve resposta ruim.',
      nextSuggested: ['lab-operacional-analitico-extracao-incremental'],
      keywords: 'well architected tool seis pilares, risco alto vs medio revisao, plano de melhoria priorizado, sustentabilidade pilar esquecido, revisao formal vs conhecimento tacito',
      level: 'advanced',
    },
    {
      slug: 'lab-operacional-analitico-extracao-incremental',
      title: 'Lab 61 — Do operacional ao analítico: por que não consultar a produção',
      icon: '🔀',
      xp: 135,
      readTime: 37,
      desc: 'Réplica de leitura reduz carga sobre o primário, mas não reduz contenção: consulta OLTP e OLAP continuam competindo pelo mesmo buffer cache. A solução estrutural é extrair via CDC, não mais réplica nem mais capacidade.',
      nextSuggested: ['lab-data-lake-bronze-prata-ouro'],
      keywords: 'oltp vs olap mesmo banco contencao, cdc dms extracao incremental, replica de leitura nao isola analytics, wal captura delete que timestamp perde, relatorio travando banco de producao',
      level: 'intermediate',
    },
    {
      slug: 'lab-data-lake-bronze-prata-ouro',
      title: 'Lab 62 — Data lake em camadas: bronze, prata, ouro',
      icon: '🥇',
      xp: 145,
      readTime: 39,
      desc: '40 mil arquivos no S3 não é problema de volume — é ausência de contrato por camada dizendo se cada arquivo é bruto, limpo ou pronto. Sem esse contrato, toda consulta vira arqueologia. Lake Formation concede acesso por tabela e coluna.',
      nextSuggested: ['lab-kinesis-shard-ordem-reprocesso'],
      keywords: 'data lake bronze prata ouro medallion, lake formation permissao por coluna, glue etl entre camadas, s3 sem estrutura 40 mil arquivos, camada ouro pronta para consumo',
      level: 'advanced',
    },
    {
      slug: 'lab-kinesis-shard-ordem-reprocesso',
      title: 'Lab 63 — Ingestão em streaming: shard, ordem e reprocesso',
      icon: '🌀',
      xp: 140,
      readTime: 38,
      desc: 'PutRecords devolve 200 mesmo com falha parcial — o erro mora no corpo, não no status. Chave de partição de baixa cardinalidade cria hot shard: throughput do stream inteiro cai ao pior shard, não à soma de todos.',
      nextSuggested: ['lab-parquet-particao-arquivo-pequeno'],
      keywords: 'kinesis hot shard chave de particao, putrecords falha parcial http 200, ordem garantida dentro do shard, trim horizon reprocessamento desde inicio, resharding nao conserta chave enviesada',
      level: 'advanced',
    },
    {
      slug: 'lab-parquet-particao-arquivo-pequeno',
      title: 'Lab 64 — Entrega e formato: Parquet, partição, arquivo pequeno',
      icon: '🗃️',
      xp: 135,
      readTime: 37,
      desc: 'Bytes varridos são decisão de escrita, não de consulta: formato decide quanto de cada arquivo é lido, partição decide quantos arquivos abrem, buffer do Firehose decide se compensa abri-los. Colunar + partição + arquivo saudável.',
      nextSuggested: ['lab-glue-catalog-crawler-job-idempotente'],
      keywords: 'parquet colunar vs csv linha, particionamento partition pruning s3, small file problem firehose buffer, athena bytes varridos reduzidos, hive style partition ano mes dia',
      level: 'intermediate',
    },
    {
      slug: 'lab-glue-catalog-crawler-job-idempotente',
      title: 'Lab 65 — Catálogo e ETL: Glue Catalog, crawler, job',
      icon: '📇',
      xp: 135,
      readTime: 37,
      desc: 'Schema conhecido só por quem escreveu o script morre quando essa pessoa esquece ou sai. Glue Data Catalog é o metastore central; crawler infere schema mas não é mágico — conflito de tipo entre arquivos exige decisão explícita.',
      nextSuggested: ['lab-athena-consulta-barata-workgroup'],
      keywords: 'glue data catalog metastore central, crawler inferencia de schema conflito, job etl idempotente sobrescrita particao, hive metastore athena redshift spectrum, schema so na cabeca de alguem',
      level: 'intermediate',
    },
    {
      slug: 'lab-athena-consulta-barata-workgroup',
      title: 'Lab 66 — Consultar o lake e pagar pouco: Athena',
      icon: '💸',
      xp: 140,
      readTime: 38,
      desc: 'Athena cobra por byte varrido, não por tempo de execução — cada otimização de formato e partição já era otimização de custo. Workgroup com limite corta consulta cara antes de terminar; CTAS materializa scan pesado uma vez só.',
      nextSuggested: ['lab-iceberg-upsert-time-travel'],
      keywords: 'athena custo por byte varrido, workgroup limite de consulta, ctas materializar resultado caro, parquet particao reduz custo athena, consulta 10x mais barata medida',
      level: 'intermediate',
    },
    {
      slug: 'lab-iceberg-upsert-time-travel',
      title: 'Lab 67 — Lakehouse: Iceberg, upsert e time travel',
      icon: '🧊',
      xp: 260,
      readTime: 26,
      desc: 'Corrigir um registro histórico no data lake em Parquet puro significa reescrever a partição inteira — caro e arriscado. Tabela Iceberg traz transação, UPDATE/DELETE de verdade e consulta a um estado passado sem tocar no presente.',
      nextSuggested: ['lab-redshift-dashboard-lento'],
      keywords: 'iceberg tabela transacional s3 tables, upsert delete no data lake, time travel consulta estado passado, snapshot compaction manutencao, athena iceberg merge into',
      level: 'advanced',
    },
    {
      slug: 'lab-redshift-dashboard-lento',
      title: 'Lab 68 — Redshift quando o BI dói',
      icon: '📊',
      xp: 150,
      readTime: 42,
      desc: 'Athena resolve consulta ad-hoc esparsa, não painel executivo com concorrência — 8 widgets, 4 a 40 segundos cada, pior com vários executivos ao mesmo tempo. Redshift Serverless com DISTKEY certo e materialized view tira isso de baixo de 3s.',
      nextSuggested: ['lab-lake-formation-permissao-coluna'],
      keywords: 'redshift serverless painel lento, distkey sortkey distribuicao mpp, materialized view refresh automatico, wlm concurrency scaling fila, spectrum consulta historica s3',
      level: 'advanced',
    },
    {
      slug: 'lab-lake-formation-permissao-coluna',
      title: 'Lab 69 — Governança do lake: permissão por coluna',
      icon: '🔐',
      xp: 220,
      readTime: 26,
      desc: 'Catálogo Glue pronto também deixa um analista de BI enxergar CPF e margem de custo por produto — dado que deveria estar restrito por papel. Lake Formation dá permissão fina por coluna e por linha, com teste de negativa provando que o bloqueio funciona.',
      nextSuggested: ['lab-qualidade-dado-contrato-quarentena'],
      keywords: 'lake formation permissao por coluna, tag based access control tbac, teste de negativa access denied, macie dado pessoal no lake, iam mais lake formation intersecao',
      level: 'advanced',
    },
    {
      slug: 'lab-qualidade-dado-contrato-quarentena',
      title: 'Lab 70 — Qualidade de dado: contrato e quarentena',
      icon: '🛃',
      xp: 145,
      readTime: 39,
      desc: 'Um produtor upstream muda a unidade de uma coluna sem avisar, e um pipeline — ou um modelo — aprende silenciosamente sobre números errados. Contrato de dado com Glue Data Quality barra o registro ruim, manda para quarentena e alerta quem produziu.',
      nextSuggested: ['lab-regra-ou-modelo-baseline'],
      keywords: 'glue data quality contrato de dado, quarentena registro invalido s3, eventbridge alerta produtor de dado, schema drift mudanca de unidade, training serving skew dado ruim',
      level: 'advanced',
    },
    {
      slug: 'lab-regra-ou-modelo-baseline',
      title: 'Lab 71 — Quando ML resolve, e quando uma regra resolve melhor',
      icon: '⚖️',
      xp: 130,
      readTime: 36,
      desc: 'Um classificador foi publicado em produção sem nunca medir contra as três condições que já decidiam a mesma coisa. Regra como baseline, modelo em modo sombra, log comparativo — e o número real de quem venceu, custo do erro incluído.',
      nextSuggested: ['lab-feature-store-treino-inferencia'],
      keywords: 'baseline de regra antes do modelo, modelo em modo sombra shadow, custo do erro falso positivo negativo, viabilidade de ml aif mla, regra vence modelo por margem',
      level: 'intermediate',
    },
    {
      slug: 'lab-feature-store-treino-inferencia',
      title: 'Lab 72 — Feature store: o mesmo cálculo no treino e na inferência',
      icon: '🧬',
      xp: 155,
      readTime: 42,
      desc: 'Acurácia de 90% no notebook e ruim em produção — a mesma feature calculada duas vezes, de dois jeitos sutilmente diferentes. SageMaker Feature Store centraliza o cálculo num só lugar, consultado do treino e da inferência, com skew medido em zero.',
      nextSuggested: ['lab-sagemaker-treino-experimento-rastreavel'],
      keywords: 'training serving skew medido, feature store ponto no tempo, mesma feature dois caminhos, point in time accurate join, glue mais sagemaker feature store',
      level: 'advanced',
    },
    {
      slug: 'lab-sagemaker-treino-experimento-rastreavel',
      title: 'Lab 73 — Treinar no SageMaker AI com experimento rastreável',
      icon: '🔬',
      xp: 155,
      readTime: 44,
      desc: 'Um modelo treinado num notebook local três meses atrás está em produção e ninguém reproduz o resultado — hiperparâmetro perdido, seed não fixada. Training Job mais Experiments rastreia commit, hash do dado e hiperparâmetro até a métrica.',
      nextSuggested: ['lab-servir-modelo-quatro-modos-inferencia'],
      keywords: 'sagemaker training job hiperparametro, experiments rastreabilidade commit dado, reprodutibilidade tolerancia numerica, spot instance checkpoint treino, seed fixada resultado reproduzivel',
      level: 'advanced',
    },
    {
      slug: 'lab-servir-modelo-quatro-modos-inferencia',
      title: 'Lab 74 — Servir: tempo real, serverless, assíncrono ou lote',
      icon: '🚦',
      xp: 175,
      readTime: 42,
      desc: 'Endpoint de GPU ligado 24 horas para 200 inferências por dia, espalhadas em poucos horários — o resto é custo parado. Os quatro modos de servir um modelo medidos lado a lado, custo e latência reais, cada um ligado ao consumidor que o pede.',
      nextSuggested: ['lab-model-registry-promocao-rollback'],
      keywords: 'sagemaker quatro modos de inferencia, endpoint tempo real serverless assincrono lote, custo de gpu ociosa medido, batch transform lote noturno, latencia p50 p99 por modo',
      level: 'advanced',
    },
    {
      slug: 'lab-model-registry-promocao-rollback',
      title: 'Lab 75 — Registry e promoção com rollback',
      icon: '↩️',
      xp: 145,
      readTime: 38,
      desc: 'Modelo promovido direto do notebook porque a métrica offline melhorou — e pior em produção, sem versão anterior para voltar. Model Registry, gate de aprovação e rollback exercitado de verdade, com o tempo de volta medido em segundos.',
      nextSuggested: ['lab-pipeline-ml-ponta-a-ponta'],
      keywords: 'sagemaker model registry versao, gate de aprovacao codepipeline, rollback automatico e manual, blue green deployment modelo, metrica offline diverge de negocio',
      level: 'advanced',
    },
    {
      slug: 'lab-pipeline-ml-ponta-a-ponta',
      title: 'Lab 76 — Pipeline de ML de ponta a ponta',
      icon: '🔗',
      xp: 150,
      readTime: 39,
      desc: 'Mesmo com Model Registry pronto, o retreino ainda é disparado à mão, quando alguém lembra — semanas sem retreinar, às vezes com dado incompleto. Pipeline orquestrado, disparado por dado novo, com cache de passo e linhagem completa.',
      nextSuggested: ['lab-drift-dado-conceito-model-monitor'],
      keywords: 'sagemaker pipelines orquestracao ml, gatilho por dado novo eventbridge, cache de passo nao reprocessa, linhagem do dado ao modelo, step functions treino automatizado',
      level: 'advanced',
    },
    {
      slug: 'lab-drift-dado-conceito-model-monitor',
      title: 'Lab 77 — Drift: descobrir antes do negócio reclamar',
      icon: '📉',
      xp: 150,
      readTime: 26,
      desc: 'Um modelo serve há dois meses, o log técnico está limpo, e mesmo assim errou — só o negócio percebeu. Model Monitor com baseline distingue drift de dado de drift de conceito, com alarme disparado sobre dado deslocado de propósito.',
      nextSuggested: ['lab-metrica-modelo-vs-negocio'],
      keywords: 'sagemaker model monitor drift, drift de dado vs drift de conceito, baseline e alarme cloudwatch, erro silencioso sem queda tecnica, deteccao antes do negocio notar',
      level: 'advanced',
    },
    {
      slug: 'lab-metrica-modelo-vs-negocio',
      title: 'Lab 78 — Avaliação honesta: métrica de modelo ≠ de negócio',
      icon: '🎯',
      xp: 190,
      readTime: 28,
      desc: 'AUC melhor no teste offline, receita igual em produção — e um segmento inteiro pode estar pior, mascarado pela média. SageMaker Clarify mede viés, teste A/B liga a avaliação a um número de negócio real, não só estatística.',
      nextSuggested: ['lab-consumir-modelo-dotnet-fallback'],
      keywords: 'metrica de ml vs metrica de negocio, sagemaker clarify vies do modelo, teste ab avaliacao honesta, auc bom receita igual, segmento prejudicado pela media',
      level: 'advanced',
    },
    {
      slug: 'lab-consumir-modelo-dotnet-fallback',
      title: 'Lab 79 — Consumir o modelo do .NET com fallback',
      icon: '🛟',
      xp: 155,
      readTime: 35,
      desc: 'Chamada ao endpoint sem timeout: sob pico ou cold start, ela trava, e a requisição do usuário trava junto — mesmo sendo um score auxiliar. Polly dá timeout, retry, circuit breaker e um caminho degradado explícito, sem travar o cliente.',
      nextSuggested: ['lab-custo-ml-onde-vaza'],
      keywords: 'polly biblioteca dotnet resiliencia, timeout retry circuit breaker sagemaker, caminho degradado sem travar cliente, cold start endpoint tempo real, latencia p50 p99 medida',
      level: 'advanced',
    },
    {
      slug: 'lab-custo-ml-onde-vaza',
      title: 'Lab 80 — Custo de ML: onde o dinheiro vaza',
      icon: '💧',
      xp: 170,
      readTime: 40,
      desc: 'Notebook ligado 24h, endpoint maior do que o tráfego pede, artefato de treino nunca limpo, GPU ociosa no modo errado — quatro vazamentos, uma fatura. Cost Explorer e Compute Optimizer acham o custo parado, com a métrica do modelo intacta.',
      nextSuggested: ['lab-bedrock-primeira-chamada-dotnet'],
      keywords: 'cost explorer vazamento de custo ml, compute optimizer rightsizing endpoint, notebook ocioso ligado 24h, gpu ociosa modo de inferencia, reducao medida sem perder qualidade',
      level: 'advanced',
    },
    {
      slug: 'lab-bedrock-primeira-chamada-dotnet',
      title: 'Lab 81 — Primeira chamada ao Bedrock do .NET 8',
      icon: '🪨',
      xp: 170,
      readTime: 31,
      desc: 'Time quer usar um LLM e ninguém sabe onde a chamada mora. Cliente .NET 8 chamando Bedrock via streaming, retry seletivo, IAM escopada ao modelo — não `bedrock:*` — e custo por chamada logado desde a primeira linha.',
      nextSuggested: ['lab-prompt-versionado-teste-regressao'],
      keywords: 'bedrock invokemodel streaming dotnet, iam escopada ao modelo nao wildcard, custo por chamada tokens logado, id de modelo prefixo do provedor, retry seletivo throttling',
      level: 'intermediate',
    },
    {
      slug: 'lab-prompt-versionado-teste-regressao',
      title: 'Lab 82 — Prompt em produção não é configuração',
      icon: '📝',
      xp: 140,
      readTime: 34,
      desc: 'Prompt editado direto no console para "melhorar" — e a qualidade caiu por dias, sem ninguém achar a causa. Prompt versionado como código, com golden set que reprova a promoção antes de qualquer cliente ver a piora.',
      nextSuggested: ['lab-rag-minimo-com-citacao'],
      keywords: 'prompt como codigo versionado git, golden set teste de regressao, bedrock prompt management versao, pipeline bloqueia promocao ruim, edicao direto no console sem rastro',
      level: 'intermediate',
    },
    {
      slug: 'lab-rag-minimo-com-citacao',
      title: 'Lab 83 — RAG mínimo que funciona, com citação',
      icon: '📚',
      xp: 175,
      readTime: 33,
      desc: 'LLM plugado direto responde algo plausível e errado, sem indicar de onde tirou — porque não tem acesso ao documento real. RAG recupera o trecho certo primeiro, cita a fonte, e mede a taxa de acerto: 35% virou 92,5%.',
      nextSuggested: ['lab-onde-guardar-vetor-quatro-opcoes'],
      keywords: 'rag chunking embedding recuperacao, resposta com citacao de fonte, knowledge bases opensearch bedrock, alucinacao sem fonte vs resposta citavel, taxa de acerto medida golden set',
      level: 'advanced',
    },
    {
      slug: 'lab-onde-guardar-vetor-quatro-opcoes',
      title: 'Lab 84 — Onde guardar vetor: quatro opções, uma decisão',
      icon: '🗄️',
      xp: 190,
      readTime: 31,
      desc: 'Knowledge Bases com OpenSearch Serverless foi escolhido "porque é o padrão da documentação" — nunca comparado. As quatro opções (OpenSearch gerenciado, self-managed, S3 Vectors, pgvector) medidas no mesmo acervo, recall e custo reais.',
      nextSuggested: ['lab-recuperacao-hibrida-reranking'],
      keywords: 'banco vetorial quatro opcoes comparadas, opensearch serverless vs self managed, s3 vectors vs pgvector aurora, recall latencia custo medidos, decisao por moda vs por numero',
      level: 'advanced',
    },
    {
      slug: 'lab-recuperacao-hibrida-reranking',
      title: 'Lab 85 — Recuperação híbrida e reranking',
      icon: '🔍',
      xp: 195,
      readTime: 36,
      desc: 'Os erros residuais do RAG não eram de geração — eram de recuperação: busca vetorial generaliza demais um código de produto exato. BM25 léxico + vetor, fundidos por RRF, com reranking, sobem o acerto sem mudar o LLM de geração.',
      nextSuggested: ['lab-guardrails-limite-do-controle'],
      keywords: 'busca hibrida bm25 mais vetor, rrf reciprocal rank fusion, reranking cross encoder bedrock, erro de recuperacao vs erro de geracao, ganho medido so na recuperacao',
      level: 'advanced',
    },
    {
      slug: 'lab-guardrails-limite-do-controle',
      title: 'Lab 86 — Guardrails: o que protege e o que não protege',
      icon: '🛡️',
      xp: 165,
      readTime: 38,
      desc: 'Guardrail configurado no RAG virou sinônimo de "está seguro" — e 3 de 10 tentativas de contorno testadas passaram. O limite real do controle, com o caso de contorno documentado e a defesa em profundidade que falta.',
      nextSuggested: ['lab-agente-com-ferramenta-quem-executa'],
      keywords: 'bedrock guardrails limite do controle, filtro de conteudo topico negado, caso de contorno testado documentado, defesa em profundidade nao so guardrail, falso senso de seguranca',
      level: 'advanced',
    },
    {
      slug: 'lab-agente-com-ferramenta-quem-executa',
      title: 'Lab 87 — Agente com ferramenta: quem executa é o seu código',
      icon: '🤖',
      xp: 220,
      readTime: 39,
      desc: 'IAM role ampla "para o agente conseguir agir" e sem teto de voltas — um pedido foi reembolsado três vezes. Uma Lambda e uma IAM role por ferramenta, teto de iteração no código do orquestrador, idempotência antes de qualquer ação real.',
      nextSuggested: ['lab-avaliar-sistema-llm-juiz'],
      keywords: 'agente laco de execucao teto de voltas, lambda e iam por ferramenta, quem executa e o codigo nao o llm, idempotencia antes de acao irreversivel, bedrock agentcore permissao minima',
      level: 'advanced',
    },
    {
      slug: 'lab-avaliar-sistema-llm-juiz',
      title: 'Lab 88 — Avaliar sistema com LLM: golden set e juiz',
      icon: '⚖️',
      xp: 200,
      readTime: 35,
      desc: 'Golden set determinístico não avalia geração aberta, e "melhorou" virou impressão de quem leu cinco exemplos. Golden set maior, LLM como juiz com critério explícito, e o viés do próprio juiz medido — não assumido como objetivo.',
      nextSuggested: ['lab-custo-latencia-genai'],
      keywords: 'llm como juiz avaliacao aberta, golden set com criterio explicito, vies do juiz verbosidade autopreferencia, media sozinha esconde regressao, ci reprova por criterio nao so media',
      level: 'advanced',
    },
    {
      slug: 'lab-custo-latencia-genai',
      title: 'Lab 89 — Custo e latência de GenAI',
      icon: '📶',
      xp: 185,
      readTime: 34,
      desc: 'Fatura de token cresceu 6× num mês: contexto repetido sem cache, modelo caro para tarefa simples, lote síncrono sem desconto de batch. Cache explícito de prompt, modelo por tarefa e Bedrock batch, com a mesma qualidade medida.',
      nextSuggested: ['lab-prompt-injection-vazamento-inquilinos'],
      keywords: 'cache explicito de prompt bedrock, modelo certo por tarefa nao um so, bedrock batch para trabalho nao interativo, fatura de token seis vezes maior, custo por resposta reduzido qualidade igual',
      level: 'advanced',
    },
    {
      slug: 'lab-prompt-injection-vazamento-inquilinos',
      title: 'Lab 90 — Prompt injection e vazamento entre inquilinos',
      icon: '🕵️',
      xp: 230,
      readTime: 41,
      desc: 'Documento do lojista A citado na resposta ao lojista B — filtro de tenant só no prompt, não na busca, e um documento malicioso injetando instrução escondida. Filtro obrigatório na query de recuperação, conteúdo tratado como dado, nunca comando.',
      nextSuggested: ['lab-atendimento-voz-prazo-escalonamento'],
      keywords: 'injecao indireta documento malicioso, vazamento entre inquilinos multi tenant rag, filtro de tenant na query nao no prompt, conteudo recuperado e dado nao instrucao, guardrail nao resolve isolamento de fonte',
      level: 'advanced',
    },
    {
      slug: 'lab-atendimento-voz-prazo-escalonamento',
      title: 'Lab 91 — Atendimento com voz, prazo de resposta e saída para humano',
      icon: '🎙️',
      xp: 225,
      readTime: 41,
      desc: 'Em voz, 3 segundos de silêncio derruba a ligação — latência é requisito que elimina o modelo mais capaz, não um detalhe de infraestrutura. Modelo escolhido pelo prazo, escalonamento para humano instrumentado, não fallback silencioso.',
      nextSuggested: ['lab-idp-extracao-confianca-revisao-humana'],
      keywords: 'connect transcribe bedrock voz, latencia como requisito elimina modelo, escalonamento para humano instrumentado, prazo de 2,5 segundos medido, silencio constrangedor em atendimento por voz',
      level: 'advanced',
    },
    {
      slug: 'lab-idp-extracao-confianca-revisao-humana',
      title: 'Lab 92 — IDP: documento → extração → interpretação → revisão humana',
      icon: '🧾',
      xp: 235,
      readTime: 34,
      desc: 'PDF mandado direto pro LLM extrair tudo trocou um valor de nota fiscal e aprovou R$ 45 mil em vez de R$ 1.284,50. Textract extrai o determinístico com confiança por campo; LLM só interpreta; abaixo do limiar, revisão humana no desenho.',
      nextSuggested: ['lab-copiloto-interno-permissao-por-fonte'],
      keywords: 'textract extracao deterministica antes do modelo, confianca por campo revisao humana, a2i revisao abaixo do limiar, llm le pdf inteiro erro caro, cascata extracao interpretacao revisao',
      level: 'advanced',
    },
    {
      slug: 'lab-copiloto-interno-permissao-por-fonte',
      title: 'Lab 93 — Copiloto interno com permissão por fonte',
      icon: '🗝️',
      xp: 235,
      readTime: 38,
      desc: 'Um engenheiro perguntou sobre reembolso e recebeu um dado financeiro confidencial — mesmo índice, times diferentes. Identity Center filtra por permissão da fonte NA recuperação, não no prompt de sistema: a mesma pergunta responde diferente.',
      nextSuggested: ['lab-busca-produto-hibrida-rerank-geracao'],
      keywords: 'copiloto interno permissao por fonte, identity center grupo de acesso, vazamento entre times mesmo indice, filtro na recuperacao nao no prompt, mesma pergunta resposta diferente',
      level: 'advanced',
    },
    {
      slug: 'lab-busca-produto-hibrida-rerank-geracao',
      title: 'Lab 94 — Busca de produto com IA: híbrida, rerank e geração',
      icon: '🛍️',
      xp: 225,
      readTime: 36,
      desc: '"Parafuso 3/4" não achava o produto certo, e a busca ruim derrubava conversão. Recuperação híbrida + rerank decide QUAIS produtos aparecem; geração só apresenta — nunca reordena. Teste A/B mediu 55% de ganho relativo em conversão.',
      nextSuggested: ['lab-enriquecimento-lote-acervo'],
      keywords: 'busca de produto hibrida rerank, geracao so apresenta nao decide, teste ab conversao medida, recuperacao decide qualidade da busca, verificacao em codigo nao so em prompt',
      level: 'advanced',
    },
    {
      slug: 'lab-enriquecimento-lote-acervo',
      title: 'Lab 95 — Enriquecimento em lote do acervo',
      icon: '📦',
      xp: 220,
      readTime: 39,
      desc: 'Classificar 2 milhões de itens chamando o Bedrock síncrono, um por um, esbarra em limite de taxa e nunca termina no prazo. Bedrock Batch com Step Functions faz o mesmo trabalho pela metade do custo, numa janela de horas, sem ninguém esperando.',
      nextSuggested: ['lab-agente-diagnostica-incidente-somente-leitura'],
      keywords: 'bedrock batch metade do custo, step functions map lote, enriquecimento de acervo dois milhoes, eventbridge scheduler nao cron, custo por item medido lote vs tempo real',
      level: 'advanced',
    },
    {
      slug: 'lab-agente-diagnostica-incidente-somente-leitura',
      title: 'Lab 96 — Agente de operação que diagnostica incidente',
      icon: '🔦',
      xp: 225,
      readTime: 35,
      desc: 'Plantão levanta às 3h para fazer sempre o mesmo roteiro manual: abrir painel, correlacionar métrica, trace e log. Agente com ferramentas SOMENTE-LEITURA por IAM — não por prompt — produz hipótese com evidência, sem poder agir.',
      nextSuggested: ['lab-trilha-imutavel-decisao-automatizada'],
      keywords: 'agente diagnostico somente leitura, blast radius zero por iam nao por prompt, hipotese com evidencia anexada, agente nao executa so diagnostica, prompt injection bloqueado estruturalmente',
      level: 'advanced',
    },
    {
      slug: 'lab-trilha-imutavel-decisao-automatizada',
      title: 'Lab 97 — Risco e conformidade de decisão automatizada',
      icon: '⚖️',
      xp: 245,
      readTime: 37,
      desc: 'O veredito de um reembolso recusado foi sobrescrito, e o log expirou em 14 dias — quando a auditoria perguntou, ninguém reconstruiu a decisão. S3 Object Lock em modo Compliance torna a trilha imutável de verdade: nem admin apaga.',
      nextSuggested: ['lab-plataforma-ia-multi-time-cota-chargeback'],
      keywords: 'trilha imutavel de decisao, s3 object lock modo compliance, cloudtrail audit manager explicabilidade, reconstruir decisao ponta a ponta, log mutavel nao e trilha de auditoria',
      level: 'advanced',
    },
    {
      slug: 'lab-plataforma-ia-multi-time-cota-chargeback',
      title: 'Lab 98 — Plataforma de IA multi-time com cota e chargeback',
      icon: '🏢',
      xp: 230,
      readTime: 36,
      desc: 'Um job de lote consumiu 91% da cota compartilhada de tokens, e a latência do atendimento em tempo real disparou de 1,8s para 9,7s. Conta por time, cota isolada por Service Quotas, chargeback por LINKED_ACCOUNT — não por tag frágil.',
      nextSuggested: ['lab-multi-regiao-ia-residencia-de-dado'],
      keywords: 'cota compartilhada consumida por um time, conta separada por time isolamento, chargeback por linked account, budgets alarme por time, mesma conta afeta todos os times',
      level: 'advanced',
    },
    {
      slug: 'lab-multi-regiao-ia-residencia-de-dado',
      title: 'Lab 99 — Multi-região para IA: onde o modelo existe, onde o dado pode estar',
      icon: '🌐',
      xp: 245,
      readTime: 37,
      desc: 'O modelo preferido só existe numa região, e o dado do cliente não pode sair da região dele — os dois requisitos colidem. Route 53 roteia por origem, réplica separada do que pode sair, condição de IAM por região barra o pior caso.',
      nextSuggested: ['lab-projeto-final-plataforma-dotnet-aws-ia'],
      keywords: 'residencia de dado vs disponibilidade do modelo, route 53 roteamento por origem, aurora global so o que pode replicar, privatelink trafego nunca publico, iam requestedregion barra chamada errada',
      level: 'advanced',
    },
    {
      slug: 'lab-projeto-final-plataforma-dotnet-aws-ia',
      title: 'Lab 100 — Projeto final: plataforma .NET 8 + AWS + IA',
      icon: '🏁',
      xp: 330,
      readTime: 44,
      desc: 'Os 99 laboratórios anteriores viram UM sistema: revisão Well-Architected dos seis pilares sobre o todo, e um Disaster Recovery ensaiado de verdade — RTO e RPO medidos, não estimados, com sustentabilidade honestamente ainda em risco alto.',
      nextSuggested: ['saa-c03-intro'],
      keywords: 'projeto final sistema integrado, well architected seis pilares sobre o todo, disaster recovery ensaiado rto rpo medido, sintese dos 99 laboratorios anteriores, maturidade da plataforma nao de uma tecnica',
      level: 'advanced',
    },
  ],
};
