import type { Trail } from '../types';

/** Fine-tuning & Customização de LLMs */
export const trilha_trail25: Trail = {
    id: 'trail25',
    name: 'Fine-tuning & Customização de LLMs',
    color: '#c084fc',
    icon: '🎛️',
    desc: 'Fine-tuning profissional: quando FT vs RAG vs prompt, SFT (Supervised Fine-Tuning), LoRA/QLoRA/PEFT, DPO/RLHF simplificado, curadoria de datasets + dedup + contaminação, avaliação rigorosa com golden set, deploy de modelo custom (vLLM, TGI, Bedrock), capstone de modelo especialista.',
    level: 'advanced',
    href: '/fine-tuning',
    prerequisites: ['llm-apis-producao', 'python-pra-dev-ts'],
    modules: [
      {
        slug: 'quando-fine-tune-vs-rag-vs-prompt',
        title: 'Quando fine-tune vs RAG vs prompt engineering',
        icon: '🎯',
        xp: 50, readTime: 12,
        desc: 'Prompt: comportamento de task. RAG: acesso a knowledge dinâmico. Fine-tune: mudar estilo/domínio/formato consistente. Decisão por cenário: format output → FT. Knowledge freshness → RAG. Raciocínio geral → prompt. FT é caro/lento — última escolha.',
        objetivo: 'Você escolhe entre prompt, RAG e fine-tuning pelo tipo de problema — comportamento, conhecimento ou formato — em vez de ir direto pra opção mais cara.',
        keywords: 'fine tune vs rag vs prompt, quando fine tuning, llm customizacao, rag vs fine tune',
        nextSuggested: ['sft-supervised-fine-tuning'],
        level: 'advanced',
      },
      {
        slug: 'sft-supervised-fine-tuning',
        title: 'SFT (Supervised Fine-Tuning): básico e prático',
        icon: '📚',
        xp: 55, readTime: 13,
        desc: 'SFT: dataset de (input, output) exemplos, treina o modelo a imitar. Chat format (system/user/assistant). Epochs, learning rate, batch size. Over-fitting signs. Hugging Face Transformers + TRL (library), OpenAI fine-tuning API, Anthropic Claude fine-tuning (limited).',
        keywords: 'sft supervised fine tuning, hugging face trl, openai fine tune, llm training, chat format dataset',
        prerequisites: ['quando-fine-tune-vs-rag-vs-prompt'],
        nextSuggested: ['lora-qlora-peft'],
        level: 'advanced',
      },
      {
        slug: 'lora-qlora-peft',
        title: 'LoRA, QLoRA e PEFT: fine-tuning eficiente',
        icon: '⚡',
        xp: 60, readTime: 14,
        desc: 'Full FT é caro (24GB+ VRAM pra 7B model). LoRA: treina adapters pequenos (matrizes low-rank), 10-100x menos params. QLoRA: 4-bit quantization + LoRA, treinando 70B em 1 GPU de 24GB. PEFT library (Hugging Face). Merge adapter ou serve separado.',
        keywords: 'lora fine tuning, qlora, peft, quantization 4bit, low rank adaptation, llm efficient ft',
        prerequisites: ['sft-supervised-fine-tuning'],
        nextSuggested: ['dpo-rlhf-simplificado'],
        level: 'advanced',
      },
      {
        slug: 'dpo-rlhf-simplificado',
        title: 'DPO e RLHF simplificado: aprender com preferências',
        icon: '👍',
        xp: 65, readTime: 15,
        desc: 'RLHF clássico: reward model + PPO — complexo, instável. DPO (Direct Preference Optimization, 2023): objetivo equivalente, matemática mais simples, 10x menos hyperparams. Dataset: (prompt, preferred, rejected). Usa pra alinhamento, style matching, safety.',
        keywords: 'dpo direct preference optimization, rlhf, alinhamento llm, preference learning, ppo llm',
        prerequisites: ['lora-qlora-peft'],
        nextSuggested: ['datasets-para-fine-tuning'],
        level: 'advanced',
      },
      {
        slug: 'datasets-para-fine-tuning',
        title: 'Datasets pra fine-tuning: curadoria, dedup, contaminação',
        icon: '📦',
        xp: 55, readTime: 13,
        desc: 'Dataset quality domina resultado. Curadoria: balanceamento de classes, remover PII, dedup (exact + fuzzy com MinHash), contamination check (não incluir eval set em train). Sintético (LLM-generated) vs human-curated. 1000 exemplos curados &gt; 10k genéricos.',
        keywords: 'ft dataset curadoria, dataset dedup minhash, contamination eval, synthetic data llm',
        prerequisites: ['dpo-rlhf-simplificado'],
        nextSuggested: ['avaliando-fine-tune'],
        level: 'advanced',
      },
      {
        slug: 'avaliando-fine-tune',
        title: 'Avaliando fine-tune: golden set, regression, A/B',
        icon: '📊',
        xp: 55, readTime: 13,
        desc: 'Como saber que FT melhorou vs base? Golden set curado (100-500 exemplos) com respostas ideais. Métricas: LLM-as-judge (GPT-4 compara), regex/exact match em structured output, human eval pra qualidade subjetiva. Regression testing a cada nova versão do modelo.',
        keywords: 'ft evaluation, golden set curation, llm as judge, regression testing llm, ab testing ft',
        prerequisites: ['datasets-para-fine-tuning'],
        nextSuggested: ['deploy-modelo-customizado'],
        level: 'advanced',
      },
      {
        slug: 'deploy-modelo-customizado',
        title: 'Deploy modelo customizado: vLLM, TGI, Bedrock',
        icon: '🚀',
        xp: 60, readTime: 14,
        desc: 'Self-hosted: vLLM (PagedAttention, throughput top) e TGI (Hugging Face Text Generation Inference). Managed: AWS Bedrock Custom Models, SageMaker JumpStart. Cost trade-off: 1 GPU A100 $3/h vs Bedrock pay-per-token. Cold start, autoscale, batch size tuning.',
        keywords: 'vllm llm serving, tgi text generation inference, bedrock custom model, sagemaker jumpstart, llm deploy',
        prerequisites: ['avaliando-fine-tune'],
        nextSuggested: ['capstone-fine-tune-modelo-especialista'],
        level: 'advanced',
      },
      {
        slug: 'capstone-fine-tune-modelo-especialista',
        title: 'Capstone: fine-tune de modelo especialista de domínio',
        icon: '🏁',
        xp: 95, readTime: 20,
        desc: 'Projeto: escolha domínio (legal, médico, code review). Colete 1k-5k exemplos reais. LoRA em Llama 3 ou Mistral. Avaliar com golden set. Deploy com vLLM atrás de FastAPI. Comparar vs base model em métricas específicas. Publicar modelo no Hugging Face Hub.',
        nextSuggested: ['ai-safety-introducao'],
        keywords: 'capstone fine tune, llm especialista dominio, lora llama mistral, vllm fastapi, hugging face hub',
        prerequisites: ['deploy-modelo-customizado'],
        level: 'advanced',
      },
    ],
  };
