import type { Trail } from '../types';

/** Voice, Vision & Multimodal */
export const trilha_trail29: Trail = {
    id: 'trail29', name: 'Voice, Vision & Multimodal',
    color: '#8b5cf6', icon: '🎨',
    desc: 'IA multimodal profissional: speech-to-text (Whisper), text-to-speech (ElevenLabs, OpenAI), Realtime APIs (GPT-4o voice, Anthropic), vision (Claude vision, GPT-4V), OCR moderno (Azure Doc Intelligence), video generation (Sora, Runway), capstone assistente de voz end-to-end.',
    level: 'intermediate', href: '/multimodal',
    prerequisites: ['llm-apis-producao'],
    modules: [
      { slug: 'multimodal-mental-model', title: 'Multimodal mental model: além do texto', icon: '🎭', xp: 45, readTime: 11, desc: 'Unified vs specialized: modelos que aceitam imagem+texto+audio (Gemini, GPT-4o, Claude 3.5) vs pipeline de modelos. Quando cada arquitetura. Custo por modalidade.',
        objetivo: 'Você decide entre um modelo unificado e um pipeline de modelos especializados pelo custo real por modalidade.', keywords: 'multimodal ai, gpt-4o claude 3.5, gemini multimodal, unified model', nextSuggested: ['speech-to-text-whisper'], level: 'intermediate' },
      { slug: 'speech-to-text-whisper', title: 'Speech-to-text: Whisper e alternativas', icon: '🎤', xp: 50, readTime: 12, desc: 'Whisper (OpenAI, open source), Deepgram, AssemblyAI. Streaming vs batch. Language detection. Diarization (quem falou). Cost ($0.006/min Whisper API). Self-host Whisper em GPU.', keywords: 'whisper speech to text, deepgram assemblyai, diarization, self host whisper', prerequisites: ['multimodal-mental-model'], nextSuggested: ['text-to-speech-tts'], level: 'intermediate' },
      { slug: 'text-to-speech-tts', title: 'Text-to-speech: ElevenLabs, OpenAI, Cartesia', icon: '🔊', xp: 50, readTime: 12, desc: 'ElevenLabs (quality top, voice cloning), OpenAI TTS-1 (barato, rápido), Cartesia Sonic (streaming ultra-baixa latência <100ms), Play.ht. Voice cloning ética + consent.', keywords: 'elevenlabs voice cloning, openai tts, cartesia sonic, play.ht, tts streaming', prerequisites: ['speech-to-text-whisper'], nextSuggested: ['realtime-apis-voice'], level: 'intermediate' },
      { slug: 'realtime-apis-voice', title: 'Realtime APIs: GPT-4o Realtime, conversational voice', icon: '⚡', xp: 60, readTime: 14, desc: 'GPT-4o Realtime API (voice native, < 500ms RTT), OpenAI Realtime, LiveKit + agents. Arquitetura WebRTC, turn-taking, interruption handling, VAD (voice activity detection).', keywords: 'gpt-4o realtime, voice ai realtime, webrtc voice, vad turn taking, livekit agents', prerequisites: ['text-to-speech-tts'], nextSuggested: ['vision-models-claude-gpt'], level: 'advanced' },
      { slug: 'vision-models-claude-gpt', title: 'Vision models: Claude Vision, GPT-4V, Gemini', icon: '👁️', xp: 55, readTime: 13, desc: 'Image understanding: Claude 3.5 Sonnet vision, GPT-4V, Gemini 1.5 Pro. Use cases: doc extraction, UI understanding (Playwright + vision), diagrama parsing, chart-to-data.', keywords: 'claude vision, gpt-4v, gemini vision, ocr ai, ui understanding ai', prerequisites: ['realtime-apis-voice'], nextSuggested: ['ocr-doc-intelligence'], level: 'advanced' },
      { slug: 'ocr-doc-intelligence', title: 'OCR moderno: Azure Doc Intelligence, Textract, LandingAI', icon: '📄', xp: 50, readTime: 12, desc: 'OCR legacy (Tesseract) vs moderno LLM-powered (Azure Doc Intelligence, AWS Textract, LandingAI Agentic OCR, Mistral OCR). Tabelas, forms, assinaturas. Quando cada.', keywords: 'azure doc intelligence, aws textract, landingai ocr, mistral ocr, tesseract vs moderno', prerequisites: ['vision-models-claude-gpt'], nextSuggested: ['capstone-voice-assistant'], level: 'advanced' },
      { slug: 'capstone-voice-assistant', title: 'Capstone: assistente de voz end-to-end', icon: '🏁', xp: 90, readTime: 20, desc: 'Build voice assistant: Whisper STT + Claude/GPT-4o reasoning + ElevenLabs/Cartesia TTS, WebRTC streaming, VAD, tool use (set alarm, search web). Deploy em mobile + desktop.', nextSuggested: ['bedrock-o-que-e-e-por-que'], keywords: 'voice assistant capstone, whisper claude elevenlabs, webrtc voice app', prerequisites: ['ocr-doc-intelligence'], level: 'advanced' },
    ],
  };
