import type { Trail } from '../types';

/** SQL & Databases */
export const trilha_trail14: Trail = {
    id: 'trail14',
    name: 'SQL & Databases',
    color: '#336791',
    icon: '🗃️',
    desc: 'SQL real com PostgreSQL: JOINs, índices, EXPLAIN ANALYZE, transações ACID e modelagem de dados. A base que todo backend developer precisa antes de escalar.',
    level: 'intermediate',
    href: '/sql-databases',
    prerequisites: ['trail12'],
    modules: [
      {
        slug: 'relacional-vs-nao-relacional',
        title: 'Relacional vs NoSQL: quando cada um ganha',
        icon: '⚖️',
        xp: 50,
        readTime: 10,
        desc: 'PostgreSQL vs MongoDB vs Redis vs DynamoDB: modelos de dados, trade-offs de consistência e quando a escolha importa de verdade.',
        objetivo: 'Você escolhe entre Postgres, Mongo, Redis ou DynamoDB pelo modelo de dado real do seu problema, não por familiaridade.',
        nextSuggested: ['select-join-na-pratica'],
        keywords: 'relacional nosql, postgresql vs mongodb, quando usar sql nosql, banco de dados comparação',
        level: 'beginner',
      },
      {
        slug: 'select-join-na-pratica',
        title: 'SELECT e JOIN na prática: INNER, LEFT, self-join',
        icon: '🔗',
        xp: 65,
        readTime: 13,
        desc: 'Os JOINs que resolvem 90% dos problemas reais: INNER, LEFT/RIGHT, FULL OUTER, self-join para hierarquias, CTEs para legibilidade.',
        nextSuggested: ['group-by-agregacoes'],
        keywords: 'sql join, inner join, left join, cte sql, postgresql select',
        level: 'beginner',
      },
      {
        slug: 'group-by-agregacoes',
        title: 'GROUP BY, HAVING e agregações que resolvem 80% dos casos',
        icon: '📊',
        xp: 55,
        readTime: 11,
        desc: 'COUNT, SUM, AVG, GROUP BY, HAVING, ROLLUP — as funções de agregação que transformam dados brutos em métricas de negócio.',
        nextSuggested: ['window-functions'],
        keywords: 'sql group by, having sql, agregações sql, count sum avg, postgresql',
        level: 'beginner',
      },
      {
        slug: 'window-functions',
        title: 'Window functions: ranking, running totals, lead/lag',
        icon: '🪟',
        xp: 75,
        readTime: 15,
        desc: 'ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, FIRST_VALUE, SUM OVER — as funções de janela que eliminam subqueries e self-joins complicados.',
        nextSuggested: ['indices-que-funcionam'],
        keywords: 'sql window functions, row_number, rank, lag lead, over partition by, postgresql',
        level: 'intermediate',
      },
      {
        slug: 'indices-que-funcionam',
        title: 'Índices que funcionam: B-tree, hash, GIN, covering, composto',
        icon: '📇',
        xp: 80,
        readTime: 16,
        desc: 'Quando um índice é usado (e quando não é). B-tree vs hash vs GIN, índice composto e a ordem importa, covering index para evitar heap scan.',
        nextSuggested: ['explain-analyze'],
        keywords: 'índices postgresql, b-tree index, gin index, covering index, indice composto sql',
        level: 'intermediate',
      },
      {
        slug: 'explain-analyze',
        title: 'EXPLAIN ANALYZE: lendo o plano e otimizando query',
        icon: '🔬',
        xp: 85,
        readTime: 17,
        desc: 'Seq Scan vs Index Scan vs Bitmap Scan, Nested Loop vs Hash Join vs Merge Join — como ler o plano de execução e transformar queries lentas em rápidas.',
        nextSuggested: ['transacoes-isolation-levels'],
        keywords: 'explain analyze postgresql, query plan, seq scan vs index scan, otimização sql',
        level: 'advanced',
      },
      {
        slug: 'transacoes-isolation-levels',
        title: 'Transações e isolation levels: ACID sem decoreba',
        icon: '🔒',
        xp: 75,
        readTime: 15,
        desc: 'ACID não é decoreba — é o que evita dirty reads, non-repeatable reads e phantom reads. Read Committed, Repeatable Read, Serializable: quando usar cada um.',
        nextSuggested: ['normalizacao-modelagem'],
        keywords: 'acid sql, isolation levels, transações postgresql, dirty read phantom read, begin commit rollback',
        level: 'intermediate',
      },
      {
        slug: 'normalizacao-modelagem',
        title: 'Modelagem e normalização: 1NF–3NF + quando desnormalizar',
        icon: '📐',
        xp: 60,
        readTime: 12,
        desc: 'Primeira, segunda e terceira formas normais com exemplos reais. Quando desnormalizar intencionalmente (analytics, performance). ERD na prática.',
        nextSuggested: ['migrations-profissionais'],
        keywords: 'normalização banco dados, 1NF 2NF 3NF, modelagem relacional, quando desnormalizar, erd',
        level: 'intermediate',
      },
      {
        slug: 'migrations-profissionais',
        title: 'Migrations profissionais: reversíveis, zero-downtime',
        icon: '🔄',
        xp: 65,
        readTime: 13,
        desc: 'Alembic, Flyway e Liquibase. Migrations reversíveis com up/down. Zero-downtime em produção: adicionar coluna nullable, backfill, NOT NULL depois.',
        nextSuggested: ['connection-pool-n-plus-1'],
        keywords: 'database migrations, alembic python, zero downtime migration, schema evolution, flyway',
        level: 'intermediate',
      },
      {
        slug: 'connection-pool-n-plus-1',
        title: 'Connection pool, N+1 e o que mata sua API',
        icon: '⚠️',
        xp: 70,
        readTime: 14,
        desc: 'Por que 100 queries são piores que 1 query com JOIN. N+1 query problem e como detectar. PgBouncer, SQLAlchemy pool, asyncpg — configuração correta.',
        nextSuggested: ['python-pra-dev-ts'],
        keywords: 'n+1 query problem, connection pool postgresql, pgbouncer, sqlalchemy pool, asyncpg',
        level: 'advanced',
      },
    ],
  };
