import type { Trail } from '../types';

/** AWS AI Practitioner (AIF-C01) */
export const trilha_trail_aws_aif: Trail = {
    id: 'trail-aws-aif',
    name: 'AWS AI Practitioner (AIF-C01)',
    color: '#ff9900',
    icon: '🤖',
    desc: 'Certificação oficial AWS sobre IA/ML na nuvem — 5 domínios com profundidade real em Bedrock, SageMaker, RAG, Agents, Guardrails e governança.',
    level: 'intermediate',
    href: '/aws-aif-c01',
    modules: [
      {
        slug: 'aif-intro',
        title: 'AIF-C01 — Visão geral e blueprint do exame',
        icon: '🤖',
        xp: 50,
        readTime: 12,
        desc: 'O que cai, distribuição por domínio, formato, scoring, e por que tirar essa certificação em 2026.',
        objetivo: 'Você sabe o que a AIF-C01 cobra, em que peso por domínio, e decide se vale tirá-la agora.',
        level: 'intermediate',
        keywords: 'aws aif-c01, aws ai practitioner certificacao, blueprint aif c01, exame aws ai',
        nextSuggested: ['aif-ai-ml-fundamentos'],
      },
      {
        slug: 'aif-ai-ml-fundamentos',
        title: 'AI / ML / DL / GenAI — distinções fundamentais',
        icon: '🧠',
        xp: 70,
        readTime: 18,
        desc: 'Diferenças entre AI clássica, ML, deep learning e generative AI. Supervised vs unsupervised vs reinforcement. Onde cada paradigma encaixa.',
        level: 'intermediate',
        keywords: 'ai vs ml vs dl, generative ai, supervised unsupervised reinforcement, machine learning paradigmas',
        prerequisites: ['aif-intro'],
        nextSuggested: ['aif-sagemaker-overview'],
      },
      {
        slug: 'aif-sagemaker-overview',
        title: 'SageMaker — Studio, Canvas, JumpStart, AI Services',
        icon: '🏭',
        xp: 80,
        readTime: 22,
        desc: 'Quando usar SageMaker Studio (notebooks + experimentos), Canvas (no-code), Autopilot (AutoML), JumpStart (FMs prontos). Visão dos AI Services managed (Comprehend, Rekognition, Forecast, Personalize, Transcribe, Polly, Translate, Lex, Textract).',
        level: 'intermediate',
        keywords: 'aws sagemaker, sagemaker studio canvas, jumpstart autopilot, aws ai services comprehend rekognition',
        prerequisites: ['aif-ai-ml-fundamentos'],
        nextSuggested: ['aif-genai-conceitos'],
      },
      {
        slug: 'aif-genai-conceitos',
        title: 'GenAI — Transformers, FMs, prompting, hallucinations',
        icon: '✨',
        xp: 90,
        readTime: 25,
        desc: 'Arquitetura transformer (attention, multi-head, positional encoding). Encoder/decoder/encoder-decoder. Foundation Models. Prompt engineering essentials. Causas e mitigação de hallucinations.',
        level: 'intermediate',
        keywords: 'generative ai, transformers attention, foundation models, hallucinations llm, prompt engineering aws',
        prerequisites: ['aif-sagemaker-overview'],
        nextSuggested: ['aif-bedrock-overview'],
      },
      {
        slug: 'aif-bedrock-overview',
        title: 'Amazon Bedrock — modelos, invocação e pricing',
        icon: '🪨',
        xp: 100,
        readTime: 25,
        desc: 'Catálogo de modelos no Bedrock (Claude, Llama, Nova, Titan, Mistral, Cohere, Stability). InvokeModel vs streaming. On-demand vs Provisioned Throughput. Cross-region inference profiles. Pricing por modelo + caching tiers.',
        level: 'intermediate',
        keywords: 'amazon bedrock, bedrock claude llama nova titan, invokemodel streaming, provisioned throughput bedrock',
        prerequisites: ['aif-genai-conceitos'],
        nextSuggested: ['aif-bedrock-knowledge-bases'],
      },
      {
        slug: 'aif-bedrock-knowledge-bases',
        title: 'Bedrock Knowledge Bases — RAG gerenciado',
        icon: '📚',
        xp: 90,
        readTime: 22,
        desc: 'Knowledge Bases como RAG managed: ingestion (S3, Web, Confluence, SharePoint), embeddings (Titan/Cohere), vector stores (OpenSearch Serverless, Aurora pgvector, Pinecone), chunking (fixed/hierarchical/semantic), retrieval + reranking, citations.',
        level: 'intermediate',
        keywords: 'bedrock knowledge bases, rag managed aws, opensearch serverless vector, aurora pgvector, chunking rag',
        prerequisites: ['aif-bedrock-overview'],
        nextSuggested: ['aif-bedrock-agents'],
      },
      {
        slug: 'aif-bedrock-agents',
        title: 'Bedrock Agents — orquestração multi-step',
        icon: '🛠️',
        xp: 90,
        readTime: 22,
        desc: 'Agents do Bedrock: action groups (Lambda), knowledge bases, prompt templates, multi-turn orchestration, traces. Quando usar Agents vs Step Functions vs custom loop.',
        level: 'intermediate',
        keywords: 'bedrock agents, action groups lambda, agent traces, bedrock vs step functions',
        prerequisites: ['aif-bedrock-knowledge-bases'],
        nextSuggested: ['aif-prompt-engineering'],
      },
      {
        slug: 'aif-prompt-engineering',
        title: 'Prompt engineering em produção (AWS edition)',
        icon: '✍️',
        xp: 100,
        readTime: 25,
        desc: 'Few-shot, chain-of-thought, ReAct, assistant prefilling, structured outputs. Caching de prompts. Versionamento. Templates no Bedrock Prompt Management.',
        level: 'intermediate',
        keywords: 'prompt engineering bedrock, few-shot chain-of-thought, react prompting, bedrock prompt management',
        prerequisites: ['aif-bedrock-agents'],
        nextSuggested: ['aif-responsible-ai'],
      },
      {
        slug: 'aif-responsible-ai',
        title: 'Responsible AI — bias, fairness, transparency, Guardrails',
        icon: '⚖️',
        xp: 110,
        readTime: 28,
        desc: 'Tipos de bias (selection, label, historical, algorithmic). Fairness metrics. SageMaker Clarify para detection. Bedrock Guardrails (denied topics, content filters, sensitive info filters, contextual grounding). Model Cards. HITL com Amazon A2I.',
        level: 'intermediate',
        keywords: 'responsible ai aws, sagemaker clarify bias, bedrock guardrails, model cards, amazon a2i hitl',
        prerequisites: ['aif-prompt-engineering'],
        nextSuggested: ['aif-security-governance'],
      },
      {
        slug: 'aif-security-governance',
        title: 'Security & Governance para AI workloads',
        icon: '🛡️',
        xp: 120,
        readTime: 30,
        desc: 'IAM least privilege para Bedrock/SageMaker. VPC endpoints, PrivateLink. KMS para training artifacts. CloudTrail data events para Bedrock. SCP para governance. HIPAA-eligible AI services. LGPD/GDPR considerations. Cost governance (Budgets, Cost Anomaly Detection para Bedrock).',
        level: 'intermediate',
        keywords: 'aws ai security, iam bedrock sagemaker, vpc endpoints privatelink ai, kms training, cloudtrail bedrock, hipaa ai',
        prerequisites: ['aif-responsible-ai'],
        nextSuggested: ['aif-fine-tuning-eval'],
      },
      {
        slug: 'aif-fine-tuning-eval',
        title: 'Customization & Evaluation — fine-tune, CPT, model eval',
        icon: '🎯',
        xp: 100,
        readTime: 25,
        desc: 'Quando fine-tunar (LoRA/QLoRA conceitualmente, full FT, CPT). Data prep (instruction/response format). Provisioned Throughput para custom models. Bedrock Model Evaluation (auto + human). SageMaker Clarify FMEval.',
        level: 'intermediate',
        keywords: 'fine-tuning aws, lora qlora cpt, bedrock model evaluation, sagemaker clarify fmeval, custom models bedrock',
        prerequisites: ['aif-security-governance'],
        nextSuggested: ['aif-mlops-monitoramento'],
      },
      {
        slug: 'aif-mlops-monitoramento',
        title: 'MLOps & Monitoramento — SageMaker Pipelines, Model Monitor, observabilidade Bedrock',
        icon: '📈',
        xp: 110,
        readTime: 28,
        desc: 'Pipelines (preprocess→train→eval→register→deploy). Model Registry approval flows. Model Monitor (data quality, model quality, bias drift, feature attribution). Bedrock CloudWatch metrics + invocation logging. Cost monitoring.',
        level: 'intermediate',
        keywords: 'mlops aws, sagemaker pipelines, model registry, model monitor drift, bedrock cloudwatch invocation logging',
        prerequisites: ['aif-fine-tuning-eval'],
        nextSuggested: ['aif-simulado-final'],
      },
      {
        slug: 'aif-simulado-final',
        title: 'Estratégia de prova + simulado AIF-C01',
        icon: '🏁',
        xp: 80,
        readTime: 15,
        desc: 'Como atacar cada domínio. Pegadinhas comuns. Time management 65 questões em 90 min. Caminho para o simulado FFV com 1000+ questões.',
        level: 'intermediate',
        nextSuggested: ['mla-intro'],
        keywords: 'estrategia aif-c01, simulado aws ai practitioner, time management exame aws ai',
        prerequisites: ['aif-mlops-monitoramento'],
      },
    ],
  };
