import type { Trail } from '../types';

/** LLM Evals Profissional */
export const trilha_trail26: Trail = {
    id: 'trail26',
    name: 'LLM Evals Profissional',
    color: '#f97316',
    icon: '📏',
    desc: 'Evals como disciplina: por que "testar LLM" é diferente de software comum, curadoria de golden sets, armadilhas de LLM-as-judge, frameworks modernos (Braintrust, Langfuse, Inspect, Promptfoo), A/B testing de prompt em produção, regression testing em agents, capstone de eval harness completo.',
    level: 'advanced',
    href: '/llm-evals',
    prerequisites: ['llm-apis-producao', 'llmops-drift-canary'],
    modules: [
      {
        slug: 'evals-como-disciplina',
        title: 'Evals como disciplina: por que LLM testing é diferente',
        icon: '🎓',
        xp: 50, readTime: 12,
        desc: 'Software tradicional: input X → output Y determinístico. LLM: estocástico, sem ground truth em tasks criativas, métricas (BLEU/ROUGE) ruins pra semantic. Eval é research-like: hipóteses, dataset, métrica, resultados. "Vibes-based testing" não escala.',
        objetivo: 'Você monta uma avaliação de LLM com hipótese, dataset e métrica, em vez de confiar em \'parece bom\'.',
        keywords: 'llm evals, llm testing, llm nondeterministic, bleu rouge limitation, vibes testing llm',
        nextSuggested: ['golden-sets-curadoria'],
        level: 'advanced',
      },
      {
        slug: 'golden-sets-curadoria',
        title: 'Golden sets: curadoria + manutenção + growth',
        icon: '🏆',
        xp: 50, readTime: 12,
        desc: 'Golden set: 100-500 exemplos (query, contexto, resposta ideal) curados por expertos. Evolve: add casos quando user reporta issue, remove quando task muda. Stratified (edge cases, easy, medium, hard). Annotator agreement: 2-3 humans, reconcilie discordance.',
        keywords: 'golden set llm, dataset curation, annotator agreement, eval dataset, ground truth llm',
        prerequisites: ['evals-como-disciplina'],
        nextSuggested: ['llm-as-judge-armadilhas'],
        level: 'advanced',
      },
      {
        slug: 'llm-as-judge-armadilhas',
        title: 'LLM-as-judge: armadilhas e mitigações',
        icon: '⚖️',
        xp: 55, readTime: 13,
        desc: 'GPT-4/Claude avaliando outputs é prático mas enviesado. Bias conhecidos: position bias (prefere primeiro), verbosity bias (mais longo = melhor), self-enhancement (prefere mesmo modelo), família bias. Mitigações: pairwise A-vs-B com order swap, rubric estruturada, cross-model validation, human calibration.',
        keywords: 'llm as judge, judge bias, position bias, verbosity bias, pairwise evaluation, human calibration',
        prerequisites: ['golden-sets-curadoria'],
        nextSuggested: ['eval-frameworks'],
        level: 'advanced',
      },
      {
        slug: 'eval-frameworks',
        title: 'Eval frameworks: Braintrust, Langfuse, Inspect, Promptfoo',
        icon: '🧰',
        xp: 55, readTime: 13,
        desc: 'Promptfoo: YAML-driven, open, bom pra CI. Braintrust: platform pro eval, viz top. Langfuse: open-source, traces + evals combinados. Inspect (UK AI Safety Institute): research-grade. Quando usar cada: time pequeno (Promptfoo), startup (Langfuse), enterprise (Braintrust).',
        keywords: 'braintrust eval, langfuse evals, inspect ai safety, promptfoo, llm eval framework',
        prerequisites: ['llm-as-judge-armadilhas'],
        nextSuggested: ['ab-testing-de-prompt-em-producao'],
        level: 'advanced',
      },
      {
        slug: 'ab-testing-de-prompt-em-producao',
        title: 'A/B testing de prompt em produção',
        icon: '🔀',
        xp: 55, readTime: 13,
        desc: 'Feature flag direciona % user pro prompt novo. Métricas: completion rate, user satisfaction (thumbs up/down), cost per request, latency. Statistical significance com sample size adequado. Guard rails: se error rate spike, rollback automático.',
        keywords: 'ab test prompt llm, feature flag llm, thumbs feedback, statistical significance ab, prompt rollback',
        prerequisites: ['eval-frameworks'],
        nextSuggested: ['regression-testing-para-agents'],
        level: 'advanced',
      },
      {
        slug: 'regression-testing-para-agents',
        title: 'Regression testing pra agents: evitar regredir por mudança',
        icon: '🔁',
        xp: 55, readTime: 13,
        desc: 'Agent tem estado complexo: tool selection, multi-turn, memory. Regression cases: "antes resolvia X, agora não". Suite de cenários end-to-end com golden answer. Rodar em cada commit de prompt/tool. Captura user sessions falhas, vira regression test automático.',
        keywords: 'agent regression test, agent evaluation, multi turn test llm, tool selection eval',
        prerequisites: ['ab-testing-de-prompt-em-producao'],
        nextSuggested: ['capstone-eval-harness-completo'],
        level: 'advanced',
      },
      {
        slug: 'capstone-eval-harness-completo',
        title: 'Capstone: eval harness completo',
        icon: '🏁',
        xp: 90, readTime: 20,
        desc: 'Projeto: app LLM real (RAG, agent, ou assistant). Monte harness: 200+ golden set stratified, LLM-as-judge com pairwise, A/B em prod com feature flag, regression suite em CI, dashboard em Langfuse. Rodar hypothesis: "reranker melhora accuracy?" com dado estatístico.',
        nextSuggested: ['quando-fine-tune-vs-rag-vs-prompt'],
        keywords: 'capstone llm eval, pairwise evaluation, ab test prompt, langfuse dashboard, eval harness producao',
        prerequisites: ['regression-testing-para-agents'],
        level: 'advanced',
      },
    ],
  };
