import type { Trail } from '../types';

/** Machine Learning Clássico */
export const trilha_trail50: Trail = {
    id: 'trail50', name: 'Machine Learning Clássico',
    color: '#5b9bd5', icon: '📊',
    desc: 'ML tradicional que ainda paga contas: regressão e classificação, feature engineering sério, árvores (RF/XGBoost/LightGBM), cross-validation, métricas que não mentem, time series (ARIMA/Prophet), recommender systems. Sem LLM, com estatística honesta.',
    level: 'advanced', href: '/machine-learning',
    prerequisites: ['python-pra-dev-ts'],
    modules: [
      { slug: 'ml-mental-model', title: 'ML clássico: mental model e quando usar', icon: '🧠', xp: 45, readTime: 11, desc: 'Regressão vs classificação vs clustering. Quando ML bate regra/heurística, quando não. Bias-variance trade-off. Por que em 2026 ainda dominamos mercado de tabular com XGBoost, não LLM.',
        objetivo: 'Você decide entre regressão, classificação e clustering pelo formato do problema, e sabe quando XGBoost ainda ganha do LLM em dado tabular.', keywords: 'machine learning classico, ml mental model, regressao classificacao, bias variance', nextSuggested: ['regressao-classificacao'], level: 'advanced' },
      { slug: 'regressao-classificacao', title: 'Regressão e classificação na prática', icon: '📈', xp: 55, readTime: 13, desc: 'Linear/logistic regression, regularização L1/L2. Support vectors. Naive Bayes. KNN. Scikit-learn pipelines. Quando usar cada.', keywords: 'regressao logistica, classificacao, regularizacao l1 l2, scikit-learn', prerequisites: ['ml-mental-model'], nextSuggested: ['feature-engineering-serio'], level: 'advanced' },
      { slug: 'feature-engineering-serio', title: 'Feature engineering sério', icon: '🔧', xp: 55, readTime: 13, desc: 'Categorical encoding (one-hot, target, ordinal, leave-one-out), numerical transforms (log, box-cox), temporal features, interactions. Data leakage pitfalls.', keywords: 'feature engineering ml, target encoding, categorical encoding, data leakage', prerequisites: ['regressao-classificacao'], nextSuggested: ['arvores-rf-xgboost'], level: 'advanced' },
      { slug: 'arvores-rf-xgboost', title: 'Árvores: RF, XGBoost, LightGBM', icon: '🌳', xp: 60, readTime: 14, desc: 'Decision trees mental model. Random Forest (bagging). XGBoost/LightGBM/CatBoost (boosting). Hyperparam tuning, early stopping, feature importance. Por que ganha Kaggle em tabular.', keywords: 'random forest, xgboost, lightgbm, catboost, gradient boosting', prerequisites: ['feature-engineering-serio'], nextSuggested: ['cross-validation-metricas'], level: 'advanced' },
      { slug: 'cross-validation-metricas', title: 'Cross-validation e métricas honestas', icon: '📏', xp: 55, readTime: 13, desc: 'K-fold, stratified, time-series split, leak prevention. Classification (precision/recall/F1/ROC/PR), regression (MAE/RMSE/MAPE/R²), imbalanced (balanced accuracy). Confidence intervals.', keywords: 'cross validation, k-fold stratified, precision recall f1, roc auc', prerequisites: ['arvores-rf-xgboost'], nextSuggested: ['time-series-arima-prophet'], level: 'advanced' },
      { slug: 'time-series-arima-prophet', title: 'Time series: ARIMA, Prophet, Neural', icon: '⏱️', xp: 55, readTime: 13, desc: 'Stationarity, ACF/PACF, ARIMA/SARIMA, Prophet do Meta, DeepAR/NBEATS. Backtesting temporal. Forecasting em produção.', keywords: 'time series, arima sarima, prophet facebook, forecasting, backtesting', prerequisites: ['cross-validation-metricas'], nextSuggested: ['recommender-systems-basico'], level: 'advanced' },
      { slug: 'recommender-systems-basico', title: 'Recommender systems básicos', icon: '🎯', xp: 50, readTime: 12, desc: 'Collaborative filtering (user/item), matrix factorization (SVD, ALS), content-based. Two-tower neural. Cold-start, popularity bias, diversity.', keywords: 'recommender systems, collaborative filtering, matrix factorization, two tower', prerequisites: ['time-series-arima-prophet'], nextSuggested: ['capstone-ml-pipeline-completo'], level: 'advanced' },
      { slug: 'capstone-ml-pipeline-completo', title: 'Capstone: pipeline ML end-to-end', icon: '🏁', xp: 85, readTime: 20, desc: 'Projeto: dataset real (Kaggle), EDA + feature eng + modelo + eval + deployment (FastAPI ou BentoML). Entregáveis: notebook + código testado + README + deploy.', nextSuggested: ['bedrock-o-que-e-e-por-que'], keywords: 'ml pipeline capstone, feature engineering producao, fastapi ml deploy', prerequisites: ['recommender-systems-basico'], level: 'advanced' },
    ],
  };
