import type { Trail } from '../types';

/** Database Deep — Postgres Internals */
export const trilha_trail38: Trail = {
    id: 'trail38',
    name: 'Database Deep — Postgres Internals',
    color: '#336791',
    icon: '🐘',
    desc: 'Postgres profissional além do CRUD: MVCC e isolation levels reais (snapshot, serializable, RR, RC), query planner com EXPLAIN ANALYZE, índices avançados (B-tree, BRIN, GIN, GiST, partial, covering), vacuum e bloat (causa #1 de DB morrendo), connection pooling (pgbouncer), replication (sync/async, failover), partitioning declarativo. Capstone: tuning real de workload.',
    level: 'advanced',
    href: '/postgres-internals',
    prerequisites: ['select-join-na-pratica', 'transacoes-isolation-levels'],
    modules: [
      {
        slug: 'mvcc-e-isolation-levels-de-verdade',
        title: 'MVCC e isolation levels de verdade (sem simplificação)',
        icon: '🔀',
        xp: 60, readTime: 14,
        desc: 'Multi-Version Concurrency Control: Postgres não locka reads, cria snapshots. xmin/xmax em cada tuple. Isolation levels reais no PG: Read Committed (default), Repeatable Read (snapshot), Serializable (SSI — detecta dangerous patterns). Dirty read impossível no PG.',
        objetivo: 'Você explica por que o Postgres não trava leitura, o que xmin/xmax fazem, e qual nível de isolamento sua transação realmente precisa.',
        keywords: 'postgres mvcc, isolation levels postgres, snapshot isolation, ssi serializable, xmin xmax tuple',
        nextSuggested: ['query-planner-e-explain-analyze-ninja'],
        level: 'advanced',
      },
      {
        slug: 'query-planner-e-explain-analyze-ninja',
        title: 'Query planner: EXPLAIN ANALYZE ninja',
        icon: '🗺️',
        xp: 65, readTime: 15,
        desc: 'Planner compara planos por cost estimado. Nodes: Seq Scan, Index Scan, Bitmap Index Scan, Nested Loop, Hash Join, Merge Join. EXPLAIN ANALYZE executa e mostra real. Ler plan: cost, rows estimates vs actual (diferença = stats desatualizadas). BUFFERS mostra I/O.',
        keywords: 'postgres explain analyze, query planner, seq scan vs index, nested loop hash join, buffers explain',
        prerequisites: ['mvcc-e-isolation-levels-de-verdade'],
        nextSuggested: ['indices-avancados'],
        level: 'advanced',
      },
      {
        slug: 'indices-avancados',
        title: 'Índices avançados: B-tree, BRIN, GIN, GiST, partial, covering',
        icon: '🔍',
        xp: 60, readTime: 14,
        desc: 'B-tree (default) é 90% dos casos. BRIN pra tabelas muito grandes ordenadas (log data). GIN pra arrays/jsonb/FTS. GiST pra geométrico/proximity. Partial (WHERE condition) reduz tamanho. Covering (INCLUDE) elimina heap fetch. Expression index pra computed values.',
        keywords: 'postgres index tipos, brin index, gin jsonb, gist geometric, partial index, covering index include',
        prerequisites: ['query-planner-e-explain-analyze-ninja'],
        nextSuggested: ['vacuum-autovacuum-bloat'],
        level: 'advanced',
      },
      {
        slug: 'vacuum-autovacuum-bloat',
        title: 'Vacuum, autovacuum e bloat: causa #1 de DB morrendo',
        icon: '🧹',
        xp: 55, readTime: 13,
        desc: 'MVCC cria dead tuples em cada UPDATE/DELETE. Autovacuum limpa — mas em workloads agressivos, não dá conta → bloat (tabela crescendo, performance caindo). Configurar autovacuum_vacuum_scale_factor por tabela. VACUUM FULL bloqueia — use pg_repack. Monitoring: pg_stat_user_tables.',
        keywords: 'postgres vacuum, autovacuum tuning, bloat table, pg_repack, dead tuples mvcc',
        prerequisites: ['indices-avancados'],
        nextSuggested: ['connection-pooling'],
        level: 'advanced',
      },
      {
        slug: 'connection-pooling',
        title: 'Connection pooling: pgbouncer e a trap serverless',
        icon: '🔌',
        xp: 50, readTime: 11,
        desc: 'Postgres usa 1 process por conexão (pesado). App moderno com pool em cada instância + autoscale = easy 10k conexões. pgbouncer entre aplicação e PG, em 3 modes: session (1 conn por client), transaction (reuse entre txs — mais comum), statement. Serverless (Lambda) trap: spawn exhaustion; use RDS Proxy ou Supabase pooler.',
        keywords: 'postgres connection pool, pgbouncer transaction mode, rds proxy, supabase pooler, serverless postgres',
        prerequisites: ['vacuum-autovacuum-bloat'],
        nextSuggested: ['replication-primary-replica'],
        level: 'advanced',
      },
      {
        slug: 'replication-primary-replica',
        title: 'Replication: streaming, logical, failover',
        icon: '🔁',
        xp: 55, readTime: 13,
        desc: 'Streaming replication (binary WAL) — primary→replica quase sync. Logical replication (decoded, selective) pra CDC/partial. synchronous_commit: off (fast but can lose) / on (default, replica ACK) / remote_apply (replica applied). Failover: Patroni, pg_auto_failover. Split-brain é real; STONITH obrigatório.',
        keywords: 'postgres replication, streaming replication, logical replication cdc, synchronous commit, patroni failover',
        prerequisites: ['connection-pooling'],
        nextSuggested: ['particionamento-e-sharding'],
        level: 'advanced',
      },
      {
        slug: 'particionamento-e-sharding',
        title: 'Particionamento e sharding: quando e como',
        icon: '🧩',
        xp: 60, readTime: 14,
        desc: 'Declarative partitioning no PG 10+: RANGE (por data), LIST (por região), HASH. Partition pruning (planner ignora partitions irrelevantes). Sharding = múltiplos servers; Citus (agora Microsoft) é extensão canônica. Quando sharding? > 10TB ou >100k writes/s sustentados.',
        keywords: 'postgres partitioning, declarative partition, partition pruning, citus sharding, postgres scale',
        prerequisites: ['replication-primary-replica'],
        nextSuggested: ['capstone-tuning-de-workload-real'],
        level: 'advanced',
      },
      {
        slug: 'capstone-tuning-de-workload-real',
        title: 'Capstone: tuning de workload — query de 30s pra 50ms',
        icon: '🏁',
        xp: 90, readTime: 20,
        desc: 'Projeto: dataset real (100M+ rows), query inicial lenta (30s+). Diagnosticar com EXPLAIN ANALYZE + BUFFERS. Adicionar índices corretos. Rewrite query se necessário. Medir melhoria (pg_stat_statements). Entregável: before/after benchmark + análise escrita.',
        nextSuggested: ['nosql-mental-model'],
        keywords: 'capstone postgres tuning, query optimization, pg_stat_statements, slow query 30s 50ms',
        prerequisites: ['particionamento-e-sharding'],
        level: 'advanced',
      },
    ],
  };
