import type { Trail } from '../types';

/** Go Profissional */
export const trilha_trail47: Trail = {
    id: 'trail47', name: 'Go Profissional',
    color: '#00add8', icon: '🐹',
    desc: 'Go 2026: mental model (simplicity first), concurrency com goroutines + channels, context pra cancelamento, interfaces pequenas, error handling explícito, generics (Go 1.18+), performance, capstone CLI tool + API Go idiomática.',
    level: 'intermediate', href: '/go-profissional',
    prerequisites: ['typescript-como-mental-model'],
    modules: [
      { slug: 'go-historia-compilador-diferencial', title: 'Go: história, compilador e diferencial 2026', icon: '🐹', xp: 50, readTime: 12, desc: 'Go nasceu em 2007 no Google (Rob Pike, Ken Thompson, Robert Griesemer) como reação ao C++ complicado e Java verboso. Go 1.0 em 2012; compatibilidade backward forte desde então. Versões marcantes: 1.11 (modules), 1.18 (generics — grande adição), 1.21 (loopvar scoping fix), 1.22-1.24 (range over func, profile-guided optimization). Compilador único oficial (gc) — fast build, static binary com runtime pequeno embutido (scheduler, GC). Diferencial: simplicidade deliberada (menos de 25 keywords), goroutines baratíssimas (stack 2KB inicial), gofmt como padrão, compilation time ~instantâneo. Mercado 2026: DevOps tooling (Docker, Kubernetes, Terraform, Prometheus), backend high-scale (Uber, Cloudflare, Netflix edge), CLIs profissionais. Go 1.22+ é o padrão atual.',
        objetivo: 'Você situa Go entre C++ e Java e sabe o que cada versão marcante — módulos, generics — mudou de verdade.', keywords: 'go historia google, rob pike ken thompson, go 1.18 generics, go compilador gc, goroutines, go docker kubernetes', nextSuggested: ['go-mental-model'], level: 'foundational' },
      { slug: 'go-mental-model', title: 'Go mental model: simplicity first', icon: '🎯', xp: 50, readTime: 12, desc: 'Go philosophy: pequena linguagem, composable, explicit. Go fmt. Go workspace conventions. GOPATH era — agora go modules (go.mod). "Do not communicate by sharing memory; share memory by communicating."', keywords: 'go programming language, go modules, go fmt, go philosophy simplicity', nextSuggested: ['goroutines-channels'], level: 'intermediate' },
      { slug: 'goroutines-channels', title: 'Goroutines e channels: concurrency model', icon: '🔀', xp: 60, readTime: 14, desc: 'Goroutines (lightweight ~2KB, millions OK), channels (send/receive synchronization primitive). Unbuffered (sync) vs buffered. select statement. Fan-in, fan-out patterns. Race conditions e race detector.', keywords: 'go goroutines, go channels select, buffered unbuffered, race detector', prerequisites: ['go-mental-model'], nextSuggested: ['context-cancelation'], level: 'intermediate' },
      { slug: 'context-cancelation', title: 'Context package: cancellation, timeout, values', icon: '⏱️', xp: 55, readTime: 13, desc: 'context.Context canonical pra cancelation + deadline + request-scoped values. context.WithCancel, WithTimeout, WithDeadline. Pass context como first arg sempre. Leaked goroutines = missing context.', keywords: 'go context, context withcancel withtimeout, goroutine leak', prerequisites: ['goroutines-channels'], nextSuggested: ['interfaces-pequenas'], level: 'intermediate' },
      { slug: 'interfaces-pequenas', title: 'Interfaces pequenas + composition', icon: '🧩', xp: 50, readTime: 12, desc: '"The bigger the interface, the weaker the abstraction" — Rob Pike. io.Reader, io.Writer (1 method). Aceita interfaces, retorna structs. Implicit implementation (duck typing estrutural). Composition &gt; inheritance.', keywords: 'go interfaces, io reader writer, duck typing go, composition over inheritance', prerequisites: ['context-cancelation'], nextSuggested: ['error-handling-explicito'], level: 'intermediate' },
      { slug: 'error-handling-explicito', title: 'Error handling: explicit + errors.Is/As', icon: '⚠️', xp: 50, readTime: 12, desc: 'if err != nil { return err } é idiomático (polarizing). errors.Is (sentinel match), errors.As (type assertion), errors.Wrap (errors.Join Go 1.20+). Custom error types. panic reservado pra programmer errors.', keywords: 'go error handling, errors.is as, errors.join, go panic', prerequisites: ['interfaces-pequenas'], nextSuggested: ['generics-go'], level: 'intermediate' },
      { slug: 'generics-go', title: 'Generics em Go (1.18+)', icon: '📐', xp: 55, readTime: 13, desc: 'Generics finally (Go 1.18, 2022). Type parameters em funções + types. Constraints (comparable, any, custom interfaces). slices/maps packages (Go 1.21+) pra operations generic. Tradeoff: simplicity vs power.', keywords: 'go generics 1.18, type parameters, constraints go, slices maps package', prerequisites: ['error-handling-explicito'], nextSuggested: ['go-performance-pprof'], level: 'advanced' },
      { slug: 'go-performance-pprof', title: 'Go performance: pprof + escape analysis', icon: '⚡', xp: 55, readTime: 13, desc: 'pprof (cpu, memory, goroutine, mutex profiles) built-in. Escape analysis (stack vs heap). Allocations count. Benchmarking (testing.B). sync.Pool pra reutilizar. sync/atomic pra lock-free.', keywords: 'go pprof, escape analysis, sync pool, go benchmark testing.b', prerequisites: ['generics-go'], nextSuggested: ['capstone-go-cli-api'], level: 'advanced' },
      { slug: 'capstone-go-cli-api', title: 'Capstone: CLI tool + API Go idiomática', icon: '🏁', xp: 85, readTime: 18, desc: 'Build: CLI (cobra) + REST API (net/http + chi router) integradas. Unit + integration tests. Goroutine pool. Context-aware. Graceful shutdown. Config via env + viper. Dockerfile minimal (scratch ~10MB).', nextSuggested: ['o-que-e-cloud'], keywords: 'capstone go, cobra cli, chi router go, net http api, go docker scratch', prerequisites: ['go-performance-pprof'], level: 'advanced' },
    ],
  };
