import { ToolDescriptor } from '../core/types';

export const TOOLS: ToolDescriptor[] = [
  {
    id: 'scan-project',
    label: 'Scan Project',
    description: 'Analyze codebase and compute AI-readiness score.',
    command: 'aiToolkit.scanProject',
    icon: 'search',
    category: 'analysis',
  },
  {
    id: 'check-drift',
    label: 'Check Drift',
    description: 'Detect when AI instruction files (CLAUDE.md, .cursorrules, …) are out of sync with the project.',
    command: 'aiToolkit.checkDrift',
    icon: 'sync',
    category: 'analysis',
  },
  {
    id: 'generate-instructions',
    label: 'Generate AI Instructions',
    description: 'Create CLAUDE.md, .cursorrules, copilot-instructions, .amazonq rules and AGENTS.md.',
    command: 'aiToolkit.generateInstructions',
    icon: 'file-code',
    category: 'context',
  },
  {
    id: 'generate-sdd',
    label: 'New SDD Spec',
    description: 'Create a Spec-Driven Development specification with the full professional template.',
    command: 'aiToolkit.generateSdd',
    icon: 'notebook',
    category: 'docs',
  },
  {
    id: 'generate-adr',
    label: 'New ADR',
    description: 'Create an Architecture Decision Record (MADR format).',
    command: 'aiToolkit.generateAdr',
    icon: 'note',
    category: 'docs',
  },
  {
    id: 'generate-test-suite',
    label: 'Generate Test Suite',
    description: 'Scaffold unit, integration, contract and e2e tests for a module.',
    command: 'aiToolkit.generateTestSuite',
    icon: 'beaker',
    category: 'scaffold',
  },
  {
    id: 'generate-architecture-diagram',
    label: 'Generate Architecture Diagram',
    description: 'Render the source tree as a Mermaid graph.',
    command: 'aiToolkit.generateArchitectureDiagram',
    icon: 'type-hierarchy',
    category: 'docs',
  },
  {
    id: 'scaffold-feature',
    label: 'Scaffold Feature',
    description: 'Create a feature folder with idiomatic files and TODO(ai) markers.',
    command: 'aiToolkit.scaffoldFeature',
    icon: 'new-folder',
    category: 'scaffold',
  },
  {
    id: 'generate-docs-site',
    label: 'Generate Documentation Site',
    description: 'Create a runnable VitePress docs site (npm run docs:dev).',
    command: 'aiToolkit.generateDocsSite',
    icon: 'book',
    category: 'docs',
  },
];
