import { ToolDescriptor } from '../core/types';

export const TOOLS: ToolDescriptor[] = [
  {
    id: 'scan-project',
    label: 'Scan Project',
    description: 'Analyze codebase and compute AI-readiness score.',
    command: 'aiToolkit.scanProject',
    icon: 'search',
    category: 'analysis',
  },
  {
    id: 'check-drift',
    label: 'Check Drift',
    description: 'Detect when AI instruction files (CLAUDE.md, .cursorrules, …) are out of sync with the project.',
    command: 'aiToolkit.checkDrift',
    icon: 'sync',
    category: 'analysis',
  },
  {
    id: 'enrich-with-ai',
    label: 'Enrich with IDE AI',
    description: 'Use the AI already in your IDE (Copilot, Claude Code…) to detect real code patterns and enrich CLAUDE.md.',
    command: 'aiToolkit.enrichWithAI',
    icon: 'sparkle',
    category: 'analysis',
  },
  {
    id: 'generate-instructions',
    label: 'Generate AI Instructions',
    description: 'Create CLAUDE.md, .cursorrules, copilot-instructions, .amazonq rules and AGENTS.md.',
    command: 'aiToolkit.generateInstructions',
    icon: 'file-code',
    category: 'context',
  },
  {
    id: 'generate-sdd',
    label: 'New SDD Spec',
    description: 'Create a Spec-Driven Development specification with the full professional template.',
    command: 'aiToolkit.generateSdd',
    icon: 'notebook',
    category: 'docs',
  },
  {
    id: 'generate-adr',
    label: 'New ADR',
    description: 'Create an Architecture Decision Record (MADR format).',
    command: 'aiToolkit.generateAdr',
    icon: 'note',
    category: 'docs',
  },
  {
    id: 'generate-test-suite',
    label: 'Generate Test Suite',
    description: 'Scaffold unit, integration, contract and e2e tests for a module.',
    command: 'aiToolkit.generateTestSuite',
    icon: 'beaker',
    category: 'scaffold',
  },
  {
    id: 'generate-architecture-diagram',
    label: 'Generate Architecture Diagram',
    description: 'Render the source tree as a Mermaid graph.',
    command: 'aiToolkit.generateArchitectureDiagram',
    icon: 'type-hierarchy',
    category: 'docs',
  },
  {
    id: 'scaffold-feature',
    label: 'Scaffold Feature',
    description: 'Create a feature folder with idiomatic files and TODO(ai) markers.',
    command: 'aiToolkit.scaffoldFeature',
    icon: 'new-folder',
    category: 'scaffold',
  },
  {
    id: 'generate-docs-site',
    label: 'Generate Documentation Site',
    description: 'Create a runnable VitePress docs site (npm run docs:dev).',
    command: 'aiToolkit.generateDocsSite',
    icon: 'book',
    category: 'docs',
  },
  {
    id: 'generate-onboarding',
    label: 'Generate Onboarding Guide',
    description: 'Create ONBOARDING.md — prerequisites, setup steps, key files, and architecture overview.',
    command: 'aiToolkit.generateOnboarding',
    icon: 'person-add',
    category: 'docs',
  },
  {
    id: 'generate-pr-context',
    label: 'Generate PR Context',
    description: 'Create a .aitoolkit/pr-brief.md with diff summary and checklist for PR reviewers.',
    command: 'aiToolkit.generatePRContext',
    icon: 'git-pull-request',
    category: 'docs',
  },
  {
    id: 'detect-doc-gaps',
    label: 'Detect Documentation Gaps',
    description: 'Scan CLAUDE.md for phantom paths, missing frameworks, and stale commands.',
    command: 'aiToolkit.detectDocGaps',
    icon: 'search-fuzzy',
    category: 'analysis',
  },
  {
    id: 'show-metrics',
    label: 'Quality Metrics',
    description: 'View score history and AI call dashboard.',
    command: 'aiToolkit.showMetrics',
    icon: 'graph-line',
    category: 'analysis',
  },
  {
    id: 'edit-overrides',
    label: 'Edit Overrides',
    description: 'Open .aitoolkit/overrides.json to customize scanner conventions and patterns.',
    command: 'aiToolkit.editOverrides',
    icon: 'settings-gear',
    category: 'analysis',
  },
  {
    id: 'compare-with-ai',
    label: 'Compare AI Responses',
    description: 'Ask a question and compare AI answers with vs. without CLAUDE.md context.',
    command: 'aiToolkit.compareWithAI',
    icon: 'split-horizontal',
    category: 'analysis',
  },
];
