import { defineConfig } from 'vitepress';

export default defineConfig({
  title: 'frontend',
  description: 'Project documentation generated by AI Codebase Toolkit.',
  lastUpdated: true,
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Architecture', link: '/architecture/overview' },
      { text: 'Reference', link: '/reference/api' },
      { text: 'Decisions', link: '/decisions/' },
      { text: 'Specs', link: '/specs/' },
    ],
    sidebar: {
      '/guide/': [
        { text: 'Getting started', link: '/guide/getting-started' },
        { text: 'Installation', link: '/guide/installation' },
        { text: 'Configuration', link: '/guide/configuration' },
        { text: 'Contributing', link: '/guide/contributing' },
      ],
      '/architecture/': [
        { text: 'Overview', link: '/architecture/overview' },
        { text: 'Source tree', link: '/architecture/source-tree' },
        { text: 'Modules', link: '/architecture/modules' },
        { text: 'Data model', link: '/architecture/data-model' },
        { text: 'Cross-cutting concerns', link: '/architecture/cross-cutting' },
      ],
      '/reference/': [
        { text: 'API', link: '/reference/api' },
        { text: 'CLI', link: '/reference/cli' },
        { text: 'Events', link: '/reference/events' },
        { text: 'Glossary', link: '/reference/glossary' },
      ],
    },
    search: { provider: 'local' },
    socialLinks: [],
  },
  markdown: {
    // Mermaid is supported via copy-paste of fenced blocks; for live rendering
    // add a Mermaid plugin of your choice.
  },
});
