import { AIInsights, GeneratedFile, ScanResult } from '../../core/types';
import { buildContext, entryPointHints, frameworkAgreements } from './shared';

export function renderCursor(scan: ScanResult, insights?: AIInsights): GeneratedFile {
  const ctx = buildContext(scan);
  const hints = entryPointHints(scan);
  const fwRules = frameworkAgreements(scan.stack.frameworks);
  const lines: string[] = [
    '# Cursor Project Rules',
    '# Generated by AI Codebase Toolkit.',
    ctx.manifestTag,
    '',
    `You are working on a ${ctx.stackLine} project using ${ctx.frameworksLine}.`,
    '',
    '## Conventions',
    ctx.conventionsBlock,
    '',
    '## Structure',
    ctx.structureBlock,
    '',
    '## Commands',
    ctx.scriptsBlock,
  ];

  if (hints.length > 0) {
    lines.push('', '## Entry points', ...hints);
  }

  lines.push(
    '',
    '## Rules',
    `1. Match existing file naming (${scan.conventions.fileNaming}).`,
    '2. Prefer editing existing files over creating new ones.',
    '3. Add tests next to the implementation file or under the existing test folder.',
    '4. Do not introduce new dependencies without strong justification.',
    '5. Keep changes minimal and focused on the asked task.',
    ...fwRules.map((r, i) => `${i + 6}. ${r.slice(2)}`),
  );

  if (insights) {
    lines.push(
      '',
      '## AI-Detected Patterns',
      `> Analyzed by \`${insights.modelId}\` on ${insights.analyzedAt.slice(0, 10)}`,
      '',
      `- Architecture: ${insights.architecturalStyle}`,
      `- Error handling: ${insights.errorHandling}`,
      `- Async: ${insights.asyncPattern}`,
      `- Validation: ${insights.validationPattern}`,
      `- Naming: ${insights.internalNaming}`,
      ...(insights.knownDebt.length > 0 ? [`- Known debt: ${insights.knownDebt.join('; ')}`] : []),
    );
  }

  return { path: '.cursorrules', content: lines.join('\n') + '\n' };
}
