import { GeneratedFile, ScanResult } from '../../core/types';
import { buildContext } from './shared';

export function renderCursor(scan: ScanResult): GeneratedFile {
  const ctx = buildContext(scan);
  const content = `# Cursor Project Rules
# Generated by AI Codebase Toolkit.
${ctx.manifestTag}

You are working on a ${ctx.stackLine} project using ${ctx.frameworksLine}.

## Conventions
${ctx.conventionsBlock}

## Structure
${ctx.structureBlock}

## Commands
${ctx.scriptsBlock}

## Rules
1. Match existing file naming (${scan.conventions.fileNaming}).
2. Prefer editing existing files over creating new ones.
3. Add tests next to the implementation file or under the existing test folder.
4. Do not introduce new dependencies without strong justification.
5. Keep changes minimal and focused on the asked task.
`;

  return { path: '.cursorrules', content };
}
