import { ScanResult } from '../../core/types';
import { computeManifest, manifestComment } from '../../drift/manifest';

export interface InstructionContext {
  scan: ScanResult;
  stackLine: string;
  frameworksLine: string;
  scriptsBlock: string;
  conventionsBlock: string;
  structureBlock: string;
  manifestTag: string;
}

export function buildContext(scan: ScanResult): InstructionContext {
  const { stack, structure, conventions } = scan;
  const stackLine = `${stack.language}${stack.hasTypeScript ? ' (strict TypeScript)' : ''}`;
  const frameworksLine =
    stack.frameworks.length > 0 ? stack.frameworks.join(', ') : 'no major framework detected';

  const scripts = Object.entries(stack.scripts)
    .filter(([, v]) => Boolean(v))
    .map(([k, v]) => `- \`${stack.packageManager} run ${k}\` — \`${v}\``)
    .join('\n');

  const conventionsBlock = [
    `- File naming: \`${conventions.fileNaming}\` (${Math.round(conventions.consistency * 100)}% consistent)`,
    `- Import style: ${conventions.importStyle}`,
    stack.testFramework ? `- Test framework: ${stack.testFramework}` : null,
  ]
    .filter(Boolean)
    .join('\n');

  const structureBlock = [
    `- Source root: \`${structure.sourceRoot}\``,
    `- Top-level folders: ${structure.rootFolders.map((f) => `\`${f}\``).join(', ')}`,
    structure.hasTests ? '- Tests folder present' : '- No tests folder',
    structure.hasDocs ? '- Docs folder present' : null,
  ]
    .filter(Boolean)
    .join('\n');

  return {
    scan,
    stackLine,
    frameworksLine,
    scriptsBlock: scripts || '_No scripts declared._',
    conventionsBlock,
    structureBlock,
    manifestTag: manifestComment(computeManifest(scan)),
  };
}

export const HEADER_NOTE =
  '<!-- Generated by AI Codebase Toolkit. Re-run "AI Toolkit: Generate AI Instructions" after major changes. -->';
