import { Framework, ScanResult } from '../../core/types';
import { computeManifest, manifestComment } from '../../drift/manifest';

export interface InstructionContext {
  scan: ScanResult;
  stackLine: string;
  frameworksLine: string;
  scriptsBlock: string;
  conventionsBlock: string;
  structureBlock: string;
  manifestTag: string;
}

export function buildContext(scan: ScanResult): InstructionContext {
  const { stack, structure, conventions } = scan;
  const stackLine = `${stack.language}${stack.hasTypeScript ? ' (strict TypeScript)' : ''}`;
  const frameworksLine =
    stack.frameworks.length > 0 ? stack.frameworks.join(', ') : 'no major framework detected';

  const scripts = Object.entries(stack.scripts)
    .filter(([, v]) => Boolean(v))
    .map(([k, v]) => `- \`${stack.packageManager} run ${k}\` — \`${v}\``)
    .join('\n');

  const conventionsBlock = [
    `- File naming: \`${conventions.fileNaming}\` (${Math.round(conventions.consistency * 100)}% consistent)`,
    `- Import style: ${conventions.importStyle}`,
    stack.testFramework ? `- Test framework: ${stack.testFramework}` : null,
  ]
    .filter(Boolean)
    .join('\n');

  const structureBlock = [
    `- Source root: \`${structure.sourceRoot}\``,
    `- Top-level folders: ${structure.rootFolders.map((f) => `\`${f}\``).join(', ')}`,
    structure.hasTests ? '- Tests folder present' : '- No tests folder',
    structure.hasDocs ? '- Docs folder present' : null,
  ]
    .filter(Boolean)
    .join('\n');

  return {
    scan,
    stackLine,
    frameworksLine,
    scriptsBlock: scripts || '_No scripts declared._',
    conventionsBlock,
    structureBlock,
    manifestTag: manifestComment(computeManifest(scan)),
  };
}

export const HEADER_NOTE =
  '<!-- Generated by AI Codebase Toolkit. Re-run "AI Toolkit: Generate AI Instructions" after major changes. -->';

export function entryPointHints(scan: ScanResult): string[] {
  const frameworks = scan.stack.frameworks;
  const src = scan.structure.sourceRoot;

  if (frameworks.includes('next')) {
    return [
      `- Entry: \`${src}/app/\` (App Router) or \`${src}/pages/\` (Pages Router)`,
      '- API routes live in `app/api/` or `pages/api/` — keep them thin, move logic to services.',
    ];
  }
  if (frameworks.includes('remix')) {
    return [
      '- Entry: `app/root.tsx` — root layout and global error boundary.',
      '- Route modules live in `app/routes/`; each exports a `loader` (reads) and/or `action` (mutations).',
      '- Avoid client-side data-fetching libraries — use loaders for all data reads.',
    ];
  }
  if (frameworks.includes('angular')) {
    return [
      `- Entry: \`${src}/main.ts\` bootstraps the Angular application.`,
      `- Root component: \`${src}/app/app.component.ts\` (or \`app.config.ts\` for standalone).`,
      '- Follow Angular CLI conventions: `ng generate component/service/module` for scaffolding.',
    ];
  }
  if (frameworks.includes('vite')) {
    return [
      '- Entry: `index.html` — Vite resolves the module graph from here.',
      `- App bootstrap: \`${src}/main.ts\` (or \`main.tsx\` for React).`,
      '- Use `import.meta.env.VITE_*` for environment variables; never expose secrets client-side.',
    ];
  }
  if (frameworks.includes('nest')) {
    return [
      `- Entry: \`${src}/main.ts\` bootstraps the NestJS app`,
      '- Follow the module → controller → service → repository layering.',
      '- Use constructor injection; never instantiate services manually.',
    ];
  }
  if (frameworks.includes('svelte')) {
    return [`- Entry: \`${src}/routes/+page.svelte\` (SvelteKit) or \`${src}/main.ts\``];
  }
  if (frameworks.includes('vue')) {
    return [
      `- Entry: \`${src}/main.ts\` mounts the root Vue app`,
      '- Use Composition API (`<script setup>`); avoid Options API in new code.',
    ];
  }
  if (frameworks.includes('react') || frameworks.includes('react-native') || frameworks.includes('expo')) {
    return [
      `- Entry: \`${src}/main.tsx\` or \`${src}/index.tsx\``,
      '- Keep components presentational; push side effects into hooks or context.',
    ];
  }
  if (frameworks.includes('hono')) {
    return [
      `- Entry: \`${src}/index.ts\` — create a \`new Hono()\` app and export its \`fetch\` handler.`,
      '- Use `c.req.valid()` with a Zod validator for all input; never read `c.req.json()` directly without validation.',
      '- Hono runs on edge runtimes (Cloudflare Workers, Deno, Bun) — avoid Node-specific APIs unless targeting Node adapter.',
    ];
  }
  if (frameworks.includes('express') || frameworks.includes('fastify')) {
    return [
      `- Entry: \`${src}/index.ts\` or \`${src}/app.ts\``,
      '- Keep route handlers thin; delegate business logic to service modules.',
    ];
  }
  if (frameworks.includes('spring')) {
    return [
      '- Entry: `src/main/java/**/*Application.java` — Spring Boot main class with `@SpringBootApplication`.',
      '- Layers: Controller → Service → Repository (Spring Data JPA). Keep controllers thin.',
      '- Tests live in `src/test/java/`; use `@SpringBootTest` for integration, `@WebMvcTest` for slices.',
    ];
  }
  if (frameworks.includes('quarkus')) {
    return [
      '- Entry: Quarkus bootstraps automatically — no explicit `main()` needed in production.',
      '- CDI beans in `src/main/java/`; use `@ApplicationScoped` as default scope.',
      '- Use Panache (`PanacheEntity` / `PanacheRepository`) for persistence.',
    ];
  }
  if (frameworks.includes('blazor')) {
    return [
      '- Entry: `App.razor` — root component and router.',
      '- Use `@inject` for dependency injection inside components.',
      '- Prefer `@code` blocks in `.razor` files; avoid separate `.razor.cs` code-behind unless complex.',
    ];
  }
  if (frameworks.includes('aspnet')) {
    return [
      '- Entry: `Program.cs` — minimal host configuration and middleware pipeline.',
      '- Use Minimal APIs or Controller-based MVC consistently — do not mix patterns.',
      '- Bind config via `IOptions<T>` with a typed options class; never read `IConfiguration` directly in controllers.',
    ];
  }
  if (scan.stack.language === 'go') {
    return [
      '- Entry: `cmd/<app>/main.go`',
      '- Follow standard Go project layout (cmd/, internal/, pkg/).',
      '- Errors are values — handle them explicitly, never ignore.',
    ];
  }
  if (scan.stack.language === 'java') {
    return [
      '- Entry: `src/main/java/**/Main.java` or the class with `public static void main`.',
      '- Tests in `src/test/java/`; use JUnit 5 (`@Test`, `@BeforeEach`).',
    ];
  }
  if (scan.stack.language === 'csharp') {
    return [
      '- Entry: `Program.cs` — top-level statements or `Main` method.',
      '- Use `dotnet build` / `dotnet test` / `dotnet run` for all operations.',
    ];
  }
  if (scan.stack.language === 'python') {
    return ['- Entry: `main.py` or check `[tool.poetry.scripts]` in pyproject.toml'];
  }
  if (scan.stack.language === 'rust') {
    return ['- Entry: `src/main.rs` or `src/lib.rs`'];
  }
  if (scan.stack.language === 'cpp') {
    return [
      '- Entry: defined in `CMakeLists.txt` via `add_executable()`.',
      '- Use RAII for all resource management; prefer smart pointers (`std::unique_ptr`, `std::shared_ptr`) over raw pointers.',
      '- Compile with warnings enabled (`-Wall -Wextra`) and treat them as errors in CI.',
    ];
  }
  if (scan.stack.language === 'c') {
    return [
      '- Entry: check `Makefile` for the default build target.',
      '- Manage all resources explicitly — check every return value, free every allocation.',
      '- No implicit fallthrough in `switch`; use explicit `break` or `/* fallthrough */` comment.',
    ];
  }

  return [];
}

export function frameworkAgreements(frameworks: Framework[]): string[] {
  const lines: string[] = [];

  if (frameworks.includes('next')) {
    lines.push('- Prefer Server Components; use `"use client"` only when interactivity is required.');
    lines.push('- Data fetching belongs in Server Components or Route Handlers, not in client components.');
  }
  if (frameworks.includes('remix')) {
    lines.push('- Use `loader` for data reads and `action` for mutations; avoid client-side fetch calls.');
    lines.push('- Error boundaries per-route (`ErrorBoundary` export) — never let errors bubble to root silently.');
  }
  if (frameworks.includes('angular')) {
    lines.push('- Use standalone components (`standalone: true`) and the `inject()` function over constructor injection.');
    lines.push('- Prefer Angular Signals for reactive state; avoid `BehaviorSubject` in new code.');
    lines.push('- Use `OnPush` change detection on all components — it is the default for performance.');
  }
  if (frameworks.includes('vite')) {
    lines.push('- Keep imports tree-shakeable — avoid wildcard re-exports from barrel files.');
    lines.push('- Env vars must be prefixed `VITE_` to be exposed to the client bundle.');
  }
  if (frameworks.includes('nest')) {
    lines.push('- Decorate every public endpoint with the appropriate guard and pipe.');
    lines.push('- Validation goes in DTOs with `class-validator`; never validate in service methods.');
  }
  if (frameworks.includes('vue')) {
    lines.push('- Use `<script setup>` and Composition API; avoid mixins and Options API in new code.');
    lines.push('- State that crosses more than 2 components belongs in a Pinia store.');
  }
  if (frameworks.includes('svelte')) {
    lines.push('- Prefer `$state` and `$derived` runes (Svelte 5) over legacy reactive statements.');
  }
  if (frameworks.includes('hono')) {
    lines.push('- Use `zValidator` middleware (`@hono/zod-validator`) for all route input — never `c.req.json()` without a schema.');
    lines.push('- Keep routes thin: handler creates response, business logic lives in service functions imported alongside.');
    lines.push('- Use `app.onError()` and `app.notFound()` for centralized error handling; never return raw error strings.');
  }
  if (frameworks.includes('express') || frameworks.includes('fastify')) {
    lines.push('- Validate all request inputs with a schema (zod, joi, or fastify schemas) at the route layer.');
    lines.push('- Errors propagate via a central error handler — never `res.send()` errors inline.');
  }
  if (frameworks.includes('react') || frameworks.includes('react-native') || frameworks.includes('expo')) {
    lines.push('- Co-locate hooks with the component that owns them unless reused in 3+ places.');
  }
  if (frameworks.includes('spring')) {
    lines.push('- Use constructor injection; annotate the constructor, not fields.');
    lines.push('- Place `@Transactional` on service methods, not controllers or repositories.');
  }
  if (frameworks.includes('quarkus')) {
    lines.push('- Default to `@ApplicationScoped` beans; avoid `@Singleton` unless shared state is intentional.');
    lines.push('- Use Panache Active Record (`PanacheEntity`) or Repository pattern — do not mix both.');
  }
  if (frameworks.includes('aspnet')) {
    lines.push('- Inject dependencies via constructor or primary constructor; never use `ServiceLocator`.');
    lines.push('- Use `IOptions<T>` for configuration; validate options at startup with `ValidateDataAnnotations()`.');
  }
  if (frameworks.includes('blazor')) {
    lines.push('- Use `@inject` for DI inside components; register services in `Program.cs`.');
    lines.push('- Prefer `@code` sections in `.razor` files; extract to a separate class only for large, reusable logic.');
  }

  return lines;
}

